== Preface to the First Edition. 1832

There is a species of instruction to be derived from
the perusal of the lives of eminent saints,
which, in the present day, has become more than ever valuable and important:
for although the age in which we live is characterized by an unusual
zeal for the outward extension of the kingdom of God in the world,
yet the living examples of the complete ascendancy of this kingdom in the heart,
are nevertheless, rare and unfrequent.
While every energy is exerted to propagate the first principles of Christianity,
its great end and aim, namely, conformity to the image of God,
by means of an increasing participation of the divine nature,
and the mortification of the will of the flesh, is in a great measure,
neglected and overlooked.

A consequence of this lamentable declension in godliness is,
that when we read in the Bible of those who "`through faith, subdued kingdoms,
wrought righteousness, obtained promises,
out of weakness were made strong,`" we are ready to consider them as gifted
of God for some particular purpose which now no longer exists;
and that Christians in our day are not warranted to expect
such extraordinary manifestations of the divine favor,
notwithstanding the exhortation of the apostle, to be "`followers of them,
who through faith and patience,
inherited the promise,`" and the words of our Lord himself, "`Whosoever believes on me,
the works that I do, shall he do also and greater works than these shall he do,
because I go to my Father.`"

It cannot therefore fail of being attended with beneficial consequences
to those who are sincerely desirous of growing in grace,
and in the knowledge of the truth, to see in the history of the pious dead,
the manifestation of that divine faithfulness and favor,
which is no respecter of persons, but in every age,
is willing to bestow its inestimable blessings on everyone who diligently seeks them:
to see that even in latter times, the same Spirit,
which dwelt so richly in the members of the primitive church,
is still given to those who submit to his teachings,
and devote themselves wholly unto God: and these blessed results,
the Translator considers to be exemplified in an eminent degree,
in the life of the individual, a short account of which is subjoined.

The history of Tersteegen`'s life, not only establishes the exhilarating truth that God,
in the gift of his Spirit, is "`the same yesterday, today,
and forever;`" but also shows the way to its attainment.
As every true follower of Christ exemplifies, in his degree, the life of Christ,
and as the prominent feature in that life was affliction,
so we find that the earthly pilgrimage of this devoted servant of God,
particularly at the commencement of his spiritual course,
was marked by suffering and trial;
for it is "`through much tribulation that we must enter into the kingdom of God.`"
There are many who boast themselves of their adoption into the family of heaven;
but none have a right to do so, who have not endured the fatherly chastisement of God:
for it is impossible for the body of sin within us to be destroyed in any other manner,
nor can the perverted will of man become conformed to the divine will,
otherwise than by submission to it under circumstances the most trying and painful.

Entire resignation to the will of God, is therefore the primary lesson we have to learn.
It is not, however, necessary that we follow the particular mode of life,
which another may have found beneficial,
in order to know a complete renunciation of self;
but that we commit ourselves wholly to the divine guidance,
in the firm conviction that the situation in which it places us,
however much it may be at variance with our views and wishes,
is the one best adapted to our advancement in holiness.
With regard to our conduct therein, the Holy Spirit will sufficiently instruct us,
if we only listen attentively to his dictates.

As the perusal of Tersteegen`'s history may be of advantage in throwing light
on the outward dispensations of the providence of God towards his people,
so the study of his writings will be found to show, in a very intelligible manner,
the inward operations of the Spirit upon the heart,
and the progress of the life of God in the soul.
Next to the word of God,
there are few authors whose works the writer has
perused with greater satisfaction and benefit;
and whose writings are so evidently pervaded by a divine unction,
which eminently distinguishes them from the generality of religious works, which,
especially in the present day, bear more the stamp of human ingenuity and ability,
than of that wisdom which comes from above.
It need scarcely be added, that his works continue to be read and appreciated in Germany,
by those who have an appetite for spiritual food,
and who are no longer content with the superficial and unsatisfying productions of those,
who, though they may be sufficiently versed in the knowledge of the letter of Scripture,
possess in reality, little of its spirit.

--Samuel Jackson.
Norwood, August 7th, 1832.
