== Preface to the Third Edition. 1837

It is a very general and prevailing sentiment among christians in the present day,
that we are on the verge of mighty changes both in the outward and visible world,
and in that which is inward and spiritual; for "`the night is far spent,
and the day is at hand.`"

Many, indeed, have been awakened out of their sleep, and, according to their ideas,
are converted characters; but instead of "`casting off the works of darkness,
and putting on the armor of light,`" have been lulled to
sleep again under the sound of human tradition and teaching.
They turn, it is true, but it is only from one side to the other;
and if they previously dreamt of the treasures and pleasures of the world;
they now dream that they are spiritually "`rich, and increased in goods,
and have need of nothing;`" while in the all-seeing eye of God,
they are still "`wretched, and miserable, and poor, and blind, and naked.`"
They dream of "`fighting the good fight of faith,`" of "`running the race
set before them,`" and of receiving at death a crown of glory,
while they are still reposing on the couch of their unregenerate nature,
without overcoming a single spiritual foe,
or eradicating one solitary earthly propensity.
They dream of being clothed in the righteousness of Christ,
and of being presented before the Father`'s face without defilement or blemish;
while at the same time,
they virtually deny the power of the blood of Christ
to cleanse them during the present life,
from the corruption of their natures and their contracted impurities.
And finally, they dream of holding fellowship with God and with Christ,
and of communion with his saints,
while they disbelieve the possibility of hearing the voice of God within them,
and under the influence of bigoted and carnal principles,
cleave exclusively to some particular sect or party,
and reject all that are not of their way of thinking.

Some, indeed, begin to open their eyes,
and to see the necessity of a more decided religious walk,
and of greater earnestness in the attainment of holiness.
They see, also, that union is strength,
and that "`a house divided against itself cannot stand`"; or in other words,
that as long as sects and divisions continue in the christian church,
the kingdom of Christ can only partially prosper.
Hence much is written and taught in order to accomplish these objects,
but generally in a superficial manner.
That they may be really effected,
"`the axe must be laid to the root of the tree,`" the wound must be probed to the bottom;
"`old things must pass away, and all things become new`";
a complete and entire renovation of the whole man, and a restoration to the image of God,
through the operation of the Holy Spirit, must ensue.
The tree being made good, will then naturally bring forth good fruit;
one spirit will then animate all such characters, and being the Spirit of God,
will bring them into fellowship with God and with each other,
which is the design and purpose of God with respect to fallen man.
(John 17.)

The necessity of this entire regeneration, the means of attaining to it,
and the bye-roads which lead astray from it, form the subject of the following work.
Two editions of which, having met with a rapid sale, a third has been called for.
The Translator would gladly hail this circumstance as a proof,
that the number of those is increasing,
who are desirous of treading the paths of the inward life,
and also as a pledge of the rising of a better and brighter day.

--Samuel Jackson, 1837
