== Life and Character of Gerhard Tersteegen

Gerhard Tersteegen was born the 25th of November 1697,
in the chief town of the principality of Moers.
Henry Tersteegen, his father, was a tradesman and citizen of the said town,
and died shortly after the birth of his son Gerhard.
He appears to have been religiously inclined, and from his papers,
to have been in correspondence with pious people in other parts.

Gerhard was the youngest of eight children, six sons and two daughters.
One of his brothers was a preacher, the others were engaged in business.
Of the latter, one of them called Johannes, was much attached to his youngest brother.
Possessing considerable abilities, he was sent by his mother to the Latin school,
through all the gradations of which he passed.
He applied himself likewise with great assiduity to the Greek and Hebrew,
as well as to the Latin; and made such progress in the latter,
that on the occasion of a public solemnity, he delivered a Latin oration in verse,
with universal applause,
which induced one of the chief magistrates to advise his
mother to allow her son to devote himself entirely to study.
His mother declined it in consequence of the circumstances of the family,
and destined him to a mercantile life.
He was accordingly bound in his fifteenth year, for a term of four years,
// lint-disable invalid-characters
to his brother-in-law, a merchant in Mülheim on the Rhur.

It was here, when only sixteen years of age,
that he received his first religious impressions,
but through what medium is not with certainty known;
// lint-disable invalid-characters
except that he became acquainted in Mülheim, with a pious tradesman,
from whom he received many excellent admonitions; he has also been heard to say,
that he was once deeply affected by reading a thanksgiving prayer of a dying clergyman.
By these and similar means, he was led, by the wisdom of God,
to seek with earnestness a change of heart;
for which reason he spent whole nights in reading, prayer,
and other devotional exercises.

The following circumstance appears in particular
to have had a very beneficial effect upon his mind.
Being sent on one occasion to Duisburg,
he was seized with such a violent cholic in Duisburg forest,
that he expected nothing but death.
He went a little way out of the road,
and earnestly besought the Lord to deliver him from his pain and prolong his life,
in order that he might have time to prepare himself
in a better manner for the eternal world.
Upon which the pain suddenly left him,
and he felt himself most powerfully incited to devote himself unreservedly to that God,
who had been so kind and gracious to him.

About this time, the vanity and mutability of everything of an earthly nature,
and the infinite importance of heavenly and eternal things,
were made very apparent to him; he perceived also that a mercantile life,
and the continual association with all kinds of people, much distracted his thoughts,
and obstructed his growth in grace; for which reason,
at the expiration of the term of his apprenticeship,
he made choice of a more retired occupation.
The acquaintance he made at that time with a pious weaver,
provoked him to learn his trade; but his weak habit of body, frequent headaches,
and pains in the bowels compelled him to relinquish it.
He subsequently made choice of the art of ribbon-making,
and had no one with him except the person who twisted the silk.
// lint-disable invalid-characters
He still continued to reside at Mülheim on the Rhur,
where he spent the remainder of his life.

In this new situation he lived in the practice of the greatest self-denial;
his apparel was coarse, and his fare, which he often prepared himself,
was of the most ordinary kind, consisting chiefly of flour, water, and milk.
In the first years of his seclusion, he ate only once a day,
and drank neither tea nor coffee.
Though his income was ever so limited,
he still showed himself extremely liberal to the poor.
In the dusk, when he could not be recognized,
he entered the dwellings of the sick and the needy,
and divided among them all he could spare from his earnings.
On the division of his father`'s property, the legatees apportioned him a house,
to prevent his giving all away; but he received at different times,
the value of the building from his brother Johannes, in ready money,
and gave the greatest part of it likewise to the poor.
His relatives being by this more incensed against him than ever,
and he being frequently ill for many weeks together, without being able to earn anything,
he fell into the greatest poverty and want.

The following extract from a letter he wrote to a confidential friend, bearing date,
24th Oct.
1766, attests the truth of this statement.
"`It is easy;`" says he,
"`to talk of poverty as long as we are surrounded with wealthy friends,
who are disposed to assist us.
The writer of this has known the time when he knew
not where he should find food for the next day,
and was without a friend who was acquainted with his situation.
He was at work from five in the morning till nine in the evening,
and occasionally lay ten or twelve weeks in bed, or in the loft,
without those with whom he lodged giving themselves the trouble
to send one of their idle servants to give him a drink of water.
But I always thought there was a necessity for it.`"

In another letter he writes, "`I once lay ill in bed of a burning fever,
and thought I should have died of thirst.
I begged my brother`'s servant, at whose house I lay ill,
to fetch me half a stiver`'s worth of table beer.
But the girl being inattentive, and her mistress giving her something else to do,
she entirely forgot me.
I was in an upper room, and no one thought any more of me.
I was therefore obliged to lie from morning till late in the afternoon,
without a drop of anything to refresh me.
At length I heard the servant on the stairs,
and entreated God to preserve me in the spirit of meekness.`"

In these and similar trials,
his filial confidence in his heavenly Father`'s care remained firm and unshaken,
and to this he felt an inward and powerful incitement.
Observing once, that a part of his dress was worn out,
and not knowing where he should find money to replace it,
it was forcibly impressed upon his mind, that he should "`be careful for nothing.`"
(Phil. 4:6) This strengthened him exceedingly in waiting for the divine goodness;
and the tender mercy of God, as will be shown in what follows, cared richly for him,
and allowed him to lack no good thing.
Our departed friend, at that period, enjoyed true contentment.
"`I cannot express;`" said he on one occasion,
"`how happy I was during the time I lived alone.
I often thought no monarch upon earth could live so contentedly as I did, at that time.
When I ate, I knew not what it was I was eating, nor how it tasted,
and often saw no one for a week together, except the girl who brought me my food.`"

This period of contentment, was succeeded by a state of inward affliction,
into which the Lord gradually conducted him.
He had to pass through many trials and temptations, and through much inward darkness,
The Lord withdrew from him the sensible perception of his favor,
in order to put his fidelity and long-suffering patience to the test,
and also to prepare him for future usefulness.
This state of spiritual darkness continued five years; until at length,
while on a journey to a neighboring town, the day-spring from on high again visited him;
and the atoning mercy of Jesus Christ was made so
deeply and convincingly apparent to him,
that his heart was set entirely at rest.
On this occasion he composed that beautiful hymn, "`My great High Priest,
how kind your love!`"

This calls to mind the following remarkable circumstance which he often related:
By reflecting on the various divisions in the christian church,
he was attacked by such a powerful temptation,
that he almost began to doubt the existence of a God;
but the Lord soon delivered him out of this temptation,
not only by fully enlightening his understanding, but also by a divine communication,
which he found it impossible for language to express.
He was by this means so confirmed in the essential knowledge of God our Savior,
that he was able subsequently to speak and write
upon it in a powerful and experimental manner,
and with much divine unction.
It was probably about this time,
that he composed that noble dedication of himself to God,
which appears in the preface to the first volume of his letters.

About a year after the date of this dedication, (1725), he consented,
after repeated solicitations, to receive a young man of the name of Sommer,
into his lodgings, who was desirous of being taught the art of ribbon making.
He did this, not without considerable hesitation,
being very unwilling to relinquish that solitude, which he had found so agreeable.
In the society of this young friend,
at the recommendation of the late pious Mr. Hoffmann, a candidate for the ministry,
he became less rigid in his manner of living,
and accustomed himself to take coffee with him.
On these occasions, after a hymn had been sung, a portion of the New Testament was read.
After coffee, our departed friend offered up a short prayer,
and then both proceeded quietly to work.

They divided the day in the following manner: at six in the morning they met,
and worked till eleven, when they separated for an hour, for the purpose of prayer.
At one, they again resumed their labor, which continued till six in the evening,
after which they were at liberty, and spent again an hour in private prayer;
a mode of life which lasted about three years.
Tersteegen employed his leisure time in the translation of edifying works;
such as The Compendium of True Godliness, and The Hidden Life with Christ in God, etc.,
// lint-disable invalid-characters
by the eminently pious Bernières de Lauvigny.
About this time also he wrote The Pious Lottery,
and prepared materials for The Spiritual Flower Garden.^
footnote:[In 1724, when he instructed the children of his brother and sister,
he wrote for their use, "`An impartial sketch of the principles of christianity.`"
This little work he never published,
but its value may be inferred from the following circumstance.
A pious reformed minister saw this tract after the decease of its author.
He desired permission to read it, and afterwards testified to a friend,
who found him occupied with the perusal of it,
that he had derived no small benefit from it.]

Not long afterwards, in the year 1727, he began to speak in private meetings.
The person who gave occasion to this, was the late Mr. Hoffmann above mentioned.
This pious individual not only spoke at the meeting which
// lint-disable invalid-characters
had been instituted at Mülheim by the late Rev.
Theodore Undereick, but also on other occasions in the year 1725,
and particularly in 1727, when a great awakening took place in that neighborhood,
and especially in the Duchy of Berg.
Hoffmann being well acquainted with Tersteegen`'s profound knowledge and experience,
// lint-disable invalid-characters
pressed him to speak a word of edification at Mülheim, and other places.
What followed showed with what blessed effects this was attended.
Many, who were in an unawakened state, were so affected by his powerful addresses,
that they attained to a thorough and permanent conversion; while others,
who were already awakened,
were induced by his impressive discourses to resort to him with the utmost confidence,
for advice in every species of temptation, trial, and suffering;
and by his wise counsels, were confirmed in their trust and reliance upon God.

The great number of those who applied to him for advice,
not only personally but by letter, together with his weakness of body,
which had been considerably increased by his nightly studies, compelled him,
about this time, to give up his employment.
It may be asked, from where then did he derive his support?
He had hitherto refused in an affectionate manner,
many generous offers which had been made to him.
A merchant once called upon him, and out of the high regard he bore for him,
offered him an annuity for life; a pious lady, who had never seen him,
appointed him in her will, executor to her property, which amounted to 40,000 florins,
on condition that he would take from it whatever he needed;
a Dutch gentleman offered him a bond for 10,000 florins,
and begged his acceptance of it with tears.
All these, and other offers of the same kind he declined;
but on becoming more incapable of manual labor,
he accepted the love offerings of a few friends, by whom he was cordially esteemed,
and whom he loved in return with particular confidence; besides which,
other friends left him legacies of certain sums in their wills.
By these means, he was not only placed in a situation to supply his own needs,
but also to show his liberality to the poor in a variety of ways;
so that even at his death, some ready money remained, which he directed in his will,
to be immediately divided among some poor followers of Jesus,
and of which his relatives likewise received a part, together with his furniture.

Although he had laid aside his former employment,
he still reserved a species of manual labor to the end of his life.
Having a valuable knowledge of physic, he prepared certain medicines,
which he gratuitously administered to a few friends and the poor,
and which were at length so much sought after,
that he was obliged to accept of the services of an assistant.

About the year 1740, when the Thursday meetings which had been commenced by the Rev.
T+++.+++ Undereick were discontinued,
our departed friend became more generally known by the publication of various works,
which occasioned him many visits.
He also received a call to take a journey once a year into Holland.
A certain individual in that country,
who had become acquainted with him through the medium of his writings,
grew much attached to him, and invited him to come and see him;
but Tersteegen delaying his visit, the gentleman above alluded to,
// lint-disable invalid-characters
resolved to take a journey to Mülheim himself.^
footnote:[This Dutch gentleman was of high rank,
and held a prominent situation under government; he notwithstanding laid his rank,
station, equipage, etc. at the feet of our dear Redeemer,
and led a retired and hidden life with Christ in God,
in a small and humble habitation in Amsterdam, until his decease.]
Tersteegen having received secret intimation of this,
and fearing he might be inclined to spend more time with him than he could spare,
determined not to wait for his visit, but to go himself to him, and after a short visit,
return home.
He subsequently went annually to Holland to enjoy, in the society of this friend,
a few weeks of tranquillity and repose; but this was not of long continuance;
his arrival was generally soon made known,
and friends came from various places to visit him,
and converse with him on the state of their souls.
There were also many,
whom he cordially loved and with whom he maintained a regular
correspondence and an intimate friendship until his death.

Till the year 1746, Tersteegen lodged in a house, where he had two upper rooms,
and where his dinner was brought him.
In that year, he rented a whole house, but continued to reside upstairs with his friend;
a female acquaintance, with her brother and sister-in-law,
occupied the lower part of the house, provided his dinner,
and also cooked at his expense, for a number of poor and sick people.

In the same year, his dear brother Hoffmann fell ill of a disorder in the lungs,
which after a confinement of some weeks, terminated his earthly course,
and conducted him into a happy eternity.
On this occasion, our departed friend gave him many proofs of his love and affection.
He assisted in binding up his wounds, and refreshed him by his frequent visits,
comforting discourse, and ardent prayers, until his death.^
footnote:[Hoffmann had requested our late friend
to return thanks to God for his happy exit,
with a few of his most intimate friends, in his house after his decease.
The following account, which Tersteegen gave to a friend in the country,
dated 30th August, will show the manner in which this took place.
{footnote-paragraph-split}
My late friend Hoffmann having
earnestly desired me to invite his most intimate friends,
a few days after his decease, to meet together in the house where he had lived and died,
to thank the Lord, for the favors he had shown him, and for his final deliverance,
I complied with his request. I was taken however by surprise.
One told it to another, by which means, in two hours, the matter became known,
and I found there, at least according to my idea,
more than one hundred and fifty people assembled, which at first confused me;
but I was obliged to comply, and instead of a thanksgiving prayer,
I spoke for two hours together on Jude, 20, 21. All present were deeply affected,
but the emotion of the senses is at best, only flower without fruit.
Still you may infer from this, that the people here are hungering after the bread of life.
Had I made it known two days, instead of two hours before,
there would not have been room enough to contain all the people.
But I feel myself neither called nor sent to engage in exercises of this nature,
because I am myself only a poor ignorant infant, and neither know nor possess anything,
except in the Lord, and have no control over what belongs to another.]
Upon his decease Tersteegen rented from his relatives,
the cottage in which he had resided, where he lodged and entertained his friends,
who came to see him from a distance,
from which circumstance it obtained the name of the pilgrim`'s cottage,
which it bears to this day.

Besides the many acquaintances which Tersteegen had in the duchy of Berg, at Mettman,
Homberg, Heiligenhaus, and other places, he was also well known at Barmen,
which place he visited for the first time, in the year 1747, after a pressing invitation.
With the divine blessing, many souls were awakened there, through his instrumentality,
whom he visited in the following years, and was likewise repeatedly visited by them.
They could not sufficiently admire his distinguished spiritual gifts.
His love, his long-suffering and patience with the weak and the wavering,
the peculiar wisdom he displayed, in leading everyone to a frank discovery of his state,
his aiding hand in all kinds of trials and troubles,
as well as his powerful manner of interceding in prayer,
remained indelibly impressed upon their hearts.
He gave the following account of the above-mentioned journey to an intimate friend.

I have allowed myself to be induced to accept the
unremitting invitations of an aged couple,
who reside about twenty miles distant from this place,
and who believe they have attained to conviction by means of my writings;
and because they were unable to come here themselves, they have pressed me,
for a year and a half, to pay them a visit.
Their two sons are likewise decidedly pious characters,
and occasionally come over to see me.
It was my intention to have made this journey incognito, but I found it impossible;
for there were not only many whom I had not seen before, in the place where I was,
who were awakened and so deeply affected,
that I found it difficult to remain firm in the midst
of the many tears which were shed by the new converts,
or to part from them;
but I was also constrained to travel about in the duchy of Berg for eleven days together,
and was surrounded with people from morning till night.
I thought myself once a few miles distant from a certain place;
but I was waited for on the way, and conducted into a barn,
where I found about twenty persons, most of whom were unknown to me,
and were desirous of hearing a good word from me.
You may think, dear sister, that I must often forget myself,
both as it respects body and soul; but I should be very ungrateful,
if I did not acknowledge, that the Lord supported me in both, and to appearance at least,
vouchsafes me his blessing.
Towards the close, I experienced attacks of fever, and took such a cold,
that my voice could scarcely be heard.
The Lord then showed me that I ought to return home.
But in the morning about eight o`'clock, when I was on the point of mounting my horse,
I found at least about twenty-five persons assembled,
to whom I could only give a very short address.
Some of them had come from a distance of several miles, for it was in the country.
You see by this, how extraordinary my present manner of life is,
and how much it is opposed to my inclinations.
My ardent love of retirement and repose appears to have
been given me to make the reverse more burdensome,
and perhaps also to serve as a counterpoise to keep me from
entering too deeply and living too much in outward exercises.
I everywhere find a hunger among the people, and there is no one to break unto them;
the customary food no longer suffices them.
He that has grace to pray,
may well entreat the Lord of the harvest to send forth laborers into his harvest.

Oct. 3, 1747.

After public speaking had been for some time discontinued, about the year 1750,
a young student at Duisburg was awakened, who held meetings at Spelldorf, Styrum,
// lint-disable invalid-characters
and likewise at Mülheim, in which he earnestly called the people to repentance.
Many individuals were brought by this means, to a salutary concern for their souls,
and numbers came to Tersteegen to unfold their sinful state to him,
and to be instructed by him in the way of holiness.
His conversation had such a blessed effect upon many, that they obtained,
through sincere repentance, faith in our Lord Jesus Christ; and by his grace,
have continued steadfast to the present hour.
The accounts which he gave about this time,
in confidence to a female friend on different occasions, deserve to be noticed here.

I have been +++[+++says he]
for some days again rather unwell; and think it proceeds from the cold I caught,
or perhaps also from the little rest I have had during the last three or four weeks;
for the awakening which seems to have taken place in several individuals,
occasions me many visits.
On the second Christmas holyday, finding myself pretty well,
I felt at liberty to go to a meeting, and give an address,
which I have not done for above a year.
I have never seen so many present here on a similar occasion.
By this discourse, I appear to have occasioned myself still more visits.
I feel I must spend and be spent.
It were a small thing to put health and even life itself into the scale,
in order to fulfill the good pleasure of God, and be of service to others;
but I confess I have no certainty in this matter.
I do what I can at the time, and ask forgiveness of God,
lest I should have been thereby detrimental to others.
One thing I know, that were I to follow my own inclination,
I would rather withdraw from it entirely, if I found myself at liberty to do so.
The Lord direct us in all things!

Jan.
14th, 1746.

In another letter, he says,

There is, God be thanked, a great awakening and stir among the people here:
for some weeks together, from morning to night,
they were compelled to wait one for another to have an opportunity of speaking with me.
Many were obliged to return five or six times,
before a quarter of an hour could be found to converse with me alone;
and I have occasionally had ten, twenty,
and even thirty anxious souls with me at the same time.
N+++______+++`'s discourses, though plain, are of advantage to many,
who are by this means awakened.
At his request, and that of many who were hungering for the bread of life,
I allowed myself to be induced, at the beginning of the present month,
to hold a meeting with him.
It was a long time since I had spoken in public.
Three or four hundred people were assembled; and the house being filled to the very door,
they placed ladders against the windows in order to hear.
It occasioned a great sensation, and I trust that it has not been without a blessing.
Upon this our clergymen took the alarm, the three Reformed, as well as the Lutheran.^
footnote:[The Protestant church in Germany is divided under two heads,
the Lutheran and Reformed.]
Two of the former went to the magistrates to present their complaints,
and begged that a stop might be put to such meetings.
Of this I knew nothing, but suspected something of the kind,
and felt myself constrained to write to our Justice of the peace,
in order to give him an account of our meeting,
and to beg him to have nothing to do in the matter.
And sure enough, the secretary had already received the order,
to be engrossed and published the day following.
The Justice, who is much attached to me,
and who knew not that I was involved in the matter,
caused the order to be returned from the secretary`'s, and sent it privately to me,
with a very friendly letter, written by his own hand.
Upon which I wrote to three of our ministers,
and represented to them in a serious yet amicable manner, their unhandsome behavior;
offering likewise, with N--, to speak in their presence, with the assurance,
that if they gave their hearty concurrence to it, the church would again be filled,
because the people would then see that they were attached to the good cause;
while on the contrary, at present, the church stood empty.
They then seemed to rely upon the Mayor, who was an enemy to the meetings.
I wrote, therefore, a pretty sharp letter to him,
and represented to him how inconsistently he would act,
if he prohibited assemblies of this nature, and at the same time permitted quack doctors,
mountebanks, gaming-houses, and taverns;
asking him how he expected to reflect upon these things on his deathbed.
In short, the Mayor, as well as the other magistrates gave way,
and acknowledged that I was in the right.

Jan.
1st. 1751

On another occasion he writes,

The awakening here, and at other places still continues.
More are added from time to time, and I am obliged to devote myself,
almost from morning till evening, to converse with pious persons,
either individually or collectively.
Since my last, I have only spoken once from home at a public meeting.
I conceive there were fully four hundred hearers.
With individuals, or with several at a time, I am constantly employed.
Last Thursday, at eight o`'clock, when I had scarcely risen from my bed,
and that with difficulty, in order to answer a letter which I had received by express,
I was told that a whole troop of country people were entering the house,
who wished to speak with me; and before half an hour had elapsed, nearly fifty assembled,
who requested me to give them an address, which I consequently did,
and spoke from Isaiah 55:10. While speaking,
a powerful emotion manifested itself among the auditory;
and had I not imperceptibly and circuitously prevented it,
confusion would have ensued--two persons being seized
with a violent trembling and sinking to the ground;
but these kind of things, I seek if possible, silently to prevent.
During the discourse, one of our preachers came to visit me; he was told below,
that I was addressing a number of friends, who had arrived unexpectedly,
and was requested to go upstairs and hear me speak,
as it would seem he had a prejudice against such meetings.
Upon this, he was offended,
and asked who it was that said he had anything against my speaking, and so went away.
But the same afternoon, he came again.
I told him I had spoken in the morning, and from what text.
On which, he assured me he had nothing against my speaking;
they would willingly grant me permission, but not N+++______+++, etc.

I had previously refused to admit the people in such numbers on a Sunday during service,
thus it would appear they had concerted together to take me by surprise.
After speaking, I allowed some who were in a state of great anxiety about their souls,
to converse with me in private.
Among these there was a widow, who seemed dreadfully agitated.
She threw herself at my feet upon the floor, but I immediately told her to stand up.
Upon this, she confessed her sins to me unsolicitedly which I acknowledged were great.
As she seemed to me to be in such despair,
I encouraged her to tell me all that lay upon her mind,
assuring her that I would keep it secret.
"`What,`" said she, "`keep it secret?
Tell it to the whole world!
I am not afraid of being disgraced in the opinion of mankind.
I would gladly bear the severest torments,
and am willing to be consumed even to a skeleton,
if I may only find favor in the sight of God.`"
You may yourself form come idea of what is to be done and suffered among
so many poor souls from this and the neighboring places.

Children of ten, twelve, and fourteen years old are awakened.
I will adduce only one instance.
A woman who had been some time before awakened and concerned for her soul,
came to me lately with about fourteen others, and brought her little boy with her,
who was about eleven years of age.
After shaking hands at parting with the others, I gave this child likewise my hand,
and asked him if he also wished to become a pious youth,
adding a few words according to the child`'s capacity;
but he seemed to wish not to hear me.
However, on reaching home, he said to his mother,
"`the devil wanted to hinder me from attending to what Tersteegen said;
but yet I heard every word very well, and resisted the devil, etc.`" and since that time,
the boy is become very silent, and goes often alone into the fields or elsewhere,
where he can conceal himself, to pray; and weeps in secret over his sins,
in such a manner, that even his father, who was before opposed to the truth,
appears to be much affected and struck by it.

On these occasions, I must exert myself violently, to keep myself from sinking.
I cannot deny that the Lord has been good and gracious to me in various ways,
and grants me more inward peace and singleness of heart,
in the midst of every disturbance and distraction from without,
than I could even have expected; but of any sensible emotion, I can say nothing;
I sometimes live as if I were dead.

February 23, 1751.

He writes further as follows.

Since my last, the people scarcely ever let me rest.
I try occasionally to withdraw myself by force, but it is of no avail.
Last Sunday, I had scarcely risen from bed,
when I was obliged to address more than sixty persons, who had thronged into the house,
which I accordingly did from Matt. 25:5. After I had finished speaking,
I had to converse with various individuals until evening.
And yesterday morning, after I had passed the whole night in a fever,
at least two hundred and fifty people assembled in the corn loft, and the room adjoining,
to whom I spoke with the Lord`'s gracious assistance,
from Gal. 1:3-5. I have been also obliged to speak this morning early,
without knowing of it a quarter of an hour before; but now I feel myself quite exhausted.
I spoke today on the last words of the Lord Jesus,
"`It is finished!`" and comforted myself with the hope,
that my toils and trouble would also soon be finished.
But I expect now so to arrange matters,
as to be freed from the necessity of giving a formal address.
Were the meetings to take place regularly, we should not be able to find sufficient room.
Between both, I am either engaged in receiving visits,
or in writing to friends at a distance.

April 9th, 1751.

In another he says,

Such strange events have occurred since my last, that I have been unable, before today,
to reply to your agreeable letter of the 9th of July.
You have been already in part informed by our friend S+++______+++,
of what happened during my journey in the duchy of Berg,
where I was detained a week longer than I had intended,
in consequence of the number of people who flocked together.
I was obliged, contrary to my wish, to speak there several times in public.
After my return, I reflected upon a plan to lighten the burden in some measure;
to accomplish which, I determined on holding the meeting once a fortnight,
if the Lord permitted;
for otherwise I was under the necessity of speaking as often as the people came to me.
But as they know in their own minds, when I purpose speaking,
the attendance is so numerous, that I am at a loss for accommodation for them.
The day after Mr. S+++______+++`'s departure from hence, the numbers increased,
so that I have not yet room enough, although I can accommodate nearly six hundred people;
for they came from a distance of fifteen or twenty miles, with an earnest desire to hear.
The magistrates had already taken the alarm, but it is now over.

I said to them, if you find yourselves at liberty, in conscience,
to prohibit my speaking, I shall find myself at liberty that instant to obey you,
which I would not do, were I certain that I was divinely called to it.
They answered that they did not wish to prevent me,
but the people assembled too numerously; I replied, I ask no one to come,
nor will I tell anyone to go away.
Finally, they were willing to let me speak, but not N+++______+++ and others.
I keep myself quiet, nor indeed did I go to the magistrates on my own account,
or because they sent for me; but voluntarily, and to prevent the evil,
that was preparing for others.

August 20th, 1751.

In a subsequent letter to the same individual, he says:--

I have still something singular to relate.
The day after I forwarded my last, the friends at C+++______+++,
very unexpectedly sent a coach to the banks of the Rhine, to fetch me.
Being very weak and confined to bed, I sent our friend S+++______+++ there with a note,
and entirely declined going.
The friends then came here with the coach,
and the next day I was obliged to resolve upon accompanying them.
As soon as it was reported that I was in the town, the Mennonite Consistory assembled,
without my being aware of it, and sent their two preachers to me,
to request I would fix a day when I would preach in their church,
as they knew I would not stay till Sunday.
This request, as you may easily suppose, appeared strange to me;
I nevertheless resolved to accept it in God`'s name, as an intimation of the divine will.
On Wednesday morning, 25th August, the two ministers came and conducted me to the pulpit.
On entering the church, I found it crowded with people of all persuasions,
but principally of the Reformed and Mennonite persuasions;
and the Lord enabled me to speak on 2 Peter 3:2.
If I have pleased God by this piece of temerity,
as much as the hearers, all will be well.
The people were deeply affected, and some so much so,
that it is to be hoped the impressions will be lasting.

From the time that the number of those who were awakened,
and such as hungered after the bread of life so much increased,
our departed friend was again induced to speak in public.
With what impression, divine power, and unction this was accompanied,
many who are still living can testify.
In 1751,
he wrote out one of his discourses on those words in 2 Cor. 5:14.
"`For the love of Christ constrains me,`" and published it.^
footnote:[A translation of this discourse will be found in the body of this work.]
Upon which, the inquiry for them was so great,
that eight writers stationed themselves upstairs, where they could hear distinctly,
and wrote down the words from his lips.
By this means, thirty of his discourses have been collected,
which were subsequently published under the title of Spiritual Fragments (Geistliche
Brosamen.) The following letters give some account of the many discourses he delivered,
and the visits he had to receive at that period.

Up to the present moment +++[+++says he]
I can scarcely use my head or my eyes, and my hand trembles very much;
the little rest I have had, owing to the concourse of people,
may have been the principal occasion of it,
to which must also be added the many letters I have to write.
I cannot think what the people seek from such a poor creature.
A short time ago, a person totally unknown to me, but a true Nathaniel,
came nearly two hundred miles on foot, in bad weather, to visit me,
to whom I could only spare a couple of hours; but who, on such occasions,
can withdraw himself entirely?
On the 25th of February I had again a visit of about twelve persons from the country.
No sooner were our friends here aware of it, than I had the house full,
so that I had to address some hundreds from the song of Simeon, ("`Lord,
now let your servant depart in peace, for my eyes have seen your salvation.`"
Luke 2:20) Some say, but for what reason I am ignorant,
that I have preached my own funeral sermon.

It is at least my wish to separate myself from every creature consolation,
and committing myself entirely to the guidance of the Spirit of God,
be found waiting solely for the salvation of Israel.
And had I even Simeon`'s righteousness, piety, revelations, and every gift he possessed,
I would, with him, willingly forget and forsake them, living or dying,
in order to exchange them for the child Jesus, Israel`'s only consolation.
It is matter of astonishment, adoration, and delight,
to see how the Lord can induce us to let everything go; everything appears so frivolous,
unsatisfying, trifling, and superficial--even good and spiritual things,
which formerly afforded such gratification, and of which we were so tenacious, but which,
for that very reason, served only to interpose between us and God, and were injurious,
because they were held so fast.
Jesus alone is sufficient, but yet insufficient,
when he is not wholly and solely embraced.
O that it might please the Lord to confirm and establish the hearts of many,
who are concerned for their immortal souls,
and enable them to commit themselves entirely to
the guidance and influences of his Holy Spirit,
who in due time would lead them to the true temple of God,
where they might substantially clasp the Savior in the arms of their spirits!

March 20th, 1753.

I contemplated the approach of Christmas with anxious feelings,
being fearful of receiving many visits,
and therefore occasionally made it known that I was too indisposed to see company.
However, a few days before Christmas, I felt somewhat better;
upon which many came from a distance whom I did not expect;
and among them were several whom I had not seen before.
The Lord enabled me to speak with much composure at two different times, on Isaiah 9:6,
"`Unto us a child is born, etc.`" although during the night I was very feverish.
The place was quite filled with people, and among them was the present chief magistrate.
He sent to inquire if I intended to speak: I replied, I thought of doing so;
on which he sent his servant to desire a seat might be reserved for him.
After sermon, he said to me among other things, "`not a single word has escaped me,
and I shall attend you tomorrow.`"
He referred to the divisions of the discourse,
and assured me that he was very well pleased.
I hear also that he has said to others, "`Those who now revile, must only do as I do,
and come and hear for themselves.`"

I cannot say that I have any foreboding or particular impression on my mind from God,
regarding my departure out of this world.
I speak and think as I feel at the time,
or with the eye of reason contemplate the consequences of this or that complaint,
although on such occasions, I very often fall short of the truth,
and cannot comprehend the wonderful manner in which the Lord deals with me;
to him alone be the glory!
The great number of friends here and at other places, occasions me continual employment,
and I find it difficult to withhold myself from them,
particularly from sick and afflicted persons, and therefore hazard it.
As we are a spectacle both to angels and to men,
and as you may easily suppose all sorts of cases occur,
I cannot always spare or take care of myself.
It occurs to me here, that at our last meeting, which was the first in the present year,
I expressed myself in the new year`'s salutation to the following effect: "`If it be,
therefore, my lot to continue somewhat longer, like some small and glimmering star,
in the firmament of this our church, I will not entirely withdraw myself.
I know what I am, and how completely I depend upon the Lord; but neither the fear of man,
nor the suggestions of the flesh shall stop my mouth.
I hope that the consciences of you all will testify now, and in the presence of God,
that I have directed you to Christ, and not to myself.
Give me, then, as in the Lord`'s presence, the hand of fellowship afresh,
and support me by your intercessions, and your faithful walk with God.
But still I must say, my dear friends, that some among you, during the past year,
have often grieved me to the heart, and discouraged me: that was not right;
may the Lord atone for it!`"
These last words touched some of them to the quick,
who afterwards came to ask forgiveness.

About the year 1756, when the attendance was so numerous,
that he was obliged to fill five or six rooms in the house with his voice,
our departed friend sustained an external injury from his exertions in speaking;
on which account he was obliged to discontinue his public addresses,
and also his journeys into the country, excepting an occasional ride in the neighborhood,
to Spelldorf, Duisburg, and Essen, to give his debilitated frame a little exercise,
and at the same time to visit his friends there.
In fine weather, in the spring and summer, he also took a little exercise on foot,
in company with a few other invalids,
particularly when visited by friends from the country.
He generally proceeded with them to a wood at a little distance, where they drank tea,
while listening to his edifying conversation, and occasionally sang a hymn,
after which he concluded with prayer.

Here we might close the history of Tersteegen`'s life,
and immediately proceed to the relation of his last moments;
but it will doubtless be of material service to the reader, if we place him,
in some degree, in a situation to become better acquainted with his peculiar gifts,
the distinguished grace which was imparted to him,
and the spirituality of his views and sentiments.
His writings, and particularly his discourses,
printed under the title of Spiritual Fragments,
in which the reader is not long detained with the shell of human wisdom,
but is immediately presented with the kernel,
sufficiently show how greatly his understanding was enlightened,
and the deep insight into the word of God, which had been vouchsafed to him.

His writings also evidence, in an equally luminous manner,
his intimate acquaintance with God and his ways.
Among others that might be mentioned, the reader is directed to that noble hymn,
which begins, "`O God,
you are not known aright,`" and to another he wrote some years after, "`Rejoice,
the Lord is God supreme.`"
In both of these, when the writer`'s divine and elevated views of God, his being,
properties, and perfections are contemplated with silent devotion,
the most pleasing evidences will be found of his experimental knowledge.
He could say, and on several occasions did make use of the much-implying expression,
"`I thank God, that he has permitted me to live so long,
as to enable me to become acquainted with him;`" words, which among others,
he repeated with great emphasis, when lying ill in the year 1738,
without the smallest hope of recovery, to a friend who took a last farewell of him,
adding, "`with respect to myself I am perfectly at ease in God,
and also with regard to my writings, which I leave with you.
I feel, respecting them, no manner of anxiety or inward reproof,
as though they contained anything doubtful or erroneous.
All that I have written, I have myself experienced as important truths;
and can therefore enter eternity with comfort.`"

In another place he writes, "`When I leave this world, I shall enter the next,
as a poor and unworthy creature,
who desires and wholly trusts for acceptance through grace alone,
and that in a more than ordinary manner.
In the mean time, I thank God,
that he has allowed me to live so long as to enable me to know him internally;
this notwithstanding my wretchedness, I cannot deny,
and for this I desire to praise the free grace of God.
I long for an eternity, that I may suitably glorify him for it.
O what a treasure it is, to set aside all spiritual light, and the gifts of grace,
in order solely to know that God is what he is; it is indeed eternal life to know him!
The desire of men to know much, even in spiritual things,
is a powerful proof that they know not God in reality.
God is in every way all-sufficient;
he alone can satisfy and rejoice the capacious powers of the soul,
and that entirely and eternally.`"

It cannot be otherwise than agreeable to the reader,
when the following extracts from certain letters
of our departed friend are laid before him,
as obvious testimonials of his superior experimental knowledge.

I have at present to inform you, that it has pleased the Lord to visit me with sickness.
In the beginning of my disorder, I lay and sat as if stupified, without feeling,
and even almost without any recollection of God, or of my own soul.
At present my mind is led with silent pleasure, to contemplate the existence of God,
his goodness, wisdom, power, holiness,
etc. all which infinite perfections are in the highest degree lovely and adorable;
so that it is therefore true, that God, and what is in him, and all his works and ways,
is the proper food and happiness of a created spirit.
In him is all my treasure.

February 1st, 1746.

We know that God is alone supremely good;
that he bears with his creatures and his children in Christ,
prepares them for the enjoyment of himself with incomprehensible condescension,
and loves them with peculiar tenderness.
We are nevertheless, so much inclined to rest in ourselves, and to return to ourselves,
that I have often been astonished at my own weakness.
I have gone to school so long to the best of teachers,
and am already employed to give others their lessons,
and yet I continue myself such a helpless infant.
At present, to all appearance, I can, with singleness of heart,
commit myself and all I have to the Lord.
I can let everything go, and still feel composed.
I am poor, yet in a wealthy place.
I am weak, but contented.
Those labors, fatigues, afflictions, trials, and dangers,
which would at other times appear to me as insurmountable,
did not the Lord keep me from contemplating the future, I can now easily forget,
nor do they any longer cause me that anxiety of mind,
which is otherwise so peculiar to me.
But I must not make the picture too glowing;
perhaps it appears different in the eyes of the Lord.
I leave it to him, be it as it may.
It is of little importance how it is, if it only be as God pleases.
I neither can nor will depend on anything except on him alone.`"

February 9th, 1748.

If I were to explain to you how I feel in my weak state, I would say, I do not know;
and was perhaps never less conscious of it.
Methinks, I believe pretty deeply, the total insufficiency of self and of created good,
both internally and externally; but at the bottom, I am neither disquieted, apprehensive,
nor afraid, although I do not know the reason of it.
On account of the weakness of my head, I am often unable either to think of God,
or of my own soul; but I know that God is, that he is the great, the good,
and the ever-blessed God.
The mere recollection of this, when the Lord affords it me, refreshes me much,
and causes every difficulty to disappear immediately.
How ought we to rejoice that he is such a God, that he is all goodness, perfect,
infinitely glorious and happy, and sufficient to make everything in us good and happy.

March 8th, 1748.

How wonderful, how incomprehensible are the ways of God!
How contrary to our expectations!
No sooner do we think of fetching breath a little, than we are again chased out.
We never cease losing, till we become so poor, that we have nothing more to lose,
and so ashamed, that we dare no longer look about us.
Let us only persevere in God`'s name!
May he alone be exalted, glorified, and well-pleased,
that by thoroughly forsaking ourselves, we may enter into his felicity, his rest,
and his joy!
We must at length be brought to look on, as innocently as an infant in the cradle.
It becomes us cheerfully to consent, deeply to adore, and cordially to say,
"`the Lord is good and gracious;
all his ways are mercy and truth,`" without examining on what the expression is founded.
Even in the full consciousness of our utter poverty and wretchedness,
we cannot help wishing that every soul were equally poor.
O how seldom do we meet with those who are entirely God`'s,
and yet how happy are such characters!
The Lord willingly becomes their portion, their treasure, their all.
That this may be the case with us, is my sincerest wish.
Pray also for me, my dear sister, and beg the rest of your family to do so likewise,
for I have need of it.

October 22nd, 1751.

I am lost in adoration,
when I reflect that God has selected such a way to eternal felicity,
as takes away everything from the creature, and gives it all to God, and consequently,
sweetly compels us to cleave most closely to him, to abide and live in him and upon him,
and to continue always poor, that we may in reality possess all things;
a way for children, but only for naked children--a way which the wise overlook.
So long as we desire to possess and retain, the road is narrow;
and he who seeks it at a distance runs past it;
while he who follows the thread of love which is thrown to him, finds it near.
May the Lord Jesus himself, proclaim this acceptable year to the poor!`"

We seldom see each other face to face,
yet still our hearts tell us that we belong to each other, and to one family.
Our hearts rejoice that we are still together on the way,
and that we possess that in each other, which we do; at least I find it thus in me; and,
next to God, I ascribe it to the prayers of his children, that I am still what I am.
God must be a very all-sufficient good; for I know that all,
who have become a little acquainted with him by experience,
cannot do otherwise than cordially love and praise him,
even should they afterwards walk for years together in barrenness and darkness.
I know, likewise, how to say a little on the subject.
I must also occasionally sigh beneath my burden on the way,
it is sometimes so heavy to bear; the heaviest part of it is but little seen externally.
At present, I have much to bear, both inwardly and outwardly;
although those that hear me, may be led to suppose that I enjoy continual sunshine.
Still, what can I say of God, but good, who in faith`'s severest trials,
can yet support the soul, and does so in reality,
lest we faint by the way (1 Kings 19:8). He that can commit himself wholly to God,
and venture all upon him, will never come short; and by so doing, we honor him.
In us there is nothing but weakness and wretchedness;
but in Jesus there is abundance of everything we need.
How true this is! and yet it is only known in the
degree in which the former is in reality felt.

8th March, 1754.

Hitherto has the Lord helped me! and his help hitherto encourages
me to hope that he will help me to the end.
O what a good and faithful God!
Ought we not to love him entirely, venture all in his name, and, with closed eyes,
blindly commit ourselves to his guidance?
The Lord is well aware that our hearts can best be overcome by love;
for which reason he does so much for us; and each of us may, for himself,
look over the large account of the lovingkindness and faithfulness of God.
God commends his love towards us in so many particulars,
and this is his last and greatest attempt to recover man.
If the love of God, and the blessings which flow from it,
do not constrain us to a reciprocal and cordial love to him,
and to a courageous progress in the path of holiness,
certainly no other means will accomplish it.
My heart still overflows with gratitude for all that goodness, refreshment,
and divine support, which I have enjoyed in my late journey,
and in your society--it is this which induces me to write in this manner;
and from your kind letters I observe, my dear sister, that you and others feel the same.
The Lord himself tune our hearts to praise him, and to glorify him in all our actions!
I feel that more of my heart remains with you than before;
and that bodily absence does not, and cannot part us.

July 5th, 1754.

I cannot express to you, my dear sister,
how more than ever worthless and contemptible this life,
and the things of time appear to me, and I can often grieve like a child, that mankind,
and even pious people, trifle so much, and do not employ their time better.
It often gives me pain, to see that God, who is such an ever-present good,
should be so little sought, known, loved, and glorified as he deserves.
Compassion, at one time, causes me to speak of it; at another,
I feel inclined to give up everything, in order not to lose my own time,
and to live more for God and eternity.
But the will of God must be my food and drink.
I can often lose myself in it, and forget all my childish sorrow.
There are still not a few persons hereabouts,
on whom I can reflect with joy and gratitude to God.
"`Truly the Lord is good and gracious to his people.
He is lovely in himself, and lovely in his children.`"
(Ps. 16:2)

November 1st, 1754.

His views of the evangelical truths which belong to the economy of human redemption,
were as pure as his insight and experience were great.
To be convinced of this, it is only necessary to peruse in connection, his writings,
particularly The way of Truth, with an impartial mind.
Even on the outset of his conversion, he contemplated the fundamental truths of religion,
in a pure and scriptural light.
Of this, the following are proofs.
A credible person, still living, relates, that on visiting him in 1727,
for the first time, he accompanied him part of the way back, and on taking leave of him,
expressly recommended the four following things--the atonement of Jesus,
the words of Jesus, the spirit of Jesus, and the example of Jesus: an obvious proof,
that he directed those with whom he associated, solely to Jesus Christ,
and declared him to them at all times,
as the sole procuring cause of our salvation and complete redemption.
Another instance--A certain individual once accusing him,
that his views and motives were not sufficiently pure, he answered,
"`how heartily I rejoice, how happy do I esteem myself,
when I am counted worthy to give testimony to the sure, and essential,
and precious truths of that internal religion,
which is regarded with so much suspicion by many pious, as well as impious people!
Methinks it would be an inexpressible consolation to me, if in my dying hour,
and when I shall have to appear in the presence of God,
I could once more proclaim to all the world, that God alone is the fountain of life,
and that there is no other way to find and enjoy him,
than the narrow way of inward prayer, self-denial, and a life hid with Christ in God,
opened out to us, and consecrated by the death of the Savior.`"
Many of his hymns in The Spiritual Flower Garden
show that the sentiments and views of the author,
and the ground of his faith were pure and unadulterated.

He was well grounded and settled in the doctrines of salvation,
of which he had such a clear perception.
The experimental insight which was granted him, after his five years of inward darkness,
remained subsequently uninterrupted, except that he obtained, from time to time,
a more practical acquaintance with them.
If his letters are perused,
an intimate harmony will be found to prevail from first to last,
except that those of the latest dates appear milder,
and possess more of the divine unction.
Our departed friend was sought after by all parties, but would unite himself with none,
except with such as sincerely endeavored to live according to the written word of God,
and the teachings of his grace.
He never allowed the light and knowledge of the truth which he possessed, to be obscured,
even when it was ill received.
He wrote as follows to a Reformed minister, whom he had cautioned against the Moravians,
but which caution the latter had taken amiss:

Ought I to speak otherwise than I feel, as is now so much the custom?
I have re-perused and examined the letter (namely,
that which he had written to the minister) in the presence of God, but I neither can,
nor ought, nor will I, say that I acknowledge it contains erroneous sentiments;
even when all the world, as in your letter you appear to do,
should look upon this holding fast of fundamental truths, as sectarianism,
and lack of poverty of spirit.
No, O Lord! never allow me to increase the sinfulness you already see in me,
by such shameful infidelity, as the giving up,
or departing a hair`'s breadth from the dear deposit of that truth,
which you have committed to me, out of weakness or hypocrisy,
because this or the other good man, or set of people were opposed to it.

He could be thus confident in the expression of his sentiments on subjects of this nature,
because a peculiar gift of trying the spirits was granted him.
A few instances of this may not be disagreeable to the reader.
In his earlier years, he was frequently attacked by strange spirits,
and supernatural influences, which he ascribed to his having associated with some,
who stood in connection with them.
At this period, when he left his work for the purpose of private prayer,
he was seized with such a shaking, that every limb trembled.
Being conscious, however, from his knowledge of the divine character,
that this was contrary to it, he never gave way to this strange, disorderly,
and terrifying influence, but returned to his work.
After repeating this a few times, the trembling ceased, and the temptation was at an end.

Another instance: A female in an ill state of health,
imagined that she heard a supernatural voice calling upon her to arise and pray;
but it being in the winter season, her weak frame could scarcely support the exertion;
she therefore consulted our departed friend on the subject,
who advised her not to rise in the cold, but when she thought herself again called,
instead of getting up, to resume her devotions in bed;
upon doing which she heard the supernatural voice no more; and other singular things,
which had previously occurred, also ceased.
To these, the following relation may be added.

A friend of his once visited him, who was very intimate with a person,
who possessed a great degree of filial devotedness to God,
but who had seen many extraordinary visions,
and to whom many strange things had occurred; she likewise said many edifying things,
and foretold events, some of which were to take place after her decease.
These, the friend above-mentioned communicated to Tersteegen,
who gave him the following reply: "`Pay no attention to all these extraordinary things,
which are only dangerous, and tend to hinder a growth in grace.
I cordially admire the substantial change which divine grace has wrought in her,
but you and I will live long enough to see that nothing will follow of all these things,
however desirable they may be.`"
The result confirmed this opinion.
After her decease, the friend above alluded to, visited him again,
and expressed his sorrow at not having paid more attention to his advice;
on which he said, "`this event will be useful,
and serve as a preservative to you in future,
to keep you from being carried away by such singular and extraordinary things,
and to pass them by.`"
The good man, however, despised no extraordinary gifts, light, or visions;
but his advice was, that they should be carefully and thoroughly examined; because,
persons who gave themselves up to them,
might be easily deceived by the influence of strange spirits.

Tersteegen`'s gift of trying the spirits,
manifested itself particularly in reference to the Moravians.
That sect of christians had given themselves all
possible trouble to bring him over to their principles,
in the hope that many others would follow him;
but God did not leave him without the assistance of his light,
and afforded him the grace necessary to prove that people.

Count Zinzendorff did all he could to gain him over to him.
At first he attempted it by letters, written to him in the tenderest manner,
which were sent open to him, by some of the brethren.
At length, in the year 1737, one of their principal teachers, a very able man,
came to him, threw himself at his feet and implored his blessing, in order,
in this manner to win his affections.
But notwithstanding all this, he remained firm to his principles,
and so little did he allow himself to be deluded by caresses of this nature,
that on the contrary, he brought many, who had already joined themselves to that sect,
to a better understanding,
by laying before them the dangerous consequences that might easily arise from it,
so clearly, that they made no scruple to leave it again.^
footnote:[At the commencement, the Moravians were guilty of many inconsistencies,
which were afterwards amended.]

The views which Tersteegen entertained of the Moravians,
brought on an unpleasant correspondence with a friend of his, a Reformed minister,
in the North of Germany, who stood in connection with that sect;
he wrote to him under date, 6th of March, 1750, among other things, as follows:

I believe that the sect of the Moravians is not agreeable in the sight of God;
I believe that of them which I mentioned to you personally,
and what I have written to you regarding them.
And in order to be brief, and not to vex or perplex you by entering into details,
I believe that it is true and no fable,
what Abbot Steinmetz says of them in his last publication,
with which you are also acquainted; and that for this and many other things,
they are justly blamable;
of which kind of errors and thoughtlessnesses I can never approve or assent to.
It is not because I am ashamed of their suspected name,
that I correspond no longer with the Moravians, much less in order by so doing,
to exclude every well-meaning person from their society, as you erroneously suppose;
but partly on account of a repugnance to their chief
mistakes which are sufficiently known,
and partly from the fear of walking in a broader road,
than my Redeemer and all his saints have trodden and taught.

The reason why I correspond no longer with those who associate much with them,
or stand in connection with them is,
that because I write in a brotherly and familiar style, the Moravians everywhere assert,
that I have joined myself entirely to them, and that my letters serve to allure to them,
such as are attached to me, etc.
Such has often been the case with myself and others.
I hope, indeed, they will gradually perceive their error, and amend themselves,
to which the mystery of the inward and outward cross,
which is so entirely unknown to them,
may perhaps serve as a wholesome medicine for their humiliation.
It is true I have received direct information from the Hague,
of the state of things there,
and what new rules and regulations have been made with respect to improvement;
nevertheless, as their evident mistakes are not only made known to the world,
through the medium of the press, by their opponents,
but are boldly maintained by their principal teachers, in language not to be mistaken;
and as the coarse levity of their ministers and members is,
alas! manifest and undeniable,
to the reproach of the precious blood and wounds of Jesus Christ,
it will be difficult for them to extricate themselves in the usual manner.

Flat denial, tortured replies, pleasantly skipping over, nay,
even mere improvement will not help them out of the labyrinth in the least;
but if they really wish to restore to God his glory, to attain peace of conscience,
and find favor with men of understanding,
they must humbly and openly confess and retract their errors and mistakes,
and entreat forgiveness for the offense they have caused.

He notwithstanding let the Moravians see his impartiality
towards those who were converted to the truth,
to whatever denomination they might belong.
On an important occasion, in the year 1741,
he felt himself induced by the community above-mentioned, who much courted his attention,
briefly to express this impartiality in a letter, of which the following is an extract:

My sentiments and my religion are these, that as one who is reconciled to God,
through the blood of Christ, I allow the spirit of Jesus, by means of mortification,
affliction, and prayer, to lead me away from self, and all created good,
in order that I may live safely to God in Christ Jesus;
and cleaving by faith and love to him, I hope to become one spirit with him,
and to obtain eternal felicity through his mercy in Christ alone.
I have one and the same religion with all those who are like-minded,
and love them as the children of God,
equally as cordially as those who belong to the same persuasion,
and are of the same sentiments with myself.

In other respects, I am perfectly satisfied, when with respect to non-essentials,
each one chooses that particular path for himself,
which he deems the most suitable for the attainment of the end he has in view;
and can love all such, who do not go to work in hypocrisy and sectarianism.
I therefore heartily esteem all those among the Moravians,
who are of the sentiments described above, and am united with them as children of God.
But I have nothing to do with that which distinguishes
the Moravians from the rest of the children of God;
nor do I by any means, accord with them in it.
It grieves me much, that there are already so many divisions in the religious world;
but I am much more grieved when new divisions are created.

This impartiality Tersteegen invariably manifested.
Being once interrogated by one of the three pious Reformed ministers,
with whom he was intimate,
and with whom he associated and corresponded in a fraternal manner until his death,
of what religion the people were who came to him, he replied,
"`I ask not from where they come, but where they are going.`"

The intimate acquaintance with God and divine truth, which Tersteegen possessed,
influenced his sentiments towards him.
The presence of God appeared to be deeply impressed upon his heart.
He knew that God saw all that passed within him;
he therefore laid open his inmost soul to this sun of righteousness,
in order to be enlightened, warmed, and renovated by its beams.
Hence his actions proceeded not from a constrained obedience,
nor from the impulse of his own spirit,
but were the result of the influence of the love of God.
Besides this, he exercised himself constantly in looking unto God alone;
in order that by the contemplation of him, he might become more and more enlightened,
and imbibe fresh vigor from the immediate presence of his God and Savior.
He also recommended to others the divine presence in the soul, as an especial favor,
and at the same time reminded them,
that light from above is not the result of our own efforts,
but must be produced in us by the sweet, powerful, and vivifying presence of God;
and this he endeavored as much as possible, in all his writings,
to impress upon the minds of his readers.
On these occasions he also called to their remembrance,
that besides the special presence of God within us,
we must likewise believe in his universal presence that
God fills heaven and earth--that he is about and in us,
and has his hand in all the events and circumstances which occur to us.
"`It is true, there are seasons,`" said he,
"`in which God withdraws his lovely presence from us for a while,
or in which it is concealed from us by outward extremity, deep affliction, fear,
and dread; it is then necessary to believe, in the absence of feeling,
that God is present,
even under such circumstances--that his paternal love overrules all things for our good,
defends us from a variety of evils, and graciously supports us under all our trials.`"

He lived at the same time, in habitual dependance on God and his guidance,
as is evident from the following letter:

May the divine promise, "`I will hedge up your way with thorns, and make a wall,
that she shall not find her paths,`" (Hosea 2:6) be fulfilled in our experience!
Let us rather suffer a thousand afflictions with God, than walk in our own way,
even were it in the smallest degree.
I have experienced the fulfillment of the promise of God above-mentioned,
at various times, in various situations, and in various ways.
In the beginning, I often felt much anxiety, trouble, and dismay,
after having gone astray, until I stood still,
and was aware that I had done something displeasing to God.
I afterwards experienced an inward feeling, which by its unction,
completely soothed and contented me; and the dissatisfaction I found in everything else,
was the barrier, which caused me to turn again.
At present, I can in fact say nothing on the subject;
I pass my life in the best manner I am able, and have, on the whole,
little certainty whether I be going right, and what it is that thus preserves me,
and hedges up my way; but still, methinks, I am really preserved.
When I can be contented with my poverty and insufficiency,
and with the situation in which I find myself at the moment,
I then seem to be at home and at rest.
At such times I am well contented,
although I may not be clearly aware of the operation of divine influence within me.
But if I do not remain in my state of nothingness,
or if I seek and wish to be something else than what I am, I become confused, as it were,
in all I do, and everything appears gloomy and difficult to me, without knowing why,
until I return.
This confusion, difficulty, etc. are therefore the thorns,
from which I am most preserved, when most unable to do anything of myself.
I will then be gladly weak, in order not to run without God,
that his power and glory may be perfected in my nothingness.
Thanks, and praise, and adoration unto our God, who is our faithful guide,
and who causes us to become more and more attached to the salutary truths of our nothingness,
and his all sufficiency!

January 15th, 1745.

May Jesus, himself,
by his Spirit guide us into the way of all truth!
(John 16:13) For we are like foolish children,
who when left to themselves, continually err from the way,
and cannot depend upon yesterday`'s light.
Methinks I become daily more foolish and ignorant,
and am therefore astonished that I am still good for anything,
or do anything in a proper manner.
But experience will teach us, that an unceasing dependance on our internal guide,
will lead us entirely right, although it may not appear to us to be so;
and that we soil and spoil everything when we do not rely wholly upon him,
and are desirous of guiding ourselves by our own light and wisdom.

January 14th, 1746.

I wish to be found faithful and not slothful in that
which the Lord gives me to see he requires of me.
I desire also to be in continual readiness, again to sacrifice, forsake, and lose,
as it were in God, all my so-called good intentions, good will, and good inclinations.
O what profound peace results from thus willingly letting everything go,
which we possess short of God!
We then enjoy all things, while desiring nothing, or while longing solely after God!
I think, and sometimes say, "`May I be deprived of everything I wish for,
beyond the time and place at the moment!
Those who are naturally indolent and unfaithful,
often imagine themselves in such a state, and endeavor to imitate it;
but you know as well as I, that the Spirit of Jesus can alone impart true resignation,
and every other fundamental virtue.
The pure influence of this vivifying power,
which is so exceedingly near us is alone able to destroy self,
and soften and allay the ardent fire of nature,
so that we can run with patience (Heb. 12:1),
and sit still without being idle (John 11:28-29); because in this manner,
Christ himself becomes our will, our life, and our delight.
How happy therefore are those souls, who walk in the way of the heart,
and silently retire within themselves, waiting, praying,
and giving place to the operation of him, who alone gives life!
Perhaps a little while only, and we shall meet each other in that blissful eternity,
which is our native country, with unspeakable joy,
to the infinite praise and glory of our God, who has called us,
and permitted us to meet in this land of exile.
Amen, Jesus!

August 3rd, 1753.

How quietly I can sit down, when my work is done!
What then will that rest be, which we shall eventually enjoy!
Therefore let us not be weary in the service of so good and faithful a master,
whose service is itself our happiness already.
It is true that all our performances are poor, unimportant, and imperfect--let us,
therefore, not take them into account, but regard them, not so much as a duty,
but as our happiness and salvation.
If we were to delay doing good, till we could do it perfectly, we should wait too long.
It is a maxim with me, that a man should go forward, even though imperfectly;
let such a one only persevere in praying, suffering, denying himself, being faithful,
etc., although much may still be mingled with it, which requires to be separated.
These ought ever to be our sentiments.
A childlike heart willingly and daily strives to improve,
and rejoices when anyone shows it its failings.
"`The Lord guides the meek, (namely,
those who are glad to be told of their faults,) and teaches them his way.
He is a buckler to them that walk uprightly.`"
(Prov. 2:7) The firm and sincere resolution and determination to serve the Lord,
is itself sufficient to rejoice the heart; what then,
will the progress and termination do?
It is a dangerous temptation of the adversary when upright minds allow themselves to
be completely cast down by the unbelieving (I had almost said proud) view of their infirmities,
in the performance of good works; such characters ought only to plead guilty,
humble themselves, and go forwards.
He who loves and exercises prayer will, in due time,
be gradually translated from self into God--from
the impure and imperfect working in his own strength,
into a working through God and for God.
I only wish that all, from the very commencement of their way, would consider godliness,
or the service of God, in a proper light, that is, as happiness and salvation,
to which we are called, and which God deigns to grant unto us;
and that the sooner and the more they forsake themselves
and the creature by prayer and self-denial,
they the sooner approach unto God, even though they neither see nor feel it,
and consequently become more happy;
for God himself is essentially our salvation and our end.
The more cordially and completely we live to God,
the more happy we become from that moment.
O this is so exceedingly true!--yet he who does not
seek after communion with God through prayer,
cannot properly understand it.

March 11th, 1755.

He also resigned himself entirely to God.
On this subject he writes as follows:

I cannot say much of myself, for it is a subject too dark for me; I leave it all to God.
I am constantly obliged to write, speak, and do much,
which does not appear to accord with my state of mind.
I seek nothing, but do not wish to escape anything.
In all cases, I only wish to follow the Lord, but cannot say that I do so,
and am far from thinking that I labor solely in the Lord, although I desire to do so;
I am perhaps hindered by associating and corresponding too much with others;
but of this I dare not think.
I must make a complete surrender of myself.
If I have any merit, it consists in my weakness and wretchedness,
for these appear to have assisted me much,
and help me still to commit myself wholly unto God,
after having sought in vain for support from my own faithfulness.
I see nothing else within me, but am not disturbed on this account;
on the contrary I possess a very tender,
but at the same time general impression of the infinite goodness and loveliness of God,
yet still the relish of it is not afforded me.

February 27th, 1742.

Jesus, close our eyes in life and death,
that we may no longer contemplate ourselves and what regards us,
but commit ourselves nakedly, blindly, and entirely unto you,
assenting willingly and sincerely to our own nothingness, and thus,
in the artless carelessness of faith, live and die with you and in you!
Amen.

August 29th, 1741.

The more that soul and spirit are divided asunder
by the quick and powerful word of God (Heb. 4:12),
and by his purifying dispensations, the more undisturbed will be our peace,
in the midst of changes and vicissitudes, when God leads us into them.
However, as it regards myself, I find I am deficient in every point.
I do, or strive to do, as well as I can.
I wish to live to, and to follow, not myself, but the Lord.
I experience that he is unspeakably kind to me in all things.
I occasionally perceive that my mind is at peace,
but at other times I am not aware of it, and must make myself content.

January 25th, 1748.

As long as union with God is sensible, the communication is only made through the senses.
I find myself so weak and destitute, that with regard to myself,
I would rather write nothing respecting the state of my soul.
But it is nevertheless true,
that I occasionally seem to experience something of a divine communication,
which is exceedingly precious, but which lasts only a few moments.
We must seek to do nothing and to retain nothing,
but resign ourselves and all we have and are into the Lord`'s hands.
Every good thing comes from him, and he can give or take it away of his good pleasure.
I sometimes think that which is really good, would not appear to me to be so,
were it in my own possession; but I am infinitely well pleased,
that the Lord alone is good.
In this, I say perhaps too much of myself, but it is not my intention to do so,
nor dare I trouble myself on that account; the Lord however enables me to cast myself,
and all I am and have, quietly into his hands.
May he be loved and glorified to all eternity!
Amen.

November 4th, 1742.

I wish you much grace, to enable you, with a childlike spirit,
to forget and forsake yourself, in order that you may be received in and by the Lord,
and be kept until the end.
Yes, my dear sister, in the Lord alone is our salvation and our glory.
Do you not feel it to be so?
What does he require more of his handmaid, than that she resign herself, just as she is,
into his hands, and in future regard herself as little,
as a thing which has once been given away.
Will He not take sufficient care of us?
Will He not redeem and sanctify us, better than we are able to do?
Shall we lack anything, in His hands?
May all such as are in circumstances of trial and affliction, feel persuaded of this!
O Lord! grant this to them, and grant it to us all until the end!
Amen.

May 8th, 1753.

See, my dear sister, does not the Lord do all things well?
Does he not deal with me gently, and like a father?
O yes, I should certainly be in a measure comfortable and at rest,
were I left more at peace externally.
But yet I ought not to say so, unless I had more of the mind and temper of a child,
that considers little what is good or hurtful, or what it is able or unable to do;
I ought to commit myself to God in simplicity of heart,
continuing to live at the expense of his grace, and believing myself able in him,
and with him,
to do and to suffer all that his providence from
time to time may give me to endure and perform.
In my present weak condition, I have no sensible, inward communication,
and occasionally do not often think of myself, yet God be praised,
I am pretty well and tranquil in him.

May 20th, 1755.

I am singularly circumstanced, even more so than I am conscious of myself,
or am able to express, and perhaps it were better,
if I knew and said nothing at all on the subject.
I am sometimes so astonished at my poverty and weakness, no one would believe;
at another time, I am amazed at my strength, and that I am so much at ease.
At one time, and indeed generally, I am so ignorant of everything,
that if I began to reflect upon it,
I should be quite at a loss with myself on the smallest occasion; and before I am aware,
I again begin to talk and act,
as one who goes to work with a great degree of light and certainty.
I am entirely without any knowledge of my way,
and know not that I ever read of anything similar.
I do not feel so much on committing an evident mistake,
as I do on a single consideration of my own state, when caring for myself,
or when attempting to help myself.
On such occasions nothing but reproof and uneasiness ensue; but when I forget myself,
and continue to live simply on the grace of God,
I am instantaneously as quiet and contented, as one who is at his post.
It even seems as if something great and excellent were at hand--a strength in weakness,
a knowledge in ignorance, a unity in variety.
I am well aware that some of the saints have passed through states,
in which they would perhaps have expressed themselves in a similar manner;
but this is not the case with me.
I am not only wretched, but exceedingly so, and this the Lord well knows.
I should be terrified, were I to compare my state with that of these holy men;
and while I write this, I really fear, dear sister,
that you may conceive too exalted ideas of my state.
Is it not wonderful to see things, so different in themselves,
and apparently at variance, in one and the same person?
What will you make of it, or how will you explain it?
I must therefore only close the account with saying, "`God is a perfect all;
the creature a poor nothing,`" and return to that which I recognize as the best,
and productive of the greatest peace of mind, that is,
forgetting myself as much as I can and continuing to live simply on the grace of God.
O Lord, confirm us in this resignation of ourselves,
that we may never return to ourselves, and that all that is within us,
may sing with your handmaid Hannah, "`There is none holy but the Lord,
for beside him there is none else.`"
(1 Samuel 2:2) Amen.

July, 1747.

He tranquillized his mind on all occasions in the all-wise and good pleasure of God:--

This is my endeavor without fatiguing myself,
that I may rest in my own nothingness and poverty, as I feel them at the moment,
desiring to live solely in and by love.
I appear to myself different at different times.
At one time, I seem to be in some respects, a warrior, and again at another,
I am weakness and poverty itself, so that I should pity myself,
did I continue to entertain such thoughts; but the Lord be praised,
that he does not allow me to do so long, and often awakens in me a secret satisfaction,
at the thought of what he is, and that he alone is good.

October 11th, 1746.

All that is within me inclines to retirement, tranquillity, dormancy of imagination,
and unity in and with God.
To be able so to live, is life indeed.
This, methinks, is my station, my food, the object of my calling--to live retired,
be emptied of everything, to be alone with God in the Spirit,
and separated from the world, at rest and in silence,
giving place to God and things divine; from which alone result truth, and strength,
and life, and salvation.
How dear to me are the moments which I can spare for that purpose!
But it appears as if they will not allow me to enjoy my food in peace and quietness.
While I give, or rather seem to give to others,
I imagine I occasionally receive a few crumbs myself.
I am well aware that the will of God can and ought to be my food;
but when do I possess the will of God?

I mean to say, I do not always know what is the will of God; on the contrary,
the thought often occurs to me, whether a creature does right,
in giving so much of his time to others.
But I am already tired of complaining, and hope to induce you by this means,
to offer me up, so much the more, in your prayers to God,
that I may but please him in all things, for I desire nothing else; yea, I repeat it,
I desire nothing else than to please him, to be his, and to live to him,
in time and in eternity.
And this I prefer, with every attendant burden, pain, and inconvenience,
to living to myself, in the possession of every pleasure and gratification,
if such a thing were possible.
In this matter, I do not inquire whether this determination be entirely pure and sincere,
or whether something very different does not lie at the bottom of it.
I leave it all to God, from whom alone is my salvation;
and my spirit rejoices that my soul`'s salvation and glory is alone from him and in him.
O then, let us go forward, relying solely on his grace,
with the simplicity of little children, and doing to the Lord what our hand finds to do,
without having much regard to ourselves or our own doings!

October 5th, 1748.

I wish to live and to suffer, according to the will of God.
I can remember the time, when I could suffer, so to speak, with the courage of a hero;
but now I must act like a child, that cries now and then, when it is in pain,
and has no idea of patience.
And when my head is so very weak, I often do not know where my mind is,
but must live a mere natural life.
I am occasionally conscious that I am in good hands, but I generally know nothing of it,
and I ought at such times to wish for nothing else.
I know not that I have any desire on earth, or wish to entertain any other,
than that of Paul--the desire to please God, whether at home, or in the body.
From which circumstance, I perceive there is a holy ambition; for the original,
literally translated runs thus: "`We are ambitious to depart, etc.`"
Self-love thinks, what can I do better than to be in heaven,
and will not buy it too dear; but divine love does not regard such a heaven;
the good pleasure of God is its heaven, its honor, its glory.
It is this, strictly speaking, to which divine love, in its nature and properties,
has respect; and the holy ambition of this love,
softly yet powerfully impels it continually to seek more and more to please God;
nor is it conscious of a greater honor or happiness, in time or eternity,
than to please him, whether at home, or in the body.
O Lord, give us this love of yours, and grant it us more abundantly,
that we may serve you in a worthy manner, and not by cleaving to ourselves,
be deprived of you and of your heavenly peace!
Amen!

August 14th, 1750.

Our departed friend had, at the same time, a firm confidence in God;
to this the following letters bear testimony:

I continue to live internally on divine grace.
I feel I must do nothing, and desire nothing, and letting God do as seems him good,
be as a child, contented.
The view of myself makes me confused, unless the Lord lead me to it.
It is strange that we can be so miserable and good for nothing,
and yet be able to trust in such a manner upon God.
O what a benevolent being!
O what substantial goodness!
While loving us, he regards not what we are in ourselves; and in loving him,
it is his will that we should forget ourselves.
He is all that can make us peaceful and happy.
At one time, he lets us see and experience what he is to us, and what he works in us;
and at another, he lets us see and feel ourselves;
and then he again conceals his way with us and his purposes towards us from our view,
in order to simplify and cleanse us, and excite us to regard nothing but him,
and to resign ourselves more entirely into his hands.

December 3rd, 1745.

All truth we shall experience to be truth, according to our measure of faith,
and the gracious purposes of God in Christ towards us.
Miserable as I may be, I must still confess,
that in the dealings of our great Redeemer with us,
in gradually causing everything to be taken from the creature, and restored to God,
whereby every ground of confidence and expectation from ourselves is destroyed,
and God alone becomes our sole support, expectation, and eternal salvation,
I see more and more, and at times, I might also say, I taste something extremely sweet,
desirable and heavenly.
How excellent this is, how ought it to delight our hearts!
Were it possible to find in ourselves any ground of trust,
how reasonable to wish for its overthrow, to have the happiness of trusting in God alone!
Receiving salvation as a mere free gift, is methinks, alone salvation.
But, O Lord, which of us understands this as it ought to be understood!
As it respects ourselves, who know in our degree,
that the way of the Lord which leads us to it,
is not always according to our ideas and our taste,
O how ought this to induce us to resign ourselves blindly, nakedly,
and unconditionally to God, and without regarding ourselves,
to let our dear Redeemer deal with us as seems him good!
Well, it is he who must grant it to us,
and he will work in us that to which we are called.
Blessed be his name to all eternity!
Amen.

November 17th, 1750.

Methinks the child Jesus kindly invites us to come to him, showing us his fulness,
and asking, if we cannot find enough in him.
O! if we could better close our roving eyes, forsake ourselves, and give up all,
we should soon find, in the naked innocence of faith, another mode of existence,
and beholding and finding nothing in ourselves, but poverty and want,
delight ourselves in the Lord, in whom we should find all that our hearts desire,
and to whom we could commit our way without hesitation.
(Ps. 37). But still, my dear sister,
you must not form too favorable an opinion of me from this letter,
as though I continually lived in superfluity and enjoyment.
O no! you certainly know better.
But still, God be praised!
I have enough, even when possessing nothing: nor can I say,
that I particularly desire much enjoyment here on earth.
My daily bread is sufficient.
I know that God is, thanks to his name!
I know that he is the God of our hearts, and that all things are in him.
I can, therefore, often in simplicity, rejoice, as though all those riches,
which I know my Lord possesses, were my own,
while wishing him their exclusive possession;
and I occasionally commend these riches to others in such a manner,
that they doubtless regard me as rich, while at the same time, I am poor and destitute,
and sometimes even make myself still poorer, when I cannot, with sufficient simplicity,
forget myself; for this is also not in my own power.
You understand me well, and will not forget, with the other dear children of God,
to remember me before the Lord, of which I stand so much in need.

December 31st, 1753.

I am weak, but the Lord is mighty, and can manifest himself within us, as such,
at his pleasure.
Methinks it suits us best, and is our proper station to be poor, and helpless,
and nothing; and that all that is within us should bow at his name, who alone can say,
I am!
O that we might look alone unto him, and forever seek in him our delight,
and our true and only rest!

August 10th, 1753.

The magnitude of the riches which Tersteegen found in God,
was equalled by the poverty he found in himself.
This is evident from many of the preceding letters, and likewise from the following:

I do not know how it stands with me.
God allows me to retain nothing on which I can place dependance; I mean to say,
I can no longer attach myself to anything with any degree of warmth or pleasure.
I hover, as it were, in the air.
I have, it would seem, no settled state, nor any stated occupation.
I am not permitted either to look or reflect further
than the ground on which my foot stands.
I am, as it were, hurried forwards.
I am full of misery and disease, but no time is allowed me, so to speak,
to look around me.
I would gladly serve the Lord, and please him;
but I am ignorant whether the wish be wholly pure or not.
You see, my dear sister, how wonderful my way is, and how necessary it is,
that you and others pray for me.
I am looked upon as quite another person, to what I am in reality--God knows it.
May he overrule all things to his glory!

August 15th, 1749.

I cannot say otherwise than that the Lord has been good to me, and that he is so still,
in continually granting me grace to overlook and forget myself, as a thing of no use;
and by means of a cheerful assent to my own nothingness, escape, as it were, from myself,
resting and rejoicing with simplicity in this, that God is such a one as he is.
O this is a truth so great and important, and a subject so adorable,
that it is alone able wholly and perfectly to satisfy and content us!
My dear sister, how poor and worthless, and sinful we are in ourselves!
Who would believe it, and who could bear the sight of it,
if God did not give us a view of himself by faith, which covers, as it were,
our sinfulness, and makes ample reparation for our unworthiness?
We may look at the subject from whatever point we choose,
the firm foundation on which we must build and rely, is God alone, and him eternally.
When by cheerfully assenting to our own poverty, we really give him the glory,
then his bowels yearn, even towards the most miserable.
Glory be ascribed unto our God forever and ever.
Amen!

December, 3rd, 1751.

Ah, my dear sister!
I am not in possession of that which you suppose me to be; and when I have it,
which may perhaps be sometimes the case, it is merely for a time.
Previously and subsequently, I am like a poor man, who has nothing in reserve;
but not always like a poor child,
for then I should neither desire to know nor possess anything.
I am not, however, always thus minded, and would willingly look a little before me.
The Lord grant that this also may tend to my humiliation!

I have often ardently wished, that I had never been unfaithful,
or guilty of a single sin; but after a retrospective view of the matter,
and after having found an atonement in Christ, my sins of omission and commission,
which I abhor, must only serve the more to exalt the glory of God and his grace.
I have palpable reason to humble myself, and to confess, that in truth,
there is none good but God.
I have obvious motives for forsaking myself, and letting myself drop,
that I may be found alone in Jesus.
I have evident cause to approach unto God,
in the greatest nakedness and poverty of spirit and consequently so much the more purely,
more than if I could call to mind a whole register of faithfulness and virtue.
Alas!
The power and the riches of the merits of the blood of Jesus are
seldom recognized in the manner in which they ought to be!

November 1st, 1754.

It is incredible how soon we begin to rely, in some degree upon ourselves,
in seasons of light and strength, and sensible communication; and it is this,
of which you, as well as myself, stand as much in fear, as of the greatest evil;
for we see our salvation alone in glorifying God.
The first title which is applied to our Lord and Savior,
(Isaiah 9:6) is "`Wonderful,`" and so is his manner of dealing with us likewise.
In order to bring us to the salvation just mentioned, he often strips us,
after having obtained firm hold of us, of our light and strength,
and of the glorious blessings for which we had longed so ardently,
in order that we may seek them the more purely in him,
while rejoicing in our own nothingness and his all-sufficiency.
We ought therefore, without delay, to forsake ourselves,
in order that by thus forgetting ourselves, we may obtain true rest and peace.

January 10th, 1755.

Our mutual union and fellowship in spirit makes amends for that interruption,
which has for awhile taken place in our correspondence.
Yet for me it was sufficient, and often proved refreshing to my heart.
I found, and find you still very near me;
and sometimes say to you much more than pen or tongue can express.
I cannot but think, that the Lord sometimes conveys something of it to your spirit,
and causes you to approach unto God with me, to adore him, glorify him, love him,
and lose ourselves in the abyss of his goodness,
which has no regard to our utter unworthiness; an unworthiness,
which appears like an abyss to me, and which,
if I did not view it in the light of divine grace,
would make me backward in holding social fellowship with God and his children, but which,
in this point of view, seems desirable to me,
because I find it so serviceable to my humiliation; a frame of mind,
which is indispensably requisite,
in order truly to be able to approach unto God as we ought.
The poorer, the more humble and destitute we are, the more unreservedly, freely,
and purely can we unite ourselves with God and his children,
and the more capable are we of the participation of the divine favor.
It was once whispered in my heart, "`Come like a naked infant,
and then shall my bosom receive you.`"
Self-love makes us afraid of mortification and privation,
and represents them to us in a melancholy light; but the reverse is the truth,
for as soon as they are cheerfully submitted to,
they are found to be pleasing and salutary; but as long as we refuse them admittance,
they produce sorrow of heart and countenance,
and are often the occasion of many tedious sufferings.

"`Christ humbled himself.`"
(Phil. 2). We cannot humble ourselves, but must let ourselves be humbled.
Christ humbles us by his guidance of us, and by his Spirit;
and thus he makes us acceptable to God, in and through him.
This ought to be a great consolation, even for the most miserable;
because they need only to approach as such,
in order to receive from God every needful grace and virtue.
And even by those, who are already more or less in the possession of these divine favors,
the humiliation which Jesus works in them, ought to be highly prized and valued;
for they are thereby made truly great:
(2 Sam. 22:36) their communion with God becomes
thereby more pure and more firmly grounded,
and they learn from experience, to bow the knee at the name of Jesus,
which is the beginning of salvation.
We ought sincerely to abhor all past and present unfaithfulness and sin,
and every species of evil; to long ardently to be thoroughly freed from them;
and earnestly to follow after holiness,
without which we shall never behold the face of God.
But how I rejoice, on examining both the good and the evil,
to find the conclusion of the matter to be thus,
that after fully acquiescing in our own nothingness,
we must give the honor and glory alone to our God, through Jesus Christ!
Yea, amen, O Lord, for yours is the kingdom, and the power, and the glory,
forever and ever, Amen!

September 12th, 1755.

His poverty of spirit enabled him to walk in unfeigned humility.
By means of his discourses and writings, he was undoubtedly a blessing to many;
he nevertheless made so little account of this,
that once in the earlier part of his life, he candidly avowed,
that it had never entered into his mind to believe that
God would make use of him for the benefit of others;
and he only once expressed himself to the following effect,
where speaking of a certain individual, who had never seen him,
and who resided upward of a hundred miles distance from him,
that if God had ever made use of him to any purpose, it had been to that person.
To another, who regarded him as very pious, and said something highly in his praise,
he replied, "`I have need to retire into a hovel, to weep over my sins.`"

He evidenced on all occasions, a similar unfeigned humility,
accompanied with a sincerity, which was peculiar to him.
When he was in company with awakened persons, he used to say on taking leave,
"`My dear children, when I sit down among you, I feel as if I were unworthy of it,
and the same ought to be the case with you also.`"
Being once in Holland, in the company of several friends, one of them,
who bore a high character for piety, related many things to him,
respecting the persecutions he had endured, his severe trials, and personal experience.
Tersteegen, with much modesty replied, "`If we have already tasted and experienced much,
and have passed through many trials, the result ought to be a lowly, artless,
and childlike spirit.`"

The following meek reply, which he gave to a certain friend,
who accused him of partiality, self-love, and self-conceit,
will likewise sufficiently convince the impartial reader how mean he was in his own eyes,
notwithstanding all the gifts and graces that he possessed.
The answer was, "`I confess before God, with all simplicity,
that I have never considered nor avowed myself entirely free from self-love and self-conceit,
but I should be sorry to cherish anything of the kind, however latent.
I know I still need many things, nor do I pretend, as you suppose,
to be so deeply grounded in poverty of spirit, although through grace,
I have attained the desire to be so; and therefore believe me, that your present wish,
that I may grow up to the stature of a perfect man, is much more agreeable to me,
than your appearing to suppose me almost a man and a father in Christ, which, thank God,
it has never entered into my mind to assert;
but if what I now write should perhaps appear to you an affectation of humility,
I must be silent, and content myself with this,
that my heart absolves me in the presence of God, and that in reality,
and therefore according to truth, I think thus of myself.
O God! you see that I know myself to be but a poor, weak, and helpless infant.
Enable me ever to rejoice, when others know me to be so, and make no account of me.
But although I be such a one, as your eye sees me to be,
you have nevertheless given me to love you, although much less than I ought,
and infinitely less than you deserve, but I have this confidence,
that in your light I have become acquainted with you and your truth,
and behold and place in you alone, all my felicity.
O you that search the inmost recesses of the heart, I appeal to you,
if this be not in reality and sincerity the truth!`"

Another instance of his humility, may be adduced in a confidential reply he gave,
upon being asked if it were proper to call aged and experienced
christians "`father and mother:`" he writes,
"`It has always heartily displeased me, and humbled me before God,
when I have been occasionally and very undeservedly called father.`"

On another occasion he says, "`I hold myself wholly unworthy,
and feel humbled when a child of God calls me brother,
let alone desiring the appellation of father.`"

He gave to God alone all the glory.
It was his delight, and his food and drink to praise him, and to magnify his greatness,
excellence, and all-sufficiency.
He never omitted testifying of him, when he could do so, either by writing,
or by conversation.
In this respect he would gladly have done still more; but his weak state of body,
and other circumstances, did not admit of it.
What he says upon this subject, in a preface to one of his hymns, is very remarkable.

During my short career, I have, through grace,
experienced many favors at the hands of God, while under the cross,
and have been taught many great things concerning him.
Observe, I say through grace.
I therefore, twenty years ago, had the intention of composing before my decease,
a hundred thanksgiving hymns,
as a sacrifice of praise to God for the mercies he has shown me,
and given me to experience.
But many other labors, and the infirmities of my advancing years,
deprive me of the hope of undertaking it on this side of eternity.
I wish to close my lips on earth, while praising this gracious God,
and expect through his mercy, an endless and happy eternity,
in which I may fulfill my vows unto God, and offer up unto him,
with all the glorified saints, more than a hundred-fold tribute of praise.
Amen.
Hallelujah!

He once said to a friend,
that he had invariably received the greatest blessings
and manifestations of divine favor,
in sickness, and in other external and internal privations;
and when the same individual once mentioned to him,
that the time set apart for prayer was as burdensome to her,
as if she were in a field of battle, he put this serious question to her:
"`Is it anything wonderful that the angels praise God?`"
She answered, "`No, for if we were in their place, we should do so likewise.`"
"`That is also my opinion,`" replied he, "`but when Job praised God,
while sitting on his dunghill, that was something noble:
and this praise pleased him better than that of angels.`"

To his humility, above alluded to, may, with reason,
be added his surprising patience in sufferings,
his meekness and lenient disposition towards his adversaries,
and his compassion and forbearance towards those that had fallen.
Continual opportunity was afforded him for the exercise of patience.
From what has already been said, and from his letters,
it is sufficiently obvious that from his youth up,
he labored under many diseases and complaints; and he was particularly subject to them,
during the last thirty years of his life, which rendered his many occupations,
such as ministering to the sick, receiving visits, his extensive correspondence,
and a variety of vexatious circumstances which attended them,
perhaps so much the more oppressive.
In short, his whole life was nothing else but a continual and very painful illness;
a few instances of which are here subjoined.
"`A week ago,`" says he in a letter to a friend,
"`I was attacked by a sinus infection in the head,
which settled itself on the left side, in, behind, and about the ear,
with such an acute pain which continued night and day,
that my head throbbed convulsively every moment.
To this, a fever joined itself.
I was obliged to lie down, but was scarcely able to do so.
A day or two after, I seized with a severe problem in my bowels;
the cold sank into my neck and chest, and made me cough much,
which was very painful both to my head and body.
The end of our lamentations is--going home.`"

On another occasion, he wrote to a friend as follows:
"`On Friday morning before Whitsuntide, I had to write an urgent letter, in doing which,
I was seized with a trembling from head to foot.
In the evening I was attacked by fever, and a severe pain in the limbs, which,
during the night, became a confirmed rheumatism in the thick part of the leg,
so that I knew not where to put myself, on account of the acuteness of the pain;
and this was accompanied with the greatest repugnance to every sort of food.
Yet in this situation, I was obliged to receive, while confined to bed,
four friends from C+++______+++, and three from E+++______+++. Thanks be to God,
who has helped me hitherto.
I have not suffered like a hero, but like an infirm person.
But I must break off here; a cold sweat which comes over me,
will not allow me to write more.`"

To a friend who visited him, he once said, "`I have an eruption over my whole body,
and my back is so sore, that my shirt adheres to it; besides which,
I have a corporal injury, from which I suffer much pain.`"
The person to whom he related this, evidenced much compassion for him, but he said,
"`The old man has sinned, and therefore he must suffer.`"
In the latter years of his life, he could so ill bear food,
on account of the weakness of his stomach, that he said,
"`I am always sorry when my dinner is brought up;
for the lightest food causes me much pain and difficulty.`"

Besides his bodily afflictions, he had much to suffer in his later years,
not only from a scorning and blaspheming world, but also from friends,
whose imperfections the Lord made use of to perfect him the more.
To some, he seemed to do too much, to others, too little: and others again,
envied him on account of his gifts,
and because he was so much beloved and esteemed by many.
But he bore all this with exemplary patience.
When seized with the most acute pains, he endured them with so much resignation,
that it was scarcely to be observed that he was suffering under them.
In the exercise of patience, he manifested such fortitude,
that during a violent toothache, he once said he had need of patience,
and yet sang the hymn, Venture Boldly, etc.

A friend relates the following instance of his patience, forbearance,
and compassion with the fallen.
"`In Tersteegen`'s society, I had for several years enjoyed many blessings,
from his edifying walk and conversation; but after some time had elapsed,
I became disobedient to the grace of God, so that my corruptions,
and the devices of the adversary, occasioned me a grievous fall.
Having by this afflicted the good man so much, and being ashamed of myself,
and fearful of receiving a rebuke from him, I ceased visiting him.
After he had observed this for some time, he sent for me.
I went to him in the full expectation of being sharply reproved by him,
which I was fully conscious I had merited; instead of which,
he met me with the affection of a father, and tenderly embraced me;
by which my heart was deeply affected,
and my love and confidence in God and his dear servant were awakened afresh.
He gave me, at the same time, the necessary instructions respecting my conduct;
and exhorted me to obedience to the grace of God.
After this he kept a more watchful eye upon me till his death.
Another time he said to me and three other friends, "`Children, be upon your guard,
and avoid every occasion of sinning.
The men of the world can often more easily keep themselves from falling,
by means of their rational powers, than those who are become pious through grace,
unless they carefully avoid the opportunity of offending,
for the enemy tries to ensnare them, more than the former.`"

When Tersteegen heard that one or other of his friends had returned to the world,
or had been in any degree unfaithful in their outward conduct,
it often occasioned him sleepless nights, and extorted from him the most mournful sighs.
On one occasion he expressed himself as follows:
"`O what a load of anxiety and care do those who are divinely called, occasion me,
who walk unfaithfully before the Lord!
It gives me so much pain, that I am often obliged to throw myself on my face before God.
O if they only knew the affliction, which those occasion me,
who live in a state of such false security!`"

His meekness and peaceable disposition towards his opponents were equally remarkable.
He had to endure much contradiction, bitterness, and enmity from them,
although he well knew how, when they came to find fault with him,
to receive them so affectionately,
that it was impossible for them to show any degree of warmth in his presence.

Yet still he never swerved a hair`'s breadth, when the honor of God,
and the testimony of the truth was concerned,
but God granted him so much wisdom and meekness,
that the majority were convinced of the truth, became ashamed of themselves,
and were positively overcome by his affectionate and pacific behavior.
It has never been heard said of him, that he treated his adversaries with anger,
either personally, or in writing;
this fact will be substantiated by the following instances.
He wrote the subjoined letter to a friend at a distance,
who had attacked him with much bitterness:

Cease in future, to attack a brother in the manner you have done,
or to desire that he should be ashamed in the presence of Christ,
on account of things which never entered into his mind.
God knows! it is something really harsh and inconsiderate.
I will forget it.
In the name of Jesus, and in humble reliance on his mercy,
I will predict to you and to myself, something far better; namely,
that although we may not be unanimous and understand each other in this matter, yet,
if we love one another, and strive to attain the object of our calling,
we shall soon embrace each other in the presence of Jesus Christ,
with the most tender and unfeigned affection, without being ashamed;
and have neither anything to forgive, nor with which to reproach one another.
Blessed Jesus! this dear brother wishes me to be ashamed of myself in your sight!
My God,
my Savior! you alone know how much reason I have to be truly
ashamed and deeply humbled in your glorious presence,
on account of my nakedness, and multiplied wretchedness by nature.
But did not my sin and shame fall upon you?
Will you not therefore permit me to behold you, and that with such calmness and freedom,
that my face shall not be ashamed.
(Ps. 34:6). You dearest friend, who are the nearest to my soul, my joy,
and all my glory, let it please you that my brother may see for his consolation,
that your countenance does not convict me of that, which his pen lays to my charge.
Fill his heart with grace and peace, and bless him eternally!
Amen.

The year before, being in Holland, a person of high rank invited him to be his guest.
This individual imagined himself to have attained to a state of peculiar inward peace,
and therefore took occasion, during dinner, to criticize Tersteegen for being too active,
and for not sufficiently knowing the ground on which he wrought.
Tersteegen attended meekly and silently to all that was said; but when dinner was over,
he offered up a fervent prayer, in which he commended his host to the Lord,
in terms of such affection and compassion,
that this great and warm-tempered man was so much struck and affected by it,
that his feelings overpowered him, and he fell upon Tersteegen`'s neck,
and begged forgiveness.

Being in Amsterdam on another occasion,
he was present at a numerous assembly of various friends,
some of whom were his most intimate ones, but others of a different description.
Among these was a pious elderly man, to whom much attention was paid,
and who was also a man of much talent and respectability.
Tersteegen`'s simplicity, frankness, and unaffected manner,
appeared strange and suspicious in the eyes of this individual;
he therefore began to put a variety of questions to him,
and to raise all sorts of objections.
Tersteegen answered them briefly, plainly, and prudently; and led the inquirer,
unobserved, from the circumference to the center of the circle.
He finally concluded all with an affectionate parting prayer and benediction,
so that they all saluted him and took a very kind leave of him.

This affords the most suitable opportunity of saying something respecting
the manner in which he treated those who were seeking salvation.
It would be doing him great injustice to suppose that he sought their society,
or endeavored to procure himself followers; it may be inferred, even from his own words,
how far removed he was from this.
A certain individual once desired he would send for a pious lady,
who lived at a distance, and who wished to become acquainted with him,
upon which he sent the following reply, dated September 19th, 1766.

Sister N+++______+++ is one of those whom I most love and esteem in H+++______+++;
she has a noble and inquiring mind, but I cannot invite her here;
for the case was very different at the time when I sung,

You know how I rejoice to see

The souls that give themselves to you.

I lived at that time incognito, even when I was accidentally in company, and loved,
as it were at a distance, without giving way to it; nothing being expected from me.
But I can never remember the time that I found my
chief delight in the society or labors of any,
however much I might love them.
The vital knowledge of such an all-sufficient, omnipresent God,
produced in me a deep and habitual inclination to live retired and be alone with God.
What I have done, deficient as its performance may be,
has been done only in accordance with the leadings of Providence and supposed duty.
Ah, our fellow creatures are often a hindrance to us, and we to them!
My maxim still is, "`to be glad to enjoy the society of the children,
but much more so that of the Father.`"

He wrote to the same individual, under date April the 3rd, 1767, as follows:

This week I have already had four visitors from the duchy of Berg;
and a friend from S+++______+++, who has the right aim in view, has been here some days.
The Latin proverb, Qui bene latuit, bene vivit, (who lives retired,
lives well,) becomes daily of more importance to me.
Of how much time and strength do even our good fellow creatures deprive us!
How easily we do ourselves harm, even when we think we are useful to others!
The trials and afflictions that accompany it,
may well serve as a suitable remedy and preservative.
The Lord overrule all things for the best, and draw us powerfully to himself,
and grant us true fidelity in the exercise of earnest prayer and inward retirement,
in order that we may give place to the divine operation and influences,
from where we must derive our strength, and life, and being, wholly and solely,
both in adversity, and prosperity.

And on another occasion, "`O God, what advantages do those possess,
who have nothing else to think of but themselves and you;
and how filthy the pearl frequently becomes, which passes through so many hands!
May your good pleasure be our constant food, and your lovely presence our strength!`"

That which Tersteegen expressed in these letters in word, he evidenced in deed.
In order to escape the attachment and society of men, he often retired,
during the summer, to a wood where he could hold communion with his God in solitude.
In this manner he used to pass whole days, which he often called his sweetest time,
and supported himself only with a little refreshment, which he took with him.

Going once with a friend to a meeting, where he was expected to give an address,
he said to him, "`I would rather hide myself from all the world,
than let myself be seen and heard.`"
At another time he said,
"`I myself sincerely wish that the name of Tersteegen might be forgotten by everyone,
and on the contrary, that the name of Jesus might be impressed on every heart.`"

We subjoin another remarkable passage in a letter he wrote to a Moravian friend,
who accused him of sectarianism:

I hope I have never shown, during all the years of my calling,
that I sought to form a party, or to obtain followers.
To this moment, I continually hear complaints from far and near,
that I withdraw myself so much.
O God, light that never flatters, you know me!
I am suspicious of my own heart on all occasions,
and in your sight I cannot and will not justify myself--but
behold how a brother judges of me!
You know how painful the sacrifice has been to me, to give up my time, and strength,
and ease, and my beloved solitude, for the sake of others.
Have I not done it purely for your sake, imperfect as it may be,
and from a fear of displeasing others by acting otherwise?
Do I seek anything else than to lead souls to you, and not to myself?
O if the latter be the case, banish it far from me!
O then, turn away the hearts of all men from me in this respect,
and let me live despised and forgotten, alone with you!
For I know, and can appeal to you for the truth of the assertion, I know that you,
O my God! are alone sufficient for me.

March 6th, 1750.

But notwithstanding his attempts to escape the attachment of his fellow creatures,
the widely diffused radiance of his godliness and his superior gifts,
procured him many visits from far and near.
He had visitors from Switzerland, from all parts of Germany, Holland, England, Sweden,
and other countries.
His correspondence with awakened individuals was equally extensive and considerable.
He was visited by persons of all ranks, from the highest to the lowest,
and also by learned and pious divines,
some of whom availed themselves of his advice in cases and affairs of importance.
A friend of his calling upon him on one occasion, he said to him,
"`the day before yesterday, Count W+++______+++, with his steward and friend,
visited me incognito.`"

But of all those that came to him, none gave him greater pleasure,
than such as had entirely devoted themselves to God,
and bore in their amiable tempers and dispositions,
the distinguishing characteristics of his children--these were his sole delight on earth.
Such of them as lived in the country, when weak or ill, he visited occasionally himself,
and to his last moments, felt peculiar gratification and refreshment in their company.

He had received of the Lord a remarkable gift,
in the wisdom he manifested in his conduct towards awakened and pious souls.
A wounded heart seldom left him, without feeling comforted and invigorated.
He was at the same time so humble, so insignificant in his own eyes, and so affectionate,
that those who came to him, confessed to him, without reserve,
the sins with which they were burdened;
on which he impressively directed them to the Savior of sinners,
and well knew how to convince them thoroughly,
that mercy and forgiveness are alone to be found in him.
But he also added, that if they wished to attain to an entire peace with God,
they must also be obedient to the invitations and admonitions of divine grace.
All his endeavors were directed to the end that the Spirit
of Jesus should live and reign in the heart.

He was entirely opposed to mere human attempts to form and restrict the mind,
and he often said, that he who has to do with the souls of others,
must act like a nursery-maid, that holds the child in leading strings,
and merely prevents it from falling and from taking harm,
but otherwise lets it go where it likes.
Were any too backward and remiss in their walk and conduct, he was able,
with much meekness and wisdom, to show them their fault,
and to make God and eternity more than ever important to them.

When he was in the company of those who were really devoted to God,
he seemed to be in his element: he was then very affectionate and communicative;
and when a question was put, that gave him opportunity,
his lips overflowed with heavenly wisdom; everything he said was full of grace and power,
and so deep and comprehensive, that his hearers were obliged to say, yea and amen,
to all he advanced.
He always entertained those who were present, with edifying discourse,
to which external objects frequently gave rise.
These he spiritualized, and often said very wonderful things on such occasions.
By this means, all useless conversation was avoided in his presence,
and some tender consciences were hence induced to decline going into company,
unless he were present.

The following statement by a friend,
will serve to give some idea of his behavior in company.
"`When I came to him with my mind afloat--which was frequently the case--his presence,
which was very striking, or a short time spent in his company,
was sufficient to collect my scattered thoughts.
And when I had anything on my mind, after communicating it to him, it generally happened,
that before I left him, my difficulties vanished,
or else I was freed from them in the course of a few hours after,
through the divine mercy, and the intercessions of our worthy friend.
His prayers, when in company, were extraordinarily powerful.
How often do I feel refreshed, when thinking of them!
How heartfelt, soothing, and dispassionate were they,
and how one felt one`'s self inwardly collected, and mightily invigorated by them!
I have never heard anyone else pray in a similar manner.
In short, all that is said of him is insufficient.
His life was hid with Christ in God.
O how the image of the Lord Jesus shone through him--so that I often thought,
if one small beam emits such radiance, what must the Lord himself be,
who is the fountain of divine light!`"

He was not only of great benefit to those in health, but likewise to the sick.
His paternal care, his consoling conversation, and efficacious prayers,
proved so edifying and strengthening to many,
that they were thereby enabled to trust the more
firmly and filially in their God and Savior.
When there was a necessity for it, he remained half the night,
and sometimes the whole of it with them.
We adduce only one instance, of which he gave an account with his own hand to a friend,
respecting a dear sister in Christ, whom he visited in her last illness:

While at dinner on Thursday,
I was suddenly called away to +++______+++. The attack passed off in a few hours.
I stayed the whole night with her, and reflected on her dissolution;
was also enabled to say and pray many things with her.
She continued collected, calm, and in possession of a childlike confidence until her end.
She not only understood my words and cries, but sealed them also with a yea and amen.

The last words to which she thus assented, were the two last verses of the hymn,
"`Forward from step to step, etc.`"
I afterwards added, "`Receive then graciously, dear Savior,
the spirit of this your child, whom you have redeemed!
Now let your handmaid depart in peace, that her eyes may behold you, her Savior!`"
And as her eyes closed on Wednesday morning at ten o`'clock,
I heartily thanked God for the gracious deliverance, support, and mercy,
which he had afforded her.
This I bore with tolerable fortitude, but on speaking a word afterwards,
to her brother and the household, and while recommending her example,
weakness overcame me, and I was obliged to break off abruptly.^
footnote:[Being subsequently asked, how he could be so childish as to weep, he answered,
"`I confess that it was childish; but believe me,
that I feel more and more depressed in the world, when those,
who are so wholly devoted to God, take their departure from it.`"
On another occasion, he also said, "`I do not desire the indifference of the Stoic,
and willingly participate in the joys and the sorrows of my brethren.`"]
She suffered long and greatly, by which my feelings were also affected,
although I did not let her see it,
but was even enabled to be the means of strengthening her.
During all this, her calm and cheerful patience has been such,
that one cannot think of it without admiration and thanksgiving,
and the serenity of her mind, and unshaken confidence in God to the end,
continues to be a great and continual consolation to me.
Glory be to God, that gave it all!

In this manner Tersteegen revived and comforted many sick and dying persons,
and was made instrumental to their consolation, support and edification,
until their decease.
And he not only ministered to his friends in their illness, but also to others,
although they were depraved characters.
Even the Jews, when ill, sent for medicine from him, and during his illness,
it was reported that they had appointed a meeting to be held, to pray for his recovery.

Our departed friend conducted himself with kindness towards all men.
He labored with all his might,
to do the work of him who had appointed him his place
in the world and to promote his own salvation,
and that of others.
It may with truth be said of him, that he was a servant of servants,
and all things to all men, in order to win them for Christ; that to this end,
he spared neither labor nor pains, and even sacrificed his own health to it;
and that particularly in the latter years of his life, he exerted himself greatly.
Scarcely had he risen in the morning, and collected his weak powers a little,
than he saw himself surrounded by those who sought advice and assistance from him,
the one for his sick soul, the other for his diseased body;
and with respect to the latter, he might with propriety be called,
"`the physician of the poor and needy.`"
No sooner was he freed from these visitors, than he had to answer a multitude of letters;
when these were dispatched, he either wrote or translated some edifying book,
and thus spent both his mental and bodily powers, in the service of God and his neighbor.
A female friend once calling upon him, who observed his face covered with a cold sweat,
he said to her, "`I am very weak, have so many visitors, have already written much,
and six letters lie there still unopened.`"
As she was therefore on the point of going away, in order to spare him,
and leave him in peace, he said to her, "`O no, stay here; Tersteegen must not be spared,
he must have no rest;`" and seeing that she felt grieved, he rose,
and walking about the room, sung a couple of verses, with a cheerful voice,
thus endeavoring to cheer both himself and his visitor,
which he continued to do after entering into conversation with her.
An obvious proof that to serve his neighbor, and to make himself useful,
was his proper element.

Tersteegen did not associate with the men of the world,
except when there was a necessity for it; but when he was obliged to be in their company,
he knew how to conduct himself in such a manner, that they were edified by it,
and compelled to feel a great veneration for him.
An innkeeper, who resided in the place where he dwelt,
once observed to a friend in reference to this, "`Every time I pass by that man`'s house,
a feeling of reverence comes over me,
and the mere recollection of him often makes as deep an impression on me,
as many a sermon.`"
To this, his obliging and amiable deportment,
joined to the noble and brilliant qualities of his mind, may have much contributed.

Tersteegen, in other respects,
generally observed silence in the company of worldly-minded people;
but when he found an opportunity of speaking a word of edification,
he never failed to avail himself of it.
The following is an instance of this:

Being once on a journey to Holland,
and finding in the passage-boat a number of merchants and people of respectable appearance,
he leaned his head backwards, and closed his eyes, as if he were asleep.
After all kinds of tales had been told, and a game of cards had been proposed,
he opened his eyes, and said that he had an excellent pack of cards in his bag.
Upon being requested to produce them, he drew forth a New Testament; on seeing which,
they said, that was a book to make people mad; he replied, "`Is it not you who are mad?`"
and rehearsed all their foolish and unprofitable conversation, and sought,
from their own words, to convince them how foolishly they acted,
in squandering away their valuable time, with such useless things.
Some approved of what he said;
and the rest were at least restrained from carrying their intention into effect.

Tersteegen`'s sentiments regarding the use of the outward means of grace,
may be sufficiently ascertained from his letters which have been published.
He had a high esteem for that which served to direct men to God and Jesus Christ,
and recommended a wise and faithful use of it.
If some have accused him of keeping people away from church and sacrament,
the accusation is unfounded--no one who associated with him can affirm the contrary.
He left each at perfect liberty, to do as he found best in the sight of God.

If anyone had scruples, and asked his advice,
he gave it according to the nature of the case: for instance,
he said to a friend who thought himself not at liberty to partake of the sacrament,
yet was urged to do so by the minister, after examining his state, "`Go to your minister,
and say, "`Sir, I request you in a friendly manner,
to leave me at liberty regarding the communion,
I am unable at present to partake of it in a proper manner; but if you cannot do this,
I will approach the Lord`'s table at your command.`"
The minister was induced by this submission, to leave him to act as he thought proper.
He let others alone, who entertained stronger scruples, and said,
"`A man ought to do nothing contrary to conscience; that which is not of faith, is sin.`"

Some have also believed, that he was hostile to the marriage state;
but this is likewise without foundation; for he advised many,
according to the circumstances of the case, to enter into it;
not to mention the endearing and intimate friendship,
in which he lived with many married people.
With respect to himself, he passed his life in the single state, because he believed,
that thus he could love God more, and be better able to serve his neighbor,
than if he had to provide for a wife and children.
What his sentiments are in other respects, relative to the marriage state,
may be distinctly seen from many of his letters.

We now come to the period of Tersteegen`'s happy departure from this vale of tears.
During his whole life, he was outwardly sickly, weak, and afflicted.
This had such an effect on his body, that he often looked like a corpse;
his labors and his faithfulness, which only ceased with his life,
are therefore the more to be admired; and from hence it is evident,
that the Lord supported him in a most extraordinary manner,
and preserved him contrary to all expectation, many years,
as a chosen instrument to be employed in his service, and that of his fellow creatures.
But the life which he lived in the spirit, hid with Christ in God, what wrestling,
watching, and prayer, what distress, anxiety of soul, affliction, agony,
and suffering he endured, with respect to many with whom he associated and corresponded,
cannot be told, because the smallest part of it is known.

His last illness appears to have been a kind of dropsy,
which showed itself towards the end of March, 1769,
and occasioned him much pain and shortness of breath.
On the 30th of March, he was outwardly very weak, but inwardly overflowing with love,
and resigned to the will and good pleasure of God.
On the 31st, at 1 p.m. he had a severe attack, which brought un convulsions in the limbs.
From this time, he appeared to die gradually.
He passed the following night in an easy chair, in great pain,
particularly on account of his shortness of breath; yet, when some of his dear friends,
who, perceiving the indications of his approaching end, took leave of him for eternity,
he spoke to each of them, according to their peculiar circumstances,
in a manner so edifying, affecting, and consoling, that all were deeply moved,
even to tears.
He himself remained inwardly firm, and entirely resigned to God, and his most holy will.

Among these friends and acquaintances, was also the Rev.
Mr. E+++______+++, who requested of the dying saint a blessing, upon which,
he smilingly lifted up his hands and said, "`Jesus Christ, our great High Priest,
who sits at the right hand of his heavenly Father, lift up his hands from his sanctuary,
and bless you with love and peace in your heart,
and give you grace and wisdom in your ministry!`"
This preacher shortly afterwards followed Tersteegen into the eternal world.
To another individual, who took leave of him, he said, "`O Sister!
The way is a good way; follow the Lamb with cheerfulness, whithersoever he leads you.`"
And to a third, he spoke as follows: "`I commend you through grace, to the love of Jesus!
Let the present moment likewise serve to induce you
to surrender yourself entirely to our dearest Savior,
and to entreat grace from him, like the woman of Cana.
This grace must be solicited, without regard to temporal things, which are of less value,
than is generally supposed; and what a happiness will it be for us,
when obliged to part with them, to have a gracious God in Christ!`"
He spoke in this manner, to all who were present, with much energy, affection,
and divine unction.

From the 1st to the 3rd of April, he was obliged, on account of his asthma,
to sit forty-seven hours together, in his arm-chair,
sometimes leaning backwards for a few minutes on the chair, and then again forwards,
on a cushion, which lay on the table.
He passed these forty-seven hours in great agony, yet was never heard to complain,
except after having slept a few minutes, and waking again, he generally said, "`O God!
O Jesus!
O sweet Jesus!`"

In all his extremely painful sufferings,
there was not even the smallest expression of impatience visible on his countenance.
This extraordinary patience and entire resignation to the divine will and pleasure,
was most consoling to the bystanders, as also his filial confidence in God,
whose will it was thus to perfect him through sufferings,
and assimilate him with the Captain of his salvation.
Without this consolation, it would have been impossible for them,
as they themselves affirm, to have borne the sight of such acute sufferings,
in one they so much loved.
Towards noon, on the 2nd of April, it was evident his dissolution was approaching;
the fits of sleep became more powerful, and his wakings shorter.
It was necessary to remind him constantly of what he had to take.
At six and seven, he slept almost continually, and at nine,
it was nearly impossible to awake him, to take what had been prescribed for him.
His sleep become more and more profound, and at midnight he could be awakened no more.
Thus he continued to sleep till two in the morning,
when he breathed out his soul into the arms of his God and Savior,
and died happy on the 3rd of April, 1769.
Those who were present, imagined themselves surrounded with a multitude of angels,
who received with joy, the departing spirit,
and triumphantly conducted it into the eternal kingdom of rapture and delight,
where he now, with all the holy angels and ransomed hosts,
ascribes an eternal hallelujah to God and the Lamb, and in the fulness of heavenly bliss,
joins in their more exalted songs.
Amen!
Praise, and honor, and thanksgiving, and wisdom, and glory,
be unto our God and to the Lamb, forever and ever!
Amen!
