== Select Letters of Gerhard Tersteegen

It is an established truth amongst Christians,
that there is no standing still in the divine life,
as little as there is in the natural world, in which everything tends towards its end,
either of perfection, or dissolution: and it is the conviction of this,
which renders a growth in grace so important to the mind of everyone,
who sincerely desires to be a follower of the Lord Jesus.

It is therefore incumbent upon us to inquire, in what this advancement consists,
lest we mistake something else for it, and finally lose our aim:
and I think no one will deny,
that it consists in becoming gradually more assimilated to the Divine image;
or in other words, in partaking more and more of the Spirit of Jesus;
for according to the measure of his gracious indwelling,
will be our approximation to the humility, meekness, resignation, self-denial, patience,
benevolence, and holiness of God, manifest in the flesh.

But how is this to be obtained?
Can it be secured by a deportment outwardly circumspect,
by a regular attendance on outward ordinances, by much study, or making long prayers,
or by strenuous exertions for the spread of the gospel?
No!
We have seen how those who were foremost in all these outward exercises,
and who exemplified great heat and fervor on the outset, in process of time,
again grew cool, and lost the power of godliness, while they retained merely the form;
while others of them have even wholly forsaken the way of righteousness,
and turned again to the beggarly elements of the world.

What was the reason?
Are not these things good in themselves, and inseparably connected with a growth in grace?
Undoubtedly they are so in a great measure: but the mistake lay chiefly here;
in attaching too much importance to them, and regarding them more as the end,
than the way to arrive at it.
It is sufficiently evident, that in order to become like unto God,
and to be filled with all his fullness,
nothing less than a continual and increasing measure of divine influence, light,
and life, must be communicated to us; and it only remains to show,
in what manner we may best become partakers of it.

I observe then, that this communication is naturally and properly an inward one.
As the body receives its nourishment from corporeal objects,
and is subject to their influence: so the spirit must derive its strength,
and is under the influence of spiritual objects, of things which are unseen,
but felt and experienced internally;
so that were it possible to hear the voice of God with our outward ears,
the communication would not be so immediate and perfect,
as when he speaks to the spirit inwardly, because it would then be indirect,
and through a medium.
How much more imperfect, therefore, must this communication be,
when it passes through a variety of hands, which add to, or take from it,
according as they are deficient in divine illumination!

The more spiritual therefore a person becomes,
the less does he seek after God and the impartation of his life-giving influences,
through the medium of outward objects.
The heart, or in other words, the inmost center of the soul is the recipient of them,
and when thoroughly purified, the place where God erects his throne,
and fixes his residence.
Tis there, where we must patiently wait for the promised influences of the Holy Spirit,
by withdrawing our minds and affections as much as possible from outward objects,
and inwardly directing them unto Him, who is ever present:
looking unto him for the fulfillment of his gracious promises, and hoping,
and quietly waiting for his salvation.
This state of mind is aptly described by the Psalmist,
in the first and second verses of the 123rd Psalm; it is that waiting for, or upon God,
which is so often inculcated in scripture, and that worshipping of God in the spirit,
which is the only true worship.

This highly important subject, will be found more fully discussed in the annexed letters,
which have been selected for the use and benefit of those,
who are sincerely desirous of growing in grace, and in the knowledge of God,
and who are willing to submit themselves to the teachings of the Holy Spirit,
in order that they may be led by him, into all truth.

In conclusion, let me add a word of serious and friendly admonition to those,
who have entered upon the way of life, and warn them against a most dangerous,
and I fear, very general error,
that of imagining themselves to be far advanced in the Christian course,
while in reality, they have only taken a few preliminary steps towards it.
To ascertain their state, therefore,
they have only to pay attention to what passes in their hearts,
and to compare themselves with that delineation of the true Christian, given by our Lord,
in his sermon on the mount.
They will then, by divine grace, be brought to see,
that they have been hitherto building their house upon the sand, and seek, in future,
to lay its foundation on that rock, which shall cause it to stand secure in every storm,
and bid defiance to every tempest.

May He, whose blessing has attended these letters in their original language,
grant it also to this translation of them,
that his holy name may be honored and glorified, in a greater degree,
by those who call themselves by that name, and profess to be his followers:
for the sake of his well-beloved Son, our Savior!

[.signed-section-signature]
Samuel Jackson

[.alt.centered]
=== Letter 1

[.blurb]
==== May the grace of God in Jesus Christ, reign in our souls, through the influences of the Holy Spirit! Amen.

[.salutation]
Dearly beloved brother in the triune God, and my fellow pilgrim;

The love with which the Lord has graciously united us together in him,
and which can therefore neither be strengthened nor weakened by bodily presence or absence,
constrains me to salute you externally by the present letter.
The providence of God be sincerely thanked, which caused us to meet in this foreign land,
so that we have found reason to rejoice together in the grace of God,
as it has been experienced in our souls, and to praise his lovingkindness for it.
Yes, let our inmost souls exalt his name, that he has, in some degree,
given us to know the lamentable bondage of our immortal spirit,
under the dominion of darkness, while driven about by the enemy of souls,
by means of every vain affection, thought, and desire; having awakened our consciences,
which were slumbering in sin, so that by his grace,
we have sought to escape from the depth of our perdition,
and to satisfy the demands of conscience.

But alas! we have to complain, as our consciences will doubtless testify,
how often we have failed in this respect.
And even when we had done that, which the conviction of our consciences demanded,
with what slothfulness, unwillingness, and constraint was it performed!
And when at length it was accomplished, with how many failings,
and with what a mixture of selfishness was it blemished; so that after all,
our consciences could not be satisfied with it!
And with what ease and subtlety did we ascribe it to ourselves, as if we were anything!
And how often, on the other hand,
was the freedom of access to a throne of grace impeded by occasional faults!

And because we possessed so little of that faith,
which is of the operation of the Spirit of God,
how imperfectly did we impress upon our minds the grace
and merits of Jesus Christ as an atonement with the Father!
It is true,
our inmost souls would gladly have withdrawn themselves
from the service of vanity and the passions,
in order to give themselves up again to their rightful Lord, with a voluntary heart,
to serve him and please him perfectly--but to this,
the requisite power and strength was lacking.
For methinks the case is the same with the conscience,
as I believe I have somewhere read of the law, that it gives us to know our wretchedness,
and tells us its requirements,
the accomplishment of which it causes us to long for and to strive after by every
means in our power--but gives no sufficient strength to fulfill them,
so that we often exclaim in this condition, with Paul (Romans 7), "`O wretched man,
who will deliver me!`"

Now, it appears to me, my dear brother,
that the faithful Captain of our salvation brings us into these straits,
in order that we may despair of our own most imperfect righteousness,
and lose all courage to attempt, by our own ability and efforts,
to escape from our sins and our misery,
and that no flesh may glory in the presence of God,
but that unto him alone may be all the glory;
and that after having previously sufficiently exerted all our strength,
and wearied ourselves, and become quite faint, as it were,
by our own attempts after holiness and righteousness, we may come,
as weary and heavy laden, to Jesus in the center of our souls, where,
according to his promise (John 14:21), he will appear;
and that we may approach to him in the exercise of
unremitting faith and love towards him,
urgently seeking, and in persevering patience expecting him,
like the Old Testament saints, who looked for his coming, and exclaimed,
"`O that you would rend the heavens and come down! etc.`"

"`O that salvation were come out of Zion!`" until he reveal himself in us,
erect his habitation within us, and renovate us;
and until we are inwardly clothed upon with him.
He then himself fulfills in us all the righteousness of the law (Romans 8); and he in us,
and we in him, obey his commandments with pleasure and delight,
which then appear no longer difficult, no longer imperfect, but perfect and blameless.
We then no longer begin to exercise first one virtue and then another;
for every virtue will then naturally, essentially, incessantly,
and freely proceed from the new man, Christ Jesus, who is born in us by regeneration,
and the divine love, which is by this means imparted to us.
We shall then see ourselves delivered at once from the slavery of the affections,
thoughts, and lusts, and from the tormenting accusations of conscience,
and hear in our souls, in their stead, the charming voice of the grace of the gospel.

Now, as God himself, by the sending of his Son, works in us that,
which it was impossible for the law to perform,
and would be to all eternity impossible for us to accomplish by our own endeavors,
we may from hence draw the inference ourselves, that Christ came not to destroy the law,
but to fulfill it;
and that faith does not make void the law but establishes it (Romans 3);
and we shall then from vital experience,
learn to ascribe our justification to the free grace and mercy of the God of love,
and to faith in Jesus Christ, by virtue of which, we can overcome the world,
and derive from the strength of Jesus support and refreshment,
who is then made of God unto us, wisdom, and righteousness, and sanctification,
and redemption.

Let us, therefore, my beloved brother, not grow weary in chastely keeping our hearts,
minds, and thoughts as much as possible from every other object,
in order that by longing for him, in sincere faith and filial love,
we may induce him to manifest himself within us,
and habitually and patiently expect his coming, that he may himself undertake the work,
and enable us to serve him, willingly, joyfully, and perfectly,
to all well-pleasing in his more immediate presence, and in the light of his countenance;
when he himself leads us forth from the darkness of the terrors of the law, and when,
as little children, we are nourished by him, in delightful serenity,
with the milk of his grace and love, and find rest for our souls (Matt. 11);
and thus the triune God possess his kingdom within us, in which he is without ceasing,
worshipped, honored, and glorified in spirit and in truth.
Therefore do not let us allow our courage to fail.
It is a small thing with him, to cause us to find that in our souls in one moment,
without trouble, which we may have sought for years externally, with much labor.
May the God of love, whose delights are with the children of men,
assist us to attain this blissful state!
Amen.

I have written thus, dear brother, in simplicity, in the presence of God,
as it came into my mind, not as though you did not know these things,
but that we might rejoice together in hope of all the good things,
which are given us in Christ.
The Lord give us the vital and essential experience of them in our souls,
even should the knowledge of them be forgotten!

I cordially salute all the dear brethren, with whom, through the providence of God,
I was at that time acquainted, particularly N+++______+++, and all others who seek the Lord,
whose names have escaped me.
I commend myself to your prayers, and remain,

[.signed-section-closing]
Your loving brother in Jesus.

[.alt.centered]
=== Letter 2

[.salutation]
Dearly beloved brother in the grace of Jesus Christ;

"`We are the Lord`'s.`" From that very moment, when in sincerity of heart,
we surrendered ourselves to him, we belong to him, with all that we are,
and no longer to ourselves; in this view we ought always to regard ourselves,
and by this we must abide, or else make as solemn a revocation,
as our previous surrender--from which, may the Lord preserve us!

We are his, I repeat, and God regards us as such.
Yet this is not all the mind must more entirely depart from every other object,
the heart be purified from self-love,
and every purpose and affection directed more purely to God alone,
in order that we may become intimately united to him.
For this purpose it is,
that we have committed ourselves to Jesus and the guidance of his Spirit;
for he is our Savior.
On our part, we have nothing more to do,
than to abide with him according to the degree of our light and state,
and follow him both _actively and passively._

Let your heart,
and the thoughts and affections of your heart be turned
towards the ever-present God in an unconstrained,
childlike manner, but at the same time in sincerity and truth.
Follow with an immediate, but considerate consent,
the impressions and inclinations he may give you, to withdraw your love, delight,
and life, from every other object, and fix them solely upon him.
Let him be in reality, the Lord and Master in your heart, and let your will,
and all your powers be unhesitatingly obedient to him according
to the instructions which he may from time to time impart to you.
This instruction is something very different from that uncertain, anxious,
and uneasy feeling, which arises from reflection and scrupulosity.
The instruction or guidance of the Spirit of Jesus is an inward peaceful impression,
inclination, or inward light, which leads the soul to God, and requires no consideration,
but only a simple serenity and collectedness of heart,
not taught by it any great or particular mysteries,
but only that one mystery--how we may die to ourselves and live unto God.
In this way we follow the Lord in an _active_ manner.

You follow him _passively,_ when you receive everything that happens to you,
on all occasions, mediately or immediately, with reference to body or soul,
with reverence and willingness, from God himself,
as something which is good and serviceable for you.
To these belong the circumstances of your bodily indisposition.
God knows best, my dear brother, what is good for you,
and whether you can serve him better in sickness or in health.
And to these appertain also, that darkness, those distressing ideas,
that melancholy experience of your failings, and your incapability of forsaking yourself,
wandering thoughts, and sensual desires.
In all these, and things of a similar nature, you follow the Lord passively,
when you suffer them in submission, and in as peaceful a manner as possible,
consenting to your own nothingness and misery, and at the same time,
resting solely upon God, or resigning yourself to him,
in the confidence that your salvation will come from him, in his own due time and way.
The will must, however, separate itself sincerely from every suggestion and idea,
which is in itself wicked and sinful.
These must also be endured, but in such a manner,
that the eye of God may see that you do not consent to them.
We ought also to divest ourselves, as much as possible,
of gloomy and constitutional melancholy, or at least not cherish it, but rather endeavor,
with an artless and resigned mind, to dispel it by some means or other.
The vagaries of the imagination must be borne without being followed.
If we cannot avoid sensual thoughts in prayer, we must despise them,
and peacefully continue in nearness to God, with our hearts inclined towards him,
and for his sake, wear the crown of thorns.

God cares for you, my dear brother.
Bow to his will all the day long, and what you are unable to do, suffer.
The Lord will accomplish it.
Let us not seek ourselves and our own advantage, in this short life,
not even when serving God, but let us seek God alone.
O, if God be well-pleased,
we ought gladly to suffer the deprivation of bodily and spiritual enjoyments!
Everything passes away like an empty dream.
God is our salvation, and in him we shall be eternally blessed.

[.signed-section-closing]
May Jesus live and glorify himself in you!

[.alt.centered]
=== Letter 3

[.salutation]
My dear friend,

The passage of scripture, which you have laid before me, "`This is life eternal,
to know you the only true God,
and Jesus Christ whom you have sent`" (John 17:3).
has reference both to the life that now is,
and to that which is to come.
The children of God inwardly commence their happiness here, and consummate it hereafter.
It begins here--but there are two things, which we ought not to forget.

I+++.+++ That this happiness is not felt or sensibly experienced by all, nor at all times.
God does not always let the soul perceive its blessedness, because of its self-love.
His people must often walk in the darkness of faith,
(Hebrews 10:36-38) and pass through afflictions, that being well purified,
they may attain the sanctification of God,
which at such times does not always appear to them to be joyous and blissful, (Heb.
1210-11) although it is so in reality.
When the soul desires nothing but God, and seeks to cleave unto him by faith,
prayer and resignation, the individual may be content,
although he experience nothing in the present life.
Yet I have no doubt, that if we ventured all upon God,
and rejected all creature help and consolation,
the heavenly manna would not entirely fail us in this wilderness.

II. We must ever remember, that the blessedness of the Christian is experienced,
in this life, by degrees.
He that at his first repentance comes to Christ, as weary and heavy laden,
will be refreshed by him: he then receives the forgiveness of sins that are past,
through grace alone, for the sake of the merits of Christ.
If this be perceptibly felt, we then know the Father, and feel a degree of blessedness,
as it is likewise expressed in Scripture, (Ps. 32:1-2;
Eph. 2:8). But we must not stand still here.
Paul admonishes those believers, who were already blessed in the first degree,
to work out their own salvation; not indeed, by their own works or doings,
but by being attentive and obedient to the grace of God, which should work in them,
and likewise in us,
both to will and to do according to his good pleasure (Phil. 2:12-13). These divine
operations aim chiefly at the destruction of all the works of the devil within us,
such as sin, the creature, and self-love,
tend to make God and invisible things of ever greater importance to us,
and draw us more and more into his saving presence.

The soul is then capable of experiencing what is written in John 14:21-23,
and 2 Cor. 6, that is, that the Lord Jesus inwardly manifests himself to her,
and even fixes his residence in her.
And he that truly experiences this, finds a much greater measure of blessedness,
than in the first degree, which consisted merely in the forgiveness of sins,
or in some views of the divine favor.
John, speaking upon this subject, says, "`He that has the Son,
has eternal life,`" and this has also its different degrees.
Paul had experienced all this,
and yet he expected to experience still more in this life (Phil. 3).

On the whole, both the knowledge of God and of his Son, Jesus Christ,
as well as the blessedness which arises from it,
may always continue to increase in the present life, and will be completed in eternity;
yet still there is so much to be experienced in this life,
as is incredible to an unbeliever.
In this life we can become "`partakers of the divine
nature,`" and he that cleaves to the Lord,
becomes one spirit with him (1 Cor. 6:17). It is true,
these things are wonderful and divine, yet God has promised them in Christ Jesus,
and willingly grants them to each of us.
Having therefore these promises,
we ought to purify ourselves from all corruption of the flesh and spirit,
and never stand still, but seek to perfect our holiness in the power of divine grace.

I hope my dear friend will now, in some measure comprehend my meaning,
and find his second inquiry answered by what has been said above: it was, "`When,
and in what manner, does this manifestation of God take place?`"
for it takes place no where else, than in the inmost heart.
Sin, hell, and perdition have their seat within; redemption,
and salvation must likewise be experienced within.
As long as God and his salvation remain external,
we have no proper acquaintance with them.
The Lord, our Savior, is unspeakably near our inmost soul.
He allures us within, in order that we may there become partakers of him,
and of his salvation.
If we follow the drawing of his love, in forsaking the creature by self-denial,
and in affectionately approaching unto him by inward prayer,
he will then fulfill his promise in our experience.

This therefore is the unerring path to the attainment of the end we have in view;
and walking in this way, we may always rest satisfied, whatever the Lord does with us,
whether he lets us feel and clearly experience much or little in this life.
Eternity is long enough for enjoyment.
Let us only begin below, and follow the Lamb, whithersoever he leads us.
All will be well in the end.
I commend my dear friend to the gracious providence of God, and remain most cordially, etc.

[.signed-section-closing]
Your affectionate friend and brother.

[.alt.centered]
=== Letter 4

[.salutation]
Dearly beloved and valued friend in the grace of God;

Your letter of the 27th January, afforded me pleasure; for as I have known in my degree,
through divine grace, both the unhappy condition of an unconverted sinner,
and the blessedness of a true convert, I heartily rejoice,
whenever I see a prodigal son coming to himself, and arising to go to his father.
I also was a swineherd once, and when, after a thousand threatenings and invitations,
I came at length, as I was, to become what I was not,
I needed only to beg and wait a little while,
before I was infinitely more graciously received, than I could have hoped or expected.

Being now acquainted with the paternal heart of God,
I cannot do otherwise than encourage the returning and repenting sinner,
by assuring him that the end will be glorious.
This impels me also to answer my dear friend`'s letter,
although otherwise I gladly remain unknown.
Extraordinary mysteries must not be expected from me.
Mine is a simple gospel path, and all my theology can be expressed in a few words:
"`God was in Christ reconciling the world unto himself.`"
(2 Cor. 5:19)

This reconciled and merciful God in Christ is inexpressibly near unto us;
he knocks at the door of our hearts, and entreats us to turn from sin,
and be reconciled unto him.
All anxiety regarding our dangerous state; every view of our own corruptions, darkness,
and insufficiency; all our grief and sorrow on account of our sins,
are the effects of this near and intimate love of God in Christ.
We have only to confess ourselves such as we are,
before the all-penetrating eye of the omnipresent God,
and without desiring to acquit or help ourselves, only hunger with humble confidence,
after that grace and love, which is revealed in Christ.
While thus engaged, it is this very eternal love of God,
which awakens in the center of the soul,
such an unextinguishable longing to depart from the creature, self, and sin,
and to return to our Father and our origin.
This fervent longing is very often obstructed by unbelief,
particularly when directed to anything else than the pure grace of God,
and when the soul expects much from itself; but it is as often re-excited,
and induced to cleave simply unto him, who is so near and so faithful.

In the exercise of this faith, the Lord does not allow a single soul to be ashamed.
When his hour is come, he opens his paternal heart, heals, and renews us,
frequently in a single happy moment, by the impartation of his love,
and the brightness of his appearing.
Although we may not perceptibly see and experience that the Lord is good,
yet we ought to believe it, according to the Scriptures,
and the testimony of those who have experienced it,
and therefore yield ourselves entirely up to God.
He is the source of all good, and alone sufficient to satisfy us,
both in time and eternity.
But this being the case, he likewise desires of us,
that we should resign all other delights,
and venture that which is most dear and precious to us, from cordial love to him,
who is such a faithful friend, and who is invariably so near to us; who,
from grace alone, has forgiven us our sins, and called us with a holy calling,
in order that he alone may become our treasure.
All for all; that is the whole matter; yet still is it not a purchase,
but a voluntary love-offering on both sides.

Be not uneasy because you have no one to guide you,
and have no acquaintance with pious people; for this the providence of God will grant,
when it is necessary.
Too many instructors are often a hindrance.
We occasionally meet with many good people, who deserve our love: but friends,
who are really of advantage to us in God, are not to be met with in such numbers.
God brings such characters into connection with us, whenever he sees fit;
but he himself is nearer us than any friend can be.
He sees, he knows us thoroughly.
It is he who directs us how to walk, more properly than any friend can do;
and what he says, he gives.
Accustom yourself to the presence of God, and he will lead you aright.

It is good and needful for you, to have renounced all open sin,
but still you feel that the source itself is impure.
Retire within yourself, with humble confidence, and learn wait for the Lord.
Do not engage in too many external pursuits; that which can afford you comfort now,
and delight you eternally, is to be found within in the heart.

I am not surprised, that the very same light which discovered to you your misery,
gives you, at the same time, to see the corruptions of the world,
and the declensions of the external church.
This is generally the case; but prudence is necessary,
in order that we may not turn our eyes too much outwardly,
and be found protesting against an external Babel,
while we are inwardly still in bondage and confusion ourselves.
Let us first extinguish the fire in our own house,
and then we may help our neighbor--but with water.
I cannot deny the corruptions of the external church; but I think,
my dear friend has now more necessary things to attend
to than to occupy himself with these. __Within! Within! With God alone!__
Neither do I recommend you to separate yourself from church and sacrament.
There is no material benefit to be derived by such a separation,
and it has often been injurious to many.
You must not, however, act contrary to your conscience;
but if you find your conscience oppressed by partaking of the sacrament,
you will do better to stay away, and wait awhile,
to see whether the Lord will give you more light on the subject.
I should not like to attend the discourse of a blasphemer,
or one who is evidently still carnal.
If circumstances call for it, one may refrain a while,
without resolving upon anything for the future, much less judging others,
who act otherwise.
The kingdom of God does not consist in meats and drinks (Rom. 14:17),
or the keeping or omitting of any outward ordinances, but in righteousness, peace,
and joy in the Holy Spirit.

Here I must break off,
cordially commending my dear friend to the comforting love of Jesus, and remain,
his sincere friend, and fellow-pilgrim.

[.alt.centered]
=== Letter 5

[.salutation]
Dearly beloved brother in the grace of Jesus Christ.

Your last letter of the 5th of this month, as well as the former ones,
have been duly received.
My delay in replying has arisen neither from idleness
nor selfishness but chiefly from bodily indisposition.
I am seldom able to write, chiefly on account of a weakness in my head and eyes.
My leisure time is quite taken up with receiving visits and writing,
so that I am unable to reply to many letters.
Nor am I a spiritual guide; I am much too deficient for that purpose.
Yet still, I am not backward in giving testimony to eternal truth,
according as God has graciously given me to know it,
nor in extending the hand of fellowship to my brethren, according to my ability,
even as one child does to another.

In other respects, my dear friend, you have no need to have recourse,
with so much anxiety, to such a poor creature as I am, in order to ask advice.
You have the best guide and teacher unspeakably near you.
His pitying eye beholds all your grief,
and it is he himself that awakens in your inmost soul, that secret hunger,
and anxious inquiry for help and deliverance.
The Lord, your teacher and your helper, is present in the secret recesses of your soul,
from which this hunger arises.
Believe this, although you may have no sense or feeling of it,
and with a meek and artless resignation, retire to him within,
as well as his grace will enable you to do.
Show him, with humility and composure, your disease, and with long-suffering confidence,
await from him the cure.
This waiting is of grace, and it is of benefit to us also;
for it quenches the ardent fire of nature.
God is a pure and gentle being; nothing harsh can approach him.
Self does not win the prize.
He voluntarily imparts himself to the secluded spirit, after it has been made meek,
little, and pure, by means of such afflictions as these,
under which you at present labor.

Persevere in God`'s name, and do not grow weary or impatient.
Continue to lie low before the Lord, and thank him for permitting you to do so.
He knows how and when to help you.
Do not reflect so much on yourself, and your own wretchedness,
when you are obliged to feel and see it; only turn away from it, with a calm disgust,
and seek to forget and escape from it;
no further effort or struggle is necessary (Ex. 14:13-14).
If you cannot forget and escape from it,
bear it, in the sight of God, as quietly as you can;
it will not be imputed to us for Jesus`' sake.
Suffering evil is the way to holiness.
Above all things, do not lose courage, although wounded;
but commit yourself confidently to the Lord, even in that state, in spite of self-love,
which is unwilling to appear so defiled.

God certainly loves you; love him, therefore, also;
and venture yourself upon him for his love`'s sake.
I recommend the way of love to you in particular; it is this alone,
which can sufficiently heal all your wretchedness and infirmities,
both of spirit and of constitution.
I do not altogether mean a sensible or susceptible love,
which is often a flower without fruit, and tends to nourish self-love, but a solid love.
Believe the inward nearness of love; perform, deny,
and suffer everything from a loving intention; in all your devotions,
do not seek to satisfy yourself, but the friend of your heart, whom you love.
If you cannot do or find anything that pleases him,
endure your wretchedness and incapacity, from love to him.
He accepts the intentions of love, even in the midst of barrenness and darkness;
this we learn to know in due time.
Prescribe nothing to the Lord, but secretly submit the will of your mind,
to the perfect will of his love and his dealings towards you,
even though your natural will should be opposed to it.

To desire to love him supremely, and to cleave unto him and eternal things,
is the basis and object of that desire, which his free love has imparted to you.
This is sufficient.
Do not dictate to the Lord, what he shall give you,
or by what means he shall accomplish his purposes in you.
Surrender yourself unconditionally to him, let him do with you as seems him good,
and then all will be well.

In one of your letters,
you state that "`it is very seldom you can realist
the presence of God in any palpable manner,
at any particular time or period.`"
God is unchangeably present with us, in the precious name of Jesus, as our God,
and our supreme good.
Faith lays hold on this, superior to all conception or perception,
cleaves with cordiality to a being so lovely, commits herself to him,
honors and loves this adorable friend, and expects everything from his infinite goodness.
But with regard to the feeling, or special gracious manifestation of the Divine presence,
it cannot be realized by any external effort, nor ought we to attempt it,
for that would be improper, and prove a hindrance to us;
both the one and the other depend solely on the good pleasure of our God.
If we only filially follow the guidance of his grace,
and exercise ourselves by it in prayer and self-denial,
we are then in that state of mind,
in which the Lord can work in us and impart himself to us at pleasure;
so that as children, we may confidently commit ourselves to our Father`'s wisdom.
Retiring at certain seasons,
(everyone according to his circumstances,) for prayer and recollection,
I regard by all means as good and necessary; we ought not, however, on these occasions,
to long for any perceptible communication, but continue as contented as we are able,
even in the midst of darkness, barrenness, wandering thoughts, and temptations,
if we be not knowingly ourselves the cause of them.
Worshipping, adoring, and offering ourselves up to God, is of itself happiness sufficient.

Your undertaking some external employment, is needful for you, and well-pleasing to God.
The idea which occurs to us, that all is temporal and transient, and therefore useless,
merely arises from the disrelish and gloom of the constitution.
We were driven out of paradise by sin, and have thereby become corruptible, worthless,
and miserable ourselves; and according to God`'s wise arrangement,
we must now till the thistly ground, as a penance, and for our amendment;
and be exercised in the performance of things so worthless.
It would be folly to doubt upon the subject.
We ought not however, to enter into them with ardor, or burden ourselves too heavily,
but do all that we do to the Lord (Col. 3: 23; Eph. 6:7), they will then,
not only not be prejudicial to the spirit, but advantageous to it;
so that by this simple intention of doing all things, whether little or great,
to the Lord, and from love to him, even the smallest things become important,
and earth is turned into gold.
To such persons, outward things are no longer temporal and perishable,
but their outward form and intent makes them eternal and abiding,
and a service done to God.

My age, after which you inquire, is near upon forty-seven years.
The number of my years is not great,
but I have learnt in them to know much of the vanity of the world,
of the corruptions of the human heart,
and of the patience and incomprehensible goodness of God in Christ,
and learn daily still more.
Blessed be the Lord, who has hitherto helped me!
About twenty-seven years ago, God graciously called me out of the world,
and granted me the desire to belong entirely to him, and be willing to follow him.
May his grace preserve this mind in us steadfast unto the end!
In the same grace, I remain,

[.signed-section-closing]
Your affectionate friend and brother.

[.alt.centered]
=== Letter 6

[.salutation]
Dearly beloved brother, in the grace of Jesus Christ.

Your kind letter, of the 2nd December, as well as the former one,
of the 23rd of November, have both duly reached me, and I will now reply to them,
as far as weakness will permit.

According to the light I possess, to speak upon the subject,
I find your state pretty accurately described in Romans 7,
and the happy deliverance from it, consists in nothing else,
than in resignedly and entirely casting yourself upon the grace of God in Christ Jesus,
which causes death to self-love, but to the spirit, life and peace.
To be saved and sanctified through grace, is not so easy as many suppose.
It is found to be otherwise,
when the light and chastening of God are applied to our souls; we then perceive,
that without the inmost purity, no union with God can be hoped for.
Efforts are made to satisfy the just demands of grace, but the deep and radical wound,
cannot be healed by our own endeavors.
If we find ourselves unable to make progress, we lose our courage and temper.
If we succeed, self-righteousness springs up,
and secretly insinuates itself into the soul,
so that even her best works continue to be polluted by self-love.
If it advance for a time, she finds herself all on a sudden,
again in the midst of the mire.
What then is to be done?
To believe that we must continue miserable sinners, all our lives,
is a desperate consolation.
To rely upon the merit and death of Christ is highly proper,
and the sole ground of our salvation; but he gave himself for us,
that he might sanctify us (Eph. 5:26-27). He came not to destroy the law,
but to fulfill it (Matt. 5:17). What help is there then?
The soul must go forwards, and cannot.
She must give something, and yet has nothing.
Hypocrisy and pretense no more avail.
There is only one means remaining, that is, that we creep to the cross,
and humbly acknowledging and consenting to our helpless condition,
cease from our own efforts, in order that God may carry on his work in us; and thus,
by a resigned and believing application to, and immersion in,
the opened fountain of the grace and love of Jesus, wait for the happy hour,
when this mighty Redeemer shall reveal himself, and fulfill in us that righteousness,
which the law demands (Rom. 8). And this is just what enlightened writers say,
when they direct us to the exercise of inward prayer and retirement,
in order that we may seek and find help alone in tranquillity and confidence.

My dear friend may apply to himself, without hesitation,
what these enlightened authors say concerning this state, with this single exception,
that when they speak of more exalted ways of purification, in which those souls,
to which they refer, cannot actively turn unto God, and collect and deny themselves,
because, by a repetition of their efforts,
they have already unconsciously obtained their object; that this, I say,
does not regard you, unless I am mistaken in my knowledge of your state.
You must turn unto God, not by any mental exertion, or by any other violent method,
but by an inward, and at the same time, resigned longing after him, by a real, cordial,
and confidential cleaving to God, and by a sweet and respectful waiting for him,
in his inward presence.
We have this freedom of access, by the blood of Jesus.
Being reconciled unto God, through Christ, he is therefore favorably disposed towards us,
so that we may inwardly retire unto him in childlike simplicity,
supplicate his perfect aid, and wait for its reception.
He that searches the inward part, sees that the soul, in filially turning towards him,
turns away in the sincerity of its will, and without thinking of it, from the world, sin,
and all that belongs to self; on which account nothing of all this is laid to our charge,
for Christ`'s sake; and by this very act of retiring within, laying ourselves open,
we are purified in the best and easiest manner,
from all the corruptions of flesh and spirit.

My dear friend must not go in search of his own wretchedness;
enough of it will be apparent, when God sees fit.
Let not your depravity be the chief object of your thoughts.
God, as your friend and Savior, God, as present in your heart, ought to be that object.
And when you are obliged to see and feel your corruptions,
endure them in the presence of God, just as a sick child upon its mother`'s lap,
causes the pain it feels to be understood, only by the moving expression of its eyes.
The view of ourselves disorders us; our cure is in looking unto God.
Let us therefore receive the discovery of our wretchedness,
as a real favor from the hands of God, and endure it courageously,
before the eyes of him, whose name is Savior, without seeking consolation elsewhere.
The Lord knows the proper time.
Even waiting is an imperceptible advancing.
Faint-heartedness is a consequence of self-love.
Our weakness and misery, should cause us to distrust ourselves,
but never to distrust God, whose pure love can sooner consume our miseries,
when we confidently commit ourselves to him, than the fire can consume a straw.

Now, my friend, it is nothing strange that happens to you;
the same afflictions are accomplished in others of your brethren in the world,
though not to the same extent or duration in all of them.
Expect nothing from yourself, but everything from the goodness of God,
which is inwardly so near you.

It is a common temptation in such states,
for the soul to imagine this thing or that is unsuitable for it,
that one person does not know its precise situation,
while another judges too favorably of it, and the like.
Do not occupy yourself with such reflections.
I do not point you to yourself.
I know, that like me, you are a child of Adam.
You have not yet reached the end of this path, but your course is correct;
and the eternal love of God only waits, that you and I let ourselves fall into its lap,
just as we are.
Amen. Let it be so!

[.alt.centered]
=== Letter 7

[.blurb]
==== To a Noble Lady

I can easily imagine, that notwithstanding your ladyship`'s high rank,
sufferings and vexations of various kinds will not be lacking;
and I am also in part aware that this is the case;
nor must we be surprised that they are painful to flesh and blood,
as your ladyship mentions.
But we know at the same time,
that flesh and blood shall in no wise inherit the kingdom of God, and must be crucified.
Your ladyship`'s mind is certainly too noble to allow itself, on this account,
to be prevented from taking the oath of eternal allegiance
to the dear Captain of our salvation,
and from persevering, with steadfast sincerity in prayer, in the good fight of faith,
and under the banner of the cross of Christ,
expecting from him the victory over all the opposing powers of nature.
The weaning of a child from its mother`'s breast is not so useful to it,
as when God our heavenly Father detaches us, by means of the bitterness of this life,
from a soul-destroying attachment to things that are seen.
O it is infinite grace, when he breaks our wills and hedges up our way,
not in order that we may be constrained to depart from him, but that we may run unto him!
Did we but recognize the high intentions of God towards us when he gives us pain,
we would kiss the rod of his paternal love,
and love him and cleave to him only the more cordially.

I am under great apprehensions, when I behold those who are still in a state of nature,
having everything their own way; who are either unacquainted with disappointments,
or always seek to escape from them by pernicious diversions.
The more we know Jesus, and the bliss of communion with him by happy experience,
the more our eyes are opened to behold everything else, with new, that is,
with supernatural vision.
His cross becomes dear and lovely in our esteem and his reproach honorable;
while the world, on the contrary, and its noblest things, please us no more;
for Christ and the world are too much opposed to each other,
to dwell together in one and the same heart.

He, therefore, is wise and happy both here and hereafter,
who esteems all that the world can offer as loss and dung,
in order that he may win Christ, the pearl of great price.
Amen.

[.alt.centered]
=== Letter 8

[.salutation]
Dearly beloved brother in the grace of Jesus Christ,

Although I am so slow in replying to your ever welcome letters,
so that it would appear to proceed from indifference or the lack of esteem,
yet I assure you, nothing is further from my thoughts.
I love you; your advancement is a subject of importance with me;
and I often feel myself induced, in simplicity,
to offer you up to the Shepherd and Bishop of souls,
being in some measure acquainted with your state.

I can easily believe that you have been exercised, this summer,
with a variety of temptations and perplexities.
Without trial and exercise, we cannot attain the desired end.
It is nevertheless true, that for much of this we have ourselves to blame;
but the infinite goodness of God in Christ supports, assists,
and again receives us with wonderful and adorable long-suffering.
Blessed be our gracious God in Christ, who has helped us hitherto!
Let us love him!
We might often fare better, if we only continued more in simplicity of heart,
without desiring, although from a good intention, to be great and wise too early;
because it is more difficult to begin again at A, B, C,
after we have in vain exerted much time and precious strength.
The intention is very laudable; we wish to increase in piety, and with this view,
we read, examine, hear and see a variety of things which at the time,
we do not fully comprehend, and which we cannot harmonize and digest;
they must therefore,
necessarily occasion much confusion and anxiety to a mind that hungers after God.
I know what I have had to pass through in this respect; and to this hour,
my soul is thankful to God, for having preserved me in my earliest years,
from a multiplicity of acquaintances and opportunities
of hearing and seeing a variety of things.

I am therefore not surprised,
that the society and conversation of friends has occasionally yielded you no satisfaction.
I very well remember what I felt, when I first heard of you,
and why I gave you no opportunity of associating with this or that particular person,
although I observed that you had an inclination to do so.
It was my belief that you would walk more quietly and safely without such society,
and that in due time,
the providence of God would send you acquaintance according to your need;
and therefore I was not glad to see you procure a
multitude of theological works of various descriptions;
not that I have anything against such books or acquaintances,
except that not everything which is good in itself, is good for us.
Many truths, and very important ones, might confuse or impede us,
if we were anxious to know them before the time (John 16:12). It is therefore my plan,
to commit the soul, in a great degree, to the free guidance of divine grace,
and lead it to nothing, except that to which God intends to lead it,
according to the best of my judgment.
I pay attention solely to the dealings of God, and admonish the individual,
when I see him in danger of receiving injury.
I associate with some, who seek to walk in cordiality and sincerity before God,
to whom I have never said a word about books which I myself have published,
because I did not think it would be of service to them.
God must be the master in all things; and we must continue to be his scholars,
and apply strictly to the lesson given us to learn.

We know how his eternal love has sought us, and inwardly met us in Christ.
We now find, in our inmost heart,
a profound and secret longing and inclination to be freed from sin, the world, and self,
and to be again united with the source from which we emanated.
In order to the attainment of this,
we have no need to occupy ourselves with external things, nor to make great preparations,
or think to carry the point by our own efforts.
Sincerity, it is true, is necessary--but a sincerity in mortification, inward retirement,
and patient waiting.
The power to accomplish this is very near at hand.
Let us only cherish this secret and inward desire, and give way to it.
For it is by this inclination of the heart,
that the power of God and our dear Redeemer is present;
from whom we must alone expect help and salvation.
Let us cleave unto him in the spirit of children, with humility and confidence,
believing in his gracious presence, worshipping him who is thus present with us,
loving him, committing ourselves entirely to him, in a word, holding fellowship with him,
as our God and our best friend, who is all sufficient for us.
If we act thus, and when he perceives that our only aim is to please him,
in the best manner possible, he comes to our aid,
and works in us substantial virtues and a thousand blessings, according to our need.
He then teaches us, from love to him, to love the cross, to mortify all self-seeking,
and to renounce all other life and inclination,
in order that everything within us may be solely and simply turned towards him,
and he alone be our life and our treasure.
In short, he that only exercises himself, with childlike simplicity,
in this important point, without paying much regard to anything else, may rely upon it,
that the Lord will provide for him wonderfully.
If he requires it,
he sends him a book or a faithful friend to strengthen and encourage him;
and as he is willing to remain in childlike ignorance, he is in the very state of mind,
that fits him to be led by the Spirit of Jesus, at his pleasure, into all truth,
and to be made of him what he pleases.

You will therefore understand, my dear brother,
that I do not altogether advise you against associating with friends, or against reading;
much less that I regard as suspicious, or of small importance,
that by which a soul may obtain nourishment in the
main point--this would be spiritual pride.
I only warn you against a superabundance, and against living in things external,
and against judging of everything without due distinction and examination,
and against entering too deeply into society and mental reflection.
This examination, however, is very simple: that which strengthens us in the main point,
that which enters into the mind without constraint,
and composes it at the time of retirement and prayer, is of service to us;
but nothing else.
We ought, however, not to reject other things but leave them.
"`What is that to you?`"
says Jesus still; "`follow me!`"
With reference to associating with others, my advice continues to be,
"`friendship with all good people, but fellowship with few.`"
And if the providence of God gives us those few, whom we have found faithful,
let us love and esteem them the more,
the rarer such characters are to be found in the present day; taking care, however,
not to idolize them.

Walk with simplicity; go forwards with confidence, my dear brother,
attending always to the main thing, prayer, self-denial, loving, and suffering.
Be not afraid of the wandering thoughts that infest you against your will:
bearing these and other things with disgust, yet at the same time with confidence,
is the way to be delivered from them.
There is much depravity in us,
and both the discovery of it and our redemption from it are of grace.

It is God, who must work in us inward collectedness and every other blessing,
instead of these being the result of our own desires or efforts.
Yet still you must not be too scrupulous in your devotional exercises;
good children do what is given them to perform, as well they are able,
and are desirous of improving every day.
May filial love govern you in all things!
The picking up a straw, with an intention to please God,
is of greater value in his sight, than the removing of mountains without such intention.
May our dear Redeemer himself work in us everything that is well-pleasing in his sight!
He is faithful and will do it.
Pray for me, even as I do also for you, though in weakness, and remain through grace,

[.signed-section-closing]
Your obliged fellow-brother.

[.alt.centered]
=== Letter 9

[.salutation]
Dearly beloved friend in the grace of God,

Your short letter by a friend, I have duly received, and was gratified by it;
and although my time is limited, I will write something in reply, as you request,
and as God shall enable me.

I repeat, therefore, my last admonition: love,
and exercise yourself more than ever in solitude, prayer, and self-denial.
Solitude is the school of godliness.
You are called--think what grace!--to social converse with God; you must therefore,
by all means, avoid all unnecessary converse with men.

This is particularly needful, while we are still so weak; we must escape from the enemy,
and not come too near the view of the world and the creature,
in order that we may not lose sight of the nearness of the Creator,
and that the world may not dazzle, overcome, and again take us captive.
We ought not to look too much at the creature,
that thus we may gradually lose the remembrance of it and fondness for it,
and become truly strangers, whose walk is solely with God in heaven.

Love prayer!
Let prayer be your constant occupation from morning till night.
Let your heart and desires continually hold converse with God, in heartfelt simplicity:
for his delights are with the children of men.

Reflect often, and if possible, incessantly, with feelings of love and reverence, on him,
on his presence, and his perfections, and often offer up your heart,
with all that you have and are, and all your ability, to him, in spirit and in truth,
as cordially and sincerely as possible.
If through weakness or unfaithfulness you forsake this exercise,
which is so incredibly useful and beautiful, all you have to do is,
meekly and heartily to begin again; and do not be weary of it,
although in the beginning you may not find any great advantage from it,
or make any rapid progress in it.
It is not true, that such a mode of life is difficult;
it is easy and pleasant to the spirit, and becomes in due time, like a heaven upon earth.
A little patience and courage alone are requisite.
With reference to express and particular seasons of prayer and recollection,
you are already acquainted with my sentiments.
Be faithful likewise in this respect, not allow yourself to be kept from it,
by any objections which reason may urge, or by the slothfulness of nature.

Self-denial makes prayer easy, and prayer again lightens self-denial.
Be glad when an opportunity offers of denying your own will or pleasure,
or any other matter, be it what it may, for the Lord`'s sake.
Act in holy opposition to your depraved nature in all things;
and even in the smallest matters, declare determined war against it.
The more the flesh is under restraint,
the more liberty and delight is experienced by the spirit in living with God and in God,
its true element.
Examine often to what it is, to which you are the most attached: mortify this first,
and sacrifice it courageously, in order that you may devote your whole heart, love,
and desire to God, in virgin chastity.
Be faithful to the smallest convictions of your spirit,
and if a thousand impediments arise in your corrupt, natural, and carnal will,
turn from them with the renewed will of the mind which God has given you,
and which no power in hell is able to constrain.
In this manner you hold converse with God, and God with you;
and he will deliver you in his own due time, from every fetter.
Flee, in particular, youthful lusts, which so much obscure the mind,
and remove us from God.
Our bodies ought to be a pure temple for the Lord.

Break through, my dear friend, in every particular, especially in the matter,
of which we lately conversed together.
Do not hesitate a moment.
God, in this instance, requires a willing sacrifice from you, and will not let you rest,
till you give him your complete and sincere consent.
I repeat it: do not let yourself be persuaded that the service of God is disagreeable,
difficult, and impracticable; rather represent it to yourself as a beautiful, pleasant,
and through divine grace, easy life, which it is in reality to the spirit,
when rightly commenced in God`'s name.
May He, our gracious Lord, who of his great mercy has called me and you to it,
give us all that is necessary, most faithfully to follow his calling!
Concluding with which, I remain,

[.signed-section-closing]
Your affectionate friend.

[.alt.centered]
=== Letter 10

[.salutation]
Beloved brother, in the grace of Jesus,

Both your letters of the 25th of January and the 22nd of May, have come to hand.
My ardent attachment to a hidden life with Christ in God,
produces in me a continual disinclination to enlarge
my circle of acquaintances and correspondence;
but the Lord often orders it contrary to my inclination,
and I cannot and will not resist his hand in anything.

I now feel myself at liberty, dear brother,
with simplicity to assure you of my cordial affection,
and that I often greet you in the spirit of the love of Jesus,
and that I have been gratified and refreshed by your letters.
I rejoice that God has granted you a relish for retirement and the life within,
to which he is drawing you.
It is a great, and at the same time, an unmerited favor,
to be called to this precious life, which must be met, on our parts,
by great faithfulness.
God invites us to his lovely fellowship;
he purposes preparing our spirits for his habitation and temple,
and in this inward sanctuary, we shall behold the beauty of the Lord.
O what a mercy!
If then the overflowings of the love of God towards
our unworthy souls are so exceedingly abundant,
we ought also, beloved brother, to be very liberal, and not withhold ourselves,
in any respect, from this eternal Good,
which seeks to have us solely and wholly for itself.
To be entirely God`'s, is the true secret of the inward or mystic life,
of which people form such strange and frightful ideas.
There is nothing more simple, safe, pleasant, and influential,
than this life of the heart, which is not the result of reading, or mental exertion,
but is thoroughly known and experienced by dying to the creature,
and love to the Creator; it is consequently more the work of the Spirit of Jesus in us,
than our own work.
Being attentive to the operation and attractive influence of his Spirit,
and satisfying and following it, makes us inwardly secluded and spiritually minded.
This spirit of love, when duly attended to,
imparts to the soul the same mind which was in Christ Jesus,
and forms it according to his image,
almost as imperceptibly as an infant is formed in the womb.
He leads it more and more profoundly into an abandonment of all created things,
and of itself also, and into an unreserved resignation to God.
He does not require this with legal severity, but leads the obedient soul into it,
and gives the individual a supernatural central inclination,
which makes him willing in spite of self, and causes him to follow the Lamb,
whithersoever he goes.

The more sincere and serene our inward devotion is, and the more we feel at ease in it,
the better and purer is our walk.
The particular exercise of inward prayer, or retiring within,
serves principally to make us, in childlike simplicity,
attentive to the delicate guidance of the Holy Spirit,
and to give him the complete ascendency over us.
Forms and the efforts of self are here of no use, they are only a hindrance;
we must lie as poor shapeless clay in the potter`'s hand.
The hand of divine love then forms us after its own fashion;
it leads us into an artless simplicity and lovely lowliness,
it makes us meek and resigned, teaches us to desist from all our own intentions,
and make God our only aim; it places us in a thorough abstraction from self-seeking;
God alone becoming the sole and complete treasure of the soul,
and glorifying himself in it at his pleasure.

Let this then be in future our whole concern, my dear brother,
blindly and nakedly to follow him, who has called us with a holy calling.
I am confident that this is the way in which God wishes us to seek him,
and learn to serve him in spirit and in truth, although I myself am wretched enough.
The true inward life is nothing new or peculiar; it is the ancient and true worship,
the christian life, in its beauty and proper form.
Those who truly live retired within, form no particular sect;
if everyone followed the life and doctrine of Jesus, under the guidance of his Spirit,
all would be doubtless thus inward, and the world would be full of mystic christians.^
footnote:[Whatever is wrought by the Spirit of God, is a mystery to the carnal mind,
and hence the men of the world, and those who are only partially enlightened,
call those mystics,
who have attained to a greater degree of divine light and knowledge than themselves.]

I know not why I write thus, seeing that you, my dear brother,
have already obtained from the Lord, sufficient certainty on this subject.
Let us therefore only abide with the Lord, and commit ourselves to him more sincerely;
for he is very gracious,
even in the trials of those that love him he is eternally all-sufficient for our spirits.
If the Lord has deigned, in any measure, to bless my imperfect letters to your soul,
to God alone be all the praise, who gives food to the hungry,
even though he were to make stones into bread.

If it be the Lord`'s will that we should see each other again,
it will afford me pleasure; if not, we will part in the heart of Jesus, and salute,
embrace, and bless each other there, in the name of him that has loved us.
Present me as an offering to his lovely Majesty,
according to the grace which he shall bestow.
This I do likewise, with all my heart.
May Jesus bless you, my dear brother, and form you after his own heart,
in which we continue united, though absent in body!
I remain, through the grace of God,

[.signed-section-closing]
Your very affectionate brother.

[.alt.centered]
=== Letter 11

[.salutation]
Beloved brother in the grace of God,

I have lately been favored with your welcome letter by our dear friends,
with whom I intend to forward the present,
and feel in my mind an entire accordance with the remarks you make.

It is true, that frequently,
one cannot contemplate the conduct and practices of awakened individuals,
and the commotion they create, without a holy apprehension and concern.
Yet we ought not hastily to reject and disapprove of it altogether;
because there are many, who seem to stand in need of guidance and support,
by reason of the miserable incapacity of the wandering and disturbed mind,
to perceive and distinguish the inward attraction and operation of divine grace.
It would be well if such characters would not always continue in the same round of observances,
but hasten with diligence to their aim,
and wisely order and moderate everything else to the mark of substantial holiness,
in inward communion with Christ,
in order that they might not always remain at a distance, and expend their weak,
yet noble powers of grace, in things which are unprofitable.

That which guides the seeking mind directly to the mortification of the creature,
sensuality, and self; that which nourishes, invigorates, and collects the heart,
and fills it with love and reverence to the omnipresent majesty of the God of love,
and in the degree in which it may contribute towards these ends,
is worthy of all acceptation, however worthless and external the thing may be in itself.
Were we really desirous of knowing a tree by its fruits,
we should soon be able to distinguish whether, and how far,
many of the practices and commotions of the religious world
serve to promote or obstruct the kingdom of Christ.

An unenlightened,
inexperienced eye can scarcely believe how great the incapacity of a child of
Adam is for substantial interaction and fellowship with its God and origin,
and how low, and with what long-suffering, this eternal Good must condescend to us,
and lead us like children, in order that we may be gradually divested of all alloy,
and be brought near to and made fit for him.
He overlooks a thousand follies, leads the sincere intention through everything,
and knows how to separate everything in due time.
If we have in part experienced this in ourselves,
we shall conduct ourselves modestly with respect to others,
regard the good intention and motive, and gladly direct them to the desired aim.

It is not without the divine permission, direction, and cooperation,
that an awakening rumor arises, first in one country, period, and people,
and then in another is felt for awhile, and excites many to that which is good.
This does not, however, take place, without the intermixture of much of what is human,
sectarian, and imperfect amongst the greater part,
both of the instruments and those that are awakened; yet still,
long-suffering love descends, and blesses the well-meant, imperfect work.
In short, the net is cast into the sea, and a multitude are taken.
After some time, it gradually subsides, and appears to diminish.
Many, who, devoid of a thorough change, were only pressed in, as it were,
turn back again to the world.
Those who are sincere, perceive, more and more clearly,
the imperfection of their former works.
The net is torn asunder, and each one goes his way.

Is it not the intention of Wisdom by this, to afford more liberty to the upright,
to excite them to a more profound attention, and to allure them deeper into themselves,
that thus they may hear, in the center of their souls, its soothing voice,
which could not be so well listened to, during the previous commotion?

It is thus that divine Wisdom orders and separates everything with precision,
both generally and particularly in due time.
That which previously served to awaken and edify, and was relished, afterwards,
frequently will not produce its former effect;
so that even ability and inclination are often wonderfully withdrawn;
for the principles of grace sinking deeper,
no longer manifest themselves in the region of the senses,
but in the silent center and sanctuary of the soul, where they seek room.
The time of true separation is then certainly arrived,
in which we no longer live to ourselves,
nor engage in any outward and self-chosen undertakings,
but in the exercise of the most heartfelt and sincere humility and abstraction,
let the Lord work in us, and expect from grace alone,
that which we cannot give ourselves;
because there is really nothing that justifies or satisfies,
but what God himself imparts and works, unmingled in the center of the soul,
where the everlasting love of God, in the gracious name of Jesus Immanuel,
is so close at hand and open to us, poor sinners; into this we plunge ourselves,
and live to his free grace.
To him be glory, forever and ever!

[.alt.centered]
=== Letter 12

[.salutation]
Beloved friend and brother,

I have for some time delayed replying to your agreeable letter of the 21st of March,
because it is not without reason that I am afraid of entering upon a more extended correspondence;
being besides this, already much engaged, and experiencing at the same time,
more and more, that the true and inward Christian life,
to which I find myself called by divine mercy,
demands a strict attention to what passes within, if we wish, in this mortal state,
to get near the end of our calling, which is,
a real fellowship and union with God in the spirit.

Our Lord Jesus was silent and kept himself concealed for thirty years,
in order that by his example,
he might inspire us with a fondness for a truly retired life,
and scarcely did he spend four years in a public manner.
I often think, if we that are awakened, would endure only four years of probation,
in silent mortification and prayer, before we showed ourselves publicly,
our subsequent activity would be a little purer,
and less injurious to the kingdom of God, both externally and internally.
This is a secret, but common temptation of the enemy, and a subtle device of the flesh,
by which the tempter seeks to allure us from the only thing needful,
and to weaken our strength, by the multiplicity of the objects in which we engage;
but the flesh and its progeny,
which finds a life of mortification too difficult for it and too disagreeable,
may breathe very easily, and even maintain itself,
in every outward spiritual and apparently profitable exercise, while in the meantime,
the mystery of iniquity at the bottom, remains unperceived and unmortified.

Let us therefore, my dear friend, for the love and honor of God,
close the eyes of our minds against minor ways and minor works,
in order that we may attend solely, in a meek and quiet spirit, to our holy vocation,
which has been so graciously made known to us,
and will be still further revealed in our hearts.
It is _in the heart,_ and not in the head,
that the attracting and collecting love will cause itself to be felt more and more efficaciously:
whose salutary doctrines of the profoundest renunciation of all things,
of self-denial and self-contempt, of attachment to his cross,
and of abiding in him with the spirit of children, ought never to seem old to us,
and be of greater value to us,
than all the ancient and modern sophistry of both orthodox and separatists, put together.

O my God! how much there is to be done, suffered,
and experienced inwardly in following you, and in communion with you!
How is it possible, that we can let anything external decoy us out of ourselves,
and that our attention can be occupied with trifles, while within,
we might see and experience that which is truth and reality!
Enable us thoroughly to forsake ourselves and all created things,
and fix our affections again upon you, who are the supreme Good, and the fulness of love!
Amen.

My dear friend will not take amiss the little that
has thus flowed without reflection from my pen.
Your own experience will teach you all these things in a superior manner;
but Christian affection would not permit me to let your letter remain entirely unanswered,
and I hope likewise, that our acquaintance in the Lord will not be without a blessing.
God be praised for all the mercy he has shown to you, my dear brother!
Let us love him; for he has first loved us!

[.alt.centered]
=== Letter 13

[.blurb]
==== To a Noble Lady.

[.salutation]
Beloved sister, according to the high vocation of grace,

Although I am weak and faint as it respects the body,
yet the love of Christ constrains me to testify with a few lines,
that your ladyship`'s letter of the 8th of November, last year,
proved very refreshing to me, and has been often answered by me in spirit.

Blessed be God, who in Christ Jesus, has granted us fellowship with him,
and with one another, irrespective of, and contrary to all our deserts!
At present (and as often as the Lord reminds me of it) I cordially
wish my esteemed sister all advancement in the life of God,
and all delight in the God of love.
I am persuaded also, at all times,
of a similar spiritual fellowship on the part of your ladyship.

The longer I live, the more I see and experience,
that no one is good but God alone--that which he is and does in us,
alone makes us holy and happy.
Mankind perceive and regard what is external and material, and respect appearances;
but their judgment is seldom according to truth,
because there are very few works that are done in God.
It is true, God has infinite patience with us in our mixed state;
yet still it is a great mistake to regard anything as good besides God,
and he that does so, is not yet in the truth.
We must make room for God, or more properly speaking, God must himself make room in us;
for our wretchedness is so great, that when we escape from ourselves in one place,
we find ourselves again in another place, in the very same thing.
We are altogether miserable and besotted; ornamenting and beautifying is of no avail;
the whole mass is corrupt, and we must be led out of ourselves by God, into God.
No one is good but God alone; and he that truly sinks and loses himself in him,
becomes good through him, were he otherwise ever so bad.

O that every poor sinner beheld, with us, this open sea of infinite goodness,
which is so near us in Jesus Christ!
How would they plunge themselves into it, and find a cure for all their ills!
There are, however, many, who still feeling themselves, must bitterly complain, saying,
"`How weary I am of myself, and yet I am still obliged to bear with myself!
People say, forsake yourself! but I cannot find the gate.`"
But here is the point: he that has not properly felt himself,
has not properly forsaken himself.
We must experience, that of ourselves we are unable to do it,
in order that in this respect, likewise, the glory may be given to God.
God himself must heal and sanctify us, and will do so, but not without affliction.
This, in my opinion, is the origin of that real but rare resignation and endurance,
to which no one perhaps attains, without suffering and mortification,
although it be a source of life and heavenly peace.

O Lord! when shall we no longer be a hindrance to you and to ourselves?
And when will you become all things in us, yes all in all?
Be so eternally!
Amen.

I will not offer any apology; I write with simplicity as it flows from the pen.
I desire again to salute your ladyship and all your noble family in the name of Jesus,
and remain through grace,

[.signed-section-closing]
Your ladyship`'s weak fellow servant in the Lord.

[.alt.centered]
=== Letter 14

[.salutation]
Dearly beloved brother, in the grace of Jesus,

I will see if I have time and ability to write a few words in answer to your question,
for which however, a short letter will not suffice,
it being a subject which is more proper for verbal communication.

The state of repentance, of the law, and the drawing of the Father,
is generally speaking, one and the same, because the one as well as the other,
is a preparation for Christ, and for regeneration, or the state of the new covenant.
But there is sometimes a distinction observable.

One, who constrained by the sincere reproofs, demands, and anguish of his conscience,
labors in his own strength, refrains from evil and does good,
in order to sooth his suffering mind, is properly speaking, still under the law.
But if I should call it a state of repentance,
it must be accompanied with a greater humiliation and contrition for sins committed;
and the more a soul, in the consciousness of its sinfulness, misery, and weakness,
sighs and longs for forgiveness in Christ,
and for his operating power and grace to renew the heart,
the more properly might this be called the drawing of the Father;
although these three appellations, as already said, signify generally the same thing,
and are often united.

The assurance of the forgiveness of sins, is commonly taken for believing in Jesus;
but in my opinion, this is incorrect.
That which I have just now more fitly called the drawing of the Father,
I might also with propriety call, believing in Jesus; for the Father draws us to the Son.
But faith in Christ has its gradations.
In the beginning it is a "`Coming to Jesus,`" (John 6:35); that is,
with hunger and desire, just as I have said respecting the drawing of the Father.
It is afterwards a _receiving of Jesus_ (John 1:12), which cannot take place,
unless the sincere will of the soul lets go at once the world, sin, and self.
In advancing, faith is an _abiding in Jesus_ (John 15), with a fervent inclination,
otherwise called retiring, within, or cleaving to him (1 Cor. 6:17),
and thus by abiding and walking in Jesus,
we are increasingly rooted and grounded in him (Col. 2:7), which, however,
is not accomplished without afflictions and trials.
Faith is, finally, a dwelling of Christ in the soul,
and of the soul in Christ (Eph. 3:17; John 17:23), and _becoming one with him._
By referring to, and considering the passages quoted,
you may perhaps attain more light on the subject.

On the whole, you perceive,
that I do not merely regard faith as an act of the understanding,
by which we represent and imagine to ourselves that
Christ has made a sufficient atonement for us,
but chiefly as an act of the will, and of the heart, in which our love, desire,
and confidence are turned away from ourselves and all created things,
and directed to the grace of Jesus, in order that by him,
we may be delivered from guilt and the dominion of sin.
Confidence, it is true, is a material ingredient of faith;
but as soon as there is a hungering after grace, or a coming to Jesus,
it is accompanied with confidence,
though this is frequently much concealed by sin and fear.
For no one ever comes to a physician, who places no confidence in him whatsoever.
If we only continue to come, confidence will manifest itself in due time.

That which is otherwise called an inward attraction, is properly speaking,
faith in Jesus, accompanied by a fervent and tender confidence.
This inward attraction manifests itself to some souls, like a flash of lightning;
but alas! it is seldom that proper room is made for it, or that it is duly attended to;
otherwise the soul would be speedily delivered by it from bondage and disquietude,
and strengthened to entire resignation.

Your question respecting free will, is equivocal.
By a free will, is generally understood, a will to will what is good,
and an ability to do what is good; and in this sense, no one has by nature a free will.
But if by it be understood the voluntary direction of the will,
freely to choose the good or evil that _is presented to it;_ not only has every man,
in this sense, a free will, but also the devil himself.
But on the one hand, man possesses naturally, neither light, nor anything,
to which his will might be able to turn itself;
yet the will is free in the element of darkness, as a fish in the water,
but it is neither able nor willing to depart from it.
The light, it is true, now shines through Christ; and when it offers itself to anyone,
his will is then free to open the window of his heart, or not.
And on the other hand, man is not able to do this by nature, but through the mercy of God.
He _can_ do it, but will not, because the light gives him pain, and on that account,
he hates it.
God, therefore, not only offers light and grace,
but likewise gives a good impulse and inclination to the will,
so that the light appears desirable to him, and the evil, hateful.
And as therefore, God for Christ`'s sake, most assuredly acts thus towards man,
there remains no excuse for the unbelieving.
However, the Lord forces no one--he offers faith to everyone, (Acts 17:31,
marginal reading,) and then the man is at liberty to accept or refuse.
In other respects, that man has in reality a free will,
who has entirely resigned and lost his own will in God.
A fish may lie at liberty upon the land, and spring about, but it is no where truly free,
except in the water.
That which water is to fish, God is to the spirit.
He that follows his own opinion, impulse, and will,
either in a obvious or a subtle manner, is a captive slave.
The kings of this world are, by nature, as little free, in respect to the will,
as a prisoner in jail.
Our spirit and our will live entirely under restraint and pressure,
until we thoroughly commit them to,
and lose them in God--for to this end we were created; and then we are free, happy,
and blessed indeed.
May this be verified in our experience!

It is, however, unnecessary, dear brother, and often injurious,
when the soul seeks to know so precisely the different degrees of spiritual life.
It is not necessary to say much upon the subject;
it may occasionally serve for the information of him who has to instruct others,
but he must not seek to lead others according to any particular plan,
even as God does not guide every soul in the same manner.
For instance; many at the commencement, enter upon a course of severe legality;
others into deep repentance and distress on account of past sins; and others again,
are drawn by lovingkindness and tender mercy.
Some attain to a view of their depravity, etc., at the beginning; others, afterwards.
He, therefore, that will minister unto others, must follow God, and observe him,
and act as a nursery maid that follows a child, and only turns it away,
when it is running into danger.
But it is our own exercise in prayer and self-denial,
which ought to give us the true insight into the ways of God.
Solitude, prayer, and self-denial!
O how necessary are they to every soul at this period!
In these we ought ourselves to live, and when necessary write,
and give occasion to others to exercise them.

A minister ought likewise to endeavor to inspire
the soul with a good confidence towards God in Christ,
yet so as never to lose sight of self-denial,
in order that the individual may detach the heart, voluntarily and from love to God,
from everything else, and fix it alone upon him.
He that walks disorderly must be admonished;
yet we must not prescribe too many laws of self-denial for peculiarities,
but leave grace to counteract them,
and chiefly insist upon the complete surrender of the heart.
We ought to know how to give way to the weak, and yet keep the end in view,
in order that by making a little circuit, they may be brought imperceptibly nearer to it.
God grant unto those, who have at present to converse with others on spiritual things,
a rich measure of his Spirit!
O who is sufficient for it!

My time is expended, I must therefore break off.
You will perhaps, be unable either to read my writing,
or to understand my meaning properly.
Brother N+++______+++ may read it with you; otherwise it is not for everyone,
particularly as I write in great haste.
The Lord bless and strengthen you, particularly in the inward man!
Remember me also.
I remain,

[.signed-section-closing]
Yours in weakness,

[.alt.centered]
=== Letter 15

[.salutation]
To +++______+++,

It is more and more apparent to me, that God loves your soul,
and has his eye particularly directed towards you, to aid and preserve you,
and gradually to lead you to place your life and delight alone in him,
and in the unconditional and voluntary submission to the whole of his divine will.
This is the reason for all your sufferings and troubles; and from this arises, chiefly,
all your vexations, and the disrelish and indifference you feel towards divine things,
because the life of self sees its end approaching,
and still does not believe that its fate is so fully decided,
and that the sentence will be executed, without mercy.
I conjecture also, that there are sometimes seasons,
in which a little hope is given to it, which makes it feel still more severely,
when the hand of divine love again nails it to the cross,
and leads it where it would not.

But let your depraved nature know, once for all, that the heaven-born spirit,
and the will of the spirit, will no longer take part,
nor be on terms of intimacy with it.
No, my dear brother, let us expect no more life, comfort, or pleasure from that quarter,
nor grasp it when it presents itself; for in reality, we have no need of it.
Let us only be planed down, endure the cross a little longer,
and in believing expectation, give unto the true and faithful God the glory,
and soon a very different, solely-satisfying life, comfort,
and delight will be perceived, and impart itself to the soul; a life,
a quarter of an hour`'s enjoyment and experience of which,
is sufficient to counterbalance a hundred years of waiting and suffering.
In due time, everything that was previously so difficult, will be easy,
and that which before presented itself to us as a profound abyss,
and as something unattainable, will be found close at hand, and become natural.

Everything depends upon God`'s free mercy, the impartation of his influences,
and the operation of his grace.
Receive it therefore, consent to all that God works in you,
and the attractive influence he gives you to experience, and follow this impulse,
but only as far as its strength extends; then suffer, be submissive, and wait.
God gives us both to will and to do according to his good pleasure;
but he often imparts the will, yes, and a sincere, cordial, and fervent will too,
long before he gives the power to do, or attain the wished for object.
This is painful, but is at the same time a purifying, humbling pain.
We must eventually experience, that it is not of him that wills;
the mercy of God must grant the blessing.
It is not our will that must seize it; for the will to do appears sometimes to fall off,
like the blossom from the tree, and to sink into a holy resignation,
that room may be made for the fruit itself.

Be of good courage, my dear brother!
I cannot think otherwise, than that the Lord leads you; endure with him to the end,
as quietly as you can.
Do not regard yourself too much, however difficult it may be to avoid it.
The Savior had incomparably more to endure, in order to redeem us,
and still he bears our burdens.
O let us love him, for he first loved us!
I desire particularly to be cordially remembered to your dear old father;
may Jesus visit, refresh, and strengthen his heart with his grace and love,
that his old age may be in this life, an infancy and commencement of an eternal life!
Amen.
Jesus!

[.alt.centered]
=== Letter 16.

[.salutation]
Very dear and much esteemed sister in the grace of God,

Both your letters have arrived safe.
From their contents, I have learned and considered, with much compassion,
your afflicted and tempted state, and have spread your case before the Lord.
__He,__ the Lord, can help you; you must not expect assistance from yourself,
nor from any other creature, nor from any particular object, but from him alone.
I confess, your trials are severe and painful; but preserve your courage,
cast not away your confidence.
These things must be; but the end will be peace.

I am not at all surprised,
that you think your dearest friends have not a sufficient insight into your state;
because your heart does not or cannot think respecting the Lord himself, who is,
nevertheless, love alone,
that he regards and acts towards you with so much love and mercy as he does.
The black veil of unbelief, which at present covers your eyes,
is the only cause why you imagine God and your friends
to be otherwise than what they are.
God has no pleasure whatever in our pain; but he is often compelled to make us sting,
in order to deliver us from our inward depravity.
The evil there is in us, is the fuel to this flame.
Submit therefore to God`'s gracious arrangements, and all will be well.

I particularly request you will observe,
that by "`evil,`" I do not so much understand the deed,
as the principle from which all evil deeds proceed.
Methinks you do not sufficiently perceive where the evil lies, that causes all your pain.
You have certainly done wrong, dear sister, in giving up your house, and hiring another,
which is perhaps not more suitable for you, without sufficient reason,
and what is still more, without the advice of good friends;
but that you should deduce from this mistake such inferences as you do,
as though you had now sinned against the Spirit of God,
and hardened yourself against the Lord; that he will now punish you with death,
and that you will eternally perish; and that you allow yourself to be brought by this,
into such a state of confusion, distress and despair,
is evidently a device of the adversary,
who makes use of the principle of evil within you (and from which the
Lord will deliver you) that he may cast you into this temptation.

If you have failed in this matter,
(which is the case,) confess it frankly before God and your friends, entreat forgiveness,
and do not make a bad use of your fault or sin, but a good one.
When children break anything, or are disobedient, they are punished for it,
but are not expelled the house; and by promise of amendment, and childlike humiliation,
the matter is settled.
See Micah 7:8; 1 John 2:1. Do but go forwards again with courage,
and make a good use of your fall.
This good use consists, not only in going more prudently to work another time,
but chiefly in letting yourself be led, after the commission of a fault,
to the discovery and sincere confession of the evil principle within.
This would be such a benefit to you, as would recompense your stumbling tenfold;
and the Lord has this in view, and expects it from you,
it being his intention to lead you into such a discovery and confession.

Learn from hence, that your happiness or unhappiness does not depend upon _the house,_
but upon the state of your mind.
When it is well within, all is well.
You must have too good an opinion of yourself,
(do not be surprised at my expressing myself thus) or you
would not allow this affair to distress you so much.
Is it possible that the very sight of your wound or sin makes you faint?
Do you not believe that you have other, and greater sins than this?
Those who are really poor sinners, are deeply humbled at the sight of their sins,
but not so much disturbed and utterly cast down.
As long as we are not sincerely humble, we resist God, and he resists us (1 Peter 5:5),
and it is this which is so hard to bear.
Consent sincerely to your nothingness and misery;
and submit to be and to be found such as you are; the Lord is then with you,
and will break your fetters.

Your ideas of the riches of the grace of God in Christ Jesus,
are certainly too mean and contracted.
Think of what I have said above, respecting disobedient children.
If anyone who had offended you, were to entreat your forgiveness with tears,
would you not forgive him?
And shall the mercy and goodness of God be exceeded by that of a sinful man;
or is it merely for those, who have deserved it by their faithfulness and their virtues?
By no means!
Even our very faithfulness and virtues, to be good for anything,
must be expected and received from the mercy and goodness of God.
O may the Lord enable us worthily to appreciate the blood of the Son of God,
of the Lamb of God that takes away the sin of the whole world!
Repenting sinners ought to cast themselves with all their sins into this abyss of mercy,
and all their sins shall be consumed like stubble in the burning furnace!
This is the comfortable assurance and promise, "`If we confess our sins,
he is faithful and just to forgive us our sins,
and also to cleanse us from all iniquity.`"
(1 John 1:9)

You have too much improper love for, and confidence in yourself,
and too little love and confidence towards God.
Is not that improper?
You think and care a great deal too much about your body, its health, and life,
just as if it belonged to you, or as if life and health depended upon your care,
although we know not what is best for us.
And you care in the same manner about your soul,
and hold it as fast as though you were your own preserver and savior.
Are not both your body and soul the Lord`'s? Have you not committed them to him,
when you first found that you were in a lost condition?
And are you not willing this moment to renew the surrender?
Do so, therefore, beloved sister, in fervent sincerity,
and do it as often as self-love seeks to plunge you in anxious care regarding yourself.
Commit unto God your body, health, and life, your soul, your time, and your eternity,
leaving hold of, and losing yourself in his faithful hands; you are then in safety,
and beyond the reach of all tormenting sorrow!
O my dear sister,
do not think that God does not love you infinitely more than you love yourself,
and that he will not take care of you, receive you, preserve and protect you,
infinitely better than you are able to do!
Yes! he will do so, if you only resign and commit yourself to him in this manner,
and this also he will work in you.

You follow too much your own opinions,
and too little the opinions and counsel of the children of God, your good friends.
But have you not reason to believe, that your light is still small,
and that particularly at present, you are in confusion, darkness, and temptation,
and consequently not in a condition to judge of yourself and of your present circumstances?
Would it not therefore be more proper and more pleasing to God,
if you did not build upon the dangerous practice of opening upon,
and appropriating to yourself a passage of scripture, or upon your own mutable, passing,
and disturbed thoughts, but that in an artless and childlike manner,
you believed what others, who assuredly know you better than you know yourself,
judge of your state and advise you?
O how soothing and salutary would you find such a childlike submission!
And if, as regards your house or habitation,
you submitted your own will and judgment entirely to that of another!

How salutary it would be for you, were you in secret to say unto God, "`O Lord,
I have brought myself into this dilemma, by following myself!
Have pity upon me, a poor ignorant child, and lead me aright!
And because I am unable, in my present dark and confused state,
to distinguish or to choose what is pleasing to you,
and will not follow myself any longer,
I will commit the matter to some particular individual.
Do therefore, instruct that person how to advise me, and then, whatever advice I receive,
I will believingly accept as the expression of your adorable will, submit to it gladly,
and regard the result, whatever it may be, as good and proceeding from you,
with the help of that assistance, which I look for from you!`"

See, my dear sister, this is the brotherly advice I give you, for I know no better.
If you follow it, I am persuaded you will reap benefit from it,
and find peace for your soul.
I repeat it once more: it is not the houses; when you are inwardly wrong,
all is wrong--when you are inwardly well, all is well, everything and everywhere well.
It is alike to the Lord where we live, but not how we live.
A royal palace is too narrow for him, that lives to himself,
and a little cottage is large and beautiful to him that lives to the Lord.
I pray God, from my inmost soul, that he may guide and bless you,
and that he may make you acquainted with himself, in order that you may love him,
and unreservedly commit yourself to him!
Amen.

[.signed-section-closing]
I salute you with fraternal affection, and remain through grace.

[.alt.centered]
=== Letter 17

[.salutation]
Dearly beloved brother,

In the supposition that you are still at N+++______+++, I write these few lines, in haste,
greeting you.
May Jesus bless you!
You do nothing else but look back upon yourself,
which cannot fail of disturbing and dispiriting you.
Had I done so, I should long ago have perished in my misery,
for I am not so holy as some take me to be; but I hold my peace,
and even let them praise me to my face, lest in addition to this,
they should scold me for my humility.
I believe the light of truth alone,
in which I secretly and simply regard myself as the most miserable of mankind,
and do not defend myself when praised by others.
The commission of a fault, particularly when others also knew of it, made me, formerly,
as ill as it does you.
Afterwards, I was directed to a cure for it,
which was the valuable love of self-contempt, which, every time I used it,
tranquillized and refreshed me so wonderfully, that in consequence of it,
I quite forgot my disease.
But this medicine should be taken courageously, and not merely tasted with the lips,
otherwise it will be found much too bitter.

I am not jesting--there is more truth in the above, than I am able to express.
Looking back upon yourself injures you more than all your faults,
and self-love is certainly the cause of it.
But why are you so astonished at the discovery?
Did you not know that you were a self-loving child of Adam, like myself and others?
Ought we to be melancholy on making such a discovery,
or rather ought we not to strike up a _Te Deum laudamus,_
that the Lord has granted us such a special favor, as the knowledge of ourselves?
No one can more cheerfully chant a _Te Deum,_ than he who knows and despises himself.

You say, in your last, that the pain on account of what you have done,
is still very poignant.
This I do not understand.
Yield yourself up in God`'s name!
We are not a thing that is so much worth looking at.
If you cannot offer yourself up as well as you could wish,
bear with yourself willingly and quietly,
and sweetly turn away your inward eye from yourself, and fix it inwardly upon Him,
in whom is all your salvation.

We must heartily believe that we are wretched, evil, and incapable of doing any good;
yet we must not tell this to everyone, but speak of the greatness, and goodness,
and blessedness of our God, and that in him all salvation and felicity dwell.
Let this be the subject on which we meditate, of which we speak and sing,
and in which alone we rejoice.
Amen!

[.alt.centered]
=== Letter 18

[.salutation]
Much esteemed and dearly beloved sister in Jesus, whose Spirit be with your spirit!

I have duly received your very welcome letter, and have perused with much union of heart,
the precious truths it contains.
It is true that self-love has struck its roots much
deeper within us than one would imagine.
The eye of God alone can trace them out, and his hand can alone eradicate them.
He that perceives but little of this self-love, goes, as he ought to do, to his labor;
but he that perceives much of it, gives up his work,
and resigns it to the all-piercing eye of God, and his adorable and faithful hand,
which makes its commencement and beginning where we leave off, and where,
after being brought into judgment by his justice, we must confess with Job (14:4),
"`Who can bring a clean thing out of an unclean?`"
Escaping and departing from one selfish principle is often but the introduction to another,
until we see no more possibility of escaping and reforming,
give God in judgment the glory, and by suffering, die unto self,
in order to make room for the divine life of Jesus Christ, which alone is pure.

It is, however, as you say, by looking back,
that we first of all discover that to have been self-love,
which we mistook for the pure love of God.
But how much ought we to praise and love the Lord, that he discovers this,
and many other things to us in the sequel, and not on the outset!
His divine hand makes use even of the evil that is in us, in more ways than one,
to make us better.
Self-love, which in its way, makes us fear hell and love heaven,
is that which generally excites men to listen to converting grace;
and the Spirit of God employs, throughout the Bible, such inducements as these,
because fallen man is incapable and unsusceptible of any other.
And not only so, but I well remember to have read,
// lint-disable invalid-characters
what you may now find in [.book-title]#Bernire`'s Hidden Life,# that
we ought not to desire perfection,
because it is such an exalted state,
but because it is the will of God that we should attain to it.
It is now nearly thirty years since I read this in French,
in the writings of that departed saint,
and through it received a kind of sentence of death to my self-love,
which was hit in the most susceptible part by this expression.
But I thank God, that I did not meet with or understand it sooner,
because I required another wind to bring me there.
And how much has been since discovered of this evil, which for awhile seemed good,
until the leprosy had spread and insinuated itself into everything, from head to foot,
both inwardly and outwardly (Lev. 13),
and I found myself obliged to submit myself helpless and without advice,
solely to the decision and the hand of the divine High-priest.
And herein we will continue with God,
that he may fulfill in us all the good pleasure of his will;
and sincerely consenting to our own nothingness, cordially rest in his all-sufficiency,
and in this, that no one is good, pure, and lovely, but God alone, and what he works.
O yes, my dear sister! in this we may rest with childlike confidence,
and sweetly rejoice, and really feel happy, that the Lord our God is what he is,
that we are such nothings, and that He is God alone!
O how good and excellent it is, that seeing there is nothing more in us that can boast,
that the Lord acts towards us so wonderfully, and that although we have nothing,
yet that we can be so satisfied and tranquil in the conviction that he is our purity,
our treasure, our peace, and all our salvation, from pure unspeakable love to man!
This he will be to us, more and more essentially.
We must not reflect on our own purity or impurity,
but close our eyes in childlike confidence, casting ourselves wholly upon him,
and waiting for his operating influences and his salvation.
Amen.

I must now break off, dear sister, while cordially saluting you,
and presenting you as a living sacrifice to the Lord in his presence.
Be He your life, your peace, your all, in every inward and outward circumstance!
I remain through grace,

[.signed-section-closing]
In tender affection, your obliged brother.

[.alt.centered]
=== Letter 19

[.salutation]
Dearly beloved brother in the grace of Jesus,

Although we correspond but little by letter, yet I can say in simplicity before God,
that I love you, and find myself united with you in spirit; as also,
that your last letter of the 17th of January, has afforded me pleasure.
I observe, it is true, that you form too good an opinion of me;
but this is the effect of your love, and I wish to derive benefit from it.
I have endeavored to lay before the Lord in prayer, your state of mind, respecting which,
like a brother, you have communicated something to me;
and shall continue to endeavor to do so,
according to the grace which I myself expect from him.

The great importance of perseverance in the exercise of
prayer and inward retirement may be sufficiently learned,
next to the experience of it,
merely from the tempter`'s artifices and endeavors to allure us from it,
and make us negligent in it.
He knows by this delightful exercise alone,
his gloomy empire in the soul will necessarily be destroyed,
through the imperceptible influx of the light, love, and life of Jesus;
and that all the flowers and fruits of the fairest
gifts of grace and virtue fade of themselves,
if he can only break them off from this their root.
Jesus alone, is the Mediator and medium,
by which divine life and strength can be again imparted
to our illegitimate and depraved humanity.
By the exercise of the prayer of the heart, in which faith, love, hope,
etc. concentrate themselves, we are, and continue united to him,
and rooted in him--the hungering desire and affection, and ardent inclination,
being as it were, the root, by which we imperceptibly receive from Jesus,
sap and strength, although we do not always obviously see and feel how it is,
and whether it is taking place.
O let us pray, and prepare ourselves for retiring within our hearts!
The most imperfect prayer is of more advantage than the best diversion from it.
The adversary lets us do many things, which seem to be good, and even incites us to them,
only to cause us to neglect prayer.

My dear brother`'s letter only confirms me in what my own experience,
and the experience of others,
has repeatedly taught me--that the tempter especially watches,
in the season of abandonment, barrenness, and darkness,
to detach the soul from the steadfast exercise of prayer, and to weaken its strength,
these being precisely the times when we might be
prepared for making the most rapid advancement,
and for thoroughly forsaking ourselves,
if we only continued firm in enduring the Lord`'s will,
and knew how to submit ourselves entirely to him.
I mean to say,
that when we cannot proceed with the exercise of prayer in the customary manner,
we ought not to hold fast, with firm efforts and self-will,
what the Lord pleases to take from us; but humble ourselves,
quietly consent to our nakedness and poverty, sacrifice our relish, light, and pleasure,
to his good pleasure, and make the latter our prayer and our food; we should then find,
in time, the advantage of thus letting go of ourselves, of privation,
and the loss of self, so to speak, and be made capable of a more profound,
or rather of a purer retirement, mode of prayer, and union with God,
which is the very object the Lord has in view.

But our misery and weakness is, that we are so much under the influence of self-love,
and seek ourselves, even while thinking we are seeking God;
and if we then find nothing for ourselves--no light, relish,
nor anything that is agreeable, we imagine we are unable to find God, become weary,
and coward-like, and even seek support for this selfish principle in other things,
because it is no longer granted in God, and in that which is good.
O my God, how extremely unsuitable is such a disposition of mind for one,
who has devoted himself to your pure service and your love!
Destroy this principle of self-love, that we may seek, not ourselves in your service,
but you in reality, not our own pleasure, but yours; for you are our end, and in you,
and not in ourselves, is all our salvation!
Amen.

Before the day of Pentecost arrived, the disciples could not hold out long in solitude,
without the bodily and visible presence of Jesus.
"`I go a fishing,`" said Peter.
Time appeared long to them in solitude, and such is the case also with us.
We go, as it were, a fishing, in a book, in the company of others,
etc. and it is a favor when we can catch nothing during the long night,
and when the Savior meets us, and shows us, as he did the disciples,
the fruitlessness of all self attempts.
I testify with fear, shame,
and deep acknowledgement of the divine long-suffering and goodness,
what my own experience has taught me with respect to this--that
the exercise of prayer is of so much importance,
and that in seasons of inward darkness and barrenness,
we fall into this temptation so easily.
The injury occasioned by it is not immediately perceived;
but the individual gradually wanders further, and sometimes so far from the track,
that he has scarcely courage enough to turn again.
A soul without the exercise of prayer, is like a solitary sheep without a shepherd.
The tempter is aware of this--he avails himself of
the dark and destitute state of the mind,
to draw the soul away from its shepherd--he then cunningly spreads his nets,
puts the mind into doubt and confusion, places something believable before it,
urges it to a variety of changes, and that it should make trial for once,
of some particular exercise, of this or that particular place,
or join itself to some superficially pleasing sect,
by which many well-meaning people in this and former times,
during the darkness of the night, have been deceived, as a warning for us,
that when in a state of darkness and barrenness,
we ought not easily to change our exercises, but continue where we were.

In the name of Jesus, let us only take courage, begin again where we left off,
and conduct ourselves precisely in the same manner as before our deviating!
The wonderful goodness of our God makes use of everything,
even of our very faults and sins, for our benefit: adored be his wisdom!
We must also, by looking back, make the best possible use of ourselves,
and lay up from it a good stock of self-contempt;
although we ought by no means to exculpate our faults on this account,
but avoid them with all diligence (Romans 6:12). When by divine light,
we perceive our nothingness, it produces humility,
but a humility of which we are sometimes a little proud;
but when our nothingness is felt by experience, self-love has no hole left for escape;
we can then do nothing more than stand and confess our disgrace.

There are many who talk of denying self-righteousness who have, perhaps,
little or no righteousness to deny;
but this poison is the first to steal into the minds of faithful souls,
that they imperceptibly place their righteousness and their confidence in their fidelity,
in self-denial, in their virtue and graces, in their devotional exercises,
and not entirely in God alone.
The Savior then opens our eyes, as with our own clay,
by which his wonder-working hand has alone the glory, we the shame.
The experience of our weakness and misery, and of our entire nothingness,
ought not to dispirit us, but to give us occasion to empty us of ourselves,
to forsake ourselves, to turn unto God the more nakedly,
and consequently the more efficaciously, in order that he may fill us with himself,
and become that in us, which we ourselves could not attain nor accomplish.
And this is the will of God concerning us, that no flesh might glory in his presence,
but Jehovah alone become our righteousness and our glory.
You see, therefore, dear brother, that the state of destitution, emptiness,
and abandonment, to which the experience of our misery gives occasion,
would make us subsequently capable of the most sublime
method of prayer and of union with God.
Blessed be the wondrous and infinite lovingkindness
of our God in Christ Jesus towards us!

Having been continually interrupted, while writing, and led to think on other subjects,
by visitors and engagements, my letter may perhaps appear to you irregular and obscure.
I only wished to show my artless love,
and accordance with that which the Unction itself teaches.
Let us continue, my dear brother, to go to school to this infallible teacher of wisdom,
and become ever longer little children after God`'s own heart.
O yes, it is truth, which the Unction teaches, and there is no other truth besides!
I greet and salute you in the spirit of love.
Remember me before God, whenever you are enabled to do so; I desire through God,
to do the same.

Remember me kindly to the dear members of your community
in N+++______+++. I often send them a hearty blessing.
May Jesus warm and animate their hearts and ours with his precious love!
Amen.

I continue in a weak state, and but little able to write,
and this weakness now tells me to break off.

[.signed-section-closing]
I remain, through grace, etc.

[.alt.centered]
=== Letter 20

[.salutation]
Dearly beloved sister in Jesus, the crucified and exalted Redeemer,

I have for some days past,
felt myself impelled to write something to you regarding the present state of your soul.
And although I find myself so dark and void,
that I do not see what I ought to say to you,
yet my mind will not be satisfied till I have done so.
I will therefore obey in simplicity, hoping that God will grant me something,
which may serve to strengthen and prove a blessing to you in your present affliction.

You may rest assured that I am more concerned for your soul`'s advancement in true holiness,
than I can express or manifest outwardly.
And notwithstanding the wretched state in which you describe yourself to be,
I am still quite at ease regarding it, and am under no apprehension of evil consequences.
Were I concerned for you after the manner of men,
and were I glad to see your own life--the life of self--preserved,
I might have reason to fear; because our Lord attacks it so forcibly and severely,
and pursues it so warmly, that it must, very likely, soon give up the ghost,
which takes place and is accomplished by the complete and
eternal resignation of yourself into the free hands of God.

You see and feel nothing but sin and corruption within you and in your outward conduct.
Whithersoever the mind turns and directs its view, everything is misery, grief, and sin;
and the way to escape from it is closed and appears as if it were always to continue so.
Ah! thinks subtle self-love, could I only find a little nook,
to which I might retire and take a little rest, like a drowsy man,
who throws himself first into one position, and then into another,
without being able to sleep.
Listen,
O soul! cease your turning and twisting! the more you seek to make matters better,
the worse you make them; the more you endeavor to perform something good of yourself,
the more faults do you commit.
There is now an end to all self-working.

You say, you do nothing good.
You ought rather to say, I do not see that I do anything good;
for subtle self-love is not satisfied with the practice of virtue,
but this left hand of iniquity must also know and see what the right hand does,
in order to take pleasure therein.
But God, whose intention it is to destroy this life of self,
and to have our virtues pure and disinterested,
does not permit the soul to reflect upon them, nor to review its virtues,
either before or afterwards.
The impurity alone is seen.

Therefore, as long as it pleases God to leave you miserable, corrupt,
and without strength, let it also please you.
You behold your real self, at present, as you are in yourself; thank God,
for having thus disclosed your inward wound to your view.
The gold is now in a state of purification--the dross appears,
the gold is hidden so that nothing but the refuse is visible.
Rejoice, therefore, dear sister, that you are so wretched, and that God is so holy,
and so perfect.
Wretchedness and nothingness is our proper station;
holiness and all-sufficiency belong unto God.
He that longs to see himself beautiful and holy,
only manifests his self-love--at least at present,
it would be a fault and an imperfection.
Resolve, therefore, with Job, to sit quietly on the dunghill of your misery,
and to love God notwithstanding.
You ought, I say, to love your wretchedness, but not your sins.
Say unto God, in the most thorough conviction of your depravity, "`Lord,
I will nevertheless not sin!
Lord, I will still remain entirely yours!
I resign my will unto you for time and eternity.
Let happen what may, only enable me to love you and glorify you!`"
And when you think that you have committed some sin, or really have come short,
continue to say the same.

I am not surprised at the ill temper, impatience, and anger, in particular,
that arise in you.
Previously, when the dealings of grace with you were so lovely and gentle,
nature and sense occasionally participated in it;
but in the way in which you are at present,
they are deprived of all inward and outward support.
It is impossible that nature and sense should acquiesce in this total destitution;
they must die, and yet will not; they often know not what to do for vexation,
and are ready to murmur against themselves and everyone else,
and sometimes even against the holy ways of God, just like a dog,
that bites at the stone which is thrown at it.
If you feel this or something similar in you, regard nature as such an evil brute,
and say to yourself, "`Let this wicked thing perish with all its rage!
What have I to do with it?
Resist as long as you will, you obstinate nature, you shall die notwithstanding,
and be destroyed!`" and then leave it, and pay no attention to its fury.
Possess your soul, at the same time, as much as possible in patience.
Do not break out too much into words, if it be any way possible to contain;
nor give way immediately to desponding thoughts, such as wishing to die and the like.

Sometimes it will occur to you,
that it is impossible for you to endure it any longer--that you must give
it up and return to the world--that you will certainly be lost forever, etc.
But reflect for once, dear sister,
have you not previously often and heartily surrendered yourself to God and his guidance?
Have you not often sincerely besought him to cleanse you thoroughly from all your corruptions,
and to sanctify you perfectly by such ways and means as he might find best?
Have you not frequently and cordially vowed, with his assistance,
to continue faithful unto him till death?
What?
Have you entirely forgotten all this?
Now, when God has heard your prayer, and touches you where it gives you pain,
will you give up your courage, and turn back again?
Is this keeping your word?
Yet no!--you are no longer your own; you have given yourself to the Lord,
and he has accepted you; you have nothing more to say in the disposal of yourself.
Certainly, God will not allow that which belongs to him, to be thus taken from him.

But in opposition to this, you will say, "`I feel nothing but corruption, sin,
and inability.
I am every instant in danger of falling and sinning, yes, methinks I sin really;
the longer I live thus, the more I increase the number of my sins.`"
I do not believe that you sin really, that this, willfully and knowingly;
for you are not so fond of sin.
The view and perception of sin causes you these bitter sufferings,
and that which alone so much distresses you is,
that you see and feel nothing within you but sin; how then can you willingly practice it?
But that in such a state of severe purification, we must feel so lively and forcibly,
the very corruptions which had been previously cherished and obeyed with delight,
so that we think nothing else, but that we really practice them, and finally,
that sometimes some particular corruption will unexpectedly break out again,
contrary to our will, is neither contrary to experience, nor the Holy Scriptures,
which say, "`wherewithal that a man sins, therewith shall he be punished.`"
(Book of Wisdom 11:17;
Rom. 8:3). You are also perhaps acquainted with
the lines I wrote some time ago upon this subject:

[verse]
____
I once committed sin, with pleasure and with lust,
But now must suffer sin with sorrow and disgust;
This suffering is wholesome--but what grievous pain,
When sin, by sin within us, is condemn`'d and slain!
____

But that you think you will fall into sin every moment,
arises partly from the darkness which at present covers your path,
which occasions all manner of doubts, fears, and apprehensions;
so that you think all kind of danger is at hand, when there is often nothing of the sort.
Close your eyes to all that surrounds you; walk in faith and resignation,
and fear will vanish.
And when the light dawns upon you, you will say that you have walked in the right way.
This fear arises also in part,
from the withdrawment of all perceptible strength and support.
The case is with you, as with a child, that is always afraid of falling,
although the mother holds it fast behind by leading-strings,
without the child`'s being conscious of it;
but as soon as it is in danger of stumbling or falling,
it would be aware of its mother`'s supporting hand.
No, my dear child, there is no need to be afraid; your mother is near,
although not before your eyes.
The more you are afraid, the worse you will stumble;
and if you were on the point of falling, you would be conscious of something in you,
which held you back, or ordered everything outwardly in such a manner,
as to keep you from stumbling.
Rely upon the supporting hand of God without seeing it, and repose,
upon the guidance of his divine providence, by which he will overrule all things,
both internally and externally, to a good end.

Commit yourself to God, and let your love be pure and disinterested,
and so shall you be healed.
Give yourself up entirely unto God and his unlimited will, both for time and eternity.
Banish all care regarding yourself, so that you would no longer look after yourself,
although you knew, that by acting thus, you would sink into hell;
for of what value are you?
And what is it that depends upon you?
_Consent to everything except to sin._

If it occur to your mind, that you are at present,
or may become the ridicule and scorn of all men and of evil spirits,
let your will agree to it, and say, "`Of what value am I! I will glorify God,
notwithstanding; I will love him, notwithstanding.`"
If the thought arise in your mind,
that your wretched condition will become still more
wretched--that it will continue so till death,
and that you will perish eternally--consent to all this, and say,
I will nevertheless not sin, I will still love and glorify God;
what does it matter what becomes of me!`"
Act thus with everything that passes in your mind.
In this manner resignation will give place to a disinterested love,
and your bitter and disturbed emotions shall be changed
into a soothing and profound peace,
and your distressed condition into an unlimited immensity and liberty of spirit.

Remember that God continues to be God; and that he is as kind and lovely now,
as when you saw and tasted his goodness.
Love him therefore now, quite as much, and if possible, still more than before.
God has many thousands, who praise him in heaven and on earth;
let him then have one instance, in you, out of thousands, who praise him in hell,
where you imagine yourself to be.
The former do it in the enjoyment of light and delight;
do you do it in the midst of darkness, and while hanging with Jesus on the cross,
in external and internal affliction.
O how beautiful, disinterested, and lovely is the praise of God,
which proceeds from the heart and lips of a suffering soul, out of whose mouth,
like Job`'s, nothing proceeds, but "`the name of the Lord be praised!
The Lord is good, the Lord is gracious, he alone is the source of life!
O that every creature might know and serve him!
Love him, all you righteous in time and in eternity!
O what a blessing that God is God; that he is so holy, so glorious, so blessed,
and so perfect as he is! etc.`"

If, my dear sister, you have little perceptible enjoyment in this state,
it is so much the purer.
If you possess no clear knowledge or light from God of his perfections,
there is no harm in it.
You cannot, therefore, praise and love God otherwise, than as the unknown, hidden,
and incomprehensible God, of whom you neither can nor ought to form any idea how he is,
or where he is; and therefore, in so doing, you act in a manner,
which is the most perfect and well-pleasing in the sight of God.

You think that your friends are unacquainted with your state,
and have a better opinion of you, than the fact warrants;
but this is a little temptation, and a lack of simplicity of faith.
Let me tell you, however, that you yourself are ignorant of your own condition,
and that you have a worse idea of yourself than the case deserves.

It is not however necessary that you know much of yourself, and of your state.
It were better if you and I knew nothing more of ourselves.
Judge not therefore respecting yourself, because you are in darkness; but believe those,
whom you know would not willingly flatter or deceive you,
although you may suppose you feel the contrary within you, to what is told you.

I know, dear sister, in some measure,
what it is to have a powerful view of the holiness and purity of God,
and to cherish some inward and sincere desires after holiness, and yet,
notwithstanding all this, to see and feel nothing in one`'s self but sin and self.
O, we ought to be ready to sink into the earth, at the sight of ourselves!
And nature ought willingly to do so before God,
and experience a little of the distress of those who shall exclaim, "`Rocks, fall on us,
and hills, hide us from the face of God.`"

I know, in some degree,
what it is to be acquainted with God to know him to be supremely excellent, beautiful,
delightful, and lovely, and yet be unable to love and glorify him; but on the contrary,
apparently only dishonor, offend,
and act in opposition to him--to know this supremely beautifying being,
and yet at the same time, to see one`'s self cast so far,
so very far away from him and the enjoyment of him, into misery, sorrow, and darkness,
yes, and to believe nothing else than that this will last forever,
and forever become more aggravated!
The troubled mind then thinks, "`O, had you never known God and his goodness!
Had you not known him to be such a God, and such an adorable being,
you would now perhaps not experience such distress and torment!
You now know something of his excellencies, you now long so fervently after him,
and yet must remain separated from him.`"

O the admirable wisdom of God, how lovely,
yet how severe in its dealings towards those that are his!
You allure them to you with lovingkindness, and let them behold your countenance;
but soon, and before they have properly seen and enjoyed you, you depart,
and hide yourself with such severity!
You wound them with the arrows of your love, and let them be forsaken in their pain!
You lift them up to behold the glories of heaven,
and cast them afterwards down into hell; and yet you continue to be love itself,
and desire that your bride should love you, as well in hell as in paradise!

But I see that my letter is growing longer than I intended;
I will therefore only add a few short and necessary admonitions,
which ought to be particularly attended to during prayer or retirement,
or in your daily walk; and with these I will conclude.

I have already often stated my sentiments regarding the seasons of retirement.
If circumstances allow, do not neglect them, either on account of your unfitness,
or the repugnance of nature, or from any other consideration or temptation.
Do not, however, continue too long alone at one time,
unless God favors you with some particular grace and strength.
Use little or no effort in prayer; for the exertion of the mental powers,
would injure both the body and the mind.
If you seek by the smallest effort to collect or elevate your mind,
you will soon perceive that it will occasion irritation, anxiety, and darkness.
When I said that you ought to commit yourself to God,
I did not intend that this should be done by any formal act,
or by much inward exertion and mental reflection; but what I mean, is,
that you ought to forget yourself, as much as possible,
nor voluntarily reflect upon your state, and the circumstances connected with it.
Abstain from all care respecting yourself, and then leave yourself to God,
and let your vessel sink, which is also an excellent species of prayer.

But it is not good for you at present to seek God as an object,
in an anxious manner in your prayers,
either by means of much elevation of thought or repeated retirement.
Remain, as much as you are able, peaceful, joyful, and cheerful, at the moment.

Continue as you are, and unite yourself with God,
not as with something which you have first to seek,
but as with something which you already possess;
for God is certainly with you and in you, although concealed by darkness.
O that I could impart to you a peaceful and enlarged heart, both during prayer,
and when not engaged in it; how serviceable would it be to you!

If, when employed or in company,
something unexpectedly occurs to call you to recollection, although secretly,
and without unction--follow it that moment, in childlike simplicity,
if circumstances permit; or cease a moment from your work;
you will experience the benefit of it: it is God`'s time.

In your walk and conversation,
strive more and more to make progress in childlike simplicity and innocence,
and without reflection.
Take no thought for the future, and look not at the past; both disturb,
and are contrary to your present state.
The present moment should be your abode, for God and his will are to be found in it alone.
Generally speaking, you will scarcely ever fail, when you go to work in outward things,
as it may appear to you at the time.
If you look forwards or backwards, you are already involved in doubt and anxiety,
and are no longer able to recognize what is the will of God.
Be not scrupulous regarding works of obedience, if not in themselves sinful.
All self-made choice, however good it may be, must yield to obedience.

Do not converse much with people, unless there be a necessity.
If possible,
never speak as long as the influence of anger or irritation is powerfully felt.
Say little or nothing regarding your sufferings to others.
Let it be sufficient for you, that the Lord your God beholds your sorrows,
and that his eye is upon you.
You must, however, account that a temptation,
which would lead you to avoid the society of his children altogether,
or to cease visiting me on any pretext.
We are all miserable and sinful in ourselves,
and it is our duty to bear one another`'s burdens.
You ought therefore to visit me as frequently as before,
and not conceal anything that might serve to make me acquainted with your state,
when it occurs to you.
You give me no trouble, nor do I suffer anything on your account that disturbs me;
but if my suffering could avail you, I would certainly, with the Lord`'s assistance,
not shrink from it.

Let us become little children, nor reflect much about anything.
If I had given way to reflection, I would certainly not have written this letter,
but have continued altogether silent,
and have hidden myself on account of the great poverty, wretchedness,
and blindness in which I am at present--yet I have the confidence
that this letter will be neither disagreeable nor hurtful to you.

Be only patient and courageous, in God`'s name, dear sister, in loving and in suffering;
and whatever may happen, through divine grace, I am, and will remain,

[.signed-section-closing]
Your affectionate brother in Jesus, and companion in tribulation in Christ.

[.postscript]
====

P.S. Keep this letter to yourself, because it may be of little advantage to your friends.

====

[.alt.centered]
=== Letter 21

[.blurb]
==== To the same.

[.salutation]
May the once crucified but now exalted Jesus bless you, my much loved sister in Christ!

I have read your letter with feelings of devotion,
have laid the state of your mind before God, and examined it anew.
Certainly, the account you give of yourself is a very painful one.
It is enough to make human nature melancholy to read it, much more so to feel it,
and that too for any length of time.
But the eye of faith views things in a different light to that of nature and reason;
it beholds a glory in Jesus quite as great, if not greater,
while hanging on the accursed tree, on the hill of Calvary, scoffed at, naked,
and forsaken by all, as when he stood transformed on Mount Tabor;
and such is also the case with all his true members and followers.

It would carry me to too great a length,
and me thinks it is unnecessary to reply to everything you mention regarding your state.
Speaking generally, I would only say,
that the more you make me acquainted with your state,
the more confirmed I am in the opinion,
that all these very painful sufferings are assuredly the dealings of God with your soul,
to unfold the deep depravity of your heart,
and to mortify the most secret remains of a life of self.
We do not know ourselves in seasons of relish and enjoyment;
the cross must discover to us what we are.
O how firmly and deeply rooted are the subtle unbrokenness of the will,
the confidence in our own works and ability,
complacency in the virtues and graces with which the Lord favors us,
and such like selfish principles in the heart!
It is true that, in the beginning,
the Lord overlooks much of this kind of impurity in his weak children;
but when he sees that it is time,
and that the soul is sufficiently resolute and established in grace and knowledge,
he then begins to press the matter out of the wound,
and touches the poor soul just where it gives her pain.
The soul is then attacked by very severe and great temptations and sins,
in order that the subtle principles of self, which are still concealed,
may be brought to light, and entirely eradicated.

It is no wonder, beloved sister,
that all that is within you stands amazed at this strange and uncommon procedure,
in which, instead of that purity of heart you so ardently longed for,
you are conscious of nothing but corruptions and abominations,
both inwardly and outwardly.
O, you cannot be at all easy at seeing yourself so wretched!
You would gladly be entirely pure and holy,
and yet you must see and feel yourself entirely the reverse.
Only be content with your wretchedness, and shut your eyes against yourself;
God will sanctify you assuredly, but in such a manner,
that you shall not see your holiness, lest you exalt yourself on account of it.

There is still something concealed within you, that seeks to help and excuse itself,
frequently without your knowledge.
When at such times you look around, and behold yourself wretched, faint,
desperate in every point,
and shut up on all sides--either a violent feeling of discontent and irritation is excited,
or else a profound dejection and melancholy, both of which are injurious and painful.
I am also well aware that it sometimes happens, that all your sorrow and suffering,
with all its vexations and apparently dangerous concomitants,
its intolerableness and wearisomeness, places itself, as in a moment,
in the most lively and susceptible manner before your eyes,
by which your affliction and distress increases to the highest pitch,
so that it seems no longer supportable.
This is something which proceeds from the Lord, for which reason,
the soul ought to be passive under it; for when suffering is thus at its greatest height,
and the poor soul is driven to extremity,
even then the most thorough and magnanimous surrender
of ourselves may be exercised--when the soul,
in the deepest resignation, sinks into death,
and gives itself up eternally to the unlimited good pleasure of God,
which is the very way to obtain rest, into which we enter by forsaking ourselves,
and giving ourselves up to God, who is the sole rest of our spirits.

The Lord himself, the faithful guide of your soul,
will find means to lead you out of yourself and into him, through death,
into eternal life, through the strait gate, into unlimited freedom,
out of the most miserable dungeon, into the most delightful liberty of spirit.
Do but let the Lord work; he will accomplish what he has begun.
Let your enemies alone also, and regard not their rage; without divine permission,
they can do nothing to you,
the combined powers of hell cannot compel you to consent to a single sin.
Temptations and sins of every kind may approach and surround you, as much as they will,
but as long as you remain in a state of passive and resigned mortification,
you may walk unconsumed in the midst of the flames.

I believe and am aware that you commit many faults,
particularly such as you are not conscious of until afterward;
but do not trouble yourself too much about them--it is not your intention to sin;
therefore when you really sin or think you do so, recant it,
and commit yourself to God anew.
I believe that almost every error in this state, arises from a departure from resignation.

God occasionally gives you grace to surrender yourself entirely to him;
and although this be only at intervals, and for a short time,
yet the mind perceives the benefit of it; a proof that you can be cured only in this way.
When we cease to care and labor, then God begins, and will be all in our nothingness.
May he himself completely work this happy death in both of us,
and grant that we may lose ourselves in him, in such a manner,
as that we may never find ourselves again in ourselves!

All you have to do, is, as you mention,
continually to regard yourself as a sacrifice to the justice and love of God,
which kills and consumes all the life of self in you without mercy.
Abraham really thought that his beloved son Isaac must suffer,
and was obliged to consent to it; but God would only have Isaac offered,
and the ram burnt.
And thus the Lord knows how to preserve that which is his own in you; everything however,
must be offered up--life and health, body and soul, enjoyment, relish, gifts,
and virtues, and even the darling image of holiness itself.

I say you are a sacrifice to the _justice_ and _love_ of God, and not to his _wrath;_
it shall not come upon you, as you sometimes write.
The wrath of God, properly speaking, is only poured out upon the wicked;
it is his justice, mingled with love, that purifies his children.
The beloved parent is not angry with his poor helpless infants;
for it is thus that we are described in the prophet Ezekiel.
(16:5-6.) Refer to the passage and see if that can be called anger.

Possess yourself, as much as possible in patience.
The bitter cup of affliction will soon be drunk up.
_You please God, when you suffer for his sake._
Is not this a sufficient reason to fortify yourself in patience?
Yes, I thank God, with my whole heart, that he has called you,
and deigned to take you so strictly into his correction, in order that through suffering,
he may perfect you in true holiness.
Yes, I thank him also, with inward satisfaction, for all that grace,
which he manifests towards you in this state,
so that in the midst of temptation and suffering, you still hate sin, and love holiness;
that you inwardly desire not to draw back from the cross;
that you love his good pleasure, praise his goodness; and that, finally,
you place your highest consolation in this,
that God may be loved and glorified in you and others, although, as you say,
every drop of your blood should be consumed by it.
If this desire be really in you, so as you express yourself,
and as I also believe is the case, thank the Lord for it with me, and boldly believe,
that flesh and blood have not imparted it to you.
God is glorified in you, even now, in your humiliation; and will glorify himself,
in future, still more, both in time and eternity.

With this, therefore, I will conclude, and resign you into the Lord`'s faithful hands.
What else might have been added, is already said in my former letter.
In other respects, this state does not admit of enjoying or observing many rules;
and if I sometimes give any particular directions,
you must not anxiously bind yourself to them, nor revolve them much in your mind.
God himself will work and remind you, every moment, of what is well-pleasing in his sight.
He will not forsake you, his disconsolate child, though all the world were to do so.

As for myself, I am obliged and sufficiently inclined to serve you, how and when I can,
according to the ability which the Lord grants;
even as one child gives its hand to another.
But as the light and grace of God, with respect to the inward way,
is less powerful in me than you and others suppose,
I would not readily advise anyone to follow my instructions further,
than he himself may believe them to be the will of God, and of advantage to him.
God will give us grace to be mindful of each other.

Be of good courage, my sister, and love Jesus and his cross, in whom I am,

[.signed-section-closing]
Your affectionate fellow-laborer and brother.

[.alt.centered]
=== Letter 22

[.salutation]
Dearly beloved brother in the grace of Jesus;

I have before me your favor of the 9th of March,
in which you desire further explanation regarding something I said in my last.
You refer to that passage, where I say, "`Looking solely unto God in Christ,
and not regarding but forgetting ourselves, produces every virtue; this has, however,
its gradations.`"
These gradations you desire to be made acquainted with,
as though you did not know them as well as myself.
I will however, simply state what occurs to me on the subject;
although I do not remember how I viewed the matter at the time.

I am now able to say,
that we must look chiefly unto God and forget ourselves in a sevenfold manner,
and experience teaches every time, although with a remarkable difference,
how by so doing every virtue and every good is produced.
We do so:

[.numbered-group]
====

[.numbered]
I+++.+++ In a way of seeking.

[.numbered]
II. In a way of feeling.

[.numbered]
III. Experimentally.

[.numbered]
IV. In simplicity.

[.numbered]
V+++.+++ By contemplation.

[.numbered]
VI. By resignation.

[.numbered]
VII. Essentially.

====

According to everyone`'s particular state and the divine guidance;
for everyone must act according to his state, and the manner in which he is led,
without being concerned whether his state be high or low;
because that particular state to which God destines us, is for us the most perfect.

I+++.+++ In the state of repentance, be it at the commencement or subsequently,
whenever the soul feels her sinfulness, distress, anxiety, and alarm in the conscience,
from a presentiment of divine justice, with reference to which,
she sees nothing before her but darkness, death, and perdition: In this state, I say,
there is no better, nor any other remedy or refuge for the soul, than to look,
not at herself, but unto God in Christ alone, in order that her wound may be healed,
and every virtue be wrought in her.
It is only like daubing with untempered mortar to
look around upon some supposed good work,
or to endeavor to help and tranquillize ourselves by duties, well-meant exercises,
self-made promises, and resolutions of amendment.
By the works of the law shall no man be justified before God.
The law is too holy and the flesh too weak to render due obedience to it.
Conscience cannot be pacified in this manner, but the man sinks ever deeper into it,
and after he has endured his misery long enough, and done his best,
he finds himself at last, at the end of the seventh chapter of Romans, exclaiming,
"`O wretched man that I am! etc.`"
But if the soul gives God the glory, and cordially assents to her demerit, misery,
and nothingness, and then looks away from herself, in order to look unto God in Christ,
who graciously receives, and heals the sinner, she will certainly be saved,
though burdened with mountains of sins,
and though the heart were the residence of seven devils.
The soul, while sincerely confessing her wretchedness,
ought to turn away her eyes from it, and look unto God in Christ,
who is able and willing, through the blood of Christ,
to forgive and blot out all our sins;
and though her sinfulness and misery continually present themselves to her view,
and though it appear to her as if she were unable to look unto God in Christ,
or as if he would not regard the soul, yet she ought only steadfastly to continue,
in Jesus`'s name, to look away from herself unto Christ, who will never forsake her,
nor allow her to be put to shame, but at length embrace her with infinite compassion.
It is thus we forget ourselves, and look unto God in Christ in a way of seeking;
just as a sick and pining infant looks up to its mother,
or those who were bitten by the poisonous serpents
in the wilderness who looked not at their wounds,
but at the brazen serpent, and were healed.
And thus, whosoever believes on the Son of God shall not perish,
but have everlasting life.

II. In the state of enjoyment--be it that the Lord graciously
allows the soul to see and taste the riches of his mercy,
in the forgiveness of all her sins,
or that he imparts to her other perceptible gifts of grace, joy, light, pleasure,
comfort, or the like.
Here the soul ought to be particularly careful not to regard, but to forget herself,
in order that the gifts of God may not be polluted by presumption and self-complacency.
She ought rather to shut her eyes, both against herself and the gifts of God,
after having thanked God for them, that she may not wish to possess any of them herself,
but again divest herself of them, in order that she may solely behold God in Christ,
and take no delight in herself, but in God, the giver and source of every good gift,
and who is alone good and lovely.

This forgetting ourselves and the blessings we have received in ourselves,
this stripping ourselves and closing our eyes against ourselves and all created things,
that we may not be desirous of possessing or beholding anything in them for ourselves,
but of looking unto God alone, appears irrational to the carnal mind,
and reason may think, "`Of what use is it to me,
if I receive and possess this or that particular blessing from God,
if I must again forget it and retain nothing of it for myself?`"
But sense and reason are blinded with respect to the kingdom of God.
Experience teaches, that the more we divest ourselves of every blessing,
and the less we are desirous of selfishly possessing them,
the more nobly we possess them in reality;
and when we also again divest ourselves of that which is noble in our possession of them,
that we may regard nothing but God, our bliss and blessings again increase.
For the more sincere our self-contempt and self-renunciation are, the more virtue, peace,
and substantial blessedness does the soul possess.
But because many, alas! selfishly regard and retain the good they receive from God,
they continue deprived of that which is better,
and even the good they have is lost and spoiled.
And thus a person in this situation, in a way of feeling,
must forget and disregard himself, and look unto God alone in Christ,
who works every good; and though the Beloved, at this agreeable period,
adorns the bride with one ornament after another, and then says "`Behold you are fair,
my love,`" she does not look at herself, but replies,
"`Behold you are fair my Beloved!`" (Song. 1:15-16)

III.
In the way of sanctification, the individual must have a sole regard to God in Christ,
and not look at himself, and this must be done in a practical manner.
Many well-meaning people, who have felt a little of the grace of God in Christ,
have a hearty and earnest desire to live to the glory of God and to follow after holiness;
but it is to be regretted that this is generally undertaken in such an improper manner.

These individuals seek out their enemies, so to speak;
they try and examine their life and conduct; they strenuously resist that which is evil,
are diligent in the exercise of virtue,
and make themselves appear as pious as they possibly can;
but the result is either a self-created external form and hypocritical appearance,
without root or foundation, or they torment themselves by despondency and unbelief,
or else they quite lose all courage, because they find so many imperfections,
and know of no means of making themselves as holy as they perceive they ought to be;
for the soul goes to work in its own strength, and without God.
The easiest and most proper way of attaining to holiness is, to look unto God in Christ,
and to forget ourselves and our miseries as much as possible.
"`Let us run the race set before us,`" says Paul; (Heb. 12) but in what manner?

"`Looking unto Jesus, the author and finisher of our faith.`"
This is that beautiful exercise of occupying ourselves with God and his beatifying presence,
of which it is said, in Ps. 16, "`I have set the Lord constantly before me.`"
This filial view of faith,
this collectedness and occupation of the heart with the
omnipresent God of love and with his divine perfections,
is a real stratagem in the inward conflict; by which the soul,
instead of openly facing the enemy,
acts as a child that flies to its mother at the sight of a dog,
instead of fighting with it, and hides itself with confidence in her lap.
By this looking unto God, and this occupation of the heart with him,
and with his divine perfections, the soul becomes wonderfully enlightened, strengthened,
satisfied, and sanctified, as though while asleep, and that in a real and radical manner,
because the impression of the presence, majesty, all-sufficiency, and perfections of God,
gradually penetrate, wean the individual from everything,
and make everything that is not God, little and trifling in his estimation.

IV. If the man be steadfast and faithful in this exercise, God blesses his endeavors,
prevents him in it, and meets him with his attractive influence,
in the center of his heart, and with the secret impression of his intimate nearness,
love, all-sufficiency, and divine perfections.
Such a one finds himself no longer adequate to the contemplation of God,
and to the discrimination of his perfections, in succession,
by the efforts of his understanding; nor is he able to employ himself in this manner;
yet when he keeps near his heart in simplicity,
he there finds a general and secret impression of the nearness, majesty, love,
and all-sufficiency of God, which, although it appears, as already observed,
to be entirely hidden and almost imperceptible,
is nevertheless accompanied by a latent power,
by which the heart is exceedingly drawn off from,
and disinclined to all created and transitory things,
in order that it may unite itself with God, and keep near unto him.
The soul has therefore nothing else to do in this state, but to follow, in simplicity,
this inward drawing and central inclination, and cleave by it unto God,
seek to continue collected in his presence, and with a meek and simple believing eye,
__look only unto him, and not unto herself;__ and thus,
by means of this simple state of inward collectedness,
the soul will be best preserved from all evil, become the recipient of radical virtues,
and be made capable of a real union with God, and of receiving innumerable blessings.

But if the individual will not act here with simplicity, but regard herself,
and follow her own imagination, she will only confuse herself and impede her progress;
for her former external, sensible, and mental meditations and exercises,
no longer afford the mind any nourishment or pleasure--it
accommodates itself to them with difficulty;
as it regards the senses, she is in a weak and barren state,
and occasionally her thoughts easily wander, and the more she tries to help herself,
by the exertion of his rational and mental powers, the worse she makes the matter.
It is only when forgetting everything else, and abiding near the heart,
or to speak more correctly, near to God,
that the individual is in some measure aware of the attraction and impression above-mentioned,
in which she finds herself at ease,
so that she has even a secret presentiment that she has nothing more to do or desire.
Such persons, nevertheless, find it difficult, at the commencement,
to be satisfied with it,
on account of their inexperience and the simplicity of the exercise;
and the soul not infrequently returns to herself and the view of herself,
instead of remaining calmly with Mary at the feet of Jesus;
because this is the "`one thing needful`" for her,
and brings with it greater blessings than others
attain by being careful about many things.
But I find I am writing too much at length,
and will therefore express myself more briefly.

V+++.+++ The individual looks unto God alone, and not at herself, in a way of contemplation,
when it pleases God really to reveal himself to her inwardly in reality (John 14:21),
and to presence himself with her.
In this state the eye of the soul is opened, and inclined,
by a delightful effect of divine power,
to the enjoyment of this present and all sufficient good,
and to regard and cleave unto him, solely and steadfastly,
and this is called the state of contemplation.
It is here not very necessary to remind such persons not to look at themselves,
because they are already sufficiently instructed therein,
by the unction imparted to them, and because they are easily drawn unto God,
by the impelling and attracting power of his presence.
Paul, amongst others,
tells us how much good the steadfast contemplation of God in this state produces,
"`While beholding the glory of the Lord, we are changed into the same image,
from glory to glory, as by the Spirit of the Lord.`"
(2 Cor. 3:18)

VI. We must look solely unto God in Christ in a way of resignation and mortification;
and not regard,
but forget ourselves in the various and important states of inward suffering, privation,
and purification.
This truth is then supremely needful to the soul; yes,
the more extreme and severe the trials are, the more needful is the recollection of this.
In the more elevated paths of mortification and purification, we can neither find light,
nor consolation, nor grace, nor God; while on the contrary,
everything appears against us.
We behold and experience our poverty, darkness, weakness,
and the indescribable depth of our wretchedness, in the bitterest manner.
All our former gifts and communications seem as though they were lost--and lost,
we think, by our own fault.
All our exercises, efforts, mental elevation, recollection,
etc. or by whatever means we were accustomed to help, preserve,
or unite ourselves with God, are of no further benefit to us.
What is to be done?
Nothing.
What is to be suffered?
Much, but apparently without hope of deliverance.
But what has the wretched creature left, and what advice is to be given him?
He has nothing left but his great wretchedness and total nothingness;
and all the advice that can be given him is this,
that he sincerely and truly acquiesce in his wretchedness and nothingness,
and resign himself to the pure grace of God in Christ, in this character,
without seeking anything further in himself, or expecting anything from himself,
or hoping anything for himself, but to justify God,
and let him do with him as seems good to Him in time and eternity.
This God must work, and the man suffer; it is then that he departs out of himself,
that he forsakes himself, that he dies to himself, and learns what it is,
to look alone unto God in Christ, in a way of resignation and mortification,
and not look at himself, but forget himself in high degree; by which means,
not only much good is produced, but we also become filled with the self-existent good.

VII.
This takes place also essentially, in the state of divine unity and transformation,
of which Jesus speaks in John 17, and of which other saints have testified,
both in the Holy Scriptures and elsewhere,
but of which I can say nothing from experience.
The Lord give us grace to feel and know what is well-pleasing in his sight!

This, my brother, is what I have written you in haste, in answer to your questions,
and during continual interruption.
You will know how to derive benefit from it all,
and to distinguish the mistakes which are mingled with it,
from that which is divine truth.

I have, however,
no great opinion of persons being much acquainted
with the different degrees of the christian life,
for self-love delights in exalting itself,
and forming itself into something to which God has not hitherto conducted the soul.
Nor do I wish this letter to be viewed in such a manner,
as though one degree ought always to follow the other.
It is true, there is something in it, but the case is not the same with every soul,
neither do they always follow so regularly and distinctly;
besides which the different temperament and deportment of the soul,
causes a perceptible difference in the manner of its guidance.
God has also not the same intentions with regard to all.

Let us, in the spirit of children, abide with God for the time being,
and resign ourselves wholly to him, according to the full extent of his grace in us,
and with all our faithfulness; and in every trial expect nothing from ourselves,
but everything from his infinite goodness.
Amen.
May he himself perform it!

[.signed-section-closing]
Remember me as your weak brother.

[.alt.centered]
=== Letter 23

[.salutation]
Beloved brethren, sisters, and friends, in the grace of God,
whose names, I pray, may be found written in the book of life.

In compliance with your repeated requests, I would gladly have visited you in person,
that with the divine blessing,
we might have been enabled to strengthen and edify one another in our vocation and faith,
and rejoice in all the blessings we possess in Jesus, our blessed and supreme head,
God blessed forever.

But as the providence of God does not at present permit this,
I take the liberty of affectionately saluting you through this medium,
and heartily wish you all increase and establishment in the grace of God.
Your love and the remembrance of you,
as far as I became acquainted with you during my last visit, have often refreshed me,
and at the same time compelled me to offer up your souls to the author and finisher
of faith and to commit you to his superintendence and gracious influences,
in order that none may remain behind, but that everyone, according to his measure,
may make progress towards the prize of our high calling
of fellowship with God in the spirit.
In this sense, may the Lord unite us more and more fully, as in one heart and soul,
in the sweet love of Jesus!

O what an unspeakable mercy of God it is,
when we not only feel within us the vocation of grace,
but also cordially give place to it--when we are impressively
convinced of our miserable and fallen state by nature,
when we sincerely feel the burden of our sins, and are thus driven,
by inward distress and grief, to Jesus, when we perceive in a lively manner,
the great necessity of a change, a universal and thorough change; and when, at length,
we take a humble and sincere resolution irrevocably to offer ourselves,
with body and soul, to the Lord Jesus and his service,
and to follow him in the narrow path of self-denial and the cross, determined also,
willingly to bear the hatred and contempt of the
world and the enmity of the devil on account of it!
Happy moment when such a feeling and determination arises in the soul!
Inestimable grace,
which is more to be esteemed than all the deceitful riches and pleasures of the world!
But here keep firm footing, my dearly beloved, who have experienced the happy hour,
in which you have sincerely given your word to Jesus.

When an awakening takes place anywhere, persons are easily carried along with the stream;
the novelty of the thing touches the senses, and the individual also feels affected--nay,
the grace of God gladly avails itself of such opportunities
to get the soul into the gospel net;
but now let everyone pay attention that it be not
a fire of stubble which burns within him,
but a flame of the Lord, which is not easily extinguished again.
The first resolution is soon taken;
but after the primary effervescence has a little subsided,
the individual is put to the test, in which foresight, courage,
and divine grace are necessary.

When he comes again amongst worldly-minded people,
who have already heard that he intends to become religious,
or more serious than he was before, what astonishment is expressed!
What apparently faithful cautions--what seemingly reasonable
arguments and sophistry assault the weak mind!
If he then gives only a little heed to the serpent,
and revolves the matter over in himself, with his carnal reason,
he is immediately weakened and overcome.
It afterwards seems to him very probable that such is the case;
that there is no need of making such a noise about it,
nor of injuring ourselves with others--that running here and there is of little avail;
that it often occasions more distraction than edification; that we can quietly serve God,
without identifying ourselves so much with the hated people that
there is also much strange fire and dissimulation amongst them,
and that they are not all so holy as they outwardly seem to be--that
it is not altogether possible to live in such a manner, etc.
O beware, beware, you that love your souls, of thus conferring with flesh and blood,
and of refusing him, who speaks quite other things to you,
by his word and by the teachings of his grace in your hearts,
but continue in that which you have heard and known from the beginning!

How many receive the word of the gospel with joy, who afterwards let their courage fail,
when they see their enemies, and feel,
that not only hearing and speaking belong to godliness, but also doing and denying;
who regard as beautiful the gospel pearl, Jesus and his blessings; but stop short,
or turn about, when they learn that they must sell all in order to obtain it.
O my dear friends stand firm, and do not let your courage sink!
The Lord is with us; a soul, a Jesus,
an eternity is certainly worthy of some little labor.

How many let their courage fail when they see that
Jesus not only distributes bread and wine,
but crosses also.
As long as the first sensible emotion lasts,
the individual is zealous and would even suffer death with Jesus.
But if the Lord in his wise dispensations,
withdraws the milk of sensible consolation and sweetness,
and lets the soul continue for a while in barrenness and darkness,
that he may try the fidelity of its love,
and establish it the more firmly in self-knowledge and humility--the
man is then ready to despond and complain,
or even to seek comfort elsewhere.
O my brethren, do not sink, do not faint!
Be strong, and wait for the Lord!
For no eye has seen, nor ear head,
nor has it ever occurred to any unenlightened human heart,
what God has prepared for those that wait for him.

If you will not be deceived nor led astray from the path of life,
it is necessary to cleave, with me, in faith unto him who has called us.
He has inwardly been beforehand with us in our hearts,
by making known to us his dear and gracious vocation, by reproof, by impressions,
by excitements, by light, and love, and life, according to everyone`'s state and measure;
to this we must cleave in all simplicity,
if we are desirous of continuing firm and of growing in grace.
Multifarious reflections, speculations and the activity of the understanding,
as well as distraction in the senses,
and outward multiplicity lead us violently away from our inward center;
we must therefore avoid them as much as possible.
There is nothing, either in heaven or earth, either in us or out of us,
that can so thoroughly heal, sanctify, and satisfy us, as the love and grace of God,
manifested in Christ Jesus.
It is this, which thus inwardly meets us in our hearts, with its salutary influences.
Now if we adhere to this, in a devout and introverted frame, often presenting,
in childlike sincerity, our whole and inmost heart open and naked,
to this discerning and healing light of life, and seek after every aberration,
to return with our hunger and devotion, again into our heart; as the Scripture speaks,
(Isaiah 4) we shall not only continue preserved from all going astray
but we shall also grow up in all things unto him who is our head,
Christ Jesus, and experience, more and more,
the unsearchable riches of his strength and grace in his saints.

For we must not fall into the foolish idea of being
able to attain to complete regeneration at once,
and reenter paradise, as it were, by a single leap; by no means!
The waving sword of the cherub--I mean the word of God,
which is quick and powerful (Heb. 4:12) has much to hew and cut off,
which can never enter into the kingdom of God; this is not accomplished in one day,
nor even generally speaking, in one year.
Therefore a continual growth and progress certainly belong to christians,
and the degrees of grace are very different in those that are called.
A christian that retains his previous habits and infirmities,
and remains in the same state, from one year to another,
has great cause to reflect maturely upon his state,
whether he be not a tree without life, or a branch which abides not in the vine.
For this is the very reason why so little growth in sanctification
is perceptible in awakened souls in the present day.
The individual does not abide in Christ, in the manner above-mentioned,
nor accustom himself sufficiently to the true prayer of
the heart as to believe that God is inwardly near him,
in his heart--to cleave unto him in a childlike manner, to possess,
in a meek and quiet spirit, his affectionate converse and communion,
to wait for his gracious operation and attraction, attend to it and give place to it,
to adhere to him most cordially, and as a child from its mother`'s breast,
receive grace for grace.
This ought to be our daily work, yes, our chief employment; but because it is neglected,
the individual does not properly attain to the power of the new covenant,
in which God writes his laws in the heart, nor to an experimental acquaintance with God,
his riches, and his truth.

O my dearest friends,
let us apply ourselves more diligently to this delightful exercise of prayer,
for we cannot exist a single moment of ourselves!
What are all our virtues and all our piety,
unless fellowship with Jesus lie at the bottom of it?
It is all only form without power, a shadow without substance.
All our faults and falls proceed from our not abiding with Christ within; nay,
we even commit many, without perceiving them because we are not in the light.
We often think we are walking purely and sincerely,
while if we came nearer to our hearts, and to the Lord within them,
we should soon perceive, that we did not stand complete before the Lord.
Innumerable selfish motives, and the whole inward mystery of wickedness,
continue concealed from the eyes of many until death, to their great dismay at that hour,
only because they do not seek to lead a retired life in the presence of God.
Nay, the most precious and most essential operations and
communications of God in our hearts are not experienced,
nor the most divine truths vitally known, because we do not sufficiently continue there,
where alone they can be known and enjoyed.
O how much is this to be lamented,
seeing that such great and precious promises are given us in Christ,
that even during this life, we may become partakers of the divine nature,
by the inward acquaintance with him, who has called us to this glory! (2 Peter 1)

Therefore, my fellow-called,
if we are desirous of being thoroughly redeemed and sanctified, of living peacefully,
and dying happily,
we must become _inhabitants of our own hearts and fellow-inmates with God,_
Jesus has opened to us this new and living way in his blood, so that eternal love,
with its attractions and influences, can now approach very near to us,
and we can draw near unto God in our hearts, with childlike confidence,
without reference to our misery and unworthiness.
Let us then draw near (Heb. 10:22), and freely use this invaluable privilege.
Let us accustom ourselves, the whole day long, and even while in business,
to the Lord`'s presence, and seek in simple faith, to make ourselves known,
and become intimate with him in our hearts;
but we must by no means regard as superfluous,
a frequent seclusion in sacred abstraction,
in order to this sweet and prayerful exercise of
recollection and retiring to God in our hearts.
We shall then more and more essentially experience how the
Lord will meet us with the tender attractions of his love,
seeing that he unceasingly waits and knocks at the door of our hearts;
and we shall experience,
that it is his delight to dwell with the children of men:--"`Come and see!`"

But think not that by this we would dissuade you
from the use of the outward means of grace;
by no means!
Rather would we take occasion to remind you,
not to despise or lightly esteem any one good action or guidance away from self-love,
pride, or excessive prudence.
We must love and esteem every good thing which is able to
lead and assist us to the attainment of the supreme good.
Only we must use everything in due order and measure,
and not attach too much importance to it,
much less continue cleaving to anything that is not God himself;
otherwise that which is in itself a good and innocent
means would certainly become an obstacle,
and cause detention in the attainment of that which is alone needful.
God has regulated all outward things for the sake of the inward--nay, he himself,
so to speak, became external in Christ, in order that he might call his creatures,
who have wandered outwards, to that which is within, and there be truly near unto us.
We ought therefore also to keep in mind this kind
and salutary object which God has in view;
and in the use of all outward means, diligently attend to our hearts,
waiting for the first impressions of divine grace,
and observing how it opens and affects the heart,
in order that we may submit ourselves to it, in filial obedience; and thus,
both by the Holy Scriptures, as well as by other good instructions,
we may come to Christ himself, that so we may have life in his name.

Prove, by grace, in all things that which is the best;
and do not spend the short time and the noble powers
of grace in unnecessary things of a secondary nature.
Be not so tenacious of your money, as of your time and the grace entrusted to you.
Let us go directly to the mark; it will soon be evening with us.
One thing is needful, which is, that we die to ourselves and every creature,
and live unto God, in spirit and in truth.
It is this, which both Scripture and grace in the heart demand of us; and it is this,
in which alone we can find health and peace, both living and dying.
With this we have enough to exercise, to suffer, and to experience;
he that has attained to it, may do what he pleases,
if he finds that he has any time to spare, or any desire for pleasure.

Avoid all unnecessary interaction with the men of this world,
lest time be stolen from you, and lest you yourselves be polluted and carried away.
The most dangerous kind are those, who make great pretensions to reason;
particularly those that are Christians only in name and appearance, and who do not act,
directly and sincerely, according to their previous calling; for such have, as it were,
truly studied every gilded pretense, by which they may render void the strict, simple,
and inward life in Christ, and seduce unstable minds.

Allow not the hope of your calling to be darkened in any measure,
by anything of an extraordinary nature,
nor by the powers and operations of strange spirits, which,
under an imposing and peculiar appearance,
may present themselves to the senses and self-love.
Whenever such-like temptations take possession of any individuals look at the result,
and how the tree is known by its fruits.
A holy foresight is necessary with regard to all that strikes the senses,
all that is peculiar, and all that has an imposing appearance.

Permit not yourselves to be detached from simplicity in Christ,
by any pretense of superior knowledge and wisdom.
Nature seeks room, and resists close confinement;
it is easier for her to amuse herself with ideas, than to suffer and die.
The poor and simple life of Jesus is offensive to scornful reason, which sophisticates,
until it has found a convenient middle way,
which just terminates in a point with the broad way.
With respect to us, let us be affectionate children; dying, praying,
and loving shall be our wisdom.
Let reason scorn us as long as she pleases; we shall see who fares the most peaceably,
and to whom the heavenly Father will reveal his mysteries.

O yes, my dear friends!
We ought to become such like children of grace; and as such,
we ought to love one another sincerely and cordially.
If we only detach ourselves more and more from all secondary things and notions,
and exercise ourselves in that which is alone needful;
how we may be truly faithful to the vocation of grace,
in dying to the world and all false life,
and remaining near to God in simplicity of heart, our spirits will then flow together,
as of themselves, in delightful unanimity and unity.
In this way, eternal love would delight to dwell among us, and to bless us,
as the dew that falls from Hermon upon the mountains of Zion;
and we should ever more deeply experience the unknown blessings,
which are to be _enjoyed in the true fellowship of the saints._
Seeing that we have cast out the world, and the world has cast us out,
let us therefore give each other the hand; and as real strangers and pilgrims,
brotherly and courageously go forward, in one mind and spirit,
to the happy land of inward and eternal fellowship with God in Christ Jesus.
Faithful is he that has called us, who also will do it!

[.signed-section-closing]
In him I remain, through grace, etc.

[.signed-section-context-close]
Mulheim, 30th September, 1734.

[.alt.centered]
=== Letter 24

[.blurb]
==== The Author`'s Ideas Respecting Marriage.

Although with regard to marriage I am inexperienced,
and have no particular insight or revelation respecting it, yet at your request,
I will attempt briefly to state to you my sentiments and opinion on the subject,
according to the Holy Scriptures.

Speaking generally, the expression of Paul (1 Cor. 7:38) decides the matter.
"`He that marries, sins not, but does well; but he that remains single does better.`"
This is the appearance the subject presents,
when in other respects the balances are equal.

But there may be various cases and circumstances,
such as those mentioned in 1 Cor. 7:2-9, and 1 Tim. 5:14,
in which the case is reversed, and when it must be said, "`It is better to marry.`"
For that which is better, does not solely and principally depend on the external state.
A humble soldier of the cross, in the married state, is better in the sight of God,
than the proud, who in the single state,
do not preserve their bodies in sanctity and honor.
(1 Thess. 4:4)

After being expelled from paradise,
we must be content with an almost animal body of humiliation (Phil. 3:21),
till our celestial robes are prepared (2 Cor. 5:2-5), and consent to animal labor,
eating, drinking, sleeping, etc., the use of which is seldom altogether blameless;
and the present mode of procreation participates still more of wretchedness and corruption;
otherwise, the law of circumcision would not have been instituted,
nor should we have been conceived and born in sin; however, it cannot now be otherwise.

Health is certainly better than sickness, and perfection than imperfection;
but as we are destitute of both, we must not be presumptuous,
but adore the kind and long-suffering condescension of God,
who bears with and overlooks our infirmity, nay,
even uses it as a remedy to lead us gradually, by its means, to greater perfection.
Medicine is a gift of God, and it is good to use it;
but he that uses it unseasonably and profusely, is injured by it;
and it is still better if we do not require it.

In consequence of the fall, we are fallen from an angelic paradisaical state,
into an impure animal condition of body and mind.
Our great Restorer purposes leading us back again, with advantage,
into the glory we have lost--not in the way we should suppose, nor by a single leap,
but through needful trials, humiliations, and mortifications; until, by degrees,
from brutes we become men, from men, saints, and from saints, we again become angels.

No one has reason to boast of the inheritance he has received from Adam: however,
one person has this particular disposition and viciousness of body or mind,
and another that, which are not all to be removed in the same way,
and by one particular remedy,
although the general cure of the soul is needful for and the same to each and to all.

Nor have all those, who are in a state of grace, the same measure of light, faith,
and power, or the same particular election and destiny.
That which causes one person much disturbance, confusion, and detriment,
does no injury to, and is easily and peaceably endured by another.
In such cases, who will give any other general rule than this?
"`Let everyone examine his vocation and faith in the light of God,
and continue in that whereto the Lord has called him,`"
(1 Cor. 7:17,20,24) but let him not judge another.
And with this condition, that everyone examine his vocation in the light of God,
the Holy Spirit certainly leaves the soul, that is in a state of grace,
at liberty to choose that which each considers to be the most serviceable for himself,
and the most pleasing to God, either to remain single or to marry.

When the Apostle says (1 Cor. 7:7) "`everyone has his peculiar gift from God;
one after this manner,
and another after that:`" he probably does not refer to natural gifts, as though one,
whose disposition did not, as it were, impart chastity to him, must of necessity marry;
but he meant to say, "`There are those, who trust, with the help of God,
to be able to abide in the single state, with the Lord.`"
"`He that can receive it, let him receive it.`"
(Matt. 19:12) But as I well know, that everyone cannot receive this word,
but that many a one, who perhaps in other things manifests his faith and fidelity,
supposes that it is not proper for him; let such a one therefore marry in God`'s name;
"`he sins not.`"

Of the three kinds of eunuchs, mentioned by our Lord in Matt. 19:12,
I know not whether the two first can be reckoned among the chaste; but those,
"`who have made themselves eunuchs for the kingdom
of heaven`'s sake,`" may truly be called chaste.
They were not born so, nor was it a consequence of their natural disposition; grace,
and a noble impulse of faith animated them to this chaste conflict.
(Wisdom of Sol.
4:2)

The marriage state itself is very different according
to the state of the persons who enter into it.
"`To the pure, all things are pure; but to the unbelieving, nothing is pure;
for even their minds and consciences are defiled.`"
(Titus 1:15) Marriages are, indeed, in general, under the divine permission;
but it is not every marriage that is made in heaven.
A truly holy marriage state, as all are called now-a-days, is perhaps very rare;
yet there is a difference amongst them.
In the mutual love and fidelity of two hearts, which are really united in the Lord,
there is indeed something good and beautiful, in this pilgrimage state; and in itself,
it is not displeasing to God, but a sacred mystery.

Married christians must, however, be aware,
that their state is under the divine forbearance;
(1 Cor. 7:28) that accompanying afflictions are
necessary for their preservation and purification;
and lastly, that it is a state, which does not accompany them into the next world,
but terminates with the present.
(Matt. 22:30)

[.alt.centered]
=== Letter 25

[.blurb]
==== Christian advice to a person who had many doubts and scruples in her mind respecting marriage.

[.salutation]
Dearly beloved friend and sister in Christ,

You have requested me to write to you something respecting
the subject you mentioned to me.
I must confess that I do not willingly speak of matters of this kind;
but since you wish it,
and because I would not have you continue longer in a state of disturbance,
and in reflections which can only cause injury and hindrance to the soul,
I will briefly and in simplicity disclose my sentiments to you respecting it,
as far as God permits.

It is generally speaking, undoubtedly true, what Paul says,
(1 Cor. 7:1) "`That it is not good for a christian man to touch a woman,`"
and therefore it is good for a person in the single state to continue so. (Verses 8, 26.
) Yes, and that he who continues thus, does better, and is more blessed;
as is expressly said, in verses 38 and 40. But all do not receive this word; and besides,
"`he that marries, sins not,`" as the same apostle says again, verse 28.
It may also be the case, through the providence of God,
or by reason of inward and outward causes and circumstances,
that it may be said of the individual with truth, "`It is not good for man to be alone.
(Genesis 2:18)

In short, the single state, in itself, does not make us acceptable in the sight of God;
but he that remains single, to the end that he may cleave to God more unobstructedly,
and be holy, both in body and spirit, pleases God (See Isa. 56:4-5. Wis.
3:13-14; 4:12). He that marries, does not sin on that account.
But he that marries and turns away his inmost love, delight, consolation,
and joy from God, and fixes it, whether in a greater or less degree, on the creature,
sins, and shall suffer loss.

It is therefore necessary, first of all, that in this matter,
you thoroughly resign your will to God, and leave to him alone the choice,
and afterwards impartially and frequently pray, and entreat the prayers of others,
that you may be led and guided in it, according to his good pleasure,
so as to please him in all things; and then further, that you consider and examine,
with a tranquil mind, and in the presence of God,
what is the best and most useful for you, both as to body and soul.
And after having done this once or twice, decide in yourself alone, in the name of God,
and with the sole intent of pleasing him, how you will act in this matter,
seeing that your mind has been long enough disturbed by it.
If it then appear to you, that it is not pleasing to God,
nor serviceable and profitable to yourself, give the individual an entire refusal,
and think no more of it.
If, on the contrary, it seem to you to be acceptable to God,
and useful and needful to body and soul, be silent, and refer it, the sooner the better,
to your parents, and hear what they say to it,
for if they will by no means consent to it, you are not at liberty,
either by divine or human laws.
O how well it would be, if you could expect all this with a tranquil and retired heart,
and in resignation,
after the example of Isaac! (Gen. 24:62-63) May
God give you grace to enable you to do so!

With respect to us, to whom you have made it known,
we are unable absolutely to tell you the will of God in the matter; but in our minds,
we find nothing particular against it.
But it is not at all proper,
that you should inwardly disturb and distress yourself
so much as I have some presentiment you do.
Only resign your will entirely to the Lord, and he will do all things well.

But that which is the most important of all, on which the most depends,
and which also requires the most exertion and grace, is still to be mentioned;
and that is, that should it take place, you must be careful above all things,
that the first and greatest command of God remain uninfringed
upon--"`You shall love the Lord your God with all your heart,
and with all your soul, and with all your strength, and with all your mind.`"
The center of your heart must be a temple and habitation of God.
Beware of becoming an idolater, or of admitting images into the innermost sanctuary,
which is the case,
when we inordinately and too ardently cleave with our affections to the creature,
"`Possessing as though we possessed not,`" is the short,
but difficult rule of the apostle Paul.
(1 Cor. 7:39)

Now, therefore, whatever may be the results,
keep this saying firmly and unshakenly with the help
of God--that your heart and inmost love belong wholly,
undividedly, and eternally to God alone, and remain devoted to him.
Regard him, as I do, as your only treasure, comfort, support, and salvation,
and you shall experience peace and blessedness, wherever,
and in whatever state you may be, both now and forever.
Amen!

[.alt.centered]
=== Letter 26

[.blurb]
==== To the awakened inhabitants of the town of Meurs.

Your wish to make me acquainted with your names,
and the desire of your hearts to belong entirely to the Lord,
has occasioned me heavenly joy and delight,
and has moved me to lay both your names and your
intention at the feet of our dearest High Priest,
that he may bless and confirm the same.
O that all your names were indelibly engraved in the book of life,
and that at the great and decisive day,
they may be pronounced amongst those blessed names,
which Jesus shall then confess before his Father, and before his holy angels!

This inestimable favor and honor is not only earnestly desired for you by me,
but is kindly intended for and graciously offered by Jesus himself,
to the most wretched amongst you.
Could we, who are deserving of the curse, behold, even only through a fissure,
the opened heart of Jesus, what should we not see! what should we not feel!

As long as we lived in a state of carnal security, without God and without Jesus,
we stood on the brink of perdition`'s yawning gulf, and were unconscious of it.
Jesus loved us, sought us, and we knew it not.
It is he that has taken us by the hand, that has drawn us away from that dreadful abyss,
that has directed our minds to himself, and instead of the well-deserved pit of hell,
has opened unto us the unfathomable abyss of his loving heart,
in order that we may flee to this safe and blessed city of refuge from all sin and danger,
and become eternally happy in him.
O come my dear brethren!
Taste and see how gracious the Lord is,
and how unspeakably blessed we may be in communion with him,
even during the present state of existence!
Seek no where else alleviation for your burdened hearts.
All besides is deception.
You will not find it out of Christ,
but only be adding to your burden by seeking it elsewhere.

He that abhors all his sins, has a right to believe,
that he has the forgiveness of all his sins,
and cleansing from them in the blood of Christ; but whoever wishes to receive Christ,
and yet secretly retain both the world and sin, his faith is vain.
He that gives all for all, shall certainly obtain the pearl of great price;
but how can a person receive anything, whose hands are already full?
Do not console yourselves on unsubstantial grounds,
till Jesus consoles you in his due time, lest you be injured by it.

Be willing to occupy the lowest place, till the Lord himself says, "`Friend,
come up here!`" (Luke 14) Only wait at Jesus`' feet,
you troubled hearts--no one waits in vain; for while we wait, the precious corn grows up.
We are not so happy in the world, when all things go well with us,
as we are with Jesus in troublous times.
Every tear and every sigh will bring, in due time, abundant fruit.
Learn to keep Lent with Jesus.
Be not disquieted, dejected, or fainthearted, when sufferings,
trials and temptations arise.
We ought rather to fortify our hearts with confidence, when these things befall us,
even as they happened to our great forerunner.
For us, he was led by the spirit into the desert,
that we might not think we are alone in it.
O let us put on the suffering mind of Christ!
Let us not lose courage, when the tempting serpent approaches us in angel`'s guise,
and says, "`This or that will I give you, if you will fall down and worship me.`"
He that overcomes, he that endures to the end, shall inherit all things.

Place no confidence whatever in your own hearts, your courage, your strength, your light,
your virtues, or your faithfulness; but like myself, be as little children,
who must perish, without a mother`'s care.
All that is our own is worthless, and everything else is free grace,
for which we must every moment wait and receive.
But we can never trust too much to our gracious Redeemer; to him,
the most miserable may approach on the footing of free grace,
cordially seek his favor and friendship, pray to him without ceasing,
filially depend upon him, and then boldly venture all upon him.
O he is faithful, and will perform that in us and through us,
which neither we nor any other mortal would be able of himself to accomplish!

Now then, my dear brethren,
if you have really given your hearts and your sincere
consent to this dearest friend of sinners,
as you assure me you have, bow with humble thankfulness before him,
who has commended his love to you, and who alone can establish you.
If the angels in heaven rejoice over one sinner that repents,
my poor heart shall also rejoice over your happy lot,
and cordially extend to you the hand of fraternal affection.
Examine yourselves narrowly, lest any anathema be cherished in your hearts,
and that they may cleave with guileless sincerity to Jesus,
and become daily more complete in him.
If we continue in him, we have boldness, we have fellowship one with another,
we shall rejoice over each other,
and shortly meet each other before the throne of the Lamb, with endless joy,
to glorify him who has ransomed us from the earth by his blood.
Amen.
So let it be!

With this wish, I salute you collectively and individually before his face,
and remain through grace,

[.signed-section-closing]
Your faithful, weak, and obliged brother.

[.alt.centered]
=== Letter 27

[.blurb]
==== A warning admonition against the snares and temptations of the enemy of souls.

1+++.+++ Let us love, and esteem, and use the Holy Scriptures or the Bible,
according to the state and circumstances of our souls.
It is undeniably the best and most divine book in the world,
and a revelation or expression of the will of God to us;
and it manifests an extremely reprehensible ingratitude
and arrogance to neglect and despise it.
We must not, however,
forget that the power and illumination of the Spirit of
God are indispensably necessary to understand it aright,
and to walk according to it.

2+++.+++ Let us constantly set before us the pure and holy precepts
and self-denying life of Jesus Christ for our imitation.
"`He that says he abides in him, must also walk as he walked.`"
We ought not to look much about us, nor pay attention to others,
except so far as they are in Christ and follow his steps.

3+++.+++ Let us never forget the doctrine of Jesus Christ,
especially respecting the denial of self and of all created things,
as the primary and most necessary characteristic of his true disciples.
He has said, "`The way is narrow, and the gate is straight.`"
Let us therefore regard and reject everything internally or externally,
that would represent it to our corrupt and carnal natures as broad and easy way.

4+++.+++ Let us watch and pray: watch over our deceitful hearts, thoughts, and affections,
that we may not allow them to wander thoughtlessly and at liberty to the creature,
but continue near to God, yes, cleave unto him with our affections, desires,
and inclinations.
Let us also watch over our senses--our eyes, ears, mouth, and tongue.
They are the port-holes into which sin, confusion, and a thousand temptations will enter,
if we open them too frequently, needlessly, and imprudently.
Finally, let us also watch over our corrupt natures, that we may never give way to them,
nor follow their will.

5+++.+++ Let us also, at the same time, pray, and that more with the heart than the mouth,
especially for the Spirit of Jesus, that he may rule and work in us.
It is he who alone can lead us into all truth, and will do so; without him,
it would be impossible for us to persevere or to perform anything good.

6+++.+++ Above all things, let us love one another,
and exercise filial interaction with God in our hearts,
and a reverential walk in his presence; because this simple exercise,
if we are faithful and steadfast in it, introduces us, through the divine cooperation,
into that true fellowship with God in spirit on which
all religion and our eternal salvation depends.

7+++.+++ Let us seek, in serenity of mind,
to be very faithful and attentive to the inward teachings
and admonitions of the Spirit of grace.
Although we may be delivered from the law,
and no longer so conscious of its threatenings, reproofs,
and the terror it excites in the conscience,
yet we can never be disunited from the law of the vivifying Spirit of Jesus,
whose gentle and internal attractive influences and
directions we ought the better to attend to and follow,
and with so much the more ease and fidelity.

8+++.+++ Let us avoid all unnecessary converse and hurtful
association with the world and frivolous people,
and likewise with those, who under the name of piety, live in false liberty,
according to the impulse of the flesh, sense, and reason; because,
by intimate interaction with them, the minds of those that are unsettled,
may easily and often unconsciously imbibe something of their disposition,
and suffer from it; while those who are truly the children of God,
and their society and conversation, ought to be so much the more dear and precious to us.

9+++.+++ Let us especially beware, in all our actions, words, and gestures,
both in our outward and inward walk, of all subtle hypocrisy, dissimulation,
and a self-assumed deportment, which is so displeasing to God; but seek, on the contrary,
to do all things in simplicity, sincerity, and cordiality, without reference to man,
but solely in order to please God.

10+++.+++ Let us ever keep watch over our corrupt reason,
in which the old serpent so gladly lurks,
and endeavors under the most believable pretexts,
to allure us from simplicity of heart into all kinds
of useless speculations and injurious disputes;
so that the better part is often forgotten and neglected in consequence of it,
and the man falls imperceptibly into all kinds of errors and mistakes,
as painful experience daily proves.

Finally.
You know, that the Son of God is manifested to take away our sins,
and that there is no unrighteousness in him.
He that abides in him, sins not.
He that sins, has neither seen nor known him.
Little children, let no man deceive you.
He that does righteousness is righteous, even as he is righteous.`"
(1 John 3:5-7)

[.alt.centered]
=== Letter 28

[.blurb]
==== A Letter of encouragement addressed to a few awakened individuals, in the prospect of danger from persecution.

[.centered]
__"`Fear not, little flock, for it is your Father`'s good pleasure to give you the kingdom.`"__

[.salutation]
Beloved brethren in the grace of God,

Is it not stated in the covenant which we have established with the Lord Jesus,
my dearly beloved! that he shall give us the kingdom in the same manner,
as his Father gave it to him?
that is, that through much inward and outward tribulation,
we must enter with him into the glorious, incorruptible, and eternal kingdom of God;
but everything according to the all-wise arrangement of our heavenly Father,
without whose will, not even a hair shall fall from our heads.
Ought we then to wonder, and not rather to rejoice,
when that befalls us which our Lord has previously announced to us?
Yes, verily, we have now much more reason to lift up our heads, with filial confidence,
that our affairs go on prosperously,
and that the Lord is in the midst of us with his blessing,
because the adversary is so much enraged at us.
If, on first devoting ourselves to Jesus,
we proclaimed war against the kingdom of darkness, it cannot be otherwise;
we must expect from it in return, every species of hostility.
Only let the eye of faith be steadily fixed upon him that has loved us,
and we shall be able to come off more than conquerors, for his sake, in all things,
and boldly to say with that hero,
who had all those enemies before him with which we have at present daily to struggle,
"`If God be for us, who can be against us?`"

Through divine goodness, much good seed has been for some time sown in and amongst us.
A sifting, purification, and establishment must now take place.
The thirteenth chapter of Matthew must now be experimentally expounded,
in order that everyone may perceive how and where he stands.
For we must by no means suppose that we are to have nothing but
intellectual consolation and sweetness in the company of Jesus.
For although we feel it unspeakably blissful to be with him,
yet all that is good must be tried, to prevent it from being lost or spoiled.
The cross is therefore mere grace and goodness.
No, my brethren, we have not entered the vessel with Jesus,
for the purposes of diversion and amusement.
A little storm already arises, and a greater one may follow.
The vessel feels the gale.
Let us possess our hearts, therefore, in calm and unshaken confidence in him,
who is in the vessel with us, who can command both the wind and the sea,
in order that he need not shame us by saying, "`O you of little faith,
wherefore did you doubt?`"

And what is there, that should move us?
If sufferings overtake us, we shall not suffer, God be praised, as evil-doers.
We have always shown due respect, obedience, and duty,
towards the constituted authorities, even as we have been taught.
We have not aimed at stirring up disturbances or divisions in church government;
neither have we formed new sects, or intend to do so.

Our consciences are at ease both upon these, as well as upon other suspicious points,
which might be falsely laid to our charge.
Our assembling together has been, according to the apostle`'s admonition,
to provoke unto love and to good works--to learn how we, who have put on Christ,
might also walk in him, and be more and more established in him.
These meetings of ours have not been privately held,
but so that anyone might have been present;
gladly wishing others to enjoy those blessings,
which we have found and hope to find in Jesus.
In short, our only aim has been, how each one ought to walk in his state and vocation,
as a true christian and christian citizen.
He that suspects us of anything else, is either misinformed or maliciously inclined.
Who is there that will harm us, if we be followers of that which is good?`"
And if we suffer notwithstanding, we suffer as Christians, and need not be ashamed of it,
but glorify God under these circumstances, by highly esteeming his reproach,
and by a filial confidence in his faithfulness which endures forever.
Be of good courage, therefore;
the cause is the Lord`'s--he will bring it to pass--his is the kingdom!

Nevertheless, the weapons of our warfare are not carnal, but spiritual.
All the victory lies in a peaceful, passive, believing, and praying state of mind.
The harsh and impetuous force of nature must be nailed to the cross of Christ,
and be broken and mollified by a believing descent
into his meek and conciliating mind of love;
so that nothing should be cherished but compassionate charity, benevolence,
and beneficence, even towards our adversaries.
In this way, Christ triumphed over all the powers of hell.
If we walk, at the same time, worthy of the gospel of Jesus Christ,
even those shall be added unto us, who now oppose us,
when they behold the beauty of truth, and what blessedness we enjoy with Jesus.

Much consideration, consultation, and acting according to human prudence,
is of little avail in this matter.
As long as innocence remains in its native nakedness, no one can lay hold of it.
All our strength, peace, and salvation must be sought in thus inwardly abiding,
with a childlike spirit, in Jesus.
Everything is then given us at the hour and moment when it is needed.
Let us therefore not be drawn out of our fortress,
nor distract ourselves with unnecessary apprehensions, human forethought,
and endless conversation on present circumstances, but continue so much the more within,
with Christ, by faith and prayer, in order to wait for the enemy at our posts.

Let us likewise not weaken ourselves by an unbelieving view of and abiding with ourselves.
We must venture ourselves on God; he will not desert us.
He pays us the costs of all we have to do and suffer for him.
We ought therefore not to take our weakness or inability into account.
If we only abide with filial confidence in him,
we can do all things through him that strengthens us.
And although the Lord often lets us feel our weakness in the season of trial,
yet this ought not to make us afraid; it is for our good,
in order that we may be no self-made heroes,
but creep the more helplessly into his strength,
and that he may be all things and alone in us.

We have only to do with the Lord.
The world acts its part.
Let it do so.
The Lord will carry on and complete his work in our hearts,
by means and in spite of everything.
Be this our only care.
To this every foe must secretly contribute, although they purpose the contrary.
Let us then remain resigned to him, unconcerned for the future,
looking solely unto him with an introverted eye, and boldly pursue our course, forsaking,
more and more entirely, all created things, and all we are,
that Jesus alone may possess and rule in us.
O my dear brethren, let us forsake ourselves!
In us there is nothing but perdition, misery, and weakness.
In Jesus there is real life and salvation.
Let everyone seek and experience it for himself.
We must be found essentially in him.
The door is opened in his blood, and near, in spirit, even to the greatest sinners.
Ah if they did but know it, how would they hasten to it!

Now my brethren, receive these lines, with which I have felt induced to greet you,
in the simplicity of love.
Be strong in the Lord.
The Lord of Hosts is with us, the God of Jacob is our refuge!
Selah.

[.signed-section-closing]
In his grace I remain,

[.signed-section-signature]
Your humble brother and servant.
