== On the Nature and Usefulness of True Godliness.

[.blurb]
=== Godliness is profitable for all things, having the promise of the life that now is, and of that which is to come. 1 Tim. 4:8.

It is a very lamentable thing, that in these our last, dark, and corrupted times,
godliness, piety, or the true service of God,
and religion (for all these are one and the same thing,)
is become so rare and so little known upon earth.
Nay, even among christians, or those whose profession or peculiar character it is,
according to the Word of God,
to let their godliness shine as lights in the eyes of other nations upon earth;
among these, I say, true piety or godliness is so little known,
that they universally manifest disgust at the very name of piety.
Or if they talk of godliness, they do not even know of what they are speaking;
and where others form an idea of it, it is soon perceived,
on close examination in the light of God,
that their conceptions of it are far from being in
accordance with the nature of the thing itself,
and that notwithstanding all the external appearance and form of godliness,
its power is universally unknown, and is even rejected as mere imagination and error.
I have therefore felt myself induced to give you a definition of it, on this occasion,
with all possible brevity, according to the measure of light and grace,
which God shall bestow.
If there were still a single church of primitive christians any where to be found,
such as existed in the first two or three centuries, the task would be unnecessary,
and I should esteem myself happy to learn of them and to read in them,
as living epistles written by the Spirit of God, (2 Cor. 3:2-3) something of that,
concerning which I esteem myself too mean and unworthy to write with ink.

=== I. What True Godliness Cannot Be

In order to form to ourselves an idea of the nature, quality,
and essence of true godliness, or describe a real godly man,
it is only reasonable that we do not direct our thoughts _first_ to such things which
the hypocrite and the ungodly can have in common with those that are really godly;
nor, _secondly,_ to anything which the godly alone, but only some of them possess; nor,
_lastly,_ to something which they may all,
but not at all times possess--but we must seek for such properties,
which the truly pious alone, and all of them, and at all times, solely possess.
This is so evident that no one can deny it.
Let us see, with all brevity, what results from these propositions.

First,
Godliness does not consist in anything which the ungodly
and the hypocrite can have in common with the truly pious.
Hence, when we refrain from outward vices, when we do not curse, nor are drunken,
nor steal, nor quarrel, etc., but lead an externally sober, just, decorous, retired,
quiet life, it is no sufficient proof that we are pious and godly--nay,
though we should have all this, and nought besides, or nothing more substantial,
we should only rank with the ungodly and the hypocrite.

We may diligently attend to outward ceremonies, which are good in themselves,
and to pious duties; we may be baptized, and go to church and sacrament; we may read,
learn, and meditate upon that which is good, make external prayers, fast, and give alms;
we may commend and in some measure love piety, and the pious; we may associate with them,
possess much literal knowledge of the truth, know how to converse in a pious strain,
and with all this, be in reality not yet pious.

We may be convinced of God and his truth; be sensibly affected to sorrow, or to joy;
we may be reproved and distressed in our consciences;
we may desire and form resolutions to repent,
and really change and amend ourselves externally, and avoid obvious sins; nay,
we may even abandon secret sins,
(which we still love at the bottom,) from distress of conscience, and fear of hell;
and yet not be truly godly.
All this is evident, and has also been circumstantially enlarged upon by others;^
footnote:[See Mead`'s Almost Christian, Spencer`'s Nature and Grace,
Wilkinson`'s Saint`'s Pilgrimage.]
and yet were all those, who have only this,
and nothing more to be struck out of the catalogue of the pious,
there would probably be found, in whole towns and countries, not many pious people left.

Secondly, I say,
that true godliness cannot consist in anything which some godly men may possess,
or have possessed, but which all have not.
Under this head may be included ecstasies, revelations, the gifts of prophecy,
a wonder-working faith, extraordinary light in divine mysteries, brilliant gifts,
an outwardly manifested zeal, and every other extraordinary gift of God`'s grace.
Godliness does not consist in any of these.

Hence we must not particularly desire any such like high things,
and by no means be envious, when we see or hear of them in others;
for self-love often thinks, "`Ah, if you had such gifts, such light and zeal,
as this or that individual, you would then be truly pious,
and able to edify others,`" and induces us to imitate something or other,
to which we are not called, and without the grace of God.
All this arises from a principle of self-conceit and self-love,
and is a very dangerous temptation of Satan,
against which we must arm ourselves by prayer and humility,
and only labor to attain the substance of godliness,
rejoicing meanwhile in the gifts which God has bestowed upon others.
He that possesses such things, has no cause to presume upon them,
or to exalt himself above others, to take heed that he do not cleave to them,
and rest in them or take a selfish pleasure in them,
and also to stop both his heart and ears against the praise and applause of others;
since they are only gifts, which in themselves, make no one more pious,
but in possessing which,
the individual stands in greater danger than others who do not possess them.

Thirdly,
I said also that the essence of true godliness cannot
consist in anything that all the pious possess,
but not at all times.
All the pious, or most of them, often experience spiritual and divine consolations,
peace, sensible delights, sweetness, occasional assurances,
and various other divine communications and gifts of grace.
I say they experience such things _frequently_ but not at all times or without variation,
from which follows, that the substance of true godliness cannot consist in these things.

And therefore those act, in my opinion, imprudently, who,
having received gifts of this kind from God,
speak of and esteem them almost more than the essence of godliness itself;
and seem to adduce them as unequivocal signs and essential properties of faith and godliness,
nay as the true end, which we must always strive to attain, and give ourselves no rest,
till we have attained it.

Hence it is, that many a well meaning person,
who reads or hears such sentiments advanced,
and has not yet enjoyed the like sensible gifts of grace, may fall into despondency,
dejection, and doubt about his state,
and be hindered in the path of self-denial and the cross, by frequently striving,
from selfish motives, after joy and consolation,
and seeking on all sides for signs and assurances of his salvation,
more than for the marks and properties of true godliness.

Those that possess these gifts of grace, generally think well of themselves,
and often secretly imagine they are now God`'s favorite children--that they are now holy,
nay, better than others, and make themselves sure of heaven.
Here the soul frequently forgets the true and only
sure path of self-denial and the cross,
and lays herself down to rest upon the soft couch of sensible enjoyments,
desirous of erecting her tabernacle, before she has finished her journey.

Now if the Lord, in his wisdom,
withdraws from such a one the milk of sensible consolation and sweetness,
he becomes dejected, discouraged, and uneasy; and seeks to return, and possess that,
which, because it is a powerful support to the life of self,
it is the will of God to take from him, that he may make him,
like the Captain of his salvation, perfect through sufferings.

For although it is an undeniable truth, that in the course of godliness,
many great and various gifts of grace are generally met with,
and even enjoyed in a perceptible manner, as is confirmed by the whole of Holy Writ,
by innumerable testimonies of the saints in every age,
and by real experience to this present time; yet such gifts of grace, I say,
are only met within the course of godliness, and are, as it were,
the resting places and inns on the road, which are neither the way itself,
nor the end of the way, and where we must not therefore always remain,
but which are only occasionally met with, and must be used merely in case of need,
for refreshment and recovery of strength,
that we may afterwards continue our journey with the greater alacrity.
Were we to reflect a little further upon this comparison, and apply it,
we might pretty well discover the proper use of the gifts of grace,
of which I will say nothing more at present,
having elsewhere given thorough instructions on the subject.^
footnote:[The author alludes to a tract of his,
entitled "`The Manual of True Godliness,`" which appeared in 1727,
and contains many useful instructions.]

=== II. The Nature of True Godliness

We have hitherto taken a view of that which may be regarded as godliness or piety,
and in fact is so by most men, which nevertheless, can by no means,
constitute its real essence and substance; the question therefore is,
wherein does true godliness consist?
Now though it be by no means difficult to answer this inquiry in few words,
yet it is difficult, nay even impossible,
to impart a proper idea of it to him who is not himself in possession of true godliness.
For they are the things of the Spirit of God, which the natural man cannot understand.
May the Spirit of God himself enlighten our understandings with his truth,
and powerfully draw our hearts to obedience!

// lint-disable invalid-characters
True godliness (ευσέβεια) is that inward state or disposition,
which is wrought by the Holy Spirit, and the occupation of the soul,
which springs from it,
by which she again renders that homage and worship to the triune God,
which is due to him, and which is in some measure worthy of him.
It consists in filial fear and veneration, in a heartfelt confidence and faith,
and in a fervent attachment and love to God,
which three things are like so many essential parts of the spiritual temple,
in which God is worshipped.
For since he is a Spirit, it necessarily follows,
that he must be worshipped not in a mere external, ceremonial, and hypocritical manner,
but inwardly, heartily, in spirit and in truth,
if it is to be done in a manner worthy of him, as divine Teacher himself demonstrates.
(John 4:24)

I say the Holy Spirit produces this state or disposition of the soul,
while inwardly giving the individual to know (to one more, and as though at once,
and with great power, and to another more imperceptibly and gradually) in a supernatural,
vital, and powerful manner, the truth, glory,
and loveliness of the omnipresent being of God.

This immediately produces in the soul an unspeakably profound veneration, admiration,
filial reverence, and inward humiliation of all that is within her,
in the presence of the exalted Majesty of God.
This glorious being appears to her to be alone great and good, and she herself,
together with every other creature, utterly mean, little, and despicable.
God is exalted and magnified by her, while she herself is abased in the deepest humility.
She esteems herself dust and ashes--nay even as something less;
and therefore cannot bear to see herself honored or esteemed by others.
She is conscious, that to this Majesty, every knee in heaven, in earth,
and under the earth, ought to bow and to worship; and this is the object of her desire.
She contemplates the Divine Being, as almost the only being, and every other,
regarded in his presence, as nothing.
It appears horrible and inhuman wickedness to her to offend such a God.
She would scorn a thousand worlds, rather than commit so great an evil.
Hence she is most deeply ashamed, in true humility and sorrow of heart,
at the retrospect of her former sins, as also at the infirmities and the self-love,
which still cleave to her, the first and most subtle motions of which,
are disgusting and most distressing to her, and the total annihilation of which,
she ardently desires and waits for.

This veneration of God and this mean idea,
or rather total disesteem of herself and of every other creature,
at the same time produces in the soul an entire mistrust
of herself and of all created things,
and a real faith and confidence towards God in Christ Jesus, to whom she yields, resigns,
and commits herself wholly, both in body, soul, and spirit; that he may do with her,
and in her, and make of her, whatever he pleases,
in time and in eternity--hoping and trusting that he is able and willing,
and will assuredly overrule everything for her good, and his glory.
It produces in the soul a departure from herself and from all that is not God,
and an ardent hunger, thirst, and flying for refuge to, nay,
a real entering and transition into Christ, with whom she inwardly unites herself;
and by a continual and believing attachment, retiring into, and abiding in him,
she receives grace for grace, essential, spiritual, vital power and strength,
by which she is wholly penetrated and animated; so that by degrees,
all inward and outward acts, words, thoughts,
and inclinations are produced and inspirited by this new principle of life.

On which account, she most willingly ascribes all the good that is found in her,
or may proceed from her,
with the utmost inward consciousness of her own nothingness and depravity,
and with a heartfelt acknowledgment of the free grace of God,
to this divine source--the vivifying Spirit of the Lord Jesus in her;
so that the soul can then say with truth, in the words of St. Paul, "`Now I live,
yet not I, but Christ lives in me, and the life which I now live in the flesh,
I live by the faith of the Son of God;`" (Gal. 2:20) and learns to understand,
in their full import, these words of Christ, "`He that abides in me, and I in him,
brings forth much fruit; for without me, you can do nothing.`"
(John 15:5) And in truth,
this essential union of faith in Christ Jesus is the sole basis of all true godliness;
and the new life which springs from it, is true godliness itself,
which is therefore emphatically called in Scripture,
"`Godliness in Christ Jesus,`" (2 Tim. 3:12)
in order to distinguish it as something vital,
powerful, and essential, from all self-made, superficially pleasing,
and shadowy religion.

A simultaneous consequence of the above-mentioned inward knowledge and vision of God, is,
that the whole heart is, as it were, blissfully taken captive,
and entirely made willing to detach and turn away, by thorough self-denial,
all its desire, pleasure, joy, and delight,
and its whole affection from itself and all that is not God,
and to direct and fix it all upon this alone all-worthy object, to love him solely,
and to cleave unto him with all the heart, and soul, and mind, and strength,
and to love nothing out of him, which cannot be truly loved in him.

The ungodly _(asebes)_ and the godly _(eusebes)_ stand, in scripture, in direct opposition.
An ungodly person is one who is detached from God,
and cleaves to himself and the creature; a godly man is one,
who is detached from himself and the creature, and adheres to God with all affection.
His whole heart says to all that is not God, "`I am not for you, and you are not for me;
you are not the object of my desire; I can do without you all.
God alone is all-sufficient.
He is my treasure.
He is my all.
He is the center of my affections.
In him alone I have enough.`"
He embraces this lovely being with all the powers of his love, and seeks pleasure, joy,
consolation, and delight in him alone.
He cleaves unto him in his inmost soul.
He immerses himself in him, until at length,
after every intervention and partition of sin and self-love is cleared away,
by the exercise of great fidelity and patient endurance,
and through the powerful operation of the grace of God, he becomes entirely one with God,
or one spirit with him.
(1 Cor. 7:17)

This, taken together, is otherwise called in scripture, "`Walking before God,
or in his presence,`" and is in reality nothing else than true godliness,
the true service of God, or real religion, in which Enoch, Noah, Abraham,
and all the saints and prophets of the Old Testament, as well as Jesus Christ,
our Savior and Forerunner, together with the apostles, primitive christians,
and all his true followers, in every age, have served God,
as will be evident to him who refers to the subjoined passages of scripture,
with a desire after truth that is according to godliness.^
footnote:[Gen. 5:17,24,6,8,9:1, 39:9; Heb. 11:27; 2 Kings 20:3;
Ps. 16:25-8:15, 116:9, 123:1-2; 1 Kings 17:1 Kings 18:15; 2 Kings 3:14-5:16, etc.
John 8:29; Acts 17:27-28. 2 Cor. 5:9; Phil. 3:20; Heb. 4:12-13, 11:22-23; 1 Peter 3:2-4.
]

Now although true godliness, with reference to its origin and essence, is wholly inward,
yet as a divine light, it is impossible for it to remain so concealed,
as not to let its living characters,
even frequently without the soul`'s will or knowledge,
shine forth in the individual`'s whole life, speech, deportment and conduct,
which is entirely different from the life and conduct of the men of this world,
and is diametrically opposed to them.
He verifies on the contrary, that saying of Christ,
"`A good tree cannot bring forth evil fruit; make the tree good,
and its fruit will be good.`"
Where true godliness dwells in the heart, there Jesus himself resides,
and there must necessarily a life,
that is in accordance with the doctrine and the life of Jesus, be also manifested,
and all his virtues shine forth--humility, meekness, love, gravity, a rejection of honor,
pomp, and the treasures and pleasures of the world, patience, fortitude, kindness, mercy,
temperance, and all the other virtues of Jesus Christ.
For although a hypocrite may, in some measure,
possess the outward semblance of these virtues,
yet a truly godly man does not let his light shine the less on this account;
which may be said as a warning to those in particular,
who are fond of speaking of great and merely outward godliness, and in other respects,
allow themselves a thousand liberties in conforming
to the world--nay even look upon and despise a serious,
self-denying, outward walk as hypocrisy and dissimulation,
"`He that says he is in Christ, ought also to walk, even as he walked.`"
(1 John 2:6)

From this inward disposition of the soul, or godliness,
all inward exercises of virtue and acts of godliness from time to time arise (for it
comprehends them all in it,) such as the duties of humiliation before God,
invocation, meditation, contemplation, adoration, thanksgiving, praise, love,
resignation, etc.
Since all external duties, such as hearing, reading, or conversing upon good things,
praying, singing, and the like, emanate,
and must necessarily proceed from such a foundation and disposition of the heart,
in order to be practiced to advantage, and to deserve the name of serving God.

From what has been said,
it may be easily perceived that the principal distinction
between true and false godliness lies in this,
that the latter consists merely in an external appearance, form, and covering,
while the heart, in the mean time, remains unchanged, full of the love of the world,
and of self, and of every abomination; but true godliness possesses in it a divine power,
and produces a thorough change in the man, powerfully withdraws his heart, affections,
delight, and all the powers of his soul from all created things, attaches him to God,
his origin, and translates him into a truly holy and divine life and walk.

=== III. The Usefulness of True Godliness

And ought not he, who is thus godly, to be blessed in God?
Yea, he is truly blessed.
He knows God and Jesus Christ, whom he has sent, which is eternal life.
(John 17:3) The understanding,
which with much weariness and anxiety had long roved about in its utter natural darkness,
groping like a blind man for the wall,
and had sought truth by the deceptive light of reason, and had found only lifeless,
frigid, uncertain ideas, opinions, and conjectures, then sees,
without much individual exertion or seeking, "`light in the life of God.`"
(Ps. 36:9) It recognizes the truth, and him that is true;
and by the contemplation of this truth, the eye of the understanding is enlightened,
gladdened, and satisfied, having now reached its object and its aim.
To know that God is, and that he is what he is,
(Ex. 3:14) affords unspeakable felicity to him to whom the Son reveals it,
(Matt. 11:27) and he cannot do otherwise than heartily assent, and say, "`Yea,
O Lord, it is well that you are, and that you are he, who you are!
Yea, Amen!`"

If it be bliss, as it really is, to possess all that we desire and wish,
the individual that possesses true godliness, must be truly blessed,
because she unites her will with God`'s which is always accomplished.
Formerly she was pained and tormented in the infernal flame of her own will,
which rendered her so frequently dissatisfied; for one thing or another was always wrong,
in the opinion of her perverse self-will; and thus she writhed and agonized,
day and night, within herself, in doleful apprehension, care, grief, uneasiness,
and anxiety, like a gnawing worm, to the injury of both body and soul;
but now she has entirely and unconditionally resigned
her will in the exercise of real faith,
and thorough self-denial, into the hands of God, in such a manner,
that the will of God alone influences and operates in her,
by which the soul is placed in a tranquil and very peaceful state.

Her will desires nothing but God; and because it possesses him (essentially and in faith,
if not always in a clear and perceptible manner,)
it cannot will or desire anything besides;
since God, as its proper and infinite object,
fills and calms the infinite capacity of its desires.
He can say with the pious patriarch Jacob, "`I have all,
I have enough;`" (Gen. 33:11) which no one else,
were he even the greatest monarch upon earth, can say with truth.
For no one knows what it is to have enough, but the truly pious soul,
because no one has ever experienced it.
People suppose indeed, that this thing or that would satisfy their hunger and desire;
and the poor, erring spirit that has departed from God thinks to itself, "`Ah,
if I were in this or that particular situation, if I had this or that,
if this or that were but removed, I should then be quiet and content.
Yet how frequently and constantly does our faithful Creator make the man conscious,
that these are only broken cisterns, and can afford no suitable food for the soul!
One thing alone is needful, and that is God, in whom the truly pious soul,
withdrawing all her desires, love, and affection from every other object,
collects them into one; and thus the spirit arrives at its origin, center,
and aim to which it belongs, and likewise to its rest and true felicity,
which is also increased in the hope of its future
extension and manifestation in eternal glory;
(Col. 3:4) so that in this respect, we are already saved or blessed in hope.^
footnote:[In German, salvation and blessedness are expressed by the same word.]
(Rom. 8:24)

The consequence of all this is an unclouded and cheerful mind, and a well-regulated,
harmonious, undisturbed, peaceful deportment, seeing, as before observed,
that self-will is broken; and hence the affections and passions are moderated,
and brought into proper order, by which even the body, as is easy to suppose,
is more benefited than injured.

It would, however,
require larger limits to touch upon the supreme felicity that accompanies true godliness,
even in this life, although all that could be said, would be only obscure and inadequate;
and hence it is, that in order to know it, the soul must really experience it.
Paul expresses the whole of it in these few words,
"`Godliness is profitable for all things,
(the infallible remedy and panacea,) having the promise of the life that now is,
and of that which is to come.`"
(1 Tim. 4:8)

So much at least is evident from what has been said,
that it is wrong to regard true godliness as something melancholy, grievous, difficult,
and vexatious; since, abstractedly considered, it is quite the reverse.
It is true it occasions severe affliction, agony, and death,
to obdurate self-will and natural depravity;
but it is this very self-will and this natural state,
that makes us wretched and miserable, and must therefore be taken out of the way,
and necessarily be removed by the power and Spirit of our Savior Jesus,
in order that we may be here and eternally happy, joyful, and blessed in God.

Therefore observe, here, two or three of the principal reasons,
why godliness appears so difficult and disagreeable,
not only to the greater part of the children of this world,
but perhaps also to the majority of those who make a profession of religion.
The first is, because some,
and alas! too many are too negligent and tender of themselves in denying the world,
in crucifying the flesh, in mortifying their self-will,
their sensual enjoyments and every selfish pleasure, joy, affection,
and gratification afforded by the creature;
on which account it is impossible to attain to true peace with God,
and a substantial experience of his all-sufficiency.
It is impossible to serve two masters.
(Matt. 6:24) He that will delight himself in God,
must no longer seek pleasure in the creature;
and he that seeks his delight in the creature, will not find it in God.

In some individuals the fault lies in a subtle but very dangerous insincerity,
in secretly, yet knowingly cleaving with affection to some particular sin or creature,
by which the Holy Spirit is grieved, and the heart continues uneasy,
and the conscience feels its accusations.
Others are deficient in a calm and strict attention to the heart,
and to the admonitions of the indwelling Spirit of grace,
and continue to live in a state of mental dissipation, and more in the senses and reason,
than in the spirit, (Rom. 8: 1, 4, 5, 9,
13) by which innumerable sins and selfishness are neither recognized nor removed;
add to this, that men, by listening to carnal reason,
often set bounds and limits to their self-denial and sanctification,
or let others do it for them;
and are thus tolerably well contented with a small beginning,
and with denying one particular thing; while they retain everything else,
under the appellation of weaknesses, without seriously resisting them.

The second principal reason why a godly life appears difficult and disagreeable,
even to many pious people is, that many,
who though perfectly desirous of pursuing it with more sincerity than the former,
yet often run into the contrary extreme,
and are improperly too active in that in which others act too slothfully.
These seek, in their own strength,
to follow and be faithful to the admonitions and requirements
of that Holy Spirit to whom they have resigned themselves,
instead of immediately forsaking themselves and their own activity and ability,
and passing (in reality,
and not merely in an ideal and imaginary manner) by faith and love, into Jesus Christ,
and spiritually and sweetly uniting and holding communion with him;
in order that he who wrought in them the will,
may also work in them to do according to his own good pleasure.
Because of this, what they perform is neither pure, complete, sincere, nor abiding;
and hence the mind, notwithstanding all its legal efforts,
lies prostrate under many difficulties, vexations, reproofs, and fetters.
This is a very important point, when well understood,
and is more prevalent among the pious, than might have been supposed.

True holiness and godliness are both impracticable and strangers
to the law and the natural powers of man.
The vivifying Spirit of the Lord Jesus must make us new creatures,
and wholly animate and influence us,
that filled with this free and powerful grace of the new covenant,
we may deny and overcome everything with delight, valor, and constancy,
and live in the exercise of true godliness, in the presence of the Lord.
If everyone who is in earnest to attain true godliness,
were to plunge himself into this only source of all grace and godliness, that is,
into Jesus Christ, in the consciousness of his deep depravity and inability,
and in heartfelt confidence, and abide in him; truly we should then grow, flourish,
and bear fruit, like trees planted by the water-brooks, and find, by vital experience,
that "`His commandments are not grievous.`"
(1 John 5:7)

But let no one suppose that by this, we wish to pass over the mystery of the cross,
or to exclude the blessed paths of affliction, by which God leads his people,
from the sphere and course of godliness--certainly not.
For by so doing,
we should condemn all the children of God that were before us (Ps. 73:15), Abraham,
Job, David, Heman, Jeremiah, and all the saints, both of the Old and New Testament;
all of whom (each in his measure and degree) have been exercised, tried,
and purified by God, both in body and soul,
by various temptations and assaults of the enemy, darkness, abandonment and barrenness,
distress, and various other afflictions and sufferings.
On the contrary, the divine saying continues true to the present day,
that all who will live godly in Christ Jesus, must not only be externally hated, reviled,
and persecuted by the world,
(2 Tim. 3:12) but be also inwardly perfected by a variety of temptations, crosses,
and sufferings, and thus enter into the kingdom of heaven.
(Acts 4:22) But notwithstanding this, all inward suffering, temptations,
and afflictions, would gradually become easy, nay even pleasant to a godly individual,
nor would they be able to disturb his profound peace in God,
if he only wisely learnt to place his strength, delight, welfare, and salvation,
solely and wholly in God and his good pleasure.
I say _in God_ and his good pleasure alone, not in himself and his own doings,
not in his own ease and satisfaction; not in divine light, gifts, emotions, assurances,
and the like; for all this may, and must be often concealed and taken away.
But God and his will never move nor change.
And when the soul in her sufferings, be they what they may,
can only resign herself and her salvation,
in obscure faith and the profoundest self-denial, to this faithful Creator,
she will certainly attain, in the degree she practices it,
and in which all self-righteousness and self-assumed piety is annihilated,
the peaceable fruits of righteousness and holiness, (Hebrews 12:11) even in this life.

Nor do I mean, by this, to lay still further discouragements in the way of those,
who are sincere in their hostility to sin, and wander about weary and heavy laden,
in penitential sorrow and contrition, nor make them distrust their state,
because it does not seem to them so easy--by no means.
On the contrary, I wish to comfort and establish them, by assuring them,
that it will not always be thus,
and would only remind them that with such a disposition of heart,
they must come to Jesus, in the consciousness of their misery and inability,
that he may refresh them, and then make his yoke easy to them, and his burden light;
(Matt. 11:28-30) and that since they have no power in themselves,
to break through and attain to the true essence of godliness, they ought,
by incessant hunger and prayer of the spirit,
to accustom themselves to cleave to the Lord most fervently and to abide in him;
for he will then infallibly grant them abundantly,
by the impartation of his divine power,
all that is necessary for life and true godliness.
(2 Peter 1:3)

May he, who is God alone, blessed forever, and who alone can make us godly,
so vitally and powerfully touch by his Spirit, the hearts of those who read these pages,
that they shall not only immediately resolve to deny themselves and all created things,
but really do and perform it through him,
that they may follow him and enjoy the unspeakable
and eternal felicity of his divine fellowship!
We must forsake ourselves in order to apprehend him and be apprehended of his Spirit.
We must depart from ourselves in order to enter into him.
This exit and this entrance is the basis and most essential act of godliness;
because by it, we restore to God what is his, I mean ourselves, thoroughly, wholly,
and irrevocably; and likewise by so doing, acknowledge and accept him for what he is,
that is, as our God, Creator, Redeemer, our Supreme Good, our One, and our All, forever.
If this one thing, this departure and this entrance be neglected,
our godliness is worth little, and is only a shadow without the substance.
But since the compassionate love of God in Christ Jesus so faithfully calls us to it,
let us follow this inestimable vocation of grace in humble
resignation by forsaking all we have and are;
that so we may be made godly and blessed in him in truth, both now and forever;
which is the cordial wish, and most fervent prayer to the source of all goodness, of

[.signed-section-signature]
A sincere seeker after godliness.
