== On the Difference of Progress in Godliness

[.blurb]
=== "`Many are called, but few are chosen.`" Matthew 20:16.

=== I. The Difference

Although God has no occasion for our worship, nor stands in need of any,
(Acts 17:25) it is his eternally immutable purpose and gracious will
that--besides the myriads of angelical spirits which in various hierarchies,
legions, ranks, and stations, surround his throne, and contemplate, adore,
and enjoy his most glorious and lovely Majesty--he should also have his church
and true worshippers from among the human race and the fallen children of Adam,
with whom he may unite himself in an inward and reciprocal manner,
hold converse with them, and make them partakers of his divine glory and felicity.

Hence it is, that Eternal Wisdom, whose delights are with the children of men,
continually goes about, as it were, like a faithful and affectionate mother and bride,
seeking souls who thus worship the Father in a manner worthy of him,
in spirit and in truth.
But alas! with the majority she is unsuccessful;
in several she meets with some degree of attention, but not exclusively in all things;
and it is only in a very small number,
that she finds free admission and permission to accomplish unhindered her divine work.
In short, "`many are called, but few are chosen.`"
Notwithstanding all this, the purpose and counsel of God stands immutably firm,
"`The Father seeks such to worship him.`"
And it is really the case, that Wisdom has always found, still finds,
and ever shall find some out of every people and nation, at all times, and in all places,
into whom she can enter,
and whom she can make "`friends of God,`" as it is said in the Book of Wisdom, 8:27.

The consequence of this very various behavior of individuals,
with respect to the gracious calling of God,^
footnote:[By this it is not meant to deny,
that God may have his sacred purposes in bringing particular
souls to particular states of Sanctification and union;
but if all would recognize within them the purpose and calling of God,
and faithfully respond to it, all men would be saints.]
is that there is such a remarkable difference observable among the pious in the
church of Christ (for with the multitude of the worldly-minded and the hypocritical,
we have here nothing to do) particularly since the
declension from the first love and power;
since the most of them stop short at some beginnings of Christianity,
without seriously endeavoring to advance continually; and hence they lead a feebler,
more common, and if I may so express myself,
more _external_ life in the sight of God and man; but others,
and those the fewest in number, have gone forward faithfully,
and have been drawn and led by the grace of God to something more substantial and inward;
in consequence of which they are diligent in leading a more holy, strict,
and inward life.
With respect to this, I might, it is true,
have explained and expressed myself more briefly; and in a mode of expression,
very customary in the Holy Scriptures and in the writings of the primitive Fathers,
have denominated the former imperfect, and the latter (in its proper sense) perfect;
but because there are many, in these truly imperfect christian times,
so unwilling to hear of perfection, that it is to be feared they dread the thing itself,
as much as they do the word, I have sought to avoid this stumbling-stone.

On the present occasion, we will only endeavor briefly to make that difference,
which exists among the pious in the present day, apparent;
if haply someone may learn by it to know himself,
and under the various external minor points and accidents,
with which christianity is now-a-days surrounded and enveloped,
begin to seek the inward germ of the hidden life.

The greater part of those who are called of God, stand still in their course,
after having experienced the primary effects of repentance,
in grief and sorrow for their sins, and anxiety at the dangerous state of their souls,
in a hunger and thirst after the grace of God in Christ,
and in turning from the dead works of obvious sins,
to an outwardly virtuous and pious life and conduct;
supposing that such a change having once taken place,
that which the Scripture calls conversion and regeneration is already accomplished;
and if, besides this, the heart has occasionally felt a degree of comfort, relish,
and delight, the man thinks his state the more secure,
supposing that he has now really found the treasure,
and that having surmounted every obstacle, he has attained to fellowship with God;
and hence he appropriates to himself the precious promises, titles, and privileges,
which God gives in his word to real christians.

Here their chariot wheels stand still.
I do not mean to say that this is invariably their sentiment, purpose, and intention,
as though they had attained the end of sanctification,
and might betake themselves to rest,
but that their supposed advancement is a standing still, if not a going back.
Observe here in what this advancement almost invariably consists.
They exercise themselves in reading, hearing, conversing, singing, vocal prayers,
and such like duties and devotions, which are profitable in themselves;
they reflect on the truths of God, and strive to form a conception of them,
or as it is customary to say, to attain a great degree of knowledge, and seek,
in such and similar activity, their delight and enjoyment.
And when they are conscious of some particular transient
susceptibility or good inclination in the affections,
they rejoice, esteem it very edifying, and often know not how to extol it sufficiently;
but if these are lacking, they complain, as if God had forsaken them,
and are even ready to compare their situation with Job, David, and other saints,
in their painful inward sufferings.
I know not if the conduct and progress of many of the pious consist in anything else;
for with respect to those improprieties which remain after the first change,
they continue in their former strength.
I believe, indeed, that they are occasionally resisted in some degree,
but never overcome, and hence they regard such things as faults and frailties,
from which they do not expect to be delivered during the present life.

Now if we pay attention to the life and conversion of such persons,
we shall find them tolerably devout in their religious exercises,
but the rest of their time, and in their daily interaction with their fellow creatures,
pretty free and unrestrained.
They do not regard it as anything particularly improper,
to have their minds engrossed by a multiplicity of worldly and unnecessary affairs,
and to lay up riches and treasures for the future.
They think themselves at liberty largely to discuss indifferent matters,
and to associate unnecessarily with the people of the world;
they regard it as allowable to please their senses, in seeing, hearing, tasting,
and the like--I will not say anything with respect to thoughts;
for they are universally little attended to by them, and are left to wander far and wide,
for hours and days together, without much scruple and without an aim.
And thus the heart is in a measure divided, although they do not always know it.
For ah! how little care is manifested by such well-meaning individuals to prevent
their delight or affections from straying to some particular created object,
and from seeking in it their gratification, solace, and joy! how negligent are they,
while following their own will and their own opinions,
first in one thing and then in another, frequently under the most believable pretenses;
so that the difference between them and the world is often scarcely perceptible!

Is not this the truth?
and will not many a one who reads this, being convinced in his conscience,
be obliged to answer, Yes?
For tell me,
is it not sufficiently evident that such characters do not
really feel within themselves the power of faith and godliness,
for the overcoming the world, both within and without--for the extermination of sin,
of the inordinate affections and passions of self-love, self-seeking, and self-will,
and for the destruction of the life of self;
and that they do not yet possess within them the great privilege of the new covenant,
which is, that God himself will write his law in their inward parts,
(Heb. 8:10) and that henceforth they should fulfill the will of God,
not from the mere constraint and compulsion of a burdened
conscience with respect to some particular things,
but from fervent love and affection, and from the free inclination of the heart.

Such characters, therefore, do not attain to true and lasting peace, acquaintance,
and fellowship with God in Christ;
and however much may have been spoken or written on the subject,
and upon the enjoyment of peace, joy and blessedness in Christ,
yet these poor people frequent know very little about it from their own experience,
except from having perhaps read or heard of it from other pious persons; or rather,
notwithstanding this, with all their devotional duties and exercises,
they are inwardly kept in a state of much difficulty
and secret reproof and dissatisfaction of conscience.
But where some degree of pleasure and joy is experienced
in the performance of any particular duty and undertaking,
which is apparently good, yet it is only superficial and not lasting, much less pure;
and it is not long before the customary accusations of conscience again commence,
when its voice is listened to.
For whatever is done in this state, results generally, though often unconsciously,
from the man`'s own natural powers and efforts, which soon droop again,
and only occasion either despondency or else much self-complacency in his own righteousness;
but bring little glory to God, and no true and lasting peace to the mind.

We ought therefore, not without reason, to reflect and inquire with reference to this,
how it is possible, that men possessing light and grace from God,
and who are desirous not to deceive themselves--for we speak here solely of such characters--can
think or believe that their state is right and acceptable with God,
since its wretchedness and infirmity is so obvious in every respect?

Assuredly no other cause can be assigned,
than the lack of observation and attention to what passes within them.
For because they allow themselves to be so frequently drawn away,
and enticed from the reproofs of the grace and Spirit of God,
and after having once obeyed its call, and impulse in their first repentance,
they go out of their hearts so to speak, into their thinking or reasoning part,
and form or receive conceptions and ideas of christianity, and divine truth,
according to the feeble and insufficient light they have obtained by the efforts
of their own reason which ideas and conceptions must necessarily be very weak,
limited, and insufficient--and then, consequently regulate and bound their christianity,
although with a good intention, according to the ideas they have once formed,
in which many fix themselves so firmly, that they regard as erroneous,
and reject all that does not accord with, or goes beyond them;
and living thus turned outwards from the interior into the exterior,
and from the light and admonition of the Spirit into human reason, they never attain,
either to a true and thorough knowledge of their inward depravity,
and of a multitude of secret selfish failings in every point,
nor to an insight into the truth as it is in Jesus, and that strict, holy, retired,
and hidden life, which is required in a true christian,
nor to an experimental knowledge of the power of
the Spirit of Jesus Christ in his true followers,
by which they are prepared for such a holy and godly life.

I will not, however,
accuse all such characters of a knowing and willful infidelity or insincerity,
and thus condemn their state entirely;
I would only briefly point out its great deficiency, impurity, and insufficiency,
if haply one or other, through the cooperation of divine grace,
might come more to himself, and ask more minutely,
for the old and only right way of dying to self and all created things,
and of the hidden life with Christ in God.
For alas! ought we not to be grieved and pained to see such
well-meaning individuals running in such an endless circle,
and satisfying themselves in such a manner with the outward shell,
or a mere rational knowledge, and with some particular bodily exercises, duties,
and beginnings of christianity, so that all advancement is forgotten over it,
and the true inward fruit of christianity, never known, nor its blessedness,
in fervent fellowship with God, enjoyed?

=== II. The Transition to a Better State

There are, however, God be praised, still some to be met with, here and there,
in the present day,
who find no rest nor satisfaction in such a mere beginning and mixed state;
but are desirous, with the young ruler, mentioned in the gospel, of becoming _perfect,_
(to use the words of the Lord Jesus,) and to this end devote and
dedicate themselves in a particular manner to the Lord Jesus,
to be his true followers; who by his grace, are also diligent in the practice of a real,
inward, and stricter christianity, and seek to exercise themselves in it,
with all their hearts, as in their only necessary work,
although even among them a great difference is again observable,
with respect to their progress and their states.
I will touch a little upon their transition into a better state, and its properties;
in which however, I must be very brief, because of my narrow limits.

This breaking through and transition of such souls, to something substantial and inward,
generally takes place in the following manner.
All external and internal employment and self-activity, on which the man`'s christianity,
though without his knowledge, had hitherto mostly rested,
is rendered disagreeable to and taken from him;
which in some cases occurs more rapidly than in others;
he can no longer continue his reading, meditation, hearing and conversing,
his vocal prayers, and the like; partly because the understanding,
which had been previously so active, becomes gradually incapable, slothful,
and disinclined to operate, reflect, and deliberate, as formerly;
and partly because the memory can no longer furnish the conceptions, ideas, and subjects,
with which it was filled, nor receive and retain others.
And all that such a one undertakes,
or is able to undertake of inward or outward employment and exercises of his own,
is performed with much difficulty,
and has no longer such an effect upon the heart and will as it had before;
but instead of the previous pleasure, relish, and sweetness, all becomes barren,
ineffectual, and even disagreeable, and vexatious.
He perceives within him, on the contrary, either immediately or in the course of time,
a more than ordinary inclination, not only to outward tranquillity and solitude,
but also more especially, to inward calmness or passiveness, with a simple,
fervent disinclination to and forgetfulness of everything created, and a secret, soft,
and tender inclination to God,
and a childlike attention of faith to his presence in him,
which latter must be very carefully cherished.
Now when the individual resigns himself to this guidance,
which is so strange to the activity of reason, and yet so blissful;
and to this inward and divine attraction, and is obedient to it,
he will find his salvation in this rest and tranquillity; (Isaiah 30:15) since by this,
he is weaned from all his former aberrations and the workings of human reason,
that he may pay attention in his interior and in humble stillness,
to the secret admonitions and instructions of eternal Truth in his center;
and instead of being occupied with a multiplicity of minor things,
he is now directed to the hidden life with Christ in God,
which cannot be attained otherwise than by a continual
dying with Christ to self and every other creature.

And with this, therefore, all sophistical, presumptuous,
and external plausibility in religion, by which the man was able to maintain his credit,
either with the world or in his own eyes, gradually falls away of itself,
and the soul begins to exhibit a more childlike disposition, and to follow the simple,
despised, and hidden suffering life of Jesus Christ,
in which very different lessons will be given than before.
He must now learn to love the sufferings, poverty, and reproach of Christ;
and on the contrary, to avoid and flee, as from things of a very suspicious nature,
the ease and gratification of flesh and sense, the riches and treasures of the earth,
together with all worldly honor or dignity.
Such individuals are then reproved, not only for evil works,
but also for an intention not entirely pure, even in good actions.
The heart must then be thoroughly and entirely divested of all creature attachment,
and of all, even the most secret, pleasure, joy and delight,
and be gradually turned away from everything that is not God;
so that a single unnecessary or inconsiderate word, even in good and spiritual things,
or a short but voluntary and unnecessary wandering of mind, care,
or sorrow is not overlooked.
The soul is then no longer at liberty to see and hear, go and stay,
act and do what and how it pleases her; she now perceives,
that she has one over her and in her, to whom she must attend,
and to whom her will must be made subject by entire resignation.
A subtle obstinacy, inordinate emotions of the mind, self-complacency,
a presuming upon the good that she speaks, performs, or enjoys,
may grieve this tender guest.
And therefore, whenever she thus finds herself in self-seeking, she departs from herself,
in real self-denial and mortification, for the sake of the love of God.
In short, the language of such souls is, "`I die daily,`" (1 Cor. 15:31) hourly,
and every instant;
so that by the various afflictions and sufferings
which befall them from within and without,
according to the all-wise guidance of God, the life of self is totally destroyed.

This sounds hard and severe, nay, it even seems to be impossible; but now observe,
how it becomes easy and pleasing to such souls.
They live, at the same time, in secret with Christ in God, and in his presence;
and God lives and dwells in them, and inwardly fits and enables them for everything.
That which leaves them of corrupt nature,
and what they lose in the exterior and in the creature,
they find again in God a hundred fold.
(Matt. 19:29) The more they are estranged from
and dead to the creature by continual self-denial,
the nearer they necessarily approach unto God and his life,
and are known of him and admitted to a hidden walk and converse with him.
Previously, the creature lived in them, and they in the creature.
God was, as it were, dead to them, and as though he were not.
Now, on the contrary, God lives in them, and they live in God; while all besides,
and they themselves also with respect to their own life, and as in reference to them,
are as though they were not.
Like as they formerly sought and possessed life in the creature and in themselves,
but now die and are dead to this wretched life, they find in the center of their souls,
true life and being, peace, joy, comfort, and delight,
to which they must ardently cleave, by abstracting their affections from everything else,
turning inwards into God, and living in their hidden center.

And thus the words of the apostle are verified in them by vital experience,
that "`God is not far from any one of us; for in him we live, and move,
and have our being;`" (Acts 17:27-28) not only according to his
universal but also according to his particular and indwelling presence.
And thus they inwardly live in God and before him, as a fish in the water,
or a bird in the air; not in mere idea and imagination,
but their spirits really and essentially imbibe,
by unceasing prayer or the hunger of faith, and by drawing near unto God,
as the breathing of the Spirit, divine life and strength from him;
so that by this permanent interaction of faith and love,
the life of God is imparted to them, and they become partakers of his divine nature.
(2 Peter 1:4) Thus they live with a meek and quiet spirit, in a simple, resigned,
innocent, and childlike state in the presence of God,
though not always in sight and enjoyment, yet in faith and reality;
so that even as they die to all things, with Christ, they also live in a hidden manner,
with Christ in God.

Yes, truly hidden! so that prudent reason overlooks this life;
the senses are ignorant of it, the carnal eye perceives nothing of it; poverty, contempt,
and suffering are three coverings, which externally conceal it from the world,
which does not imagine or believe that a king`'s daughter,
(Ps. 45:13) arrayed with unspeakable inward glory, is concealed beneath them.
She therefore looks upon such characters as a poor, miserable, despised,
and afflicted race, as a sect, which is everywhere spoken against, as mean, blind,
and foolish people,
that only occasion themselves such a wretched life and so much suffering and tribulation.
And although the glory that is concealed within,
breaks forth in a variety of divine virtues, like so many rays of light,
so that their life of self-denial, and their renunciation of the world, its riches,
honors, and its pleasures, their resigned, lowly, childlike, innocent, ingenuous,
and artless deportment is apparent to everyone;
yet this is a form and comeliness which does not suit the world and blinded reason,
but which, on the contrary, it often ridicules.
Nay, what is still more, they appear, even to other pious people,
who judge more according to the outward sense and reason,
and govern their religious life more by it than by the Spirit,
often black as the tents of Kedar, (Song. 1:5-6) as the curtains of Solomon;
being ignorant, that underneath this outward garb,
they have inwardly hidden their beauty and loveliness so that their
mother`'s children are often angry with such souls,
who without making any great outward show and appearance, only strive,
in quiet abstraction, to keep the vineyard of their own hearts;
and thus they continue "`the hidden ones`" of the land--(Ps. 35:20;
82:3) their best part is not seen, their divine wisdom is hidden;
(1 Cor. 2:7) their communication with Christ is hidden, their intimate walk with God,
and their life in God is hidden; (Col. 3:3) the enjoyment of so much delight, peace,
joy, and blessedness which flows from it, is hidden.
In short their life is a life in the spirit, (Rom. 8:1,4,9) and all their glory,
rank, and excellence (Ps. 45:13) is inwardly hidden in God.

That such divinely sanctified souls,
who seek to follow the Lamb most closely wherever he leads them,
by the most thorough denial of themselves and of everything besides,
by the most fervent and continual adherence to God,
and by such an abstracted walk before the Lord,
and let their sanctification be perfected here (2 Cor. 7:1) that such souls, I say,
have assuredly and infallibly to expect extremely
great and precious privileges and glory,
in time and eternity, is incontrovertible from many testimonies of Scripture,
of which for the sake of brevity, I will only adduce a few,
requesting the devout reader to refer to them, and to meditate further upon them,
in the presence of God.
Num. 12:6-8; Duet. 10:8-9. Ps. 45:14-15, 64:4; Song. 6:9-10; Jer. 35;
Lam. 4:7; Mal. 3:3; Matt. 19:27-28; Luke 2:37; John 14; 15:15;
1 Cor. 2:15-6:41; Rev. 14:1-5; etc.

Let no one think it is a small thing when he is conscious in his heart of a secret inclination,
drawing, and affection for a peculiarly retired, serious, strict,
and inward life before God, but accept it as a particular grace and holy vocation of God,
and esteem it as a great privilege, and as something very blessed,
which God will condescend to grant him in time and eternity.
I repeat for this purpose, once more, the marks of such a calling,
which among others that might be mentioned, are principally these:
when a person finds no rest or satisfaction in the
mixed life of the generality of the pious,
but is reproved and has a disrelish for even the most latent sins, imperfections,
secret attachment to created things, and all selfishness, self-love, self-will,
and self-complacency; when on the contrary,
he is inwardly conscious of something attractive and alluring,
so that he would gladly be united with God, in the closest and most intimate manner,
and live before him,
in a state of abstraction from the world when the soul is divested and deprived
of her former external activity with regard to reason and the senses,
and no longer feels within her any inclination, nourishment,
or excitement in her usual exercises and employments, or in consideration and meditation,
but in opposition to this perceives within her a drawing and inclination to inward simplicity,
resignation, and composure, and to a universal and tender devotion and attention to God,
who is present with her, without any particular exercise of her thinking powers, etc.

The first christians, in the times of the apostles and their immediate successors,
were evidently such a chosen generation and royal priesthood, such a peculiar people,
(1 Peter 2:9) and applied themselves in earnest to a simple, abstracted,
and godly life; as might be sufficiently demonstrated from the writings of the apostles,
and the testimonies of the primitive fathers.
But my limits do not allow me to enlarge upon this point,
and therefore I refer the reader to [.book-title]#Arnold`'s Delineation of the Primitive Christians,#
and especially to his [.book-title]#True Representation of the Inward Christianity of the Ancients,#
where numerous proofs of it may be met with.

But by degrees, the first love and zeal of many, and in time, of the greater part,
began to cool;
so that they everywhere contented themselves either with the mere outward profession,
or else with a small beginning of grace;
and where they were not kept in a state of watchfulness by persecution, fire, and sword,
they frequently allowed themselves to be seduced into the external element of this world,
and into a multiplicity of secular cares and undertakings;
so that little difference could be perceived between them and the heathen
among whom they dwelt--which lukewarmness and declension obtained,
as it were, possession and firm footing in the church,
during the time so delightful to sense and reason,
of the celebrated emperor Constantine the great;
and the life of the greater part of the christians was no
longer the ancient hidden life of Christ in God,
but an outwardly splendid and pompous life--no more an inwardly real christianity,
but an outwardly seeming christianity.

Still there have been, in all ages, a few select and precious souls,
who while finding no rest for their souls and consciences
in the lukewarm and corrupted life of the generality,
dedicated and consecrated themselves in a particular manner to the service of God,
and made, above others, their whole work and profession, as was only reasonable,
consist in exercising themselves with all diligence, in this abstracted, godly,
and hidden life,
while slighting everything that might in any manner
impede or render them slothful in their serious course.
Among the rest, there were also many devout young persons of both sexes,
whose only care was, how they might please the Lord, and be holy,
both in body and spirit, that thus they might cleave unto the Lord with greater liberty;^
footnote:[Of such Justin Martyr boasted before the Emperor, about the year 130,
in the following terms:-- "`There are many among us, of both sexes,
who live a life of singleness and chastity till their old age,
after having followed from their infancy the doctrine of Christ.
(Matt. 19:11) I for my part assert,
that I can produce instances of this from among people of all classes.`"
Apol. 2.
{footnote-paragraph-split}
Another shortly after him, wrote openly as follows:
"`There are many among us, both men and women, who grow old in a single life;
because they hope in such a state to be nearer to God.`"
__Athenag. Apol.__ page 36.
And Augustine says, "`It is now scarcely a matter of surprise,
that so many young men and women despise marriage and live in chastity.`"
// lint-disable scan-errors
De ver. Relig. Cap. 3. See also __Arnold`'s Delineation,__ sec, 5. cap. 5.]
there were likewise those who are generally called
"`Ascetics,`" or such as exercise themselves in godliness,
who being desirous, according to the admonition of the Lord Jesus,
(Matt. 19:31) of being perfect,
refrained from all unnecessary association with mankind, and from superfluous concerns;
and frequently, at the divine call,
sold all that they had and distributed it among the poor,
and afterwards lived a peaceable life, in a small habitation or apartment,
working a little with their hands,
and employing all the rest of their time in dying unto all things,
by means of thorough self-denial, and in leading a hidden life in God,
by constant prayer and communication with him.

And when the lukewarmness and declension to that
which is external became so general and so great,
many thousands, in order not to be carried away with it,
nor allow any diminution in the strictness of their walk,
by the slothful and worldly life of other christians,
fled from the common interactions with men, and retired into remote and desert places,
according to the divine will, and exercised themselves, day and night,
with all diligence, in such a holy inward and hidden life before God,
and in his presence.

It is not my object and intention to bring forward
and recommend the outward mode of life,
the bodily exercises,
or any other peculiarities of these or the holy individuals before-mentioned,
since they had themselves no general rule, nor any particular method,
and in course of time, while the darkness continually increased,
fell also by degrees into outward observances and human folly;
my intention is merely to show that by these devoted souls and solitaries,
such as they continued to be till the fifth century, primitive, inward,
and powerful religion, was principally maintained and propagated.^
footnote:[As may be seen in the lives of the primitive fathers, Anthony, Hilarion,
and others, and particularly in the writings of Macarius, Ephraim, Syrus, Nilus,
and also of Cassian, Climacus, etc.]
And even in the succeeding wretched times,
God has always had his "`hidden ones,`" (1 Kings 19:18;
Ps. 83:3) as may be seen by reference to the __Catal. Testim.
Veritatis,__ and in other books, such as [.book-title]#Arnold`'s Theol. Myst.# Cap. 16-17.

Among those elect and God devoted souls are also particularly to be reckoned
those who are generally called "`Mystics`" (that is secret or hidden) whose writings,
next to the Holy Scriptures,
contain a true definition of real inward christianity and genuine divinity.^
footnote:[In a work of the author`'s, entitled The Lives of the Saints,
in three volumes quarto,
he has collected a variety of facts and information on this subject,
to which the reader is referred.]
It is true,
that most of them lived and were known with their writings in the Romish Church;
yet in bearing testimony to the truth, I must say,
that the sincere among them were more evangelical and reformed than most protestants;
I mean to say, they were real inward christians,
who did not continue clinging to externals,
but served and worshipped God in spirit and in truth,
by withdrawing their affections and confidence from all created things, from themselves,
and from all their own works, through true faith and union with God in Christ.
And although I do not approve or defend all the minor points
and external incidents that occur in such writings,
yet it is certain, that more divine unction, light, counsel, comfort, and peace,
for a soul that is seeking after God,
is to be found in a single page of the true mystic writings,
than is often contained in many folio volumes of weak and watery school divinity,
as enlightened divines among the protestants themselves concur in testifying.^
footnote:[Vide Godfried Arnoldi Histor. Theol. Myst. Cap. 8. 38. Sophia prefat. No. 7.]
But why is it that such valuable works are generally so little esteemed and used?
Is it not because an inquisitive curiosity does not find food in them,
and that the nature of the old man and the life of self is too severely attacked,
and that they do not require to be reasoned and speculated upon like other books,
which are accommodated to the taste of the old Adam,
but insist upon mortification and self-denial?
However, as many pious divines among the protestants themselves,
have rescued and defended the divine truths, which are to be found in these writings,
I again turn myself to those select souls,
who feel themselves called to this inward and stricter hidden life.^
footnote:[See among the Reformed writers, Voetium de Exer.
Piet. et in Ascetes. Lodenstein Beschauu. Zions.
page 39 et seq+++.+++, Franc Rous Interiora Regni Dei, J. de la Roque dernieres heures,
page 63., Poiret de Eruditione ejusd. Economiam Divinam, etc.
And among the Lutherans, Lutherum, Joh. Arndt, Varenius, Hoburg.
Jac. Speneri Praf. in Taulerum. Arnoldi Myst.
Theol+++.+++, Weismanni Introduct. in H. E. part 2. page 555 et seq+++.+++,
Aletophili Myst. Theol.]

=== III. A Particular Address to those select souls, who have resigned themselves to God and his inwardly hidden life.

To you, you elect and beloved souls,
you devout Nazarenes--to you my dearest brethren and sisters,
who have sincerely dedicated and consecrated yourselves to a more exact religion,
and to the hidden life with Christ in God;^
footnote:[The holy martyr Cyprian,
in addressing the females who had devoted themselves to God,
bestows upon them the following titles: "`Flowers among the plants of the church,
the beauty and ornament of spiritual grace,
the pleasant and noble scions and children of praise and honor,
(of Christ and his church,) a whole and unconsumed work, an image of God,
according to the likeness of the holiness of the Lord Jesus,
the most excellent of the flock of Christ.`"
The learned Sandaus, in his Prafat. Theol. Myst.
borrows these appellations, and applies them,
not improperly to the Mystics.]
to you in particular, I have still to address, in love,
a word of admonition and incitement on the present occasion.
For although some of you even already possess the Spirit of unction,
(1 John 2:27) which leads you into all truth; yet the wisdom that is from above,
will also manifest itself in this instance, by gladly receiving instruction from another.
(James 3:17) But that I may not myself be found lacking,
I will seek to keep my own soul especially in view, while addressing yours.

We see from all that has been said, that we are not to govern,
form and limit ourselves according to the example of others,
although they may be pious people;
but that God most certainly demands of us something particular.
(Matt. 5:47) I mean stricter duties and a more holy life and conduct,
both inwardly and outwardly, than is alas! evinced by others.
Let us therefore forget what is behind, and keep the mark and the prize in our eye,
which our heavenly vocation holds out to us.
Let others live as they please,
and though many of the pious are not without their failings, what is that to you and me?
Let us only look, with a tranquil and introverted mind,
to him who is ever calling to us to follow him.
(John 21:22) Great and unspeakably glorious is our high vocation in reality;
but let us remember the words of our Savior, "`Many are called, but few are chosen.`"
(Matt. 20:16) It is not he that has more light
or a deeper insight into the ways of God,
who is better than others; but he who has more love,
and leads a more exact and holy life.
In this, my beloved, consists that peculiarity, which must be found in us above others.

If others serve God and mammon at the same time, and while professing to be pious,
are seeking and laying up treasures on earth,
by engaging in extensive secular concerns-- let us look unto him,
who calls unto all those that resolve in earnest to follow him, "`The foxes have holes,
and the birds of the air have nests, but the Son of Man has not where to lay his head.`"
(Luke 9:58) And remember, that if the former be Israelites, we ought to be Levites,
a royal priesthood, concerning whom God has said,
"`You shall possess nothing in the land, nor have any portion among them;
for I am your portion and your inheritance.
(Num. 18:20; Duet. 10:9;
Ezek. 44:28) We must show that we are dead to the world,
and look no longer at the things that are seen; but that our lives are hidden in God,
and our abstracted world and wealth-denying walk must be as a loud voice,
saying unto all men, "`God alone is sufficient!`" (Ps. 73:25)

If others take and allow themselves liberties by an immoderate
condescension and seeking to please men,
in the company they keep, in their conduct, fashions,
and such like vanities--we must be particular in this respect,
and not give way to the world a hair`'s breadth;
better be called self-willed than worldly-minded.
How easily may giving way become going astray,
and by too great complacency to this Delilah, the inward power be lost, as in a dream.
The jealousy of the Bridegroom of our souls does
not permit so much to be done to please his rival,
and he that will not believe must feel to his loss,
"`that the friendship of the world is enmity with God.`"
(James 4:4)

If others follow their sensual appetites,
and spend and misspend their valuable time in the variety, adorning,
and beauty of their dress, their houses, and their furniture;
and apply so much valuable attention to the ease and enjoyment of their
vile bodies--it is for us to show that we are not sensual nor animal,
but spiritual men, who therefore no longer live after the flesh and sense,
but after the spirit,
(Rom. 8:1,4,9) and do not seek to lie here upon roses and at ease,
when our Head and Forerunner was born in a wretched stable and manger,
and died upon the cross, wearing a crown of thorns.
Indeed I cannot believe it, nor do I know whether the world will believe it,
that the inward religion of those is great and exact,
who will have everything outwardly so elegant, so convenient,
and so precisely to their mind, even did they know all mysteries,
and spoke of the most exalted spirituality.
He that feels himself called to be an heir of heaven and bride of the King of kings,
ought therefore to be "`all glorious within,`" (Ps. 45:13) that his inward
part may become a suitable dwelling and residence of the Divine Majesty;
and hence he will find so much to cleanse, adorn, and beautify there,
that he will soon lose all relish for any external fancies.

If we see others turning outwards into the senses,
and by trifling and unnecessary hearing, seeing, speaking, and thinking,
open their hearts as it were to the creature--let our hearts be as an enclosed garden,
and a sealed fountain to all created objects,
and solely open to the Beloved of our souls.
We must wait day and night at the posts of his doors, as a spiritual priesthood;
and therefore we are under obligation,
because we believe the Lord to be present in the temple of our hearts,
(Zech. 2:13) from that reverence which we supremely owe to him, to keep our mouths,
minds, and thoughts in holy silence and abstraction.
When we speak, we ought to speak from God, before God, in Christ Jesus,
and real words of God.
(1 Peter 4:11) For can you suppose my dearly beloved,
that we who may here behold and address the Lord of glory within us,
are at liberty to slight him so much, as to leave him there, so to speak,
and turn ourselves outwards to visible things?
O how irreverent would such conduct be!
Our silent, considerate, abstracted, and retired life and deportment,
ought rather to give to everyone an impression of
the inwardly hidden holiness and fear of God.
// lint-disable invalid-characters
It was in reference to this, that Bernières commended his spiritual guide,
after the latter`'s decease, saying,
"`mere remembrance of him replaces my soul in the presence of God,
if it has wandered from him,
and gives me courage and boldness to strive earnestly after true virtue.`"
// lint-disable invalid-characters
(Lettres viè illum: litt. 35. page 283.)

If others fix their affections first on one created object, and then on another,
and seek and find in them enjoyment, comfort, joy, and delight--let our hearts,
our affections, and all our love be solely and eternally devoted,
in true virgin chastity, to the Bridegroom of our souls.
If we still possess too little love to love the infinitely lovely Good sufficiently,
how can we dare to deprive him of any part of it?
And besides, what is there in the wretched and needy creature,
that may not be found in supreme perfection, and infinite abundance in the Creator,
and be enjoyed a hundred fold, even in this life?
(Matt. 19:29) Therefore let our whole hearts say unto
every good that is not this one and supreme good,
"`I need you not.`"

On the whole, we must be dead to all created things,
and lead a hidden life with Christ in God; a life of holiness and godliness,
of humility and meekness, of simplicity and innocence, of love and mercy,
of chastity and moderation; in short, a life before God and in God.

But my beloved, besides all this, let us most carefully beware,
in all our walk and conduct before God and man, of all affectation, dissimulation,
outward holiness and formality, which vice has so often gotten possession of us,
that frequently without our knowledge,
it defiles our life and conduct--if not in a manifest, yet in a subtle manner,
by which the mind is stripped of all freedom, peace, and liberty of spirit.
Our conduct, walk, words, and gestures,
as well as the thoughts and disposition of the heart, must be judged and weighed,
not by men, who only see the outside, but by the purest light of God.
We must not seek to appear holy, but to _be_ holy, and that in the eyes of God alone,
who searches the heart and the mind.
We must keep our inmost souls constantly naked and open to the rays of this eternal sun,
that we may walk in simplicity and purity, and in truth and righteousness.
(2 Cor. 1:12) God is a God of truth;
we must therefore walk in the truth and in simplicity of heart,
if we are desirous of having fellowship with so pure a being.

Be it likewise consequently far from us, when possessing an insight into,
and finding ourselves called to this more strict and particular christian course,
to imagine ourselves to be something particular,
and exalt ourselves above other pious persons,
or even claim to ourselves some spiritual privilege or title of honor,
and mentally slight, or even despise others.
By such conduct, we should show, that though we had a light,
yet we had not the reality nor experience of genuine and inward christianity;
because the most profound humility and thorough self-annihilation
are the essential properties,
characteristics, and aim of the truly inward life.
But if we really possess some degree of experience and progress in this divine life,
the divine unction will undoubtedly teach us that we have
to ascribe it not to our own diligence and fidelity;
but to the unmerited grace and power of God.
What have we then, that has not been given us?
If we have become holy and happy, it is by grace and not of ourselves,
it is the gift of God.
(Eph. 2:8) What have we then to boast of?
If there be anything good _in us,_ it is not _of us,_
nor is it ours--it is and remains God`'s property,
who has it in his power to take his own back again.

And therefore we may not glory, even in any measure in our piety and virtues,
or regard them with self-complacency;
how much less are we at liberty to do so in reference to spiritual or divine gifts,
sweetness, joy, or illumination, even were it ecstasies and revelations!
We must indeed accept the gifts of God with thankfulness,
but presume so little upon them,
as to be able to restore them any moment to the giver without difficulty,
and seek our rest in him alone, and not in his gifts.
Ah, how many, in the possession of such like gifts and sensibilities,
imagine themselves very fervent, pious, and holy,
while they are perhaps still full of self-love, self-will, and self-conceit,
instead of that most necessary humiliation and self-abasement before God,
and beneath every creature!
It is written, "`Rejoice in the Lord,`" (Phil. 4:4) and "`count it all joy,
when you fall into manifold temptations.`"
(James 1:2) But of gifts it is said,
"`Rejoice not,`" (Luke 10:20). We must be perfected and united with God,
not so much by doing and enjoying, as by suffering and privation.
(Heb. 2:10) Let us remember and retain it well,
that the substance of christianity and true holiness does not consist in such like things;
but in dying to ourselves and every creature,
and in leading a hidden life with Christ in God, and before God.

I say "`with Christ,`" for ah, how soon everything vanishes that is not founded on Christ!
The sole, real,
and immutable basis of the inward life is the inward or
mystic union and fellowship with Christ Jesus by faith.
Here, neither good intentions and resolutions, nor our own willing and running,
(Rom. 9:16) nor any legal exertions of our own powers avail
to bring about the due foundation and establishment of our holiness.
We know what the Supreme Teacher of the inward life says, "`Abide in me,
and so shall you bring forth much fruit, for without me, you can do nothing.`"
(John 15: 5) O that we might only strongly believe and continually practice it!
What is required of us is to depart from ourselves
in the deepest conviction of our own inability,
and with fervent desires of faith,
to cleave in the center of our souls to this only source of all grace and holiness,
and "`Receive out of this fulness, grace upon grace.`"
(John 1:16) Let us, by withdrawing our affections from all created things,
continually retire into him, and wherever we go or stay,
habituate ourselves to abide in a childlike manner in him;
and thus shall the vital power of his Spirit, which pervades us from within,
thoroughly sanctify body, soul, and spirit.
(1 Thess. 5:2-33) We shall then see, whether Martha,
with her well-meant outward labors and efforts, or Mary,
with her sitting at the feet of her Savior, will attain the better part,
the one thing needful.
(Luke 10:42)

But now, my highly esteemed brethren and sisters,
if we find ourselves redeemed from the earth, and made kings and priests unto God,
and if we have freedom of access in the center of our souls into the most holy place,
before the presence of God--let us never forget to ascribe thanksgiving
and honor to the precious atoning blood of Jesus Christ,
by which alone this grace has been purchased for us, (Rev. 5:9) and is opened to us.
(Heb. 10:9) For certainly, had not Jesus Christ died for us and rose again,
the way to true holiness and communion with God might
have been eternally closed against us,
miserable creatures; which I touch upon here particularly,
because those who apply themselves to a strict and inward religion,
or bear witness of it, are universally blamed,
as if by so doing they slighted or even despised the work
of redemption accomplished by Christ for us.
Now I will not deny, that possibly many,
who have not hitherto been particularly humbled by inward affliction, poverty,
and suffering, may, with a good intent,
in order to resist the general abuse of this truth,
have used immoderate and inconsiderate expressions, and may have run into extremes;
yet all truly enlightened souls, even the so-called mystics among the Roman Catholics,
have in reality more highly esteemed and gloried in the merits of Jesus Christ,
as our atonement and justification, than perhaps many of their accusers.

But let us, you elect souls, meanwhile acknowledge with humble thankfulness,
that if we had no Jesus _for_ us, we should never have had a Jesus _in_ us.
And if we should ever be exalted to the state of the most
elevated and purest contemplation of the Deity,
whether in this life or the next,
yet this consideration will ever remain most delightfully and supremely precious to us.
The Lamb that was slain, is worthy to receive power, and riches, and wisdom,
and strength, and glory, and thanksgiving, and praise; for he was slain,
and has redeemed us to God by his blood, out of every nation, and tongue, and kindred,
and people, and has made us kings and priests unto God.
Amen and Amen!

"`Blessed Savior, Jesus! who by your death and resurrection,
have brought this divine and hidden life to light, O may the long-desired,
happy time arrive, when instead of all human ordinances, speculations and controversies,
this genuine, inward, christian life,
may again flourish in its first esteem among all nations,
that they may willingly submit their hearts to the sway of your love!
Lo, I offer you my heart, most lovely Jesus, sanctify me in this your truth,
conceal me ever deeper in the secret of your countenance, hide me,
O my high Priest! with you in your pavilion from every danger!
Preserve, carry on, and perfect your gracious work in me,
that all the life of self may die and decay, till I see no other life, will,
or motion in me, than that which proceeds from you and your pure Spirit,
to the eternal glory of the Father!`"
Amen.
