[short="The Shadow and Substance of Godliness"]
== On the Shadow and Substance, Form and Power of Godliness, in a Letter to a Friend

Having the form of godliness, but denying its power. 2 Timothy 3:5.

My dear friend,

If I were to communicate to you my thoughts on the
contents of the manuscript which has been sent me,
I should say briefly,
that all which is not internal and has not God himself
in Christ as its foundation and source,
can only be called the mere shadow, and not the substance and essence of godliness.
From this general proposition,
it is not difficult to deduce all that I have otherwise to say upon the subject.

I+++.+++ When we conduct or show ourselves before men, in conversation, action, or gesture,
otherwise than we mean, or different to what we are in reality, or wish to be,
however secretly or subtly this may take place, we do not walk in simplicity;
it is falsehood, and not truth; or at least it is something assumed and dissembled;
a shadow and not the substance--an abomination in the sight of God.

It is not only wrong to show ourselves better than we are,
but it is an improper affectation, nay,
often a vain desire of being better thought of when we represent ourselves,
whether in words or otherwise, to be poorer, more miserable,
and worse than we believe and feel ourselves to be.

I have purposely employed above the expression "`are
or wish to be,`" for a person that is evil,
proud, irritable, etc. but who still sincerely wishes to possess the opposite virtues.
Such a person ought, according to the divine law, and his own conscience,
to resist the evil and suppress it, that it may not break forth; and in doing this,
he neither dissembles nor acts the hypocrite; on the contrary,
he would be guilty of dissimulation, if he allowed it to break forth;
since he purposes and wishes in his heart what is good, and not what is evil.
But if such a one, who suppresses the evil that is within him, for instance, anger,
and behaves himself meekly, to imagine on this account,
that he already essentially possessed the virtue of meekness,
or should seek to be esteemed by others as a meek character,
he would be deceiving himself.
He has the appearance, but does not yet possess the substance of this virtue.

O my God, how much does hypocrisy, formality,
and dissimulation pervade fallen and perverted man!
And how little are we aware of this abomination in ourselves,
since by reason of the thick darkness and confusion which fill our minds,
we do not perceive what is in them, because we remain so little with ourselves,
and abide still less with you!
Teach me, O God, who are so inexpressibly near me, both outwardly and inwardly,
teach me to walk under the observation of your eye, in the pure light of your truth,
that I may practice simplicity in all my actions and deportment.

II. It follows from the above general proposition,
that all the duties which are included in serving God,
and which have not real devotion of heart and the worshipping
of God in spirit and in truth for their basis and origin,
are nothing more than a shadow, outward semblance, a form of godliness,
but not the substance.

Hence I remark, that it is not good for a devout person, who walks in the spirit,
to engage in too many religious exercises, because by this means,
the inward power and devotional feeling is easily weakened and wearied;
but he must attend and apply himself with so much the more circumspection
and heartfelt devotion to the fewer and more moderate exercises,
which he retains.

However, if there be but sincere devotion of heart in all our external religious duties,
our works are then no mere and vain shadow, but acceptable to God in their degree;
even supposing that we have not yet attained to the worshipping of God in spirit and
truth taken in its fullest sense--and at which we cannot arrive by our own efforts.

III.
We may infer from hence,
that all light or knowledge of God and divine truth which is communicated to us,
either mediately from without, or which we attain by the efforts of our own reason;
or if, after receiving some real light of truth from God in our center or understanding,
we transfer it into our imagination and reason, and form to ourselves ideas of it,
draw consequences or inferences from it,
and obtain some measure of light or knowledge by our own efforts (even though it were
concerning the most spiritual and inward paths of religion)--all such light and knowledge,
however profound, beautiful, pleasant, and inward it might appear to us to be,
is a counterfeit and imitation, a portrait, the work of our own hands,
in which self-love often takes more delight than in the original.
For when this knowledge is taken in its best sense, it is only a speculative truth,
that is, when the substantially acquired knowledge of the truth within, reflects itself,
and represents itself in the mirror of the imagination,
and thus the individual contemplates a beauteous object in this mirror,
but not the object itself.

By this, I by no means intend to reject any good external means whatever,
or any attained knowledge in its right use and due season,
for this would be going too far;
I only wish to show that there is a difference between the means and the end,
the form and image, and the substance.
The form can represent to us the substance or original, and incite us to love it;
the means may lead us to the end proposed,
without which we perhaps never should arrive at it;
the making use of them in proper order and degree is very useful and laudable:
but it is imprudent and dangerous to stop there,
as if they were the end and the substance of the thing itself.

Speculative or reflective knowledge is the production of our reason,
(our operative understanding,) and there are various kinds of such knowledge,
according to the individual`'s state;
but substantial and contemplative knowledge is the effect of the pure or passive understanding.
Reflective knowledge of the truth is a more or less laborious speculative cogitation,
effort, and operation of our understanding or reason,
and has never the essential truth before its eyes, but merely an image of the truth,
as in a mirror; but contemplative knowledge of the truth is a very easy, direct vision,
and extremely simple act of our understanding, if that can be called an act,
when our eye sees and enjoys the light;
and he that possesses this contemplative knowledge has also the substance of the truth,
according to the measure of his grace and illumination.

Notwithstanding all this, let it be well observed,
that I by no means reject reflective knowledge entirely and without distinction;
for God has given us a capacity for this purpose, which is our imagination and reason.
A soul that seeks God and his truth,
may occasionally be much supported and assisted in her course by means of a good meditation.
Nor could enlightened souls ever make known the truth to others,
if they did not in some degree make use of their active understanding,
and declare the truth in a more or less figurative manner.
It is true, that during the states or paths of purifying suffering,
all previously acquired reflective knowledge, seems, as it were, to fall away and vanish;
for where fruit is to be produced, the blossom must first fall off;
if the substance is to enter the heart, and truth present itself there,
the image in the mirror must be covered up,
that the sight may be turned away from and into it.
But even this is frequently restored to us, in the divine good pleasure, and that too,
in a manner much more pure, beautiful, and lively; and after we ourselves,
and the powers of our souls with their operation, have been purified,
God grants us occasionally a holy diversion and excursion of this kind; yea,
he sometimes leads us out to look at his paintings and delineations,
and then again inwards to contemplate the original substance of truth;
and thus going in and out with our Shepherd, we everywhere find food and pasture.
But let it be observed,
1st. That a person thus inward must not linger too
long or too frequently in this kind of activity,
nor apply himself too powerfully and with all his energy to it;
but let the Lord lead him to it, rather than undertake anything from his own will.
2nd. He must also not neglect occasionally, and even frequently,
to discontinue entirely this kind of activity and mental cogitation,
that he may lay open his whole soul fervently, nakedly, and passively before God,
and the essential light of his divine truth;
otherwise he would be in danger of imperceptibly losing the truth,
if he always sought its image and shadow,
and wished to seize it as something substantial.

IV. The general proposition, with which we set out, teaches us that all godliness,
virtues, and good works,
which do not spring from the union of faith with God in Christ as from their inward root,
and therefore do not proceed from the bottom of a heart that has been changed by grace,
are not that which they are called, but only a self-made resemblance, mask, and form,
and not the substance of the thing; nay, when beheld in the light of God, all appears,
on account of the natural depravity of its source, to be more evil than good;
"`splendid sins,`" as one called them.

But by this I will not say, that all is evil, which is not perfectly good;
and that we must not begin to practice the virtues,
before they can be performed without fault,
or till we are assured of a real and universal change of heart.
When a soul that seeks God does good with all possible sincerity,
in the intention of obeying and pleasing God, it is certainly not without his grace,
nor is it any evil or mere self-made form;
even supposing that she had not yet arrived at a total change of heart,
and that therefore the virtue did not proceed purely from Christ.
The soul then does what the law requires of her, and what,
with the cooperation of preventing grace, she is able to do.
It is certainly requisite for her not to lay much stress on her actions, virtues,
or faithfulness, since all is assuredly still very human and imperfect,
and even only the semblance of virtue, in comparison with the spiritual virtues,
which the Spirit of God, in his own time, produces in the soul; it is also necessary,
that she disregard all her own doings, and immerse herself, with humble confidence,
in the grace of God, with inward longing and believing patience,
pressing forwards to union with Christ, and expecting the operation of his Spirit in her;
but it is unnecessary and very dangerous for her to distress herself with
incessant scruples and despondency in all her attempts to do good.
Let her do good, as she is able, however imperfect it be,
and expect that the Lord will purify and perfect it.
"`There is none good but one, that is God.`"

V+++.+++ When we seek by our own endeavors, labor, or activity, to destroy and eradicate evil,
sin, or self within us,
that which is evil is not essentially slain and destroyed in us by such well-meant endeavors,
but only in appearance; it seems to be dead sometimes, but it is not yet dead,
it is only asleep and hidden,
and afterwards comes so much the more dangerously and dreadfully to light.
In order that the evil may be essentially and thoroughly slain and eradicated in us,
God must do it, and we must be passive under his operation.

The former, however, precedes the latter.
We are bound, according as our state and the grace we have attained requires,
to resist that which is evil, to suppress it, to turn away our will entirely from it,
and inwardly to hunger after full redemption through Christ.
"`O that the salvation were come out of Zion unto Israel;
O that the Lord would redeem his people from their captivity!`"
And this is therefore a denial of self, a crucifixion and a mortification,
but not the real death and dissolution of the life of self, which is God`'s work alone,
and a free favor, an impartation of the death of Jesus Christ.
However, no one dies with Christ, who is not crucified with him.

"`Yea, O Lord! whatever may be called true goodness, virtue, holiness, is all your work,
and a free gift of grace.

My heart, without your power and grace,No real good can e`'er possess.

How easy it is to say this, but how much does it cost to learn to practice it,
if we sincerely seek to acquire it,
and are not content with the mere exterior of this knowledge; I desire,
O Lord! to experience, through your grace, its substance and reality.
Therefore let all my own work and virtue perish and vanish from me;
that in the day of trial, your work alone may stand and receive commendation.
Only let your grace never depart from me, lest your hand be too heavy upon me;
for without you I can do nothing, am nothing, and have nothing, but sin and misery!`"

VI. All that is called inwardness, or inward life and devotion,
which has not for its foundation the Spirit of Christ
and the real denial of ourselves and of all things,
but which we produce by our own efforts and the mere exertion of our own thoughts,
is only an imaginary inwardness, an empty shadow and form, but not the substance.

The whole mystery and essence of true inwardness
consists in this one thing--in living with God,
and in his presence;
but no one can do this who does not die to himself and to all things.
It is certainly very good for one who strives after this inwardness,
to subdue and restrain his senses, not purposely allow his thoughts,
especially the thoughts of his heart, to rove about upon unnecessary objects,
to retire occasionally, even externally,
for the purpose of sacred recollection in the presence of God,
and in other respects to strive in all things to live a life of abstraction;
but let him know that with all this, he would never become an inward man, unless,
through the power and teaching of the Spirit, he turn away his heart, desires,
and affections, from everything, and center them in God;
resignedly surrender his whole will into the hands of God; and in all things seek,
with simplicity, to set the Lord before him.
Now as often as he strives to enter in reality into this state of mind,
expecting at the same time the operation of God to lead him substantially into it,
he practices what is termed "`peculiar recollection.`"
In other respects,
it is unnecessary and dangerous to endeavor to place ourselves in a forced
frame of mental devotion and united exertion of the thinking powers.
The head and all the rest will follow, in due time, without difficulty,
if the heart and affections only go before.

I do not say that a soul cannot become inward before she has really denied herself,
and is dead to herself in all things; for the inward turning to, and abiding with God,
above-mentioned, is the best,
nay the only means of becoming thus abstracted and mortified; I only say,
that with his inmost and total will,
the man must sincerely turn himself away from all that is not God,
in order that he may retire to him in his heart.
And he that acts thus, is in no danger of false detachment,
and does much when he thus continues with God, without doing anything.

VII.
Another inference from the first mentioned proposition, is,
that if in our inward exercises, we do not keep ourselves naked and open before God,
in all filial simplicity, humility, and resignation, such as we are,
but show ourselves in any way different, or make ourselves something,
that we neither have, nor desire to have--we are then guilty of dissimulation,
and our deeds are then a self-created shadow, and no reality, a form and no substance.

It is thus that not only all who are manifestly hypocritical act, who draw near to God,
as his people, with their lips, while their hearts are far from him,
but there are also subtle, double-minded individuals,
who likewise do not lay their whole souls open before
God in their most inward exercises and prayers,
but still cover their nakedness in some measure with a fig-leaf.
Ah, how much is required before men will lay themselves entirely naked and open before God!
Even those who are sincere, may through inattention,
occasionally say or think something in their prayers,
which they probably do not find or perceive in themselves;
or they may frequently present themselves before God in another guise and form,
than what they are and feel themselves to be;
which occasionally proceeds from what is called a good intention,
while dealing with God as if he were a man, who when he is addressed,
is often better pleased if some particular expressions are employed,
or if the individual appear before him in some particular dress.
Thus for instance, the man may present himself, though unconsciously,
in the robe of his own virtue or piety;
another time he may seek to make himself very poor and little; again at another,
he may place himself in a state of great sorrow and contrition of heart, etc.
If the grace of God produced this, it would be well;
but we endeavor to effect it by our own efforts, and do not expect it from God,
and then it is a self-made thing; a shadow, but not the substance.

But in order to discover and avoid such like faults and selfishness in ourselves,
it is not necessary,
but rather injurious to be always examining in an anxious and scrupulous manner,
and retrospectively considering each and all of our inward acts.
All this may be avoided without difficulty and danger,
if we be not of ourselves too operative in our inward exercises, but look unto God,
and think more upon him than upon ourselves and our own doings,
and in other respects seek to keep ourselves with all simplicity, innocence,
and openness in the presence of God, so as we are, and as he forms and places us.

"`O God! is it possible, that a rational creature, even a believing soul,
can dissemble before your all-seeing eye?
Who could believe it, did not melancholy experience too often prove it!
Alas, that miserable self-working, by which sincere souls stand most in their own light,
so that they are unable to perceive the folly of such an assumed deportment!
Lord, deliver them all, and your servant likewise from it;
by your strict light and judgment,
take away all such folds and coverings from our hearts;
bind the hands and feet of our imperfect self-working,
and anatomize our inmost souls with the two-edged sword of your living word,
and lay our very entrails and our inmost souls naked and
open to the light of your health-bringing countenance.
Make us simple and peaceable children before you,
and place us yourself in that form and figure, in which you prefer to see us,
till we are all changed from glory to glory, into the original image of your resemblance,
by your Spirit!
Amen.`"

VIII.
When we observe anything good in another, or when we read or hear something,
or otherwise receive light and insight into any good
disposition or state of the inward life,
and fix our imagination strongly upon it, without the guidance and grace of God, and,
as it were, establish ourselves in it,
before God translates us into it--we have not the reality
and substance of that particular good or state,
but only the form of it.

All that we see, read, hear,
or consider with ardent desire and strong devotional feelings,
impresses its form or image in our minds, but not its substance, unless faith,
as the inward hungering desire of the soul, lays hold of the substance at the same time.
Hence it is, that he who associates frequently with,
and takes pleasure in the society of pious people, often assumes, unconsciously,
many of their expressions, habits, demeanor, and opinions, which is not always improper,
but still it is only a form, an affectation and imitation, if he do not,
at the same time, inwardly possess the substance of it.

In the same way, we may sometimes read of others,
or of much more elevated states of the inward life than that in which we walk,
or of such into which the Lord has not yet introduced us,
and form to ourselves a conception, image, or idea of them.
Were this done frequently and with strong devotional feelings,
we should find what was read, so deeply and lively impressed and expressed within us,
that we might easily be led to imagine,
that we were in possession of the substance of these states,
while we had only the image of them.
In this way, for instance, one who is not yet dead to himself, or quite a novice,
might dangerously deceive himself, were he to read much of passive prayer,
or of exalted states;
and he to whom God grants this noble gift of prayer (either as a foretaste,
or in a more permanent manner,) and gives him to sit with Mary at his feet,
would on the contrary, occasion himself much unavailing or injurious distress,
were he with fervent devotion to read much upon active prayer.
In the same manner, one who enjoys much sweet and susceptible devotion,
might imagine himself in the contemplative state;
and a contemplative individual might confuse and distress
himself if he heard or read much of severe trials,
painful sufferings, and purifying dispensations.

Hence it is not profitable for one who is not well established in the
state and path in which God designs more particularly to lead him,
to read a number and variety of books, and associate with all kinds of people,
however good and excellent they may be in themselves;
but rather keep chiefly to such good men, through whose medium he receives power,
unction, and grace for devotion and recollection;
such as in some measure accord with his particular calling,
and the way in which he is led, entering as it were, without compulsion,
and with a secret delight into the mind, and thus making it sufficiently evident,
that they are suitable for him, at least at the time.
For although the individual must love all the children of God,
and may associate with them; and though he be not forbidden from reading other books,
which treat of the inward way--yet it is well, when this is done with moderation,
and not with too strong devotional feelings, in order that the mind may not be disturbed,
unsettled, nor filled with imagery.
He that walks through a desert by an unknown path, must not always look aside,
nor wish to examine every byway, if he be willing to avoid going astray.

IX. When we receive in our minds any particular impression, invigoration, sweetness,
unction, and peace from God, or any other grace and divine communication,
and seek to retain or augment it by our own efforts, or even from self-love;
or when we strive, by our own exertions to excite them within us,
and to experience something of the kind--it is all a production of our own,
which only obstructs our progress; and were we even to succeed in it,
according to our own ideas, yet all that is brought about, is something merely human,
and not divine; an image, a shadow, and no reality.

"`Teach me, O Lord! to live in all resignation and childlike dependance upon you,
that I may receive, with humble thankfulness, what you give; but neither seize, desire,
nor seek to retain what you do not give nor permit me to keep.
O that I might be in your hand like yielding wax,
which lets itself be moulded into every form at pleasure,
and takes no other shape than that which the master gives it!
I will be as you make me, and not otherwise;
and willingly continue devoid of that which you either do not give,
or after having given it, take away again, that so I may rest alone in you,
and in your sacred good pleasure.`"

X+++.+++ Only that which passes in the spirit, in the inmost soul--that which is there done,
suffered, experienced, and enjoyed, is, properly speaking, substantial;
since it proceeds more immediately from God,
and takes place in the most noble and essential part of man; but all besides,
all that passes in the powers of the soul, the inward or outward senses, etc.,
however good, useful, and necessary it may be of its kind and in its season,
yet when compared with the former, it is only the form and not the power.

How good and profitable, yea how necessary, are frequently the susceptible,
sensible sweetnesses, refreshments, and delights in good and divine things,
and other similar gracious gifts, to tear us away from the false enjoyments of sin,
and the transitory pleasures of this world! but how obstructive
and injurious are these good and useful things,
when we take pleasure in them,
and do not really restore everything to God when we stop short there,
and wish to erect our tabernacles in such an agreeable place
when we do not regard these things as the gifts of God,
but as God himself,
and the sensible pleasure we enjoy in the reception of these effusions of divine goodness,
as the real and essential union with him!
Is not this also taking the shadow for the substance,
or at least the blossom for the fruit--embracing Leah instead of Rachel,
and reckoning seven years too soon?
(Gen. 29:25-27) That which is sensible has certainly
some resemblance to that which is really spiritual;
but they are not therefore one and the same thing.

Finally.
We may also observe on this subject, that all our inward acts of prayer and devotion;
of collectedness, humiliation, resignation, adoration, and love,
in so far as they proceed solely from ourselves in short,
all that is not God nor God`'s work in us, when viewed in its proper light,
is something self-made, and only a form but not the substance of godliness.

When an individual, by passing through many trials and paths of humiliation,
is in some measure purified, and hence is permitted to experience in his center,
the pure and substantial operation of God,
everything that he had previously done or experienced,
even his most inward and simple activity in communion with God,
notwithstanding the grace that cooperated with it, then appears sensual, outward,
and imperfect, as something affected and not real, and as something human, mixed,
and of no value.
Yet that which preceded this state is not to be altogether rejected as evil,
or even to be disesteemed; much less ought it to be regarded in this light,
with reference to other seeking souls,
who perhaps may not have experienced similar purely divine operations.
For the soul that experiences them,
regards them not as they are good in their kind and season,
but as they are in comparison with the sublimity
and purity of the substantial operation of God,
which the man then experiences, with reference to which, as before said,
all appears to him mean and unsubstantial.
Such a judgment is good and proper for himself, but not always good and useful for others.

It is scarcely credible how feeble, worthless, and faulty is all that we do,
even that which is most inward and spiritual, in so far as it proceeds from ourselves.
It is therefore very advisable for a devout individual, in his interaction with God,
gradually to learn how to cease from his own fleshly works,
that he may keep a Sabbath to the Lord, and let him work in him by his Spirit;
and when in advancing further in the experience of the pure operation of divine influence,
he perceives a secret displeasure and disgust at his own works,
and on the contrary a peaceful inclination to inward passiveness,
that he should resign himself, without apprehending any danger,
to this guidance of divine Wisdom.

But lest any unmortified person should from hence derive
occasion for a state of religious apathy and false detachment,
reference may be made to what has been already said in the preceding pages,
and the following general rule may also be observed,
except in an extraordinary state of suffering--that as soon as God works,
we must be passive; and when we are not conscious of his operation, we must wait for it,
as before said, in a state of sacred calm and solemnity in his presence.
It is, however, not advisable to be altogether quiet at such times, and not do anything.
We may, nay, we must work at such times, when grace gives us liberty to do so,
but as our state may require, altogether simply and fervently,
with the heart and affections, meekly and resignedly as in the presence of God,
and ready, at the least hint or consciousness of his operation, to be passive,
and make room for him.

"`O Lord, you all-sufficient and infinite Being, the supreme Being, the sole Being, yea,
more than Being; You alone can say with effect, I am;
and this '`I am`' is so unlimited and undoubtedly true, that no oath can be found,
which places the truth more beyond all doubt,
than when this word proceeds from your mouth, '`I am.`' '`I live.`'

"`Yea, amen! you are!
My spirit bows before you, and my inmost soul confesses unto you that you are.
How happy do I esteem myself that you are, and that you can not cease to be!
How blessed am I, in knowing that God is, and that I can make this confession,
that God is!
Hear it all you creatures, God is!
I rejoice, O my God, that you are; it delights me that you are.
What a blessed and happy thing it is that you are so good, that you are,
and that you are he, whom you are!
I had rather that I were not, and that all things were not, than that you should not be.

"`Yet what am I, and what are all things?
Am I in reality, and is all in reality?
What is this I? What is this all?
We are only because you are, and because you will that we should be;
poor diminutive beings, that in comparison with you, and in the presence of your Being,
are a form and a shadow, and not worthy to be called a being.
My being, and that of all things vanishes, as it were, before your Being, much sooner,
and in a greater degree, than in the full blaze of the sun,
which is so overpowered by the greater light, that it is as though it were not.
O that you would thus overcome and annihilate me,
and that the sight of you might thus supersede, and as it were, extinguish me;
your grandeur, my meanness; your immense light, my twinkling light, yea, my obscurity;
your most pure operation, my defective working; your all, my nothing!

"`I am only a form, a wretched shadow, when you are not in me, and I in you;
when you are not the basis and the being of my being.
All that I know, and all I contemplate, is only a self-created, lifeless nonentity;
or at least an uncertain image, an unsatisfying, transient form and shadow,
if you yourself do not enlighten me, and if you do not grant me yourself to contemplate.
O you solely substantial truth! all that I seek, all that I love,
all that I possess is only a shadow and semblance, but no reality, if I do not seek you,
and love you, and possess you, O, you who are the solely substantial good, the joy,
the delight, and the glory of my soul! all my works, yea,
every motion and effort of my internal and external powers, are shadow and not substance,
unless you yourself are the origin and mover of them, O you original,
solely essential good, and infinitely prolific life!

"`But what do I say?
Without you, I am not only a form and a shadow, but a wretched and horrible monster;
and when I work of myself, all my works, however good and holy they may appear,
are hateful, nay even sinful in your sight; not only because they proceed from me,
who am altogether sinful and corrupt; but also because I seek, please,
and exalt myself in all things, under the most believable pretexts and appearances,
and ascribe to myself the glory which most justly belongs to you.
O what a dreadful thing is self!
I justly abhor myself, when I behold myself in the immediate presence of your purity.
Self pervades me; I am utter selfishness;
all my outward and inward motions are selfishness; all my virtues as, proceeding from me,
are selfish and impure in your sight.

"`O that I might be no more, nor have any longer in myself, either life,
or understanding, or will, or thought, or any other motion; and that you, my God,
my Jesus, might be and work all in me!
Let that, O Lord! which you yourself do not speak and work in me,
be forever silent and cease.
Condemn and destroy in me, all which you are not, and which is not you.
Take entire possession of the place which I now occupy and do in me and through me,
what is pleasing in your sight.
Let me exist no more, but you alone be all in all;
and thus do you lead me entirely out of myself, and of all that belongs to me,
into you O my God, my origin and my end!
Then shall I no longer be in a state of non-existence and appearance,
but in a state of reality, and be delivered from every evil,
to the eternal glory of your name!
Amen.`"
