[short="True Wisdom"]
== True Wisdom, or Communion with God and Ourselves Alone

[.chapter-subtitle--blurb]
"`Think that God and yourself are alone in the world;
and so shall you possess great peace of heart.`" --Thomas a Kempis

[.alt.centered]
=== True Wisdom

I+++.+++ Nothing is by nature more unknown to us than God and ourselves;
we are occupied and concerned about other objects
and things which are irrelevant and unnecessary,
but we forget God and our own souls.

Man is become so devoid of understanding by his melancholy fall,
that he is wholly turned away from God,
with his affections as well as with his cares and occupations,
which are entirely directed to vain and worthless outward things.
Nay, his folly and distraction of the senses go so far,
that in consequence of his ardent and constant application
and attention to the trifling concerns without him,
which contribute nothing to his improvement or true happiness,
but are even an impediment to it and dangerous to him; he entirely forgets and neglects,
to his temporal and eternal woe, not only God, but himself also--that is,
his soul and its welfare.

Is it not surprising to see how rational creatures so wretchedly immerse
and bury their noble faculties in the visible things of this world,
and that although they generally know and acknowledge
that the latter are transitory things,
which they must at length most certainly forsake;
yet they allow themselves to be so engrossed by the desire, enjoyment, care,
and consideration of such vanities, that they stagger about like drunkards or madmen,
and imagine they have accomplished some mighty work,
when all happens according to their wish in the world.

Every fool has his own puppet and foolish fancy.
One man busies himself with honor and dignity, another with money and property,
a third with pleasure and sensual gratification.
They think and talk of buying and selling, of houses and gardens,
of furniture and apparel, of eating and drinking, and of every novelty that occurs;
and this not merely as need may require, and in a cursory manner,
as ought reasonably to be the case, but with their whole attention,
even as if they were matters of the greatest importance.

Their hearts and heads,
their mouths and hands are filled from morning till night with external things;
it is only on God and the state of their souls that they never think,
or at least not in the manner they ought; and their actions plainly evidence,
that such subjects are not considered by them as
of equal importance and necessity with other things,
because they leave themselves neither time nor space for them--nay,
they occasionally undertake some vain or worthless employment on purpose,
or resort to gay and mirthful society.
And these things and the like, they term "`killing time.`"
For since the poor creatures are ignorant of the great and solely
important work and business for which this life is given them,
they are also unconscious how highly necessary every moment of it is to us.
They say, they must divert themselves a little;
while alas! the mind is already so lamentably diverted and turned aside,
that it is much more highly necessary to sit down quietly,
to abstract all their ardor and attention from external things,
and apply them for once to the consideration of themselves.

Hence it is also,
that although the grace of God may inwardly announce itself with its reproofs,
yet the constant confusion and aberration of the mind towards outward objects,
never allows it to become truly serious concerning itself,
for the purpose of examining the state of the soul, with earnest attention and sincerity,
in the presence of God,
nor be concerned about that which can alone avail in the hour of need and death.
Ah, what must be the sensations of such poor spirits,
when they must eventually close their eyes forever upon every beloved object;
when roused by the stern voice of death, they at length come to reflection,
open their eyes, and experience too late,
that the world with all its lusts is vanished like a shadow,
and that they possess nothing more of all their highly
prized trifles and delicious dreams,
than the empty and perturbing images of them!
And in this lamentably blind and senseless state, almost the whole world,
great and little, rich and poor, learned and illiterate, pass their lives.

I say also the learned of this world;^
footnote:[Reference is here made to those learned men,
who by dry speculation and the fertile efforts of their perverted reason,
think to acquire, without divine illumination, the knowledge of God, and his truth;
who lose their time in learning and investigating so many worthless subtleties,
needless opinions, external events, and a variety of minor sciences,
which are of no avail with regard to the principal thing.
In other respects true learning and the learned, who are at the same time pious, meek,
and lowly of heart, are to be highly esteemed.
See Kempis, book I. cap. 2 and 3.]
even those among them,
who take the precedence of others in their application
to the study of spiritual and divine things,
for the most part, no wiser,
and continue equally as blind and estranged from
God and as ignorant of themselves as the rest,
although all they do is meant to have reference to God and the salvation of souls.
How vain and unprofitable, nay even detrimental,
are the greater part of their occupations!
Only look at the unnecessary prolixity and wonderful
preparation they make before they come to the point!
It seems to me just as absurd, or even more so than if a person,
who intended traveling to Rome,
were to imagine he must previously study all the voyages and travels, not only to Rome,
but to every part of the world, and a regular conception of them in his memory,
but at the same time never set out on his journey, meanwhile imagining,
that he had made much progress in it,
although he remained sitting quietly at home as before.

It is often the case, that many good things are introduced into the head,
but not into the heart and the practice.
It is just as if these things had no reference to such persons,
and that they need only know them and talk about them.
And thus with all their labor, investigation, controversy,
and meditation on divine things, they never arrive at themselves, and much less at God;
but are constantly running outwardly about themselves and the thing itself; while,
by the various and violent efforts of the understanding
and the continual distraction of the mind,
the intention becomes, on the contrary,
more and more diversified and absorbed in self-conceit,
and hence the individual becomes more and more unfit
for paying attention to his own heart,
to God, and to the inward operations of his grace.
They make a great noise, and quarrel about the shell,
while the simple quietly carry away the kernel.
Yet such characters think, nevertheless, that they act more wisely than others,
and that they have well applied their time and strength in this manner.
But alas! when their most important and serious studies
and employments are calmly viewed in the presence of God,
what is it all but vanity of vanities, and vexation of spirit;
seeing that it avails nothing to true sanctification and fellowship with God.

The Most High laughs at all the artificial imagery of the wise of this world;
and they themselves, when death and judgment shall call them, must eventually,
with shame and grief,
lament their folly in having spent the valuable time of
their short life in so many needless and childish things,
and in having disturbed and consumed their noble mental powers by them,
which were given us of God, for higher objects.^
footnote:[Of this, the learned Hugo Grotius is an example,
who though a towering figure in philosophy, political theory,
law and associated fields during the seventeenth century, on his death bed,
exclaimed, "`I have spent all my life in ingeniously trifling!`"
His last words were purported to be, "`By understanding many things,
I have accomplished nothing.`" --Note of the Editor.]
Would to God, that they would at length become wise,
and penitentially seek again to forget what they have learnt, with so much loss of time,
in order to know nothing but Christ and him crucified.

But to come a little closer to the point.
How far and estranged from God and their own hearts are, for the most part,
even those who are _called!_
How ill do we keep watch over our own hearts!
How little do we remain at home, to converse with God and ourselves,
and forsaking everything else, make this our sole, our constant,
and our chief employment!
O how much is it to be regretted,
that we let ourselves be so easily and variously
allured and diverted by the subtlety of the adversary,
from the great work to other matters and minor points; from God and our interior,
to other objects and that which is external!

How often do we let our thoughts and senses rove about to
needless (I will not say vain and evil) things!
How frequently do we immerse and entangle our minds
in the external concerns of the present life!
How inquisitive are we to hear and talk about all that happens,
and of what this or that person is doing, which rarely concerns us nor can profit us!
How lamentable is the pernicious custom that well meaning persons have on coming together,
of speaking and judging so readily and frequently of others!

And what else can result from all this, but restlessness, obscurity,
and coldness of heart, dissipation of thought, irreverence,
and estrangement from God and from that which is internal?
Ah, I fear that many a one, in consequence of this trifling,
is so unacquainted with God and himself,
that he knows better what a hundred others are doing,
than what passes in his own heart and is wrought in it by God!

O how unwillingly do we come to ourselves!
If there be many who have received a little light from God,
so as in some measure to perceive the universal corruption,
which reigns in themselves and others, or if they possess any insight into,
or impression of any particular truth,
the subtle serpent immediately hastens there to lead the mind away from itself, outwards,
to others; so that the individual employs that light and grace,
which was only bestowed that he might know and amend himself, to regard others,
and forget himself, to judge of others, to be zealous against others,
and to endeavor to convert others,
while he himself remains inwardly in his own wretchedness and corruption,
generally without being conscious of it.
For while he can see and judge of everything so acutely and minutely in others,
it seems to him as if he himself were not in much danger.
In conjunction with this, there are a variety of arguable pretenses for acting thus;
such as, that he must let his light shine, and employ his talent;
that he is zealous for the glory of God, and is under obligation to reprove sin;
but meanwhile he does not perceive the intention of the adversary,
who only seeks to direct the mind outwards,
and to involve it in disturbance and dissipation.

There are again others, who, desirous of making sure of their purpose,
practice a variety of outward means and external devotions.
They pray, they hear, they read, they meditate, they associate with good people,
and the like; which would all be good and profitable,
if such exercises were only employed in a proper manner, and to a proper end.
But many lay so much stress upon the _means,_ that they lose sight of the _end,_
and entirely neglect it;
and although God has ordained and granted us such an excellent guide,
that by its means we might be brought back from dissipating
our senses with external things,
to ourselves, to our interior, and his true worship,
in spirit and in truth--yet it becomes to many a real impediment,
because they cleave so closely to it, that the senses are kept in continual distraction,
and the influences of grace are thus exhausted; and how is it possible for those,
whose senses and reason are in continual action and agitation,
to attain to a thorough knowledge of themselves, and to fellowship with God;
since they do not seek, even in prayer,
to attain to true composure and collectedness of heart;
but have constantly so much to do, to tell, and to complain of to God, that the Lord,
so to speak, has neither time nor place to address a word to them in reply.
(Ps. 85:8)

Another stratagem of the arch-deceiver to hinder and restrain
the well-meaning in that which is solely necessary,
is, when he excites them to an immoderate exertion, investigation,
and speculation of presumptuous reason,
by which they are often entangled in all manner of
unprofitable controversies in the theory,
outward ceremonies, and secondary considerations,
or to subtle sophistry and particular opinions.
Such a one then frequently seeks, without divine direction and illumination,
to fathom and comprehend, with his reason, the deepest mysteries;
and many a one often admires his own light and progress,
when he has found out or agreed to something new, by which his soul is not made better,
and which will not be inquired for at the last day.
And there are many, who devote their whole attention and application to such-like things,
and thus imperceptibly waste their strength and the invaluable day of grace.
For, because all they do seems to aim at that which is spiritual,
the danger is not observed; add to which,
reason finds its life and pleasure in such employments,
and they are much easier to nature, than following Jesus, the Savior,
in affliction and the renunciation of all things.

And thus one man is kept in a more obvious, and another in a more hidden manner,
in a state of dissipation of thought, multiplicity, and mental confusion,
although they often do not think so themselves,
and even pass for very pious characters with others.
The Most High knows how rare those are, who become truly sober,
and come to themselves--who seek to turn away their hearts
and minds from all that is and occurs without them,
that they may walk and commune alone with God in the Spirit.
Hence it is also,
that the generality of awakened souls either live in a state of frigid security,
or of believable zeal and outward piety,
or else in continually lamenting and complaining,
without making true progress in sanctification;
and instead of enjoying delightful freedom and profound peace in communion with God,
continue inwardly oppressed with heavy bondage.
Nor is it wonderful, that to many on their sick and dying beds,
God and eternity appear so strange, dark, and dreadful;
since their minds are so set upon outward things,
and they have so little accustomed themselves to
become properly acquainted with God and eternity.
O the lamentable blindness of the human race!

But blessed and truly wise are they who solely exercise themselves,
with all their hearts, in the one thing needful; and without stopping short with others,
seek so to live here as if they were alone with God in the world.
This is the shortest and easiest way to attain to a thorough, genuine,
and habitual holiness and peace of mind.
But in order that, while writing this,
and perceiving the lamentable neglect of this beautiful exercise in others,
I may not forget myself, and act as foolishly as they, I will now turn to my own soul,
and give myself some additional mementos, how I desire to walk with the Lord,
by his grace, in future.
Yet still I should be glad,
if every reader regarded and used them as if they concerned him,
and were intended for himself alone; in acting thus,
it would certainly be well with us all.

[.alt.centered]
=== II. Counsel for the Soul

Therefore bid eternally farewell, O my soul, and you that read this,
to the vanities of this world, which in a little while, shall vanish like a dream.

All that the world can offer you is not worthy of a single look.

What does the rich man (Luke 16:19) now possess of his pomp and pleasures?
And what would it avail you,
supposing you had enjoyed thirty or forty years of worldly gratification and splendor?

Vanity of vanities!
You seek in vain outside of you, that which you need; it is inwardly, in your heart,
that the true good, and your glory and felicity may be found.

Close your heart and senses against all that is and occurs out of you:
they are all foreign matters that do not concern you.

Do not pay much attention to external things, nor let that be a hindrance to you,
which cannot assist you on your journey to eternity.

Pass through everything unmoved, like a stranger and pilgrim, whose heart, thoughts,
and whole citizenship is in heaven.

Seek to become inwardly a little innocent child, that finds fault with nothing,
and lets all the world act and speak of it, even in its presence, as they please,
without regarding it, or letting itself be troubled by it.

Cherish true collectedness, by the teaching of the Spirit,
and accustom yourself to live and dwell within yourself,
even as you are by nature inclined to live and move out of yourself.

Let your constant employment be to abide with yourself,
and so to walk with the Lord in the secret of your spirit,
as if you were alone with him in the world.

To this end, your Savior Jesus came and sojourned in the flesh,
that he might help you out again, and lead you home to God, and to communion with him.

But he possessed nothing here of his own; he only passed through;
even as he proceeded forth from the Father, and came into this world,
so he also hastened to leave the world and go to his Father.
(John 16:28) Follow him in this respect.

By his blood he has again reconciled you, who were under the curse, to God,
opened his paternal heart to you, and now he stands at your heart,
and beseeches you in a thousand different ways, to be reconciled unto God,
(2 Cor. 5:20) and receive this best friend into your heart.

The Savior seeks you and your friendship so cordially and sincerely,
that he died for you, to the end that, whether waking or sleeping,
you might live in intimate communion with him.
(1 Thess. 5:10)

Therefore apprehend this truth in simple faith;
and regard God as the confidential and secret friend of your soul,
whose delights are with the children of men,
and who is willing to converse with you in spirit, and to have fellowship with you.

The eyes of your God are upon you; he thinks incessantly of you;
therefore let the inmost thoughts of your heart be also directed towards him,
and do not wander in the senses and among created things.

Remember that all your treasure and your best friend is with you internally,
and will gladly hold converse with you; therefore why would you run out,
and leave him alone?

Ah, who would not willingly forget every creature for the sake of such a God!

Let it seem to you as if you were traveling in the company of a kind and beloved friend,
through a foreign land, and a desert wilderness.

From cordial love to this intimate friend of your soul, do all, suffer all,
and assent to all that befalls you in this world, be it little or much.

Deny yourself, for his love`'s sake,
and die to every lust of the flesh and sense--to your excessive, busy,
and self-complacent reason,
and also to secret attachment and false delight in anything out of God.

Let no lust or sin be so dear to you, and nothing be fixed so firmly in your heart,
as that you would not, for the Lord`'s sake, immediately and willingly part with it.

If others be rich and renowned, honored and learned, live in pleasure, ease,
and joy--if one places his gratification and comfort in this thing, and another in that,
yet let God alone be enough for you.

That which is to others a transitory good, and a needy creature,
shall the immutably all-sufficient God be to you in your heart.

For the sake of his love, deny your own will, your self-love,
and self-complacency in all things; in short, deny yourself wherever you find yourself.

And O how much of this _self_ will you find,
when you have accustomed yourself to remain near yourself, and near your God!

Do not pay much attention to your body; it is of no value; the food of worms;
it is corrupt,
full of evil motions and desires which often obscure and obstruct the spirit.

You must regard your body in such a manner, and act as reservedly towards it,
as a master towards his servant.

Govern your body wisely; and do not, under pretense of necessity,
give it more than is proper.

He that is tender of his body, and seeks so many things for its convenience,
will never be truly collected and spiritually minded.

Do not make much to do,
when any inconvenience and suffering or disappointment happens to you.

Seek with God`'s grace, to endure all outward and inward sufferings with serenity,
patience, and meekness from love to your Savior.

Yea, embrace the cross, and every species of adversity, and cordially love it;
for nothing is more profitable to you than dying to self,
and being detached from everything in order to approach near unto God.

Continually dying in such a manner to the world and yourself,
and thus living with God in secret, is the true imitation of Christ.
In this consists the sum and substance of christianity.

This ought to be your sole-important,
your only and daily business here on earth--this the sole aim,
which you ought to have continually in view in all things,
and to which everything else should tend.

Exercise yourself in this chief concern,
with simplicity and without making any great circuit and preparation.

Receive and use everything that may assist you in this, whatever it may be,
with humility and gratitude.

But do not entangle yourself in anything, attach yourself to nothing,
stop not at anything except the accomplishment of this chief concern.

Let Martha trouble herself about many things; this one thing alone is needful,
and continually so, which can alone avail and solace in time of trouble and death,
when all besides, however seemingly important, will be taken from you.
Therefore make all things tend directly to this one thing.

What you know, hear, or see of what is godly,
bring immediately from the head into the heart, that is,
seek to make it useful to yourself alone, while endeavoring to exercise yourself in it,
or to be otherwise awakened and strengthened by it;
but not merely for the sake of knowing it and of talking to others about it.

Whatever may befall you in the world, whether inwardly or outwardly,
receive it all with simplicity as from the Lord,
without regarding the instrument or the circumstances attending it; only seek,
in and by all things, to advance yourself in the main thing--that is,
in the knowledge and mortification of yourself, and in fellowship with God.

Do not make much ado about your piety, your self-denial,
your inward feelings or experience.
Let your secret remain between you and your God.

Let it suffice you that God knows what is in you;
for it is generally too much for us to know the good that is within us,
which often no longer continues good when we are able to see it in ourselves.

He that lives in silent attention to his heart, in secret with God,
dies a thousand deaths, and often enjoys unspeakable delight and blessedness,
without making much noise about it.

Do not seek to be seen and known by others.

Strive to live in this world, as much as your station and vocation permit,
as a pilgrim or a stranger, of whom little is known, heard, or spoken,
and who likewise desires to know and bear nothing but his God alone,
and speaks with none so gladly as with his God.

Be afraid when you are known and praised; but on the contrary, rejoice,
when you are forgotten and despised; for by this,
the road to much danger and distraction is blocked up,
and you gain so much more time and opportunity to abide in yourself,
and to walk alone with God.

Seek only to stand well inwardly with God;
it is then of little consequence how it fares with you in other respects,
or what others think or speak of you.

Do not unnecessarily associate much with the men of this world,
but when you are and must be with them,
strive to keep yourself inwardly so as if you were with God alone.

Be familiar with very few,
and only with such as you have found to be serviceable in strengthening, exciting,
and promoting your progress in the principal thing, lest under the appearance of good,
you be allured outward from God and your interior,
and your little precious time be stolen from you by your friends.

Associate only with God and yourself.

Break your will gladly, in order to follow what another thinks right,
when it is not contrary to God.
Ah, how much more easy, peaceful, and profitable it is to obey, than to command!

If your state and vocation do not require it,
do not stop to observe or judge the life and conduct of others.

He that seeks to rectify and amend all that is wrong in the world,
only involves himself in much disturbance and distraction,
and is often of no service either to himself or others.
"`Take heed to yourself.`"

O how peaceably may a soul live, that has no need to look much at others,
and to think of them!

Nevertheless, love all men, be kind to all, and do good to all,
according to your outward and inward circumstances and ability;
but continue at the same time, in holy fear and inward abstraction,
lest you fall into mental dissipation, and be entangled in a multiplicity of affairs.

Love, in particular, all the pious, and esteem them all, even the very meanest of them,
in all sincerity, better than yourself.

Love truth, and that which is good, and thank God for it wherever you find it;
do not however stop at others, but strive yourself to be good also.

Love those likewise, who do not walk in all things as you do;
let everyone go his own way; what is that to you?
_Follow Jesus._

Think no ill of your brother, judge not, be not hasty,
put the best construction upon everything.

If you can amend his obvious faults, do it with meekness and with holy fear,
and immediately return with humility to yourself in your own heart.

Let this alone, O soul, be such a serious and important matter to you,
as to make you apply yourself to it with all your heart.

Exercise yourself in it from morning till night,
and inwardly let it seem to you as if you had nothing else to do in the world.

Allow nothing irrelevant and unnecessary to arrest your progress.
He that seeks to "`keep his heart with all diligence,`"
and follow Jesus in constant self-denial,
finds so much to do and to suffer, that he has no time left to meddle with other matters.

What you have else to do outwardly, perform it, as much as possible, without desire,
care, or anxiety.

Do everything solely in order to accomplish, with humility, the Lord`'s will;
for in this way, you do it to the Lord,
and it will not prejudice you in the one thing needful.

Do not let your attention be directed with too much ardor, or more than is necessary,
to your external employment, that your work be done in a tranquil frame;
and at the same time keep your heart, and continue with the Lord.

Ah, how vain and insignificant is everything besides,
that is done in the world without God!
And what comfort or advantage will you have of all your labor in the hour of death?

Yea, what shall console you in all the troubles of this life,
if you do not always and in all things, strive to have God for your friend?

Soon must you depart hence, and be no more seen.

Of all that you have and see in this world, you can take nothing with you out of it;
all men will forsake you and you must part with all men;
you will then have to do with God alone.

Exercise yourself therefore, from henceforth, in this one thing:
in forsaking all that you must then forsake.

Act and walk with God from henceforth, as if alone with him.

O happy he, that thus lives in calm seclusion with his God,
and solely seeks to become acquainted with him, and with eternity!
To him, death will not come as a thief in the night,
neither need he fear to stand before God.

For as here he lived to the Lord, so shall he also die to the Lord;
and as his life here was hid with Christ in God, so when Christ his life shall appear,
he also shall appear with him in glory.
(Col. 3:3-4)

[.alt.centered]
=== III. The Example of Christ

He that contemplates with a devout and tranquil mind,
the life and conduct of Jesus Christ, from the manger to his death on the cross,
will find impressed and expressed in it the steps which we are to follow,
in a very lively and perfect manner.
We will now briefly notice them.

He, the Savior Jesus, who might without sin, have lived in this world in honor, wealth,
joy, and pleasures, refused to do so, in order that he might give us an example;
but chose rather reproach, poverty, and affliction.
He left Herod and the Pharisees in possession of their state, dignity, wealth,
and conveniences, and lived the most of his time,
with his lowly and despised parents in Nazareth, a very despicable and miserable place,
as an insignificant tradesman, so entirely hidden and quiet,
that it was almost unknown to the world, that an individual resided at Nazareth,
whose name was Jesus.
He could have shone in everything; he was not lacking in understanding, wisdom, gifts,
and divine power.
He could have written the most excellent works upon every spiritual
and natural science which all the world would have admired,
and by which, many thousands, as it appears to us, would have been converted.
But it was not intended that he should shine, neither would he.
Even in his public life, he sought as much as possible to keep his miracles,
his divine dignity and glory concealed,
and fled wherever or whenever he was praised and honored.

He regarded his life here on earth, as a passage through it.
"`I am come into the world,`" said he, "`again I leave the world, and go to the Father.`"
(John 16:28) His sole concern was to be about his Father`'s work,
without troubling himself about other matters, for which he did not come into the world.
And even as during the short space of his public life,
he frequently tore himself from the people, to pray in secret,
and often passed whole nights in solitude and in prayer to God, so it is easy to suppose,
that in his long concealed life at Nazareth, this was no less his dearest,
and most constant, and chief employment.
David and Peter tell us,
that the Savior exercised himself continually in walking before God,
and inwardly rejoicing in him, his heavenly Father.

Thus they introduce him, as saying, "`I have set the Lord always before me;
he is at my right hand, I shall not be moved.
Therefore my heart is glad, and my glory rejoices, etc.`"
(Acts 2:25-26) And his Father did not leave him alone,
because he made it his business to direct his eyes to him,
and always to do that which was pleasing in his sight,
while constantly resigning his will to the will of his Father,
and voluntarily and joyfully taking the most painful sorrows upon himself,
from love to it.

He left likewise, the Scribes and Pharisees to dispute about their particular opinions,
and to drag along, under the burden of their outward devotions and human ordinances,
teaching them on the contrary, by word and conduct, the one thing needful,
of which they still destitute.
And even as he did not mix in the useless controversies of the learned of that day,
neither did he interfere in other things for which he was not sent.

"`Who made me a judge and a divider?`"
(Luke 12:14) was his answer, when they sought to draw him into other matters,
yet he went about, doing good to all.
(Acts 10:38)

He loved those that were simple, poor, and despised; and associated with them gladly,
when they had a desire after God; he was also impartial in his love.
The Samaritan woman was as dear to him as Nicodemus, who was learned in the law;
and not less so, those, who at the same time, were not yet become his followers.
(Luke 9:49-50) He even rebuked his disciples,
for being wroth against those who acted improperly,
(Luke 5:54) nor would he condemn the greatest public sinner.
(John 8:11) The one work for which he came, he meditated upon,
and practiced day and night, with unwearied diligence;
of this his heart and mind was so full, that what he saw or heard of outward things,
served only to lead him to those that were spiritual;
so that he immediately took occasion to speak from them.
(John 4:10)

His doctrine corresponded with his life.
It was, that we should watch and pray always, and without ceasing;
that we should follow him by self-denial, and taking up our daily cross,
without troubling ourselves much about others.
One thing alone was needful; besides which, it would avail a man nothing,
if he gained the whole world.

May Jesus Christ, the true Shepherd of our souls, who has redeemed us from the earth,
and purchased us with his precious blood, but also in having suffered for us,
has left us an example that we should follow his steps, so work upon us, by his Spirit,
that the same mind may be in us, which was in him--that is,
to empty ourselves by thorough mortification, from all love to self, and to the creature,
that we may pass the few days of our pilgrimage in
true abstinence from all transitory enjoyment,
become dead to sin, estranged from the world and ourselves,
but become acquainted and familiar with him and a peaceful eternity;
and that we may follow him blindly, as strangers and pilgrims,
and calmly go forwards with him, through the wilderness of this world,
till we reach our true and eternal home!

Yea, Lord Jesus, turn us, your lost and wandering sheep, to you again,
and we shall return unto you!
Amen.
