== Short Instructions

How to Seek God and the Light of His Countenance.

They looked unto him and were enlightened, and their faces were not ashamed. Ps. 34:5.

Short Instructions.

O man, even you that reads this, stand still awhile,
and seriously consider the noble end for which you were created,
and for which God has placed you in this world!
You were not created for time and the creature, but for God and eternity,
and to employ yourself with God and eternity.
And you are in the world to the end that you may again seek God and his beatifying countenance,
from which you have turned yourself away by sin,
and have become attached to the creature;
in order that you may become thoroughly sanctified and enlightened,
and that God may have joy, delight, peace, and pleasure in you, and you in God.

In this alone lies your temporal and eternal salvation and well-being,
which nothing out of God can give you.
The outward objects of this world can scarcely satisfy your outward man,
during the short period of your toilsome life.
But inwardly, you have a hunger, which cannot be appeased,
and a mind that cannot be satisfied,
except by an all-sufficient and infinitely lovely object, which is God alone,

If therefore,
O soul! you possess a sincere desire again to seek and find your God and his countenance,
take heed that you do not begin it in an improper manner.

God is a spirit, and near your spirit; hence you have no need to run here and there,
or distract yourself with a multitude and variety of exercises,
much less with reasonings and reflections, which only serve to confuse you.
This would rather be the way to remove you still further from God,
and to make you more unfit for the knowledge of him and his truth.

Seek only to become conformed to God in your mind;
you may then infallibly and easily find him and become acquainted with him.
Even as he, who wishes to behold and enjoy the sun,
must place himself in its light--so must you become like unto God,
in order to enjoy real communion with him.
This eternal and inaccessible light is only seen in its own light.
(Ps. 36:9) God is a spiritual, eternal, unlimited, simple, meek, serene,
and exalted Being; now the more you inwardly attain these qualities,
the nearer you approach unto God and become capable of his manifestation and communication.

God is a secluded and spiritual Being, estranged from this outward world, the senses,
and reason.
Therefore if you will find him and see his face,
you must likewise keep yourself with your spirit, love, affection,
and the desires of your heart,
as much as possible separate and estranged from the world and all that is in the world.
Do not voluntarily admit any created object into you,
nor fix your love and affections on any creature out of you.
Avoid all unnecessary diversion and exertion of your senses and reason.
Regard your sensible and rational part as if it were another person,
and continue in spirit with your desires and affections directed towards God within you.
Make yourself very familiar with him in the secret recesses of your spirit,
and be unmindful of what occurs outwardly.

God dwells in himself, in eternity.
He is ever the same; with him there is neither past nor future, but an eternal now.
Therefore, if you will draw near to him and have fellowship with him,
avoid all unnecessary reflections on the past or the future, all your reasonings, cares,
and searchings; and like an innocent infant,
abide with your mind and sense in the present moment with the Lord,
and let him care for you and guide you.

God is a universal, undivided, and unlimited Being, and cannot be comprehended by reason.
He is neither this nor that particular thing, but one and all.^
footnote:[Let it not be supposed that this is anything else than sound reason.
The meaning is, that the particular excellencies of a creature may be divided, measured,
limited, and comprehended; but God is an extremely simple Being.
He is not any particular perfection, but all good, and all perfection, in indivisible,
incomprehensible unity.]
Hence, in order to know God, and to approach near to him,
you must gently divest yourself of all peculiarity,
all your particular limited childish images and thoughts of God,
take your reason captive under the simplicity of faith,
and enter with your spirit into an unlimited universality and serene extension of mind,
without particular object and reflection, especially at the time of prayer.

God is simplicity and purity itself; on which account no one can find or see him,
who is not of a clean and pure heart.
(Matt. 5:8) Therefore seek likewise to become pure and simple in all things.
Be upright and sincere in all things and everywhere, in your actions, speech, thoughts,
and desires.
Let the single eye of your mind look straight to God,
and have him for its object in all things,
without any impure secondary motive or self-seeking,
remote from all blatant or refined hypocrisy, dissimulation, or formality.

Let all your thoughts and actions be such as dare
be seen by the radiant sun of the Divine presence;
and if anything false or impure arise within you against your will, lay it open,
with sincerity and tranquillity, before the Divine presence, and it will disappear.

God is a meek and friendly Being; "`He is love; and he that abides in love,
abides in God, and God in him.`"
(1 John 4:16) Be therefore also meek, friendly,
and kind in your whole conduct and deportment.
Let the wrathful and discordant powers of your nature
be softened by the Spirit of the love of Jesus,
the obduracy of your temper be calmed,
and your obstinate self-will be bent and rendered pliable;
and as often as anything of an opposite nature springs up in you,
immerse yourself immediately in the sweet element of meekness and love.

God is a placid Being, and dwells in a serene eternity.
Therefore your mind must become like a clear and silent streamlet,
in which the glory of God can reflect and portray itself.
Hence you must avoid all disturbance, confusion, and irritation, inwardly and outwardly.
There is nothing in the world deserves being troubled about:
even your past faults must only humble, but not disturb you.
"`God is in his holy temple,
let all that is within you keep silence before him!`"
(Hab. 2:20) Be silent with your lips,
silent with your desires and thoughts, silent as it respects your own activity.
O how profitable and precious is a meek and quiet
spirit in the sight of God! (1 Peter 3:4)

God is a happy, contented, and delightful Being.
Seek therefore to acquire an ever joyful and peaceful spirit; avoid all anxious cares,
vexation, murmuring, and melancholy, which obscure the mind,
and make you unfit for converse with God; turn yourself meekly away from these things,
when you are conscious of anything of the kind in you.

Let your heart be estranged from, and closed against all the world and every creature,
but entirely familiar with and open to God.
Keep a very strict eye upon yourself, your evil lusts, self-love, and self-will;
but towards God, be truly free, childlike, affectionate, and confidential.
Regard him as the friend of your heart, and think nothing but what is purely good of him.
Though everything without fall into confusion,
and though your body be in pain and suffering, and your soul in barrenness and distress;
yet let your spirit be unmoved by it all, placid and serene,
elevated above the accidents of all things, and delighted in and with its God inwardly,
and with his good pleasure outwardly.

If you endeavor to exercise yourself in this manner,
your mind will gradually become more conformed unto God,
and also more and more capable of substantially finding
this all-sufficient and most amiable Good,
and of beholding his beatifying countenance.

In reference to which, I would add the following important remarks.
First.
That because external objects and occupations,
particularly as long as we are not well versed and established in this exercise,
occasion much distraction, and hinder the mind in it more or less,
and put it out of the proper frame; it is highly useful and necessary,
now and then during the day, to appropriate a short time, specially and purposely,
for the wholly divesting ourselves of all visible objects and reflections,
for recollecting ourselves in the presence of God,
and for entering into the requisite state of mind, by the assistance of his grace;
everyone according as his state and outward circumstances will permit.

Secondly.
We must above all things believe and be firmly persuaded,
that all depends upon the mercy of God, and not upon our willing or running.
(Rom. 9:16) Therefore we must not expect to find and see God by our own diligence,
much less by our own efforts and mental exertions.
Our activity in approaching to God must be a wholly inward, gentle, calm,
and peaceful act or inclination of our will, our love, and our heart;
in which it principally depends upon the divine influence
and the secret attraction of the love of God,
to which we must simply attend and follow, and before which,
all our own activity must cease and be silent.
When we perceive that the Lord will elevate or collect, calm or tranquillize us,
or that a profound feeling of satisfaction, a filial reverence for his presence,
or anything of the kind is felt in the center of the soul;
we must fearlessly resign ourselves to his operation, and continue passive in his hands,
in all simplicity and abstraction.

You will then in time experience, that you have not only an outward man, a body, senses,
and reason, which belong to this life, and the objects of time; but also an inward man,
a noble spirit, that has its root and foundation in eternity; and such powers of spirit,
which (independent of all that is,
and happens in the world) are capable of enjoying and beholding God and eternal things,
in a substantial manner, to their complete and real delight and repose.

Your love, your heart, the fiery desire of your soul, would then at length,
(and this is the very end for which we are created
and redeemed,) when emptied of all things,
imbibe and possess the Supreme Good, the infinite Deity, in its boundless capacity.
With all the powers of your love collected into one, you would embrace this Eternal love,
this exalted Being, in the most tender and cordial manner,
as an innocent child its kind mother,
and press him to your heart with the purest familiarity,
and be blissfully embraced by him in return.
You would be enabled to shut yourself up, as it were,
with this intimate friend of your soul, in your inmost closet,
in the center of your heart, far, far from any creature.
In this sweet solitude, through the blissful proximity of this all-sufficient Being,
you would also become in some measure all-sufficient; that is,
you would be so perfectly satisfied, delighted, and contented with your God,
that for all the glory, riches, and pleasures of heaven and earth,
you would not cast a look outwards,
nor esteem them worthy of an inclination of your love;
but in secret you would burn like a seraph, in the purest love of your God;
and under the influence of this gentle flame of love, become wholly kind, meek,
and amiable, yea love itself.

Your pure understanding, the eye of your mind,
would be turned inwards and away from every other object, and enlightened, strengthened,
and elevated in spirit, by the light of eternal wisdom,
in order that it may stand like a cherub, with downcast visage,
and contemplate the face of God, Wisdom itself, the mirror without spot.
In this light you would know light, even truth;
and this very glory of the Lord would in return reflect
itself in your clear and serene center.
(2 Cor. 3:18) Your formless, naked countenance,
and the uncovered countenance of your God, would meet, salute, and embrace each other,
with the most affectionate regards.
You would fix your simplified eye, like a little innocent infant,
upon the countenance of God, steadfastly and joyfully; and he in return,
like a faithful and affectionate parent, would keep his eye directed to you,
by which you would be thoroughly sanctified, and transformed into the same image,
from glory to glory.

Your mind, or intellectual capacity, abstracted from all creature joy, solace,
and delight, would be filled with the purest and most inward joy,
and the profoundest peace.
All your delight, joy, and bliss would be in God, and God in return,
would have his joy and good pleasure in you.
He would rest and dwell in you, as in his serene throne of peace; and your spirit,
that had so long gone astray, like an outcast orphan in a foreign land,
would also again sweetly repose in its true rest and home,
and lie down in the lap of God, in undisturbed peace,
and hide itself in the stillness of eternity.
In this boundless kingdom of peace,
you would live untouched and undisturbed by the tempests of the affections,
and be secluded from all perturbing joy, grief, fear, and hope,
which might assail your spirit from without.

And thus you would become a clear heaven of the ever blessed triune God,
in which he dwelt, and which he filled with his light, love, and every divine virtue,
and in which he would glorify himself in time and in eternity.

Therefore act no longer such a foolish part,
O you noble creature and image of the eternal God,
as to make your kingly (I will not say divine) spirit and its noble powers,
so shamefully the slaves of the base, beggarly, and worthless creature and vanity,
by the lust of the eye, the lust of the flesh, and the pride of life.
For God has sent his Son in order to redeem you from such bondage,
and to exalt your spirit again to the glorious liberty of the children of God.
Remember, that as it respects your superior part, you are a child of eternity;
God himself is your Father and your home; there must you live and dwell.
The world must be to you a land of banishment, and your body a prison and purgatory.
O lift up therefore, the everlasting doors of your mental powers above nature, sense,
and reason, that the King of Glory, the God of Hosts may enter into you!
