== On Inward Prayer.

Inward or spiritual prayer is an approach of the soul to God, in the name of Jesus,
and an abiding in his presence.

In order to properly understand this approach and put it into practice,
it is especially necessary, as an irreversible basis of the whole matter,
that through grace we possess, cherish,
and exercise a deep impression of the immediate proximity of the presence of our God,
and reflect how near he has approached unto us, in his lovingkindness towards man,
in the name of his Son, Jesus Christ; and that this very approach of God unto us,
is the foundation and procuring cause of our approach to him.

God is essentially present with us, in a manner which is incomprehensible to us.
He fills heaven and earth; in him we live, and move, and have our being.
He is also near our most secret thoughts, inclinations, desires, and intentions;
all our inmost soul lies open in his presence.

But God, as a Spirit, is more especially near to our spirits,
and to the most secret recesses of the heart.
This spirit of ours does not belong to this world, nor to temporal objects;
it was created for God alone, therefore capable of enjoying true fellowship with him.
It may, and it ought to be the temple and sacred residence of the Deity.
Its occupation is, to contemplate, love,
and enjoy this beneficent Being and to repose in him; for this end it was created;
for this it possesses capacity.
God, as a Spirit, is near our spirits, and can only be sought and found there.

This lovely and adorable Being, is not only present with us as God,
but also as our God in Christ Jesus, as God with us, as our Redeemer, Savior,
and our soul`'s true friend, who cares for us, who remembers us in love,
who by his drawing, attracts us to himself, who is willing to dwell in us,
and abide with us eternally, irrespective of our unworthiness and wretchedness,
if we will only open and surrender our hearts to him.
This is a great, evangelical, and fundamental truth,
which we ought deeply to impress upon our mind,
and never allow ourselves to be deprived of it,
because it includes in it the entire foundation of our redemption and salvation.
This I will now briefly demonstrate.

Fallen man, as it respects his inward part, lies bound in darkness and the infernal gulf.
These he bears about with him during life, and these he finds at death,
when dying out of Christ.
God, and his kingdom of love, are during this state, at a distance from him,
and strongly barred against him.

God, in his blissful eternity, had compassion upon him; which compassion,
in his lovingkindness, he made known, in the incarnation, sufferings,
and death of his Son.
When Jesus Christ, our dear Redeemer, shed his blood for us,
the springs of the tender mercy of God towards man were opened;
so that God is now unspeakably near our hearts, in the name of his Son Jesus.
By his death, the veil has been rent, not only in the temple at Jerusalem,
but the way to an eternity of peace and blessedness is now opened up;
so that the kindness, grace, love,
and fellowship of God stand open in the hearts of the vilest sinners,
if they will only come to him; yea, this near friend of man is even beforehand with us.
He stands at the door of our hearts, and knocks in various ways; waits for us,
and desires nothing more, than that the sinner should turn unto him and live.
His message to us now is, "`Repent,
for the kingdom of heaven is at hand!`" and (in Hebrews 10:19-20) "`Having therefore
boldness to enter into the holiest by the blood of Jesus--let us draw near.`"

Now in this approaching or drawing near, true spiritual prayer consists.
I do not here allude to the first approach of a repenting sinner to God,
at his primary conversion, in which he turns, in a general way,
to God and devotes himself to him,
with the sincere determination to live henceforward alone unto him, who died for him,
and rose again.
This preliminary happy step, I necessarily presuppose, and do not speak of it here,
but I refer to the persevering continuance of that approach, in a soul devoted to God.

Those, who are in reality drawn by him, and devoted to him,
cannot possibly rest satisfied with the general dedication of themselves,
which they made at their first awakening;
and although they acknowledge this first conversion, when it has been genuine,
as an eternal memorial of the infinite mercy of God,
yet they cannot be contented with it, but observe, in process of time,
a latent inclination, by which they are more completely drawn away from all other things,
and led and exhorted to set their affections upon God.
They perceive that something noble, entire,
and complete is required of them--their hearts tell them from God,
that he desires to have them solely and wholly for himself.
In some, this feeling is found to be distinct and powerful; in others, weak, obscure,
and general, according as the state of mind is settled or confused.
Happy is the individual that recognizes within him this divine and holy calling,
and surrenders himself to it, childlike, and unconditionally!

This latent inclination above alluded to,
arises from the immediate proximity of God to us in the name of Jesus.
For God, who is love itself, touches our spirits with his love, as a magnet attracts iron.
He draws us to himself, and hence it is,
that our spirits feel such an impulse and tendency,
that they cannot rest satisfied with anything short of God.
If we pay due attention to this, and continue inwardly collected,
removing every obstacle out of the way of the spirit, by the exercise of self-denial,
and follow this impulse, by committing ourselves entirely into the hands of God,
this principle, like an impelling power, will lead the soul to God by love,
even as a stream flows towards the ocean, and as a stone, pendant in the air,
sinks down to the earth, which is its center of attraction.
The exercise of inward prayer is the abiding by this fundamental inclination,
and by this means, approaching and committing ourselves to God in Christ Jesus,
while denying and forsaking everything besides.

Our spirits then become the temples in which the glory of God,
as in the Holiest of Holies, is near unto us.
The altar is the name of Jesus; the sacrifice, our heart, our will, our all.
The love of God which inflames our desires after him, by means of his secret operation,
is the eternal fire, the flames of which are truth and sincerity.
As much of the world, of corruption, and of self remain in us,
so much moisture is there still in the wood and the offering,
which is gradually dried up by the flame.
This flame is that which I previously called an affectionate fundamental inclination;
it manifests itself in the souls of beginners,
and of those who walk through the gloomy paths of suffering and contrition,
by profound sighs and groans.
If the soul is obedient,
it manifests itself by a gentle "`Abba Father!`"
or by something else of a familiar nature,
that ascends like a grateful odor; at length it forms the basis of an abiding peace,
by which the heart and mind are kept in Christ Jesus.
As long as much moisture remains, the fire burns fiercely, and occasions much smoke.
Afterwards, it burns clearer and less intensely, until it becomes an inwardly calm,
and delightful divine heat.

I close with the beautiful words of David, Ps. 65:4,
where he thus eulogizes inward prayer: "`Blessed is the man, whom you choose,
and cause to approach unto you, that he may dwell in your courts.
We shall be satisfied with the goodness of your house, even of your holy temple!`"
