== The Excellent Way of True Love

God is love, and he that dwells in love, dwells in God, and God in him. 1 John 4:16.

I+++.+++ The Exercise of Love.
Nothing is more beautiful, pure, delightful, powerful, and perfect, than love,
for "`God is love.`"
There is no better way in which God can gain possession of the human heart, than by love,
nor can man please God by anything better than love;
for "`Love is the fulfilling of the law.`"
That which man could not,
and which cannot be accomplished by the strictness of the law and all the fear of punishment,
is all easily fulfilled where God commends his love to man in Christ
Jesus--where he proclaims to him forgiveness of his sins,
redemption, and eternal salvation, and allures him by these motives to repentance,
and to love him in return.

Now as the tender compassions of the love of God are again opened to lost man,
in the sweet name of Jesus Immanuel,
and to this hour stand wide open to the poor sinner in his soul,
whether he be conscious of it or not;
eternal love is therefore constantly occupied in the center of our souls,
in offering and recommending itself to us, and in insinuating itself,
and seeking admission into us, in a thousand different ways, for our eternal felicity.
Every good thought and desire that arise in the human heart;
all grief and sorrow for sin, all reproof and admonition,
incitement to prayer and to true godliness, entire resignation to God, and the like,
are the pure effects of this long-suffering love of God.
If the vilest sinner could perceive the thousandth part of it,
he would feel instantaneously compelled to resign himself to this love.

O Love, manifest to sinners that you are love, and they shall all love you and follow you!

Now if an individual is willing to be led to repentance by the goodness and love of God,
let him henceforward believe without hesitation that he cannot
please God better and more easily by any work or exercise,
than by love.

Let him only duly tend and cherish the hidden spark of the love of God in his heart,
by a cordial remembrance of God, by a filial turning to God,
and by simply occupying himself with God and his perfections.

Let him exercise himself in love.
From love to God let him give up all that is most dear to him, and resign himself,
in faith, to this pure love.

Let him rejoice whenever a good opportunity presents itself of doing, denying,
or suffering anything for the love and glory of God.

Let him accustom himself to do everything from love to God, to receive in love,
everything that occurs to him, as from the hand of God, and to endure, in love,
all he has to suffer for the Lord`'s sake.
Everything must be sacrificed to love, by love.

By love the bitterest sufferings become sweet, the most adverse occurrences beneficial,
and the smallest works great and god-like.

Do not suppose that, by this, a sensible and refreshing love is meant;
possessing love and feeling it, do not always go together.

Real and constant love consists in an inward estimation of God;
in knowing and acknowledging him by faith, to be supremely, yea, solely lovely;
and therefore we willingly offer up and resign ourselves, and all that is in our power,
to God, and to his service and glory.

This love, which the Holy Ghost sheds abroad in our hearts,
may exist even in the midst of barrenness, darkness,
and the deepest processes of purification,
which are nothing else than the blessed effects of the pure love of God.

II. Complete Resignation to Love.
Truly, when a sinner can attain to the art of pure love,
so that by an entire abandonment and renunciation of himself,
he resigns himself in sincerity to God,
and leaves him at full liberty to make of him what he pleases, both in time and eternity,
not esteeming nor regarding his own prejudice or advantage, but simply God,
and that he alone may be glorified, loved, and pleased over such a one,
wrath and hell have no more power; but his sins, were they ever so great,
pass away and are sooner consumed than a handful of flax in a burning furnace; yea,
this love makes him holy and god-like.

Now it is true, that we are by nature wholly rooted in sinful self-love,
and so bent by it upon ourselves, that we can neither see, nor love, nor trust in God;
but the Son of God himself must shed abroad this love in our hearts, by his Holy Spirit;
(Rom. 5:5) and he is also willing to do so, having, in his incarnation,
taken our sins upon himself, and through the medium of this pure love,
again fully reconciled us to God.

It is in thus serving God with such a selfless love, that true religion,
properly speaking, consists; while it is much to be lamented,
that even pious people grope about so long, and some even their whole lives,
in anxious attention to and solicitude for themselves,
without an entire renunciation of their own interest, or committing themselves to God,
and seeking after pure love in the heart and countenance of Jesus Christ.
O let us love him, for he has first loved us! (1 John 4:19)

"`O infinite Love!
O adorable Trinity!
Father, source of love, Son, the lovely light, and Holy Spirit, the living flame,
and holy ardor of love!
O God, who are pure and perfect love, you are a burning and consuming fire,
which must consume all that cannot consist with pure love!
O destroy in us, by your adorable flame, all that is contrary to your holiness!
Begin, continue, and perfect here in our souls,
the great work of purification and sanctification, without which,
no man can see your face!

"`Grant us, O Lord! a little of your sensible and ardent love,
to awaken us out of our insensibility and deadly sleep,
and give us a degree of dread of your fearful judgments,
that we may quickly forsake the paths of error!

"`Pour into our hearts a drop of your powerful love,
which can transmute hell into paradise.
Yea, O Lord! do speedily kindle this fire on earth, which you did come to kindle,
and did so much desire that it should burn again;
that the kingdom of your love may be eternally established, and that we may be in you,
in unity of heart, soul, word, and action, one spirit with the Father, Son,
and Holy Ghost, blessed forever!
Amen.`"

III.
On Brotherly Love.
From love to God we derive love towards the brethren, yea, even love to all men.
The former as well as the latter is not a subject which can be taught, or learnt,
or self-produced; both are a fruit and property of the new birth from God,
by which we escape from the element of wrath and darkness,
and are translated into the kingdom of the Son of love,
and become more and more pervaded by the sweet and delightful powers of love,
which emanate from the heart of God.

In the old birth, there may be a soft tenderness, sensual flattery,
and self-loving complacency towards those that please us and behave kindly towards us;
but corrupt nature and self-love is everywhere concealed under it,
and the individual continues, notwithstanding all the appearance of love,
a child of wrath at the bottom, who in reality, loves nothing but himself,
and both God and his neighbor only in reference to himself.

Hence arises that latent and continual restlessness, irritation, suspicion, vexation,
and a thousand other harsh powers, which disturb and distress the poor heart;
first one person and then another being unable to
act so as to please its self-will and haughtiness.
In such a state, all terms of peace, points of union,
and the most solemn obligations are nothing but air-built castles.
If we are not born of love, we cannot love as we ought.
Among the proud, there is always contention.
(Prov. 13:10)

Therefore we must ardently long to be delivered from all such inherent wretchedness,
and to be made partakers of the meek and gentle love of Jesus,
seeing that this eternally loving good is so unspeakably near us, and willingly inclines,
by the Spirit of his love, to him that thus belongs and pants after love.
We must filially resign ourselves to his secret drawing,
unremittingly plunge all our selfishness, all haughty, harsh,
and distrustful feelings towards God and our neighbor, into the love of Christ,
and not grow weary of this humble hungering and waiting,
till Love bestows herself upon us, and pervades us with her divine influences.

Now the more we let ourselves be led by the secret attraction of divine love,
into this state of heartfelt devotedness to God and learn to abide in it,
in love and simplicity--the more we shall imbibe, like an infant at the breast, the pure,
innocent, and tender life of love;
so that our inmost soul is more and more satiated with delight,
and the whole man becomes pliant, amiable, full of, and overflowing with love.

We then experience that true brotherly love is an unconstrained, unaffected,
informal state and work of God, a free motion of the new creature.
In this abyss and element of love, one individual may then find, embrace, bless,
and enjoy another very intimately, to the glory of God.
And because we are baptized in and by this Spirit of the love of Christ to one body,
(1 Cor. 12:13) and have drunk into one spirit,
we enjoy substantial communion with each other, (Phil. 1:19) as well when absent,
as when met together in the name of Jesus.

And even as this pure brotherly love arises from the love of God,
and in a state of placid fervor of heart so it does
not stand in the way of the love of God,
but rather promotes it.
It does not allure us to that which is carnal and to unstable sensuality,
but collects and calms the mind,
and strengthens us in the intention to be wholly for God.

In short, where love is born in the heart, there it manifests its fruits,
that they are of the right sort,
and her whole deportment and behavior towards her
neighbor becomes a living exposition of that,
which the Spirit of God, by the apostle Paul, commends of her,
(1 Cor. 12) and which we here subjoin.

"`Love suffers long.`"
Nature seeks to effect everything instantaneously or gives it up entirely.
If the man does not see an immediate amendment in the mind of another,
he rejects him entirely.
If another cannot immediately apprehend his views and follow his admonitions,
he casts him off.
But real love suffers long; she looks on awhile; she does not disoblige her neighbor;
she can labor long, endure long, amend long, wait long, try long, and try again,
love long, and love again.

She is kind; so that her obliging and amiable deportment, her words and works of love,
rejoice and benefit everyone, and openly show how she devotes herself,
and all that is in her power for the use and enjoyment of others.

Love is not envious, but is willing that others as well as herself, should be, have,
enjoy, and be capable of doing something, whether it be in temporal or spiritual things,
and rejoices at it, as cordially as if she herself had performed it or had to enjoy it.

Love is not rash in judging of others, nor forward, cross,
or spiteful in the company of others, but openhearted and modest;
what she does is done heartily, from a modest and upright intention.

She is not puffed up; she does not proudly pass over others,
she prefers serving and being subject to others.
She does not wish her actions to be seen, nor to receive many thanks for them.
The reason and motive why she loves, is love.
She is her own reward and crown.
Love therefore always thinks others do too much for her,
but that she herself has hitherto done little or nothing.
(Matt. 25:27)

She does not behave herself unseemly, by a harsh demeanor,
when others do not act according to her mind.
Love is like a little child--she is soon pleased.
She is far from putting others to the blush by an improper behavior, reproaches,
or the like; but condescends and adapts herself to the feeblest, the most wretched,
and the poorest individuals, without being ashamed of them.

She seeks not her own, as nature always does, even in her best things.
Real love regards neither her own advantage and convenience,
nor the approbation of others--she puts all to the stake.
If she can only give, gratify, please, and be serviceable to another, she forgets herself.
She is delighted, if he whom she loves, is pleased,
and esteems his temporal or spiritual happiness as her own.

She is not easily provoked, although she may be often improperly treated, vexed, excited,
and even the worst construction put upon her love and her good actions.
If another have fire, she has water enough in her meek fountain to extinguish it,
by a modest and friendly deportment, by silence, and by doing good.
Nor is she excited to anger by the evil she sees in others, but to compassion.

She thinks no ill.
She is not suspicious, she draws no evil and malicious inferences,
nor misinterprets the conduct of another, but rather excuses him,
and explains all for the best, in simplicity of heart, as much as she is able.
She takes an account of the wrong she does to others, and the good they do to her;
but does not regard the good she does to others, and the evil others do to her;
that is all as nothing to her.
She has forgiven and forgotten it unasked.

She rejoices not in iniquity, when others stumble, that she may appear the more pious.
She sees it not willingly, but with grief, when any wrong or injury is done to another.
And should one who is adverse to her, or who had previously censured her,
stumble and disgrace himself, she does not rejoice at it from secret revenge,
but is heartily grieved at it.

She rejoices in the truth, whenever it prospers,
whether in reference to herself or to others.
When she sees many children walking in the truth, when the virtue, piety,
and uprightness of others is known and commended, she rejoices over it with others,
even though she herself should be forgotten and less esteemed on account of it.
She loves truth when she finds it, even were it in her adversaries.

She bears all things.
Nature hides her own evil, and is fond of talking of the faults of her neighbor,
but divine love only sees that which is good in others,
and bides their misery and weaknesses.
She excuses such characters as much as possible, both to herself and to others,
in all simplicity.
She speaks unwillingly of their failings afterwards,
except when it must be done for the improvement of others; that which is good,
is her proper object; hence it is said, she believes all things; because she is good,
faithful, and sincere herself, she gladly believes the best of others.
If she hear good news of her neighbor, she does not seek out many doubts and scruples,
as corrupt reason does.
She does not easily believe evil of others.
In such a case, she requires full certainty.
But because she loves, and wishes that which is good, and that which may glorify God,
she therefore also willingly believes it.

She hopes all things, and does not readily cast away the hope of the amendment of others;
in this hope she prays and labors, as much as she is able.
Though she sees the evil before her,
yet still she hopes and thinks the individual is already sorry for it,
and that he may have already repented of it, or will still do so.
God can restore him again.
He may still become better than she is.
She hopes, where nothing is to be hoped for.

She endures all things;
although she be ridiculed and oppressed for her bearing all things, believing all things,
hoping all things, and always loving, yet she endures it all.
And whatever trials and sufferings may be imposed upon her in her labor of love,
even from those whom she loves, yet she is not weary in her faithfulness and patience,
even though the trial should be of long continuance.
She endures unto the end.
Yea, she is invincible in suffering, and finally is victorious over everything.
For love never fails or falls away; for where should she fall,
since she is already in the deepest abyss of humility, beneath all?
A man may have much of what is good, but if he have not love, it avails nothing,
he falls away again.
Nay, much of what is good must fall away from the pious, that the best--that is,
pure love, may fill its place.
This love never fades, it endures forever; it is pure gold,
it is the life of God in the soul, which is shed abroad in the heart by the Holy Spirit.
Now he that abides in love, abides in God, and God in him, so that he can never fall away.
Amen.
