== Important Rules of conduct

[.chapter-subtitle--blurb]
Addressed to a Society of Christians living together.

The blessing of Jesus, the Savior, be with you,
that your hearts may be filled with grace and heavenly peace, both here and hereafter,
to the glory of his name!
Amen.

Attend with feelings of simplicity, devotion, and good will, and not merely from habit,
to the exhortation which will now be addressed to you, in the Lord`'s name,
and from heartfelt affection.
But let each one also examine himself by it, and not esteem it lightly.

1+++.+++ Remember that your house and your hearts ought
to be a habitation of the Lord Most High.
The Lord Jesus himself will be your superintendent and patron,
and his holy angels your companions; judge therefore yourselves, with what devotion,
serenity, simplicity, and sincerity, you ought to conduct yourselves,
both inwardly and outwardly, in the sacred presence of the Lord,
if you desire that he should abide with you and in you,
and if you wish to continue to participate in his divine favor and blessing,
both as it respects body and soul.

2+++.+++ Your calling is sincerely to forsake the world and its spirit--to
die continually to your corrupt nature and all the life of self,
and to converse night and day with God in your hearts, in the exercise of true prayer.
How holy and blessed is your vocation!
Give yourselves up to it cordially, and with great fidelity.
This is your aim, be this also your constant employment!

3+++.+++ Do not pray merely at certain times, but wherever you are.
And whenever you come together,
strive to keep yourselves in a frame of fervent desire towards God, and in his presence;
just as if each of you were alone in the house with God,
yet without much external show and gesture.
And when anyone wishes to converse with another, be it either when at work,
or on other occasions, let him previously think in his own mind,
"`My brother or sister is praying,
I ought not to disturb him or her,`" in order that all unnecessary conversation,
even on spiritual things, may be as much as possible avoided.

4+++.+++ Again--pray much and speak little.
O let me particularly recommend to you that sacred, gentle, and peaceful silence,
which God and all his saints love so much!
The spirit of loquacity is the bane of all religious society; the extinction of devotion,
occasions confusion of mind, is an abuse of time, and a denial of the divine presence.
Love, obedience, or necessity, must influence the tongue to speak,
else it should continue silent.
Even in spiritual things, edify one another more by a holy walk,
than by a multitude of words.
God dwells only in peaceful souls, and the tongue must be at peace also.
Behold the fruit of sacred silence!
It gives time, strength, collectedness, prayer, liberty, wisdom, the society of God,
and a blessed and peaceful state of mind.

5+++.+++ Love one another in sincerity, as the children of God,
and believe that you are beloved by each other, though nothing of that love,
or even the reverse be manifested.
Let everyone be concerned for his brother, in unfeigned kindness, attention,
and subjection, as though he did it to the Lord, in all sincerity.
Bear one another`'s burdens, both of body and soul, as if they were your own.
Be ever ready to serve each other gladly and in artless humility,
and to wash each other`'s feet, so to speak,
or in the meanest and most laborious offices.

6+++.+++ Remember the important words of Jesus, "`I came not to be ministered unto,
but to minister.`"
Therefore under the consciousness of his own unworthiness,
ought no one to expect the like from others; and in accordance with this sentiment,
we ought never to believe that any creature shows us too little kindness,
or wrongs us too much.
Let everyone really think respecting himself, that he is the most unfaithful,
the most miserable, the most unsuitable, and the meanest of all;
and hence he ought reasonably to desire to be little
thought of and forgotten by all the rest.
Be ready to give way to each other in all things.
Let each one humble himself beneath the other for the Lord`'s sake; by this means,
fervor and peace of heart will be obtained and preserved.

7+++.+++ Avoid all suspicion.
Give no ear amongst you to the accuser of the brethren,
and allow no wrath or bitterness to harbor in your breasts.
Put the best construction upon everything that may
appear offensive to yourselves or to others.
Look only at that which is good in others, in order that you may love it,
thank God for it, and imitate it.
But do not remark their weaknesses, or if you observe them,
commend them to God in prayer, and forget them again immediately,
unless it be your office to remember them.
If anyone be overtaken in a fault or crime against his brother,
let him immediately go and confess his guilt in unfeigned humility.
Satan, by this means, will be trodden down under your feet, mutual love confirmed,
and the favor of God be doubly redirected towards you.

8+++.+++ Seek nothing more than the moderate supply of your bodily needs,
and beware of the subtle deceitfulness of riches.
What have we to do with the world`'s poisonous trash?
Are we not redeemed from the earth, and called to eternity?
O love and exercise that estimable virtue of the inward and outward poverty of Jesus,
who cares for us!
Love, for the Lord`'s sake, that which is little, mean, contemptible, disagreeable,
and burdensome in everything,
in order that you may inwardly live unhindered in communion with God,
and externally rejoice in the society of each other.

9+++.+++ Flee from all selfishness, as the greatest bane of fellowship.
Let no one desire anything, which he would not as willingly grant his brother,
even more readily than himself; for we are called to deny ourselves.
Let none of you possess anything, whether great or small, be it what it may,
which he would not immediately part with, and give to his brother.
If we do not thus divest ourselves of everything which we regard as our own,
we are still idolaters, and no true servants of God,
and must continue destitute of a noble, pure, and peaceful liberty of spirit,
and of an unobstructed approach unto God.

10+++.+++ Let every individual of you believe that the place of your present habitation,
your state and occupation, is that in which God has placed you,
and in which he at present wishes you to continue to serve him,
and is the best adapted for your advancement in true holiness,
which you must not forsake, nor even desire to forsake,
without a clear knowledge of the divine will.
This will compose your minds,
and divest you of a thousand unnecessary scruples
of injurious reflection and distraction of thought,
with which the tempter might otherwise torment you.
This will cause you to regard with other eyes, not only your residence, station,
and occupation, but also all your difficulties, disappointments,
and whatever else you may meet with, receiving all as from the Lord`'s hand,
and bearing it so much the more joyfully.
This will also tend greatly to promote love and peace amongst you.

11+++.+++ But let everyone of you well consider,
and through grace be deeply impressed with the object for
which God has led you individually to this habitation,
which is, that you may serve him in it, and be exercised in sanctification.
You are not placed there, that you may live quietly and at ease,
according to the flesh and self-will,
and serve God according to your own fancy and ideas; but that you may crucify the flesh,
with its affections and lusts--that you may deliver up your carnal nature, sensuality,
reason, self-will, and self-love to judgment and to death,
and thus walk directly contrary to yourselves, and love God in purity and fervency.
It is for this reason, that the Lord has brought you into this house,
that you may strive after it in union of heart and soul,
and that you may assist each other in prayer and in holy life;
for when two or three are met together in Jesus`'s name,
there he is in the midst of them.
Let everyone pay attention, how he exercises himself in this particular;
nor by any means forget it when God purposes to exercise you in it;
but rather eagerly seize every object and opportunity,
which the kind hand of God presents to you, to lay open, attack,
and destroy the above mentioned, and any other symptom of your natural depravity.
Welcome the hour,
when God sends you a dear friend to assist you in overcoming your adversary.
Love such a one very cordially.
He that does not thus seriously resolve to venture his own life,
does not deserve the name of a christian, and will neither live there nor elsewhere,
peaceably, but perplex both himself and others.

12+++.+++ Beware of a dissipated mind and disposition.
In such a state, you will be attacked by a thousand combined and opposite temptations.
Scarcely speak nor determine on anything, as long as your mind is thus distracted,
if you wish to avoid committing faults and creating disturbance;
for you are then in a false light and in the confusion of nature.
Live retired in the center of your hearts with God as innocent children,
who though unable to reason, possess much love and affection; and as such,
suck the breasts of divine love.
You will then find everything good and well as it comes, regardless what others do or say.
Thus you will become all meekness, and kindness towards each other.
In filial confidence towards your heavenly Father, you will then be of good courage,
and experience that his commandments are not difficult.

May God himself grant you grace, wisdom, and strength in all things,
in order that it may with truth be said of you,
"`Behold how good and how pleasant it is for brethren to dwell together in unity;
for there the Lord commands the blessing, even life forevermore.`"
Amen.
