== On Faith and Justification

Many possess the word of truth, who have not the truth of the word.

Faith is an inward conviction of the truth of things invisible and future relating to us.
He that believes from his heart that there is a living and omniscient God in heaven,
and that his word is truth, is possessed of saving faith.

"`Very well,`" will many a one say, "`if that be all, all is right with me,
for this I have believed from my youth up.`"
But do you really believe it from the heart?
This believing from the heart, is the work of the Holy Spirit.
Evidence and show me your faith by your works.
"`What works?`"
some may say; "`Faith saves us, and not works.`"
True, but faith and works belong together, and tread in each others steps;
otherwise we do not really believe that which we say, or think we believe.
For instance, if I say to a person severely wounded, "`My friend,
your wound is dangerous, go instantly to a physician!`"
How do I know that he has believed my warning?
By his really going to the physician, and placing himself under his care.
Say to one perishing with hunger, "`See, there is a rich man yonder,
who readily gives to all who ask him.`"
How are you to know that he believes you?
When he in reality hastens to the rich man and supplicates relief.
If one tells us that our neighbor`'s house is in flames,
and bids us run to extinguish them--when we sit still at the news,
without going to the place, it is evident we do not believe it;
for if we did we should immediately hasten to save whatever we could.

"`What a work the people make,`" says the world, "`what trouble they give themselves,
as if they could merit heaven by their piety!`"
Yes, my friend! did you believe, you would also hasten to save your soul,
for you are that sorely-wounded, poverty-stricken man,
and the dwelling of your soul is already in flames!

Faith is consequently the foundation and mainspring of all good works and holy deeds.
(Heb. 11)

But justifying faith can never be that faith, by which I merely believe I am justified.
Justifying faith consists in this, that a poor and humbled sinner,
believing that he can find forgiveness, help, and salvation in Christ alone,
comes to him, hungering and thirsting,
(John 6:35) accepts him as offered in the gospel, (John 1:12) and to this end,
commits and gives himself up to him with this faith,
justification is inseparably connected, but God gives the assurance of his forgiveness,
in a greater or less degree, earlier or later, as it pleases him,
and is useful to the soul.
It is however not only necessary to believe once, but without intermission;
we must be grounded in the faith, must be kept in the faith, through many changes,
crosses, and trials;
and thus our justification will become more confirmed and more glorious.
(1 Peter 1:6-7; 2 Peter 1:10)

Justification, according to Scripture and experience, is properly fourfold;
which being seldom sufficiently distinguished,
is the cause of so much misunderstanding and controversy.

The first has taken place externally,
and is nevertheless the foundation of all the rest--namely, when Christ as our surety,
stood before the stern tribunal of the insulted Majesty of heaven,
during his sufferings in Gethsemane and on the cross;
and by virtue of his merits and perfect atonement,
was absolved and justified in our stead, at the bar of that tribunal.
Christ himself speaks of this justification (Isaiah 1:8). "`He is near,
that justifies me,`" and in Isaiah 53:8 it is written,
"`He was taken from judgment;`" and Paul says,
(1 Tim. 3:16) "`Christ is justified in the spirit.`"`' See also Rom. 6:10-7.

Now as Adam fell not for himself alone, but being the great progenitor of the human race,
our common head, so all his descendants fell with him.
Thus Christ stood likewise not for himself alone; he was our general representative,
the plant of renown, the man Zemach,^
footnote:["`Whose name is the branch.`"]
the patriarchal head of all the redeemed; and even as he arose justified,
all of them were justified with him.
He our Mediator and surety being justified, so are we also.

And this is so certain and so true, that all true believers can say,
"`If one died and was justified for all, then were all dead, and all justified.
God has made him to be sin for us, who knew no sin,
that we might be made the righteousness of God in him.`"
(2 Cor. 5:19 etc.)

By virtue of this justification of Christ in our stead,
God overlooks the season of ignorance,
(Acts 17:30 etc.) but now commands all men
everywhere to repent and offers unto every man,
through the resurrection of Christ, faith and justification.^
footnote:[Marginal Reading]
He beseeches and invites men by his messengers outwardly, and by his Spirit inwardly;
saying, "`Be reconciled unto God!`" "`Repent and believe,
for the kingdom of heaven is at hand!`"

Adore, admire, and stand amazed at this abyss of divine love, O my soul!
Thus has God loved me, before an atom of my being existed!

What grace!
He gave his Son for me!
I behold him who knew no sin, standing at the bar of divine justice, for my crimes,
and for my debts, which he took upon him as his own,
and paying the forfeit of all my sins, and those of the whole world.
I behold him on the cross, blotting out the hand-writing that was against me.
I behold him, after having entered with his own blood, into the holy place,
return with a full and valid discharge, and with eternal redemption,
while at the same time he offers me his grace and salvation.
Then come, my soul, while you may, and love him who first loved you,
and has made known unto you this great mystery of his will,
into which even angels desire to look!

The second justification takes place in the heart and conscience of a humble,
heavy laden sinner, who comes to Christ with an ardent desire for mercy;
while that which has been accomplished externally and for him,
is appropriated to him by the Holy Spirit; namely, that for the sake of Christ,
all his sins are forgiven him, a clean heart,
a better hope and a freedom of access unto God are granted him.

When a female, miserably poor, and arrested for debt, becomes the wife of some rich man,
all her debts become his, and she stands acquitted at the bar of judgment.
The possessions of her husband now belong to her; but from that moment, her heart,
her will, nay all that she is and has, belongs no more to herself, but to her husband.
In this manner, a true and lively faith unites us to Christ, not merely in idea,
but in reality; and thus we are justified by grace, without works.
But as soon as the soul, like some poverty-stricken female, unites herself, by faith,
with him, then comes to pass what is written, "`He is your Lord;
him only shall you serve.`"
(Ps. 44:11-12) He becomes ours, with all that he is; and we become his,
with all we possess.
(Luke 15:31) From that moment, we are in the way and in a state of salvation,
and from that moment also, in the way and in a state of sanctification, (Eph. 2:10;
Tit. 2:14,6,8).

This justification is the foundation and commencement of godliness in Christ Jesus,
who for this very purpose died for all, "`that they that live,
might live no longer unto themselves, but unto him who died for them and rose again.
(2 Cor. 5:15)

Although this justification may be regarded as a judicial proceeding,
yet we must be careful not to measure the works of God by any human criterion.
Before a human tribunal, hypocrisy may successfully deceive, and a thief be pardoned,
who may still retain as thievish a propensity as before.
With God the case is otherwise.
His judicial sentence is a powerful word, which creates what it pronounces;
it soothes the conscience, and at the same time renews the heart.
When he justifies the ungodly, he also makes him righteous.

The penitent soul has therefore a ground of confidence in itself,
on which it can courageously persevere and proceed.
The certain assurance of the forgiveness of sins
may accompany it in a greater or less degree,
earlier or later, or be entirely lacking according to the good pleasure of God.
This assurance is not absolutely necessary to justification; but an inseparable fruit,
and the surest proof of justification is, that sincerity of heart in Christ,
that hatred of all acknowledged sin,
and a heartfelt desire after and love to him that has loved us and forgiven us.
If this fruit be lacking, justification is also lacking.

This justification continually maintains its place, through the whole course of godliness.
It is, and remains, the groundwork from the beginning to end;
for sins and imperfections continue to arise; and when the children sin through weakness,
they are again reconciled to the Father, through the intercession of Christ.
(1 John 2:1) A growth in sanctification discovers also
more and more of the corruptions of the flesh and spirit,
of self-love, self-conceit, secret reliance on gifts, good works, etc.,
and thus our inward and outward holiness itself requires justification.
Our finest robes must be washed and made white in the blood of the Lamb.
(Rev. 7:14)

The third justification, of which the Holy Scriptures speak,
is chiefly that whereby we are acknowledged as righteous in the sight of others,
and is nothing else than sanctification, so far as it gives testimony,
by its undeniable fruits, that we are in possession of that faith,
which justifies us in the sight of God.
"`Show me your faith by your works,`" says the apostle James.
(2:18) Justifying faith unites us with Christ, as our head and vine,
or groundwork of a new life, this must manifest or justify itself.

Sanctification and its fruits do not justify before
the tribunal of the offended Majesty of heaven.
Even the man after God`'s own heart must here pray,
"`Enter not into judgment with your servant;
for in your sight shall no man living be justified;`" (Ps. 143:2)
but still they justify before the tribunal of the church.
True believers follow after holiness, and gladly do good;
but they are not on this account justified before God;
(1 Cor. 4:4) they cannot lay it to account with God, in order to their justification,
either here or hereafter; nor do they so, but forget it.
(Matt. 6:27-3) But God is not therefore unjust, that he should forget it.
(Heb. 6:10) Their works do not go before them, as if to open the doors of heaven,
but they follow after; (Rev. 14:13) and they shall eat the fruit of their labors.
(Isaiah 3:10) They that are in Christ Jesus, come not into condemnation,
and are justified in Christ Jesus,
according to the judicial sentence of the Divine good pleasure.
(Matt. 24:34, Rom. 2:7)

But still, holiness, with its fruits,
may testify with the conscience to the justification in the sight of God,
received through grace.
If our heart condemns us not, but absolves and attests that we possess an operative love,
we may then rest satisfied and be of good courage.
But this is not the highest tribunal;
neither is the heart at all times infallible and impartial,
either in accusing or excusing.
We ought therefore still to pray with David, although our hearts may excuse us,
"`Search me, O God, and know my heart, try me and know my thoughts,
and see if there be any wicked way in me.`"
(Ps. 139: 23)

In this way a man is justified by works, and not by faith alone.
(James 2:14) "`He only, who does righteousness, is righteous, even as he is righteous.
Whoever thinks otherwise deceives himself.`"
(1 John 3:7) He who is in Christ Jesus by a true faith, evidences by his thoughts,
words, and works, the foundation on which he stands.
Through genuine conversion, we become engrafted into Christ;
and are therefore also planted in the house of the church of God,
that we may flourish in the courts of that temple, whose beauty is holiness.
(Ps. 91:15; 92:5)

Yea, the holy and blameless walk of believers should also
justify them in the sight of the world,
as the epistles of Christ, known and read of all men.
(2 Cor. 3:2)

Alas, dear Savior! how much are you and your name dishonored
by the people that call themselves by your name,
and yet allow nothing to be seen in them that is worthy of your name, your spirit,
and your doctrine!
With all their boasting of your merits,
they shamefully trample under foot your blood and merits.
Can those be your people, who serve you only occasionally with their lips,
and your daily enemies in their hearts?
Can those be your children, who evidence by their deeds,
that they do not possess your divine nature in the smallest degree?
Are those the living branches of the true vine which
bear nothing but wild grapes and corrupt fruit?

O no! dear Savior!
He that commits sin, has never seen, has never known you.
A deceitful heart boasts falsely of forgiven sin.
Christ is not the minister of sin.
They know you not, who thus appropriate to themselves your merits and your righteousness,
while sinning and making use of them as a cloak for their sins.

The fourth justification I wish myself and others to be acquainted with,
rather from experience, than from a bare description of it.
It may be called the inherent and final justification
at the bar of the divine good pleasure.
Justification, commonly so called, and sanctification flow in this together,
and attain in it their completion.
The end of all the ways of God with fallen man, is incontrovertibly this, that God,
through man`'s restoration may be again glorified and become All In All.

In the second and third justification and sanctification, man stands as guilty, ashamed,
and utterly degraded; while on the contrary,
God and free grace in Christ are highly exalted and glorified.
The natural and sinful life of man (besides which he possesses
nothing,) with all the corruptions of the flesh and spirit,
are made manifest, denied, and slain; Christ, and the kingdom of his grace,
rise in their stead.
The man by degrees, with all his own attempts after piety, holiness, faithfulness,
and devotion, however latent they may be, is put to shame before God;
he feels he must leave the work to Christ, and the operation of his spirit within him;
must give place to Christ, make room for him, and let him work and live in him.
In short, he must decrease, and Christ must increase, till he can say of a truth,
"`Now I live, yet not I, but Christ lives in me.`"
(Gal. 2:20) Christ himself is made unto him wisdom, righteousness, sanctification,
and redemption, not only objectively, and by appropriation, but also inherently,
by virtue of his gracious indwelling.

God then again approves of his own goodness, which he has implanted in the soul--that is,
what Christ has wrought in the heart by his Spirit.
God pronounces good the individual`'s state of grace, (Rom. 8:16,
Heb. 11:5) his holiness, beauty and virtues,
for they are Christ`'s. (Rev. 2:17) His works please him,
for they are wrought in God.
(John 3:21) God then rests with delight in the works of his hands, as at the beginning.
(Gen. 1:2)

But before this can be the case, much self-denial is necessary;
and before Christ can have in all things the preeminence, much forsaking of ourselves,
to be found complete in Christ.
Paul was justified and sanctified, he was in Christ, and yet he sought to press forward,
(Phil. 3) he wished to be found still more complete in Christ,
not having on his own righteousness, etc.
In this manner, Jehovah himself at length becomes our righteousness,
in the full sense of the word, (Jer. 11:6) and we are enabled to say,
"`In the Lord Jehovah have I righteousness and strength.`"
(Isaiah 45:24)

Yea, Amen!
You be all, and I nothing!
This, O my God! is the aim of my desire; to this tend all your dealings with us men;
to this lead all your ways and all your judgments!
No one is good, or holy, or righteous, but you alone!
The saints in heaven and all on earth are alone holy through you,
and because your indwelling communicates to them something of your goodness and holiness.
All our righteousness, all the goodness we can possess, flows from you,
its original source, and must flow back unmingled to you again.
You alone be great and exalted, O my God,
and let me lie here and in eternity at your feet, and say, "`To you,
who sits upon the throne, and to the Lamb, be praise, and honor, and glory ascribed,
forever and ever.
Amen!`"

Of this fourfold justification, many attend merely to the two first,
but not in their essential connection with advancement
in true holiness and union with God in Christ.
Those who wish to improve upon this, at one time comfort all with the gospel,
and at another require of the people a holy life, without pointing them, as they ought,
to Christ, who alone can sanctify.

Many well-meaning men, who see the lamentable abuse of the doctrine of justification,
(often advanced unguardedly enough) are led to deny the two first,
or at least the second,
and wish to have all that the Holy Scriptures say of justification,
understood merely of the third and fourth.
There are also not a few, who will hear nothing of the two last kinds of justification,
easily pass over the second, paying regard merely to the first,
and that in a very imperfect and superficial manner.

Thus do people divide and dismember Christ and his word,
each one taking from it that which suits and agrees with him,
while very few receive him wholly as he is offered to us in the gospel.

May this not be the case with us, but may we be of one and the same mind;
cordially laying hold on Christ crucified for us, as our justification,
and Christ dwelling and living in us, as our sanctification;
and by faith and love abide in him to the end, that we may at length be able to say,

"`We are made partakers of Christ.`"
(Heb. 3:14)
