[short="The Constraining Love of Christ"]
== A Sermon on the Constraining Love of Christ

// lint-disable invalid-characters
Preached at Mühlheim, on the Rhur, 14th October, 1751.

Sermon.

The love of Christ constrains us.
-2 Cor. 5:14.

My dear hearers,

If we are desirous of seeing a true representation of ourselves,
both as to what we are by nature, and what we ought to be by grace;
as well as the appearance we have presented or still present,
so long as we continue dead in sins,
and what manner of persons we ought to become by
the communication of that life which is from God:
we must turn to the thirty-seventh chapter of the prophecy of Ezekiel,
where the Lord showed that man of God "`a large field full of dead men`'s bones,
which were very dry.`"

In fact, if it should please the Lord to open the eyes of our spirits,
as he did those of the prophet, the wide field of this lower world,
(and would to God I were not compelled also to add that of the
so-called religious world) would present just the same appearance.
We should see, alas! in every quarter and station, scarcely anything else but dead bones,
dead hearts, dead formalists, dead words, dead works, a dead walk, and dead worship.
And among this multitude of dead bones, we should find ourselves likewise,
so long as we continue in our natural state.

These bones could not appear to Ezekiel more miserable, dry, and wretched,
than the aspect which our hearts present, as long as we cleave to the earth,
devoid of and estranged from the life which is from God,
and destitute of the vital power of godliness.
Who could have thought, while contemplating these dry bones, which the prophet beheld,
that they had ever composed the beauteous frame of man!
So entirely has he lost, by the fall, his original form;
so completely is he become a horrible monster,
that no resemblance to it is any longer visible.
No one would say, that this was the noble God-man,
that formerly proceeded forth from his Maker`'s hands in such superlative beauty.

It is true, that fallen man still possesses species of life; but such a life,
as is wont to be found in the carcasses and bones of the dead.
In dead bodies it is not a natural,
but an unnatural life that presents itself to our
view--they live and swarm with worms and vermin;
and a similar strange and unnatural life has penetrated into our hearts,
which are dead to God--they swarm no less with all kinds of worldly, sinful,
inordinate lusts and affections, like so many horrible vermin, snakes,
and scorpions; so that we are justly become loathsome in the sight of God, of angels,
and of enlightened men, in the same manner as a dead carcass is loathsome to us.
Nay, I am persuaded, that if we were properly acquainted with ourselves,
in this state of unnatural deformity, we should loathe nothing so much as ourselves,
and abhor ourselves as much as we do a mass of putrefaction.

"`Son of man,`" said the Lord to the prophet,
"`Do you think these dry bones can live again?
And he answered, O Lord God, you know!`" as though he had said,
"`It is impossible for me, as a son of man, to know it;
I must therefore leave it to your wisdom and omnipotence.`"
"`Prophesy,`" said the Lord, "`concerning these dry bones, and say unto them,
O ye dry bones, hear the word of the Lord!
Thus says the Lord God unto these bones, Behold I will cause breath to enter into you,
and you shall live.
And I will lay sinews upon you, and will bring up flesh upon you,
and cover you with skin, and put breath in you; and you shall live,
and you shall know that I am the Lord.`"
Upon which the prophet prophesied, and behold, there was a noise and a shaking,
and the bones came together, and the sinews and the flesh came upon them;
but there was still no breath, no soul in them.
Just as little possibility,
or appearance of a possibility of renovation is there to be found in fallen man,
as these dry bones presented.

And who that was acquainted with us, who have felt the influence of divine grace,
particularly many among us, only a short time ago,
while we were in our former corrupt state and conduct, but might also have inquired,
"`Do you think that such dry bones,
and such a loathsome dead carcass can still become a living man?
Do you think that such a vain and careless sinner,
or that such an abominable and rebellious brand of
hell can still become a favored child of God?`"
O my God,
what little hope or prospect of such a change could we have afforded at that period!

Nevertheless, it has been prophesied to us in the name of the Lord.
The Lord sent his word and accompanied it with the power of his Spirit.
A noise, a rumor, and a shaking has been excited among us in this place.
The world has heard of it, and has wondered what would result from these dry bones.
The prince of darkness has been astonished at it, and afraid,
lest too great a number of his subjects should escape from the regions of death.
The dry bones have come together, bone to his bone;
and thus it is that we are here at present.
The world now regards us as living characters; we have the appearance of men, that is,
of christians; there has been at least a shape, a body produced.
But is there a real soul, is there a breath and unrestrained vital activity in this body?
As little as a man consists merely of a body,
so little does true christianity consist in the mere form and appearance,
in merely associating with others, in speaking as they do,
or in a constrained deportment.

It is true, God be thanked! that life has also entered into us;
for otherwise from where proceeds that shaking, that creeping together of the dry bones?
For, by nature,
there is not the smallest impulse or inclination in us to that which is good.
But is it a thorough, free, and unconstrained vital feeling that pervades us,
or is it only a sort of half, grovelling, miserable, existence?
Such a state cannot be either pleasing or satisfactory; it must not continue thus with us.

A change, yea even a remarkable change has taken place in many of us.
But my dear hearers, do we not feel, are we not conscious,
that there is still something lacking, and that much is still lacking?
The heart does not yet move and beat aright in the christian body;
we are still incapable of loving, trusting, and cleaving to God aright,
and of delighting in him and in his ways.
We are willing, it is true, but unable to perform; the heart is still backward, cold,
and dead, it still easily sinks powerless to the earth.
The case ought to be otherwise with us.

What labor and exertion is required to bring a lifeless corpse, or a man in a swoon,
only a few feet from the place where he fell down!
What efforts are necessary to move him!
Alas, my dear hearers! are there not many in the same state,
with respect to the work and career of godliness?
How long and how painfully do they drag the body of death about with them!
They abstain from some particular things, but not altogether; it requires such an effort,
it costs them so much.
They exercise themselves in this or that particular duty,
which they acknowledge to be essential;
but how must they exert and do violence to themselves to accomplish it!
They would gladly be steadfast, faithful, and holy; but alas! they make little progress.
Such is the case, and it cannot be otherwise, so long as we possess a christian body,
which is only half alive.

Finally, a dead corpse may, though with much difficulty, be raised up and supported;
but what avails it, unless life and soul enter into it?
Let us not regard it as a small thing,
that the goodness of God favors us with many means of grace for our awakening,
encouragement, and refreshment,
but humbly acknowledge them as divine and inestimable favors and benefits.
Yet still, if in the use of all such means,
we are not chiefly concerned to obtain the spirit, strength, and love of Christ, we may,
by having the senses affected, be lifted up like a dead corpse,
in the manner above-mentioned; but in a short time,
the senseless mass again falls prostrate upon the ground,
in all its former sluggishness and customary evil habits.

It is quite another thing with those who are in possession of spiritual life;
they may be also listless, faint, and slothful, and again be awakened, quickened,
and powerfully assisted in their course, by thus assembling together,
and by other means of grace.
But, O my dearest friends! the best supports are of no avail, for any length of time,
to him who has obtained no life and soul with his
godliness--they soon lose their influence over us.
Those who are satisfied with merely attending and hearing,
and are not concerned about the inward power of godliness, do not,
and cannot long remain steadfast.
The fairest corpse will soon decay, corrupt, and produce worms,
unless a soul be imparted to it.

In a word,
as necessary as it was that the prophet Ezekiel should
prophesy a second time in the name of the Lord,
and say to the wind or Spirit, "`Come, O Spirit, from the four winds,
and blow upon these dry bones, that they may live! on which, breath entered into them,
and they became alive: even so indispensably necessary is it for us,
who have felt within us the first motions of spiritual life,
that it be again prophesied to us in the name of Lord,
that the true spirit of christianity may enter into us,
and that we may be made alive and whole.
"`Come, O Spirit!`" ought every heart to cry, "`come, and blow upon me,
who am spiritually dead, that breath and life may enter into me!`"
Now this soul, this life and power of godliness, is nothing else than the love of Christ,
which makes us living and active christians.
O, it is for the possession of this love, that we ought to be solicitous!

Not only were the apostles such living, active, and holy christians,
but believers generally, in the times of the apostles.
If we turn our attention to these first and fervent christians,
and inquire how these people were able to do such great things,
to suffer so much and to live in the manner they did, the holy apostle Paul,
in the name of them all,`' answers in the words of our text,

"`The love of Christ constrains us.`"--2 Cor. 5:14.

According to the direction given us in these divinely inspired words, let us,
with the divine assistance, consider on the present occasion,

I+++.+++ The love of Jesus Christ; and

II. Its divine power.

"`O most blessed Savior! behold your servant will
now venture to testify of your wondrous love,
O look not upon my unworthiness and incapacity!
Draw near to my heart, and inflame it;
touch my uncircumcised lips with a burning coal from your altar,
that I may not speak of your ardent love in a cold or feeble manner!
Amen.`"

It has not pleased the Holy Spirit to indicate more clearly,
whether by the "`love of Christ`" in the words of our text,
is meant the love wherewith Christ loves us,
or that love with which the believing heart loves Christ; perhaps for this very reason,
that we should take them both together.
They belong in fact, most closely to each other; the one is produced by the other,
and they are originally one.
For how should we possess even a spark of love to Christ, unless he had first loved us?
And the love wherewith we are enabled to love him, is not less his love,
than that with which he has loved us, both in tine and in eternity.
It is Christ who makes the commencement in loving; therefore in our present meditation,
we must also begin with considering his love to us.

1+++.+++ Christ loves us with a love surpassing the most
faithful and fervent affection of a friend.

2+++.+++ Christ loves us, and loves us voluntarily, with a most compassionate, attentive,
and unwearied maternal love.

3+++.+++ Christ loves us, and loves us voluntarily, with the most tender, ardent,
and felicitating love of a bridegroom.

Christ loves us with a love surpassing the most faithful
and most fervent love of a friend.
Friendship among men consists in the free and inward inclination of the heart,
by virtue of which, the individual wishes his friend the possession of every good,
and gladly procures it for him; while he seeks, on the other hand,
to defend him from every injury and misfortune,
and to aid and assist him in every emergency.
It is with such a friendly affection,
that Christ is in reality attached to us in the highest degree.

If we wish to form to ourselves an idea of the most faithful friendship,
it must be such a friendship as will continue firm in the hour of need.
But where among mankind do we find a friend in need?
and if we are desirous of representing to ourselves this affection of the soul,
in its sublimest exercise,
we must suppose the case of one friend laying down his life for the other;
but where is such a friend or such friendship to be found among men?
In Christ, we really possess such a friend, and in his heart, such a friendship for us.
"`No one,`" says himself, "`has greater love than this,
that he lay down his life for his friends.`"
(John 15:13) Ah, dearest Savior! why talk of friends?
We were foes and rebels,
and yet have you laid down your life for us! "`Christ,`" according to Paul`'s expression,
"`died for the ungodly.`"
"`God commends his love toward us, in that while we were yet sinners,
Christ died for us.`"
(Romans 5:6,8) It is therefore with due reflection,
that I have denominated the love of Christ,
a love that surpasses the most faithful and most fervent love of a friend.

O the astonishing intensity of the love of Christ!
You and I, my dear friends, were fallen from the friendship, light, love,
and fellowship of God, into the depths of misery, wretchedness, and hell.
We were no longer friends but foes; no longer worthy of being loved,
but hateful and deserving of wrath.
Yet God, in his eternity, had compassion on our great and boundless misery.
He let it cost him that which he held most dear.
For our salvation he gave up his only begotten Son, the child of his bosom,
and in his Son, the heart of his love.
Neither man nor angel can comprehend or fathom this.
We must believe it, we must adore it, and with Christ himself, astonished exclaim,
"`God so loved the world,`" this miserable world! (John 3:16)

Christ`'s surpassing friendship for us constrained him to leave heaven for us.
Listen to the joyful and wondrous tale! it is no fable but a certain fact.
Listen to this glorious gospel of the ever blessed God;
not as a matter with which you are already acquainted,
and which you have learnt from your youth up, from your Bible and Catechism;
but listen to it as important news; listen to it this day, for once,
as if you had never heard it in your life before.
Christ`'s surpassing friendship constrained him to leave heaven,
that he might save and deliver us.
And in order to do so, and that we might not be afraid at his appearing,
he clothed himself in our wretched humanity and sinful form.
As our God and near relative,
he really took upon himself the burden of our sins and transgressions,
as though they were his own.
During the space of nearly thirty-four years he labored, prayed, and struggled for you,
my friends, and for me.
Under the most appalling sense and agonizing feeling of that divine wrath,
which sin had roused, he became exceeding sorrowful, sweated great drops of blood,
and experienced the torments of hell and the hiding of God`'s countenance; in a word,
he suffered and endured all that, which you and I, my friends, would have had eternally;
yes, eternally to suffer for our sins.
And all this he did from the voluntary affection of a friend,
and that by the inestimable value of his blood, he might again reconcile us,
and purchase us to become his friends.

Can we imagine greater love?
Is not Christ a true friend in need, a real friend, even unto death?
And he suffered all this, not for us generally, but for everyone of us in particular.
In this view Paul regarded it: "`Christ loved me,`" says he, "`and gave himself for me!`"
Ah, Paul! what is it you say?
Did Christ then die for you solely?
O yes, solely for me, and solely for you!--thus we ought to view the subject,
in order to behold it to the most advantage;
and it is thus that Christ loves everyone with a particular affection.

[.asterism]
'''

I said, secondly, that Christ loves us, and loves us voluntarily,
with the most compassionate, attentive, and unwearied maternal affection.
When an infant is sick, or falls down and hurts itself, and lies weeping and in pain,
before its mother`'s eyes--instead of hating it on account of its pitiable state,
she regards the poor babe with heartfelt compassion, and seeks, in every possible manner,
to relieve and comfort it.
Christ puts on similar bowels of maternal love towards us, fallen and sinful children,
especially when we penitently feel and bewail our sins.
He then regards us with feelings of the most tender compassion.
Poor penitent soul! you probably do not believe that Christ loves you thus,
and looks upon you in such a manner; you think you are altogether too abominable,
and that having willfully plunged yourself into all this misery,
he pays no more attention to you.
Hear therefore,
what he says on this subject in Ezekiel 16:6. "`I saw
you lying in your blood;`" and as certainly as he sees you,
so certainly will he also say to you when his hour is come,
"`You shall live! yea I say unto you, you shall live!`"
Let us only look unto him by faith, even as children that are sick, are wont to look up,
with weeping eyes, at their mother.

A penitent and distressed individual often finds it impossible
to believe that his weeping and lamenting are heard and answered.
Be assured, my friend, the Lord hears when Ephraim complains; and says,
"`Is not Ephraim my dear son, is he not a pleasant child?
etc.`" (Jer. 31:20) If this cannot be called the expression
of the most compassionate maternal affection,
I know of none.
We should not dare to ascribe to God such tender feelings of maternal affection,
if the Lord himself had not done so.
Ah, you penitent souls! could we believe it, could we see it,
our hearts would likewise melt with feelings of reciprocal filial affection.

Christ loves us, and loves us voluntarily, with the most assiduous and maternal love.
It is from its mother, that a child derives its natural life, and it is by her means,
that it is brought into this miserable world;
Christ regenerates us to an eternal world of light and joy,
and imparts a life to us which is incorruptible.
A mother nourishes her child from her own breasts; but Christ gives himself,
his flesh and blood, to be the food of his regenerate children.
This no human parent does.

A mother cleanses her child, cherishes it, carries it about, and fosters it,
till it is grown up; she is constantly doing something for her child,
and her maternal love causes her never to be tired of attending to it.
Ah, who can reflect without shame and astonishment,
how the ever-loving God is obliged to have patience with his stubborn children,
to speak after the manner of men! how we weary him with our transgressions!
Nay, it is impossible to say, how much he has to do in bringing up a single soul.^
footnote:[Bringing down would be also a correct, but no common mode of expression.]
The Lord himself expresses this active, aiding, maternal love in Isaiah 46:3-4,
where he says, "`Hearken unto me, O house of Jacob! which are borne by me from the womb,
and carried from the birth, even to hoary hairs will I carry you, etc.`"

The parent of a child preserves it from every accident,
and seeks its welfare to the utmost of her ability.
Christ, our ever-loving parent watches over, and protects his offspring,
incomparably more attentively, lest the Evil One should touch them.
Nay, not even a hair can fall from their heads, without his will.
Everything that befalls these sucklings of his grace, be it little or great,
inwardly or outwardly, is so guided and governed by the parental love of Christ,
that all things must work together for their good.

As little as a child, born of human parents, is anxious how it may become great,
so little ought a child of grace to be concerned how it may grow up,
and become strong and holy.
The parental love of Christ provides for all this;
it is only necessary that the child remain in its mother`'s lap, and by prayer, faith,
and love, seek nourishment and strength for its life and growth,
from the breasts of divine grace.
And while thus lying in the lap of love,
the weakest and most needy infant need not be afraid of any danger.

This love, however, destines the children of grace to experience a variety of trials,
temptations, and sufferings, for their good;
and they are often left in such a state of barrenness and darkness,
as to cause them with Zion to exclaim, "`The Lord has forsaken me,
and my God has forgotten me!`" but how widely does the soul err from the truth,
in such a supposition!
The Lord himself asks, "`Can a woman forget her child,
that she should not have compassion on the son of her womb?
Yea, she may forget; yet I will not forget you.
Lo, I have engraven you on my wounded hands!`"
O my dear hearers! this has reference both to you and me; ought we not, therefore,
to commit ourselves, body and soul, to Christ`'s maternal love and care,
both for time and eternity?

[.asterism]
'''

Christ loves us also, and loves us voluntarily, with the most tender, ardent,
and transporting love of a bridegroom.
O yes! the love of Christ really entreats the hearts of poor lost sinners;
and how long must he frequently woo us, before he receives from us the desired consent!
How often have not you and I shamefully spurned and
rejected his proffered kindness and love;
and yet he was not weary of seeking us!
O how tenderly does he love, even before he is beloved!
But still how infinitely more tenderly, when he has attained his object,
and when he can forever betroth himself with the soul, as with his bride,
and engage himself to her in righteousness!
This is often succeeded by many precious and even
sensible communications of his love to the soul.
Christ presents her with many invaluable jewels and celestial blessings,
and gives her to experience, in her measure, "`righteousness, peace,
and joy in the Holy Ghost.`"

And as Christ finds his bride so entirely destitute, and so beggarly clothed,
he divests her, by his love, and by sanctified affliction,
of her filthy and tattered garments, clothes her with his righteousness, sheds abroad,
together with his love, his whole mind, image, and resemblance, more and more in her,
so that she is arrayed in his humility, meekness, purity, simplicity,
and every divine virtue.
And after having thus beautified her with himself, he then rejoices over her,
"`even as a bridegroom rejoices over his bride,`" (Isaiah 62:5) "`Lo,
you are fair my love,`" says Christ, the heavenly bridegroom.
(Song of Solomon 1:15-16) "`No,`" replies the bride, "``'tis you alone that are beautiful;
for even the beauty that you see in me, is yours.`"
These are no empty words or vain imaginations, but mighty wonders of the love of Christ.
Would to God, that we could read them, not only in the Song of Solomon,
but also in our hearts by happy experience!

It is impossible, my beloved hearers, to express the profound and ardent affection,
and the intense desire there is in Christ, to regain possession of our hearts,
to have us again near him, and to bind and unite us eternally to himself,
and himself to us.
Angels and men cannot comprehend it, but will adore this mystery,
with the profoundest admiration, to all eternity.
The Spirit of Christ, which dwells in believers, desires us, even to jealousy;
he cannot bear that a heart, which has cost him so dear, that a heart,
which he loves to such a degree, should still cleave to other objects,
and not remain wholly and solely devoted to him.
He loves the soul, as though he loved nought besides;
and she must love him in the same manner in return;
for the love of Christ--the profound and ardent affection of Christ for the soul,
excites in her similar ardent affection for him.
The love of Christ touches the soul and attracts her to itself,
and she follows this attraction.
"`Draw us, and we will run after you!`"
Her heart and her whole being, while departing from every other object,
longs after and inclines to closer union with her Beloved.
What tender meetings, caresses, embraces, communications, and unions then take place,
may well be experienced by pure and abstracted hearts, but can never be expressed;
for these are subjects that belong more to eternity than to time.
In short, the love of Christ is a great mystery of godliness,
and an inexhaustible source of unmingled felicity.

Now, therefore, you dear immortals, all of whom as well as myself have been created,
redeemed, and called, for the purpose of loving, and of loving God,
behold--and O that our eyes were really opened to
see it!--behold how God loves us in Christ,
and how tenderly he loves us!
How ought all those to be ashamed, who seek to represent God as a tyrant and a grouch!
There is no wrath in God, except against what is evil.
God has not created us, in order to hate us, or to be hated by us,
but solely for the purpose of loving us, and being eternally beloved by us.
But alas! alas! where are the hearts that love God in return?
O that there should be such a God, such a Christ, a Christ that bears such love to men,
and that there should be such a love of Christ, and yet be so little known, experienced,
and enjoyed, and that too by so few!

How often do men repeat the words,
"`Dear Lord! dear Savior!`" but ah! how are their hearts inclined towards him?
What have our hearts experienced of the power of this love of Christ?
For we must not imagine to ourselves, a sort of capricious, inoperative,
and injurious love of Christ, as though he could, or ought to love us,
while we continue in our vicious practices, like many parents,
who possess such a senseless affection for their children,
that they give way to all the perversity of their wills,
and allow them to plunge themselves into perdition.
The grovelling and perverted mind of man would desire
such a love on the part of Christ also,
and such divine mercy; and that Christ should permit him, in the days of health,
to enjoy the vanities and pleasures of the world, according to all his will,
and that afterwards, when he came to die, and gave God a few good words,
God should be so merciful, and Christ love him so much,
as to take him immediately up to heaven.
No, foolish man! such a love of Christ,
and such a heaven is but the result of your own imagination;
with God there is nothing of the kind.
Christ loves you, even against your will, far more than you love yourself.
He will rather cause you pain and save you, than flatter, and let you perish.

The love of Christ is therefore no vain imagination, but a vital, active,
and mighty power of God,
which actually raises and restores us from our errors and corruptions, sin and death;
imparts a new and real life; makes us willing, alert,
and able to the performance of all that is good, and renders us truly happy.
The love of Christ is the commencement, foundation,
and the soul of christianity and of all real religion.
He that does not possess the love of Christ, has either no godliness or piety at all,
or only such a piety as is hypocritical and dead.
Christ in order to save us, must not remain at a distance from us;
we must experience the power of his love upon our hearts, and make room for it;
otherwise, notwithstanding all our speaking and hearing of the love of Christ,
we continue in a state of spiritual darkness and wretchedness.

Christ undoubtedly makes the beginning by first loving us.
When, for instance, the love of Christ urges a man to repentance,
the Spirit of love then reproves him for his unrighteousness,
convinces him of the necessity of repentance and conversion,
alarms him on account of his sins, and the dangerous state of his soul.
There is something that seems to pursue the man, and presses itself upon him,
constraining him to repent and yield himself to God, and to become another man.
`'Tis true, the blinded mortal regards it, in his ignorance,
as a temptation of the devil which he ought to resist,
or else he looks upon it as proceeding from his own uneasy and accidental thoughts,
and as something of an evil or melancholy nature; yet,
although he would often gladly be rid of it,
it still returns to prove that it does not proceed from the man himself.
Many a one, alas! allows days and years to elapse,
without perceiving that it is the saving love of Christ, which thus constrains him.

Be assured that it is the compassionate and ever-loving Jesus,
who stands at your door and knocks; he entreats and begs for your heart,
just as if he really stood in need of it, saying, "`Give me, my son,
O give me your heart!
Be reconciled unto God!`"
Thus it is that the love of Christ constrains; and how often,
and how long has he dealt thus with us!
How often would he have gathered us, as a hen gathers her chickens under her wings,
but he did not come at a convenient season, and we would not!
In our natural state, we are running straight to perdition; is it not love, therefore,
when the Savior arrests us in our course?
We wander, as it were, on the brink of hell; is not that love,
when he lays hold on us and draws us back, even by the pains he makes us feel?
Ah, what advantage does the all-sufficient God derive from thus following after you and me?
Are we of any benefit to him?
Has he any need of us?
O beloved soul, if you knew the gift of God, and who it is,
that with such constraining influence speaks unto you, saying, "`Yield yourself to me,
delay no longer!`" certainly, you would no longer resist nor seek to escape from him,
but would fall at his feet that very moment, and cast yourself into the arms of his love.

Now, if the soul be fortunate enough to stand still and give
ear and admission to this attracting and restoring love,
so that the heart being depressed, bowed down, and broken: by true repentance,
seeks for refuge in the mercy of God; it is again the love of Christ,
by means of which the soul is constrained to experience such painful feelings.
Her carnal nature would indeed gladly expel the subject from her mind,
and live the day through as before, free, jovial, and merry;
but such a burden has fallen upon his heart, as cannot be got rid of--she feels her sins,
her wants, her danger, and she feels them at all times.
It is the love of Christ which constrains her to feel thus, although the soul, as yet,
knows nothing of this love, but is only conscious of wrath and condemnation.
She has heard and acknowledges, that it is she, who, by her sins,
has crucified her loving Savior.
This pierces her to the heart, this gives her pain.
It is necessary that she feel it a little here,
that she may not feel it too severely hereafter--is not this love?

The love of Christ impresses the soul with a feeling of her lost state,
in order that this loss and its attendant misery, may humble her,
and constrain her to seek the love of Christ,
that in it she may find alleviation and a cure.
For this is the sole intention of God in bringing us into
this state of distress--not in order to repel us from him,
and plunge us into perdition and despair--but to induce us to seek his loving heart,
and by a penitential hungering after the love of Christ,
escape from all our sinfulness and its consequent misery,
and cast ourselves upon the atoning blood, precious merits,
and eternal grace of Christ--not, indeed, by an inefficient self-made appropriation,
but by a humble longing and aspiration of the heart
after the influences of the grace and love of Christ,
in the manner in which it may be really experienced to the
tranquillizing of the distressed heart and conscience.
In such a situation, all that the soul has to do is deeply to humble herself,
confess her guilt, cast away every other confidence,
and desire to know nothing but the love of Christ, and his eternal mercy.
And when sin and the guilt of sin,
and when wrath and condemnation press with all their weight upon the mind,
the individual must do nothing else than plunge himself so much the more
profoundly into this open abyss of the eternal mercy and love of Christ.
It is thus that we ought to let the love of Christ constrain us to repentance,
and through repentance to love; it will then assuredly follow eventually,
that the love of Christ will cover the multitude of sins, so that afterwards,
the individual is ashamed, as the prophet expresses it,
(Isaiah 16:63) with humble thankfulness and confusion,
when the Lord thus forgives him all his sins, and repays them, as it were,
solely with his love; and then it likewise happens, that they,
to whom most has been forgiven, love more than others.

The love of Christ then further constrains a converted soul to depart from sin,
the world, and all its vanities.
The man can no longer run with the multitude as before,
without feeling himself under restraint.
What is the reason?
Are you perhaps afraid of being punished by your parents, masters, or magistrates?
O no!
The individual then becomes sensible of such sins,
of which no man knows or can know anything; even the smallest things,
which do not come under the jurisdiction of the magistracy, or of man.

But why?
Is a person subject to be despised and ridiculed, when he lives a life of vanity,
and is not under the influence of piety?
By no means!
The world, on the contrary, ridicules and slanders him,
who no longer runs to the same excess of riot.
(1 Peter 4:5) But why do you not act like the men of the world,
and why do you live so retired?
Were a converted person to reply to this and to state the true reason,
he would be obliged to say, "`The love of Christ constrains me to forsake these things;
I dare not and will not follow my depraved nature any longer.
The time past of my life is sufficient to have wrought the will of the Gentiles.
I have long enough crucified my beloved Savior with my sins--that Savior, that Christ,
who so loved me, as not only to forsake the world but even heaven for me.
Ought I not, therefore, for his sake, to deny myself an odious sin,
a vain and transitory worldly lust?`"

Yes, the love of Christ constrains us not only to deny the obvious vices of the world,
and the dead works of sin,
but urges us also to the real renunciation of the love of the world,
and of attachment to created things, which may still remain in the heart;
to the abandonment of the false and deeply-rooted life of self;
to the mortification of lustful and angry passions--to the sacrifice of our own will,
our self-love, and self-complacency, in small things as well as in great,
in natural as well as in spiritual things.

What gloomy and terrific ideas do we not often form of self-denial!
How many weak and inexperienced souls are frequently deterred
from it without a cause! "`O,`" say they to themselves,
"`what a painful life must that be,
when we cannot enjoy a single happy hour more in the world!
It is impossible for us to live such a life;
we shall never be able to part with this or that particular object, etc.`"
Ah my dear friends, what erroneous ideas you are continually forming of your God!

He has no need of our self-denial, as it regards himself: but we have need of it.
He is not an austere man,
that makes our life and the road to heaven painful and laborious to us,
nor permits us to have any enjoyment in the world; but the reason is,
that we are such foolish, blind, and degenerate children,
as to be ignorant of our true happiness and salvation, and call that joy and pleasure,
which is in reality our destruction, torment, and hell;
just as a child that is playing with a knife, weeps, and resists in its ignorance,
when the mother`'s careful love commands it to put the knife away.

We must not look upon the inward impulse to self-denial as something of a legal nature,
but as the constraining influence of the love of Christ;
he seeks in a friendly manner to persuade us, simple children,
to put the dangerous instrument out of our hands;
and if his friendly persuasion avail not, he sometimes lets us wound ourselves,
that we may lay the dangerous knife aside.
O it is love alone!
Christ will gladly have our whole hearts, and by means of such mortifications,
remove every obstruction out of the way, that thus he may make us partakers of his real,
perfect, and eternal joy, love, and delight.
Yea, the more the Lord leads a soul to deny herself, and the less he permits her,
the more especial is his love towards her.

Now as we ought not to ascribe this incitement to self-denial to legality,
but to the love of Christ,
neither ought we to act in a legal manner in the exercise of it,
but let the love of Christ constrain us to it.
When the soul`'s constant exclamation is, "`I must do this,
or perish eternally;`" and when she thus falls upon self-denial without Christ,
in her own strength, ah,
such a life is indeed wearisome! but this must be also known by experience.
It is true, we must, otherwise we shall be lost;
but is it not already a part of condemnation, to be always acting from compulsion,
and never from a willing heart?
to be always compelled, and never be able to perform?
We must therefore hunger after the love of Christ;
seek the willingness and the power to deny ourselves in the love Christ;
and seek it until we find it;
until the love of Christ constrains us voluntarily
to renounce ourselves and all created things,
and esteem ourselves happy in denying ourselves,
and hazarding something for the love of him, who is our friend, our parent,
and our bridegroom, and to live so as we may best please him.

Were I pointedly to address those who are in a state of grace,
those who would so gladly deny themselves, but find to their sorrow,
that they everywhere fall short,
I would say "`Do not think so much upon denying yourselves, upon being faithful,
or upon living holy and strictly: but only seek to love, hunger after love,
exercise yourselves in love.
Love is always exercising self-denial, without tasting its bitterness,
and almost without ever thinking of it.
Think only how you may love Christ, how you may love him more cordially than ever,
and do everything to gratify and satisfy his love.`"

The love of Christ constrains the believer into suffering, and through suffering.
This sounds strange, and yet it is true.
The individual is frequently placed so wonderfully
and unexpectedly in some painful situation,
that he knows not how it happened; he is, as it were, pressed into it.
Some particular person must just speak or act towards us in such a manner;
some expression or circumstance is taken in a wrong light;
things must so happen and follow each other, that we may just have a little trial, cross,
or suffering.
It is not necessary that such things be always great or important;
the love of Christ often makes use of a trifle,
and knows how to touch us with it in the most sensible part.
Thus it happens with regard to the body and outward things,
and thus it takes place also with reference to spiritual things,
in innumerably different ways; and it is the love of Christ that does it,
although we are ready to ascribe it to some other cause.

Weak and timid souls may often distress themselves much by an unbelieving
anticipation of future external or internal sufferings,
temptations, and I know not what kinds of trials, which may perhaps never befall them.
Their language is, "`If I have ever to suffer that which such a one has to endure;
if I shall have to tread in this or that difficult path,
I know it will be impossible for me to bear it.`"
Ah, my friends!
Do not torment yourselves with unavailing care and sorrow.
Trust in love, that it will impel you to the cross, and through the cross; I mean,
be without carefulness concerning the future.
Love distributes afflictions wisely; she understands it better than we.
As long as we remain little weak children, she will not impose any heavy burden upon us.

But whatever we may have to suffer at the moment,
we ought to receive as coming directly from the hand of the love of Christ,
and not as from any particular individual.
When Christ suffered, he did not regard his sufferings as proceeding from the Jews,
the Pharisees, or from Pilate; but as coming directly from his Father`'s hand, saying,
"`The cup that my Father has given me, shall I not drink it?`"
Therefore do not think so much of the affliction, as of him that sends it.
If the case be thus, my friend--if you believe that it is Christ himself,
who sends you any particular affliction, O how precious,
how estimable and lovely ought everything to be to you,
that proceeds from a hand so dear!
Think how much he has suffered for you;
will you not therefore endure a light affliction to please him?

Think not so much of affliction, as of the love of Christ.
Love him, and you will be able to endure all things.
What cannot love do?
What have so many thousand martyrs and numberless other holy souls endured,
and were enabled to endure,
solely because they were constrained to it by the love of Christ!
The love of Christ imparts a growing willingness to suffer,
and secretly keeps the soul as if nailed to the cross;
so that frequently when the individual is in painful situations,
he would not descend from the cross, to let nature breathe,
even were he left at liberty to do so.

The love of Christ must constrain us to sanctification.
How repulsive and impracticable do many persons regard their sanctification.
To live so strict as the Scripture directs--to become so meek, so devout, so humble,
so pure, so blameless, and so holy, they think is impossible, and they cannot,
by any means, endure or attain to it.
True, my friends, when the severe reproofs of Moses in the conscience impel you to it,
it is impossible; and when you constrain and force yourselves to it, it is unattainable;
but it may be attained and that very easily,
when we let the love of Christ constrain us to sanctification.

Ah, what anxiety do many exemplify,
and what pains they take to become holy by their own efforts!
O my dear friends! all you have to do is to love Christ,
and to unite yourselves with him, by faith, love and prayer,
as the branch is united to the vine.
Does the branch find it difficult to bear sweet grapes?
Is it necessary to compel it to do so by commanding, threatening, and rough usage?
O no! the whole process takes place very quietly, easily, and naturally;
the branch merely abides in the vine and imbibes its noble sap,
and then it flourishes and bears fruit without any further trouble.
It is thus, that we ought also to act.
"`Abide in me,`" says Christ, and you shall bear much fruit.`"
We have only to love him, to remain inwardly secluded in his love, and,
as barren branches in ourselves,
let the pure and divine influence and power of the
precious love of Christ penetrate our whole souls.
We should then become, as though naturally, a people dear and acceptable to God,
and filled with all the precious fruits of righteousness, to the praise of Jesus Christ.
The virtues would then become easy and natural to us,
and we should esteem ourselves happy in being able to live to Christ,
according to all his good pleasure.

And really if it were possible,
(which it is not,) that we could become holy by our own efforts,
yet all would be only an imperfect, lifeless, and worthless phantom,
proceeding from the will and power of man,
and in which we only regarded and loved ourselves.
It is the love of Christ which must impart true life, power,
and value to all our godliness, works, and virtues.
Paul, therefore, knows not how sufficiently to recommend this excellent way.
"`Though I had the tongues of men or of angels,`"
says he,`" and have not charity or love,
I should be as sounding brass,`" and so on to the end of the chapter,
which you will find in his first epistle to the Corinthians,
and which you may read at home.

The love of Christ constrains to all diligence, watchfulness,
and activity in every good work and during the whole course of godliness.
Many a one, who slumbers securely in the deadly sleep of sin,
may be terrified and awakened by fear and chastisement;
strong emotions and the most serious resolutions
may be produced in a man by the judgments of God,
by illness, fear of death, the decease of near relatives,
or by other reproofs of conscience,
so that one would think something really good would result from it;
but how soon it passes away,
when unaccompanied by the heart-renewing grace and love of Christ!
Distress, and death, and hell may constrain as they will;
yet if the love of Christ does not constrain at the same time,
the man falls asleep again.

The external means of grace may also be of service in awakening
and encouraging slothful and sleepy souls;
but if we wish to be effectually and permanently awakened
by the means of grace which God puts into our hands,
we must remain near our hearts, and pay attention to the cooperating love of Christ,
which inwardly awakens,
animates and seeks to let its influence be felt in the deepest recesses of the heart.
Although love knows no anxious and distracting care,
yet it is equally remote from slothfulness and drowsiness.
Its possessor is ever anxious, the day through,
to be trying to do something to please his Beloved.

And here I must also allude to outward slothfulness and heaviness.
There are many who complain of being so easily overpowered by sleep,
when alone and towards night.
It must be allowed that this has its natural causes with some,
who are weak and fatigued by labor, in which cases,
the individual must have patience with himself; but I fear, that with many,
it is love that is lacking.
I have witnessed how many have been overtaken by sleep in the evening,
when anything good was read or spoken of, but who immediately roused themselves,
when any favorite topic of another kind was introduced.
How shameful!
Ah, if we had but a little more love for Christ, we should not be so slothful!

The love of Christ constrains to good works.
The learned dispute in all manner of ways about good works and their merits--whether,
and how far they are necessary to salvation, and the like.
A soul that loves Christ, interferes not with such controversies; love,
as is natural to it, constrains incessantly to every good work towards God,
towards the brethren, towards our neighbors, and even towards our enemies.
Love cannot act otherwise; she seeks to do everyone good, and to devote herself to all.

She has always enough--she is rich, she is kind, she is bountiful;
and if she has no money or anything else to give, she has still a heart,
which she gives in sympathy, compassion, and in rendering every possible assistance.

In a word, love is always doing good, almost without thinking of it;
she performs a thousand good works, without asking whether she ought to do them or not,
and the merit of good works never occurs to her.
Even when she has done much she thinks she has hitherto done nothing,
and that she will now begin.
Thus it is that the love of Christ constrains.

The love of Christ constrains to a continual progress in sanctification and godliness.
Those controversies are also completely unnecessary,
which are carried on about perfection--whether the commands of
God can be kept--whether such a particular state be attainable,
and the like.
My God!
People dispute about perfection, and ought reasonably first to inquire,
if they have taken one step towards it.
Methinks they only betray their lifeless and loveless hearts by disputes of this nature.

Love knows no bounds; she invariably seeks to advance further, to be more faithful,
pious, and acceptable in the sight of God.
She does not long inquire whether the thing be practicable or not,
she essays it in good earnest;
she must necessarily follow her impulse and her constraining influence.
The apostle Paul was doubtless, further advanced than any of us,
yet what does he say in the third chapter to the Philippians?
"`Forgetting the things that are behind,
and reaching forth towards those that are before, I press towards the mark,
for the prize of the high calling of God in Christ Jesus.`"
And if it were to be said to him, "`Why, Paul, are you not pious enough?
You are certainly no longer afraid of hell!`" "`Ah,`" he would reply,
"`it is not hell nor heaven that constrains me,
but it is the love of Christ that thus constrains me.`"

The love of Christ enters voluntarily into all our concerns.
She will and must have her hand, not only in the greatest,
but even in the smallest things.
All that we do, in reference to our natural life,
however great and important it may appear,
is in itself worthless folly and not worthy the attention of a heaven-born spirit;
but by love, all these trifles may become truly great, and a means of serving God.
He that picks up a bit of straw from the ground, from love to Christ,
performs a great work.

There are many who complain heavily that their outward
and necessary occupations cause them so much distraction,
hindrance, and detriment.
What is the reason, my dear friends?
It is, perhaps, because you perform what is incumbent upon you,
merely as if it were a worldly affair.
When you are sitting in your chamber, or at church, or meeting, or are able to read,
or do something good, you think you are serving God; but when engaged in the field,
or the kitchen, or elsewhere, wherever your avocations lead you,
you imagine you are serving the world.
Ah how lamentable, if this were the case!
We should then be obliged to spend the greatest part
of our time in the worthless service of the world.
Do all that you have to do, as a service rendered to the love of Christ,
and then it will be no longer detrimental to you.

When the love of the world, care, or unbelief, or any other of the powers of nature,
constrains us to business, and is our leading motive in it,
the mind must naturally become more and more darkened and distracted;
but if the love of Christ constrains us to the work,
and if we let ourselves be restrained by it in our affairs,
so that we perform them in a childlike manner, solely to his love and glory,
they are then no longer a hindrance, but become a real service rendered unto God.
It is this, that the Holy Spirit means, when it is said in Colossians 3:17,
"`Whatsoever`"--observe how everything is included--"`whatsoever
you do in word or in deed,
do all in the name of the Lord Jesus.`"

The love of Christ will gladly keep us all the day near itself and within its influence,
urge us on our way, and by its constraining power,
preserve us from wandering either to the right hand or the left.
O if we would but carefully abide within its precincts!
Persons often make to themselves a variety of good maxims, rules,
and regulations for their conduct, which I do not entirely reject.
I know that order and discipline is requisite to keep untoward nature in restraint,
otherwise she would run wild; it is only to be lamented,
that all these good rules and maxims are so soon broken through.
There is no better rule, regulation, or precept, than the love of Christ,
which is inwardly so near us.

The love of Christ will lead us like a mother leads her child.
A child that walks in leading strings is carefully held and guided;
for though it goes at liberty and without constraint,
yet if it were on the point of running into the mire, or if danger were apprehended,
it would immediately feel that it was held by something from behind.
The love of Christ seeks to lead us in the same manner,
in order that we may be "`drawn in the cords of love.`"
(Hos. 11:4) When, through ignorance,
we may be ready to fall into something improper or dangerous, we should perceive,
like a child in leading-strings, that something held and restrained us, namely,
the love of Christ.

The love of Christ must and will constrain us to prayer.
Praying without the heart, and from the mere constraint of habit, is no prayer.
Praying, when danger and distress of soul,
and when a feeling of sin and necessity constrains, is a very good prayer;
but when the love of Christ constrains us to pray,
that is the noblest and most excellent prayer.
We often complain that we know not how to pray, that we have not a due desire for it,
and that the time when we are engaged in it appears long, etc.
But this proceeds from the lack of love to Christ.
Let us give way to love, and love will constrain us to pray.
We are glad to be alone a little with true friends;
and if we love Christ and love him cordially, we shall be willingly alone with him,
nor will the time spent in his society easily appear long to us.
If we love Christ, we shall always have something to say to him;
and if we have nothing to say to him, yet still we have something to love,
and that is praying.
O it is an excellent prayer, to love and be silent in the presence of God!

Yes, my dear friends,
we cannot believe what an excellent teacher of prayer the love of Christ is,
which awakens in the heart of the pardoned soul such innumerable
and inexpressible sighs-- that it were only more carefully cherished!
It causes many a tender aspiration to ascend from the bottom of the heart, frequently,
involuntarily and almost unconsciously.
Though the lips be silent, yet the heart exclaims in sincerity at one time, "`O my God!
O my Lord Jesus!`" and at another, "`I am forever yours!
My God, and my all!`"
And a single one of these heartfelt exclamations
is of more value in the sight of the Most High,
and really includes in it more than a long prayer of another description,
which is said from a book, or which proceeds from the understanding alone;
and the reason is, because it is the language of truth.
We are ready to say, "`Tell me, friend,
from what book have you learnt these beautiful aspirations?
I should like to procure such a prayer-book for myself.`"
"`The love of Christ,`" replies the soul, "`is my prayer-book;
the love of Christ constrains me to utter these exclamations.`"

The love of Christ is not only the most excellent teacher of prayer,
but is also prayer itself.
Love is like a continual fire, that descends from heaven upon the altar of the soul,
in the temple of the heart, where the sweet incense of silent,
spiritual devotion gently and delightfully ascends from the inward sanctuary,
in a thousand acts of praise, and love, and offering, of elevation and humiliation,
and of veneration, adoration, and admiration of the ever-blessed God;
where a single one of such inward acts of faith and love includes in it more life, peace,
delight, and blessedness than all the world can afford.
This the soul does not produce of herself, nor is she able to produce it; what does then?
The love of Christ constrains her.

The love of Christ constrains the soul, in one word, more and more,
by a blissful attraction, to complete and eternal union with the Beloved.
She has drank of the water of love which Christ has given her,
and this will gradually become in her a fountain of water,
springing up into eternal life.
She feels that there is no more happiness for her
here below in anything that is created and temporal.
Everything becomes so strange to her and so worthless in her sight.
All that is within her longs after Christ and eternity; and Christ,
the divine center of attraction, cannot long leave her here in sorrow--he draws her,
and finally takes her to himself.
"`Father, I will, that where I am, they may be also whom you have given me,
that they may behold my glory.`"
(John 17:24)

See, my friends, this blessedness, of which we have now imperfectly spoken,
is laid up for you, and offered you in Christ; yea, it is for you,
and for the weakest and most wretched among you.
O my dear hearers, love God, who thus loves you, and will eternally love you!
Surrender yourselves unconditionally to the constraining
and attracting influence of this beatifying love of God.
Set no bounds to this love, it leads further than the human understanding can reach;
and there are greater wonders and blessings to be experienced and enjoyed in it,
during the present life, than the tongue of men or angels can express.

O the lamentable blindness and ignorance of the generality of mankind,
in being so cold towards God, and so warm in the pursuit of other objects,
and in letting the love of the world, sin,
and vanity have more influence over the heart than the love of Christ!
The love of the world need only give the hint, and the man is immediately on the alert;
while the love of Christ constrains so long,
and yet people do not follow it nor resign themselves to it.
O how many an unhappy worldling allows himself to
be constrained by the sinful love of the world,
and driven from one sin, vice, and vanity to another!
He is like a slave, who is so constrained by his hard master,
that he is almost unable to forsake his old habits;
Satan and the love of the world govern and constrain him,
and will drive him into hell itself, if he do not consider in time,
and let himself be constrained to repentance by the love of Christ.

Let us therefore, my friends, examine what it is that we love.
What has the greatest weight with us?
On what object do we think first in the morning and most frequently during the day?
For by this we may ascertain where our treasure lies.
Are we beginning to let the love of Christ take possession of our hearts;
or are we still in our lifeless and loveless state of nature,
without Christ and his love?
O indescribably unhappy state!
O dreadfully dangerous condition!
If we are not in love, we are in wrath, in the horrible kingdom of darkness,
where the wrath of God is impending over us, and where,
held merely by life`'s slender thread, we hang over the bottomless abyss.
O the eternal misery of dying in such a state!

O you immortal souls!
You are now listening to the love of Christ, but who knows how long?
It is now proclaimed, recommended, and offered by Christ himself to our hearts.
Yes, Jesus loves you, all of you, however sinful you may be,
and who must confess that you have been hitherto slaves of sin and Satan;
you need not perish; Christ will gladly save you; he entreats you; ah,
give yourselves up to him!

If your misery and danger, if the wrath of God, the fear of death,
and the dreadful judgment-day,
together with your own eternal woe and perdition cannot constrain and affect you,
let the love of Christ now do so.
Let me set before your eyes the suffering Savior.
See him lying in his bloody sweat and dreadful agony of soul,
as though upon the ground before you, weeping, and beseeching you.
Behold him hanging on the fatal tree, in the greatest anguish of soul and body,
with his arms extended to receive returning sinners!
See, he shows you his bleeding wounds, and commends his grace and love to you!
As sure as these words are addressed to you,
so sure is the compassionate love of Christ busy with your hearts,
and urging itself upon you.
O submit yourselves to it!
Do so now, that you may not eventually too late behold him,
whom you have pierced with your sins.
Lay hold on love, lest wrath lay hold on you--lay hold on love, while it is yet at hand!

But let us, who through grace, are become recipients of a spark of this love of Christ,
esteem it highly; it is an invaluable pearl; and small as this pearl may be,
yet it is of more value than the whole world: however small the spark is,
it may still become a glowing heat, a flame of the Lord,
when carefully cherished and attended to.
Preserve it cautiously by a truly circumspect walk; avoid all unnecessary interaction,
friendship, and entanglement with the men of this world,
and every other occasion of temptation.
In such circumstances,
we ought to conduct ourselves like one who walks against the wind with a lighted taper,
or who passes through a forest with a precious jewel; for the enemies of our souls,
who watch for our treasure, are everywhere in ambush;
we must therefore be constantly upon our guard, and pray,
from the hymn we have just now sung,

O make us watchful, night and day,

To guard with care love`'s precious prize;

Lest to those hellish hosts it fall a prey,

Which, from the pit, with might against us rise!

We are apt to think this is a needless caution,
and that we shall take good care of ourselves;
but ah!--we are not sufficiently acquainted with the enemy`'s
devices and our own weakness in the hour of temptation.
We have no need to adduce the example of Peter as a warning to
us--we have sufficient painful experience of it near at hand.
Let us then beware of all levity, dissipation,
and the unbelieving suggestions of our carnal reason.
I am well aware that the love of Christ constrains us to all that has now been recommended,
and instructs us in it according to our need; but we are, alas,
not always in a right state to listen to it.
We ought, therefore, to remain near our hearts, where love carries on its work,
in a tranquil, devotional, and collected frame of mind.

Now therefore, one word more of encouragement to us all, and with that I will conclude.
Let us listen to and accept this glorious gospel of the ever-blessed God,
which has been at this time announced to us, though in weakness,
yet in the name of the Lord.
Christ loves us, and will continue to love us;
he will impart to us the power of his love,
and along with it everything that is good in time and eternity.
Christ loves us, he loves all of us; what then are we doing; why should we despond;
why are we still asleep?

Christ loves you, you youthful souls,
who in your blooming years are seeking something to love.
Ah, how would I grieve, how would the Savior grieve,
if you allowed yourselves to be captivated by a false and deceitful love!
Would it not be forever to be lamented, if you should be seduced, defiled,
and disgraced by the vain love of this world?
By the love of such things, as have nothing really charming,
nothing truly delightful in them, which so soon, so very soon wither away, cause disgust,
and vanish like smoke?
Christ loves you, are you conscious of it?
Do you reflect upon it?
It is for him alone that your hearts have been given you;
for him alone has the noble inclination to love been so deeply implanted in your hearts.
O, if you rightly knew what it is to be found in Christ and his love,
you would certainly become enamored of and captivated by his incomparable beauty!

Christ loves you, you penitent, distressed, and fearful hearts, and you know it not,
you believe it not.
Christ loves you of a truth; will you then continue in your despondency?
Ought not this joyful message to inspirit you?
If you cannot yet fully believe it, make the attempt for once; venture,
like Queen Esther, who said, "`If I perish, I perish.`"
She approached the king with fear,
and when she thought it was all over with her the gracious
scepter was extended to her and the king embraced her.
Come then you fearful souls,
and you shall experience that your lot will not fall out less favorably than hers.

Christ loves us--all who, with myself, are partakers of the heavenly calling.
Ought we not therefore to awake out of sleep, to lift up the eyes of our hearts,
to love Christ in return, and to walk in his ways with the utmost alacrity?
What an honor people esteem it when they are beloved by a king or a prince,
or by the noble or the great,
though it be with a love that imparts to its object nothing substantial or permanent!
And, lo, Christ, the Son of God, loves us as his bride!
Ought we then to let the worthless follies of this world occupy our attention?
Ought we not to let his love constrain us to detach
our hearts from every worthless idol and rival,
and devote them eternally to his divine love?
In the heart of Jesus, I behold nothing but love towards us; O what a shame, what a pity,
that anything else should be seen in our hearts but the love of Christ!

In future, however, it must be otherwise with us.
Shall we then conclude, by once more renewing our covenant of love with Christ,
now in his presence?
Are we willing to bind and resign ourselves anew to the fairest among ten thousand,
in sincere and mutual love, and with an unfeigned and, God grant,
an irreversible assent and consent?
Shall we do so?
Is it the mature determination of our hearts?
Come then, and let us give the hand of our hearts to Jesus, who is present with us,
and say in the spirit of true devotion,

Yea and amen with my whole heart,

Lord, I devote myself anew;

Willing with all, for you, to part,

And swear to be forever true!

Your lovely name will I confess,

Whate`'er a scoffing world may say;

And trust your covenant faithfulness,

To own me in the last great day.
